### ISSUE TITLE
Android "Quick tiles" not translated

### ISSUE THREAD

**Issue by marciozomb13** [bitwarden/android#1013]
## Describe the Bug
Even the Crowdin project being up-to-date, Android Quick tiles are still in english, sounds like they are hard coded on smali.

## Steps To Reproduce
Just drag any of the 3 tiles to quick settings panel

## Environment

- Device: [Samsung A51]
- Operating system: [Android 10]
- Is this a Beta release? [No]

**Comment by RePacked** [comment]
Can confirm. But personally I prefer my own language in-app and English quick tiles.

Device: OnePlus 8
Operating system: Android 10 (OxygenOS 10.5.9.IN21BA)
Build Version: 2.5.0 (3093)
Is this a Beta release? No

**Comment by marciozomb13** [comment]
Not solved.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1013
