### ISSUE TITLE
Auto-fill Service Disabling Periodically

### ISSUE THREAD

**Issue by suuoh** [bitwarden/android#102]
I've been using the Android app for several months now. In the recent few months, I noticed that the Auto-Fill Service notification does not always pop up when it usually should.

In every instance, the bitwarden app detects that the Accessibility services status is *disabled*. When I open the Accessibility settings, it always reports bitwarden as "On".  I normally just turn it off and then switch it on again, and it fixes it immediately. Any ideas?

In the meantime, I have set it so that the notification always persists to see if it helps.

**Comment by kspearrin** [comment]
I think @Primokorn had some problems with this in the past and was able to figure out a workaround.

**Comment by Primokorn** [comment]
Actually I have [another issue](https://github.com/bitwarden/mobile/issues/66) with the Accessibility service and there's no workaround AFAIK.

**Comment by suuoh** [comment]
That is unfortunate. Without the Bitwarden notification, it is really cumbersome to have to navigate between apps and copy and paste things. I wonder if other password managers have this issue on Android.

**Comment by kriswilk** [comment]
FYI, I have just experienced the same symptoms as @suuoh a couple of times today. I've been doing a bunch of cleaning up of my imported logins from LastPass and noticed more than once that as I browsed/tested some links I had no auto fill notification. Bitwarden thought the accessibility service was off but when checked, it was on.

Toggling the service got it working each time.

I will follow up after some more typical usage...

**Comment by dougmaitelli** [comment]
I have the same issue, the service disables itself multiple times a day. It is extremely annoying. But I only started having this issue after changing my device from a pixel to a Huawei mate 20

**Comment by kspearrin** [comment]
Try disabling battery optimization for Bitwarden under Android Settings. Someone told me that fixed it before.

**Comment by alexks02** [comment]
The same issue. Battery optimization for BitWarden is disabled.
Xiaomi Mi6, Android 8, MIUI 10.2

**Comment by kwaredk** [comment]
I just got the same issue :-O It keeps turning of in the Accessibility settings :-( It is happening so often, I'm thinking about moving back to Google Chrome password manager...
Please fix it :-)

**Comment by ryanpcmcquen** [comment]
Same issue here, Unihertz Atom on Android 9.

Even with Bitwarden battery optimization off and accessibility battery optimzation off _and_ the Bitwarden app kept running, the accessibility still turns off. Or Bitwarden thinks it is off. It makes logging into anything a several step process. Anyone find anything??

**Comment by Stephan-P** [comment]
Depending the brand of phone, OEM battery optmization services may be active closing down apps and services at will. This can include Whatsapp and Bitwarden Accessibility services.

In my case (Nokia 3.1, Android 9) I had to use adb (Android debugging bridge) and the MacroDroid app to hack my way into permanently disabling com.evenwell.powersaving.g3 and duraspeed.
(https://community.phones.nokia.com/discussion/48121/stop-phone-from-killing-apps)

**Comment by jef** [comment]
> Same issue here, Unihertz Atom on Android 9.
> 
> Even with Bitwarden battery optimization off and accessibility battery optimzation off _and_ the Bitwarden app kept running, the accessibility still turns off. Or Bitwarden thinks it is off. It makes logging into anything a several step process. Anyone find anything??

Funny, because the Unihertz community is quite small (pun intended) and it's been happening on my Jelly 2! Bitwarden doesn't even seem to have battery optimization; although I do see other apps that have it on.

**Comment by ryanpcmcquen** [comment]
I remember it was some system app or thing that I had to disable and I think it eventually worked somewhat reliably. I wish I could remember but I don't use that phone anymore.

**Comment by jef** [comment]
Well that's reassuring. I'll go back to it again at some point and take a look. Thanks for the response!

**Comment by SODDINGIT** [comment]
over 3 years later and this still happens on my SO's Huawei. I cannot always be there to enable it again so this makes me not want to use Bitwarden anymore.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/102
