### ISSUE TITLE
Update documentation for generating SSL for Apple's new extendedKeyUsage

### ISSUE THREAD

**Issue by chench00** [bitwarden/android#1028]
## Steps To Reproduce

1. Follow install instructions for Bitwarden Linux
2. Generate SSL certificate without domain
3. Import certificate into iOS device and instal
4. Try and log in to the Bitwarden app and it doesn't work

## Expected Result

Login successfully

## Actual Result

The certificate for this server is invalid.

## Environment

- Device: iPhone XS MAX
- Operating system: iOS 13
- Build Version (go to "Settings" → "About" in the app): Can't see as I can't login
- Is this a Beta release? N

## Additional Context

I am following the instructions [here](https://bitwarden.com/help/article/install-on-premise/#manual-docker-installations) for trying and update my certificate with the new extendedKeyUsage flag requirement but nothing here mentions how to achieve it. 

If someone could provide instructions for achieving this would be greatly appreciated.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1028
