### ISSUE TITLE
No support for huge font sizes

### ISSUE THREAD

**Issue by insiderser** [bitwarden/android#1033]
## Describe the Bug

The app doesn't respect system font size setting. I have `huge` font size selected and text in Bitwarden is too small for me (as if I changed font size to `normal`).

## Steps To Reproduce

1. Change font size to `huge` in system settings.
2. Open Bitwarden.

## Expected Result

All text in the app is big, consistently with other apps and Android itself.

## Actual Result

All text is small with no respect for `huge` system font size.

## Environment

- Device: Doogee X5 max.
- Operating system: Android 6.0.1
- Build Version (go to "Settings" → "About" in the app): 2.5.0 (3093)
- Is this a Beta release? N

## Additional Context

- App font size is the same when I change system font size to `small`.
- This started after one of the updates. Before that, app font size was gigantic.

**Comment by bill-mcgonigle** [comment]
This is WFM on Android 11.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1033
