### ISSUE TITLE
Vault sync time in 24-hour when device time is in 12 hour

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/android#1043]
## Describe the Bug

Vault sync time is displayed in the 24 hour format even though my device time is set in the 12 hour format

## Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Sync vault'

## Expected Result

Display time in accordance to the device time.

## Actual Result

Vault sync time is in 24 hour format even though the device time format is set to 12 hour format.

## Environment

- Device: Honor 5C
- Operating system: Android Nougat 7.0
- Build Version 2.5.0

##Additional Context 
Device language is set to English(U.K) but the device time is in the 12 hour format.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1043
