### ISSUE TITLE
Auto-fill bug in Yandex Browser on Android 10

### ISSUE THREAD

**Issue by Etsuya233** [bitwarden/android#1049]
## Describe the Bug

Do not shows list of account in Yandex Browser
## Steps To Reproduce

1. Open 'github.com'
2. Click on 'sign in'
3. Click on 'Input box'
4. Click on 'use Bitwarden to Auto-fill'

## Expected Result

Show the list of account, click to auto fill.
## Actual Result
There is no item for -- in your password library.

## Screenshots or Videos

![Screenshot_20200824-222911_相册](https://user-images.githubusercontent.com/42312804/91057091-5aea3e00-e659-11ea-82b3-a98dc1b4810a.png)
![Screenshot_20200824-222939_相册](https://user-images.githubusercontent.com/42312804/91057111-60478880-e659-11ea-8794-3e8497ef1a17.png)

## Environment

- Device: Redmi Note 5 Pro (Whyred)
- Operating system: Android 10 Lineage OS
- Build Version (go to "Settings" → "About" in the app): 2.5.0 (3093)
- Is this a Beta release? [Y/N]
N
## Additional Context

Work well in Chrome.
Not working in Yandex Browser.
Bad English,sorry.

**Comment by 4867896** [comment]
you can add URL androidapp://"your package name"
such as androidapp://com.autonavi.minimap
then when you open the web app can auto login in

**Comment by Andrew666** [comment]
I have the same problem

**Comment by leni8ec** [comment]
My Yandex browser doesn't offer to fill in passwords from Bitwarden at all - there's no popup.

Built-in Password Manager - I disabled it, but it didn't help.

**Comment by leni8ec** [comment]
Looks like Yandex Browser has removed support for third-party password managers ([4pda](https://4pda.to/forum/index.php?showtopic=791713&st=680#entry109144559))

**Comment by Etsuya233** [comment]
> Looks like Yandex Browser has removed support for third-party password managers ([4pda](https://4pda.to/forum/index.php?showtopic=791713&st=680#entry109144559))

I think so. Because third-party password managers like Bitwarden, LastPass works fine on browser like Chrome, Via, Kuake etc except Yandex.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1049
