### ISSUE TITLE
Bitwarden incorrectly shows its accessibility service as disabled

### ISSUE THREAD

**Issue by nikkehtine** [bitwarden/android#1058]
## Describe the Bug

When you press the "Auto-fill" tile in quick settings, you get an error message telling you to enable the accessibility service first. Despite this, autofill still shows up after tapping on a login/password field in most apps, but it doesn't work in browsers like Bromite, Samsung Internet, Mi Browser

## Steps To Reproduce

1. Set Bitwarden as your default autofill service
2. Enable Bitwarden as an accessibility service
3. Open a login page
4. Add the Bitwarden Autofill tile to your quick settings and tap on it

## Expected Result

The "Autofill with Bitwarden" screen should appear and you should be able to autofill your login credentials

## Actual Result

After enabling the Bitwarden accessibility service, the app still shows that it's disabled. When you click on the autofill tile, it shows an error message telling you to enable the accessibility service first.

## Environment

- Device: Mi Note 10 Lite
- Operating system: MIUI 11 (Android 10)
- Build Version: 2.5.0 (3093)
- Is this a Beta release? No

## Additional Context

I tried switching my system language from Polish to English and it fixed the issue only the first time I opened the app (autofill in Bromite worked as well). After opening the app again it still doesn't acknowledge its service being enabled.

**Comment by adamluzsi** [comment]
+1 for this

**Comment by neodada** [comment]
Having same problem on Redmi Note 9 Pro MIUI12 Android 10.

**Comment by WillyKaze** [comment]
Same issue on a Huawei P20 with EMIU 10.0 (Android 10)

**Comment by sanket-bhalerao** [comment]
i am having same issue with MIUI 12, in earlier MIUI version it worked as expected.

**Comment by nri82** [comment]
Same as here, poco x3, MIUI 12.0.6 Android 10. But mine is a little different, it's work with browsers but not in bank apps fill. I tried turn off MIUI optimization, lock app, select auto start but it's work only one time, and then stop working.

**Comment by isacfjr** [comment]
Same issue on MI 9 using MIUI 12.0.5 Android 10.

**Comment by vaisdev** [comment]
Same issue on LG LM-G850EMW, Android 10

**Comment by mod-john** [comment]
Same issue on Blackview BV5900

**Comment by nikkehtine** [comment]
I want to confirm it's still an issue on MIUI 12 (Android 11), ver. 2.11.3

**Comment by brenoteles** [comment]
Same issue on MIUI 12.0.15 with Android 10QP1A.190711.020 with 2021-06-01 security patch level.

**Comment by Talha-Jamil-TJ** [comment]
Same issue in Mi 10T with MIUI 12.5.1

**Comment by mod-john** [comment]
Same issue on Blackview BV5900 running Android 9

Like everyone here, the app is enabled in Accessibility, I have also loaded the app beforehand and the title is not greyed out like it can be sometimes but when you press it it gives the error message in screenshot.
![Screenshot_20211216-094357](https://user-images.githubusercontent.com/12935853/146349468-53f4f8c2-4ccb-4686-a548-328107f9a574.png)

**Comment by mod-john** [comment]
> I downloaded the beta version of the app and the issue was resolved
> 
> MIUI 12.0.16

I am also running the beta version of Bitwarden but the problem persists for me.

**Comment by nri82** [comment]
I'm using Poco X3 NFC android 11, MIUI 12.5.

 I had noticed that if you allow it to autostart bitwarden it's working as expected.
![IMG_20220420_103928](https://user-images.githubusercontent.com/18355195/164177748-f158886a-c12c-4da7-9baf-57e774ec2d31.jpg)

**Comment by TheBigSadd** [comment]
+1 same issue here on the Xiaomi Mi Pad 5 Pro

**Comment by Longoon12000** [comment]
I too have this issue on a Galaxy A50. In apps (like eBay) that have multiple stages for logging in (username, next panel, password) this causes an issue, where BitWarden will show the popover on the username field and input it, but on the next panel with the password it won't show the popover and using the tile will cause the error message to pop up. No way to login except switching to BitWarden, unlocking, searching, opening, copying the password, switching back and pasting the password.

**Comment by lloricode** [comment]
+1

**Comment by businessBoris** [comment]
Believe the same issue here. Pixel 7 Pro Android 14 + Nov '23 service pack.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1058
