### ISSUE TITLE
IOS releated accessibility problems

### ISSUE THREAD

**Issue by christopherpross** [bitwarden/android#1089]
Hello,
my name is Christopher and I would like to report a few issues in the area of accessibility. These relate exclusively to IOS with VoiceOver. Since I am blind myself, this is very close to my heart. Although I am a software developer myself and would love to address these issues myself, I don't have an Apple Developer account that I can use to create Provisioning profiles. Now I hope that the list is not too long, because it looks long. But I think this is feasible and not as much effort as it seems.
If we can manage to fix these entries in the list, the app will be fully accessible and will benefit from all features in ios accessibility that xamarin knows. Some entries are with low priority or are feature requests, but I hope if there others are resolved these will olso be fixed. 
For feedback or beta-testing I would of course be available, also I know Xamarin very well, so I also know the possibilities to improve accessibility.
Sorry for destoying the issue template, but I had collected some bugs / feature requests and I think this is the right place. Please correct me, if I am wrong and also sorry for my grammar.
To reproduce the issues, use the bitwarden build 2.6.0 (262) and turn on VoiceOver in the Settings under Accessibility -> VoiceOver then follow the "description collunm in the table below.

### issue (priority high): VoiceOver ignores visibility 
- VoiceOver sees UI items, there are invisable for normal users.
- That means if bitwarden try to hide something, Voiceover see it and read it out.
- very convusing and the importent UI elements are now in the background and you don't know which is the right item for the screen.
- the best example is the add screen for an item, here voiceover reads all fields of the types there are possible. So the blind user can see the Password, login-username, credit-number-field, otp-field in one screen.
- Here is the accessibilityTree the solution, the binding handles only switch the visiblity not the accessibilitytree, I think.
- This behavior is in all screens except the settings.

### issue (priority medium):  In Vault view, you can not navigate to the end of the screen
- Voiceover has a navigation gesture which allows to jump to the next item in the screen, but in the fault view, flolder view also in the cipher view, you can not navigate with this gesture to the end of the screen.
- you have to use your finger to manualy explore the screen, something seems to broken in the accessibilitytree also here.
- maybe the same reason as above, but you can reroduce it as follows:
- create a folder with one item, torn on voice over and tap with one finger at the first item on the screen.
- then flick your finger to the right try to reach the settings tab-button, you should not reach it. normaly you can reach it. 

### issue (priority low):  some emty not known elements for Voiceover
- this elements are present in the password generator, and in the folder screen, cipher screen and the add screen. I don't know what there are. in the folderview and the cipher view it activates the nearby element.
- so it can be ignored, but there are useles

### issue (priority low):  some missing element roles 
- some roles are missing, for example some headings in the settings don't recocnice voiceover as them.

### feature request (priority medium):  use custom accessibility actions
- for Voiceover users exist a convinient way to access other actions of an item for example the copy of username and password .
- this is called custom accessibility actions with this small improvement, blind users can incres there speed and can reach the work speed of an seeing user.    

### feature request (priority low): back buttons
- if we mark the back buttons in the settings as back for voiceover, users can easyly navigate back with a single gesture and this is very convortable.    

All the best,
Christopher

**Comment by cscharf** [comment]
Hi @christopherpross , thank you for the very detailed submission. I have a question for you regarding: 

> issue (priority high): VoiceOver ignores visibility

Can this be toggled for iOS in Xamarin Forms using the `AutomationProperties.IsInAccessibleTree` property? see: 
[docs.microsoft.com](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties#automationpropertiesisinaccessibletree)

We'll let you know if we have any other questions, thanks again!

**Comment by christopherpross** [comment]
@cscharf yeah exactly, this property toggles that. Maybe you can also apply that to a parent to toggle the child  elements, that I haven't try out.
All the best and thank you for the quick answer,
Christopher

**Comment by christopherpross** [comment]
Hey, are there any updates here? It would be very nice if some of the problems could be fixed. 😃

**Comment by mohdshara** [comment]
I am very interested in any development on this front. Of course, ready to test if something gets implemented.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1089
