### ISSUE TITLE
S20FE scanning TOTP QR is using wide camera / camera is stretch up on height

### ISSUE THREAD

**Issue by sionzee** [bitwarden/android#1130]
## Describe the Bug

The Samsung S20FE supports ultra-wide camera. Unfortunately when I open the TOTP scanner then it uses this camera and the QR looks stretch to height. So I'm not able to scan the QR (sometimes it works but in most cases not).

## Steps To Reproduce

1. Buy or get S20FE or a mobile with ultra-wide cam.
2. Go to Bitwarden application and edit details at any card.
3. Open TOTP scanner and try to scan any QR

## Expected Result

It should use the proper camera what is not using ultra-wide lens and perfectly read the QR.

## Actual Result

QR is not readable. The Bitwarden don't see it and is not scanning it.

## Screenshots or Videos

I'm not able to record/take a picture because the application is blocking it.
Anyway on this step I noticed something interesting. When I open it through Bitwarden TOTP scanner then it is stretched up to height. But if I use a default camera in the phone and use any mode of the camera then it doesn't looks stretched up.

## Environment

- Device: Samsung S20FE 5G
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.6.1 (3178)
- Is this a Beta release? No

## Additional Context

As I mentioned in the "Screenshots or Videos" section maybe it is not related to Ultra-wide camera. 
Anyway seems I'm able to "scan" everything now even when the camera looks really stretched up.
Maybe it can be related to QR density? Where it is able to read it on small QR but have problem with high density one's.
I also cannot remember what page was not working at all. So I want to at least report the stretch up issue.

**Comment by sionzeecz** [comment]
Sorry for commenting it immediately after posting it.

Maybe would be great to have an option what camera should be used in the app settings?
The future is bringing here multiple cameras/lens and the camera which is opened in Bitwarden have no any settings.

**Comment by dberthia** [comment]
Also seeing this issue on my OnePlus 8 pro, and somebody on Reddit is seeing this as well:
https://old.reddit.com/r/Bitwarden/comments/jkv7ho/bug_cannot_scan_qr_codes_to_configure_totp/

**Comment by cbrherms** [comment]
Same issue here on pixel 5

**Comment by gittyhubbyfrankybobby** [comment]
Same issue pixel 4xl

**Comment by CDNHammer012** [comment]
Same issue here: OnePlus 6

**Comment by ThorpeJosh** [comment]
Same issue with Oppo F7 and R15, landscape and portrait both stretched the standard 4:3 camera to entire screen making it unable to read QR

**Comment by palalex38** [comment]
Same issue on Xiaomi Mi 10T Pro

**Comment by Hyrules** [comment]
Same issue on One plus 6T image seems stretched and scanning does not work.

**Comment by AdamHess** [comment]
This is still an issue: OnePlus 5T

**Comment by NaxNir** [comment]
Also an issue still with the Pixel 4a.

**Comment by hmmcclish** [comment]
Same on F(x)tec Pro1, in both portrait and landscape mode. Workaround was to paste QR code into MS Paint, shrink height to 75%, and retry. Scanned perfectly.

**Comment by renaudallard** [comment]
About the same issue with a Motorola Edge 20 pro. Picture is not really stretched, but completely blurry, I had to increase the size of the QR TOTP code to about 20cm to be able to scan it on my screen. QR code scanner pro and the camera app are able to scan the same QR code without issue.

**Comment by donutboy929** [comment]
Same issue on Samsung Galaxy S22 except I am able to scan the QR code, just looks warped in the viewfinder

**Comment by ksolheim** [comment]
Samsung S21+ - Looks like it's using the ultra wide camera.
Unable to scan any QR codes for with Bitwarden.

**Comment by christopher-ursich** [comment]
Same issue on Pixel 5a on Android 13.

**Comment by JuliaSzulc** [comment]
Same issue on Samsung Galaxy A5 with Android 13
Blurry and stretched picture, can't scan anything. It's been over two years since opening this issue. Are you planning to fix it?

**Comment by sinap-se** [comment]
This issue is present on a Pixel 7.

**Comment by FaviFake** [comment]
Same on my Samsung Galaxy A72

**Comment by FaviFake** [comment]
I have the same issue on my Samsung Galaxy A72. For more information about my phone, see issue #2448

Here's a video showing the bug:

https://user-images.githubusercontent.com/86537048/227742136-2c5ff612-4070-48c8-b8c4-411b850f0708.mp4

**Comment by renaudallard** [comment]
> I have the same issue on my Samsung Galaxy A72. For more information about my phone, see issue #2448
> 
> Here's a video showing the bug:

Your video doesn't show trying to scan a QR code.
The strangest thing is that bitwarden is the one and only app I have seen with that issue.

**Comment by FaviFake** [comment]
> > I have the same issue on my Samsung Galaxy A72. For more information about my phone, see issue #2448
> > Here's a video showing the bug:
> 
> Your video doesn't show trying to scan a QR code. 

Yes, but it shows how distorted the camera is.

**Comment by FaviFake** [comment]
> HELLO PLEASE FIX THIS ASAP (GALAXY z FOLD 5)

@capatina You can easily fix this by clicking this button:
![Screenshot_20231019_144536](https://github.com/bitwarden/mobile/assets/86537048/19d149b8-e5a0-4621-8134-9d51cda6f006)

**Comment by capatina** [comment]
@FaviFake here is coinbase.com, for example: 
<img width="446" alt="image" src="https://github.com/bitwarden/mobile/assets/13295539/7517eab8-1c37-4be9-901c-e2f16ca26502">

I had to scan the QR code with my phone camera, copy the link to a notepad app, copy the secret key, and then paste that into Bitwarden because the bitwarden scanner doesn't work

**Comment by rvt0001** [comment]
I resolved this issue on my Samsung android tablet by changing the **_auto-rotate_** setting to _**portrait**_.

**Comment by stefandier** [comment]
Same on Pixel 7 with Android 14 (January 2024).

That's  what's making me refrain switching from free to paid...

**Comment by FaviFake** [comment]
You're saying _this bug alone_ is enough to make you refrain from upgrading your account? You can easily go around it by entering the code manually.

**Comment by cbrherms** [comment]
> You're saying _this bug alone_ is enough to make you refrain upgrading your account? You can easily go around it by entering the code manually.

This bug, plus so far it being 3 years without a fix, is why I haven't returned to BW.

**Comment by FaviFake** [comment]
... There is a fix: https://github.com/bitwarden/mobile/issues/1130#issuecomment-1868421257

**Comment by renaudallard** [comment]
What I don't understand is that all apps that I have installed and that can scan QR codes work just fine. Only bitwarden is having the issue.

**Comment by AndrewHutcheson** [comment]
I am also having this issue. Oneplus 6t. It doesn't matter if it is landscape or portrait mode.

**Comment by tehniemer** [comment]
> On a Pixel 6, I was able to resolve this by going to the camera app and disabling the Camera setting "Camera scan suggestions".

This didn't work for me on a Pixel 6a

**Comment by Cris--** [comment]
> This is still an issue: OnePlus 5T

+1

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1130
