### ISSUE TITLE
Android - The vault item selection drop-down menu for auto-fill covers the credential fields.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1132]
## Describe the Bug
The vault item selection drop-down menu for auto-fill covers the credential fields in an application called Heisenberg (IPTV Application) and IPTV Smarters Pro on Android.

## Steps To Reproduce
Open an application Heisenberg.
Click on the Username or Password field.
The vault item selection box will appear in the middle, covering both the username and password fields.

Or

Open an application IPTV Smarters Pro.
Go to Create a user
Tap Add Xtream API
The vault item selection box will cover the fields on that page.

## Expected Result
The vault item selection box should appear below the password field.

## Actual Result
The vault item selection box appears on top of the username and password fields.

## Screenshots or Videos
![Screenshot_20201101-090905_Heisenberg](https://user-images.githubusercontent.com/73389600/97867136-2bb11680-1d05-11eb-890f-a6e45738598b.jpg)

## Environment

- Device: Samsung Galaxy S20 Ultra 5G.
- Operating system: Android 10.
- Build Version: Android 10.
- Is this a Beta release: No.

## Additional Context
N/A.

**Comment by rsngfrce** [comment]
I have never used Heisenberg, but I have definitely experienced the same issue of the box covering the fields at times in other apps or sites.

(Samsung Galaxy S10e, Android 11)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1132
