### ISSUE TITLE
iOS - Opening the application sometimes does not prompt to use biometrics (TouchID or FaceID).

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1134]
## Describe the Bug
Opening the Bitwarden application on iOS sometimes does not prompt to use Touch ID or FaceID, unlocking the vault using the master password, closing the app, and reopening solves is temporarily. Another work-around is to force close the app and then re-open it.

## Steps To Reproduce
Launch the Bitwarden application on an iOS device after the vault has locked.

## Expected Result
The application should use a biometric option to unlock.

## Actual Result
The application does not offer a biometric option to unlock.

## Screenshots or Videos
Internal.

## Environment

- Device: iPhone 11 and iPad.
- Operating system: iOS 14.0.1.
- Build Version: 2.6.1.
- Is this a Beta release? N.

## Additional Context
Issue appears to happen when an update is made to the vault and is pushed out the devices.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1134
