### ISSUE TITLE
iOS - Toggling AutoFill Passwords in the Settings app causes the device to feeze when Bitwarden is installed.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1143]
## Describe the Bug
Toggling the AutoFill Passwords options in Settings causes the device to freeze.
This started after upgrading to iOS 14.2.

## Steps To Reproduce
On an iPad or an iPhone:
1. Open the Settings application.
2. Tap on Passwords.
3. Tap on the Autofill Passwords toggle.

## Expected Result
For the toggle to turn on and to be able to select Bitwarden.

## Actual Result
The device freezes.

## Screenshots or Videos
Internal.

## Environment

- Device: iPhone 8 and iPad Pro 11" 2018.
- Operating system: iOS 14.2.
- Build Version: 2.6.1.
- Is this a Beta release? N.

## Additional Context
This started after upgrading to iOS 14.2. Uninstalling and reinstalling Bitwarden does not resolve it. The AutoFill toggle does not cause the device to freeze when Bitwarden is not installed.

**Comment by mportune-bw** [comment]
I'm unable to reproduce this behavior.  Does it keep happening once Bitwarden has been re-installed?

**Comment by lschober-bw** [comment]
I also can not reproduce this. My device was just updated to 14.2 to test this behavior.

@SergeantConfused What lock mechanism do you have set to access the "Passwords" menu? (FaceID, TouchID, etc.)

To add, after uninstalling Bitwarden, the device should be power cycled (restarted) before reinstalling the application.

**Comment by ljm625** [comment]
Facing same issue here on a new iPhone SE2 with IOS 14.2
Currently using TouchID, but can reproduce the freeze even if I disable lock password & touch id.
Also uninstall then reboot then reinstall doesn't fix.

**Comment by mportune-bw** [comment]
@SergeantConfused @ljm625 Is this still happening with the 2.7.0 release?

**Comment by arno-vdk** [comment]
Enabling 2FA for apple-id solved the problem on my device (iPad/ios14.2)

**Comment by InitPatch** [comment]
I have the same behavior, but it's not related to Bitwarden specifically. It was happening on both of my devices (iPhone and iPad Pro) before I install Bitwarden. Same behavior with LastPass, Safari, Google, etc... 
I think it's an OS related issue eventually.

**Comment by alexandrunicula** [comment]
Same issue before installing Bitwarden. Ios 14.4.1 iPhone XS

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1143
