### ISSUE TITLE
Wrong keyboard layout when creating an account from iOS app

### ISSUE THREAD

**Issue by matthttam0** [bitwarden/android#1151]
## Describe the Bug

When using the iOS app to create an account using an "AZERTY" keyboard (I'm from FR), the keyboard layout for the password is "QWERTY".

## Steps To Reproduce

1. Install the iOS app
2. When opening for the frist time, select "create an account"
3. Enter the email (the Keyboard is in "AZERTY" for this field"
4. Clic on the password field --> the keyboard layout switch to "QWERTY"

## Expected Result

Keeping the layout un "AZERTY"

## Actual Result

Layout switch to "QWERTY"

## Screenshots or Videos

I tried taking screenshot, but on the Password field the keyboard don't even show !!! I don't know how it is possible but I retried a bunch of time, and when the "QWERTY" layout is displayed, the screenshot don't show it !

- Email field : 

![image](https://user-images.githubusercontent.com/74500698/99189565-00e1ac00-2762-11eb-9abe-10e60661f4db.png)

- Password field (not very usefull...) : 

![image](https://user-images.githubusercontent.com/74500698/99189721-ccbabb00-2762-11eb-8669-bbcaf34f3c7d.png)

## Environment

- Device: iPhone 6s
- Operating system: iOS 14.1
- Build Version : 2.6.1 (278)
- Is this a Beta release? N

**Comment by Greenderella** [comment]
Hi @matthttam0, we were able to confirm this issue. The development team has been notified about it and will proceed to investigate what's causing it.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1151
