### ISSUE TITLE
Android - Go to my vault button remains on screen after password has been entered.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1170]
## Describe the Bug
When you open a password-protected PDF in Adobe Acrobat, Bitwarden's overlay 'Auto-fill with Bitwarden' remains on screen after entering the password using the keyboard.
This does not happen if 'Auto-fill service' is enabled, and 'Use Accessibilty' and 'Use Draw-Over' are disabled.

## Steps To Reproduce
1. Enable all 3 options under Settings > Auto-fill Services.
2. Open a password-protected PDF in Adobe Acrobat Reader.
3. Tap on the password field, ignore Bitwarden's overlay, type the password, and hit enter.

## Expected Result
To open the PDF and to stop seeing Bitwarden's overlay.

## Actual Result
The PDF opens but Bitwarden's overlay remains stuck on screen.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/73389600/101507756-ce952a00-396e-11eb-89d7-a158261e0752.png)

## Environment

- Device: Samsung Galaxy Note 10+.
- Operating system: Android 10.
- Build Version: 2.7.0 (3258).
- Is this a Beta release? N.

## Additional Context
This was originally encountered on a Samsung Galaxy Note 8 running Android 9.

**Comment by nickcaballero** [comment]
This is not limited to viewing PDFs. It happens randomly.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1170
