### ISSUE TITLE
Android - Accessibility service shows vault items but Auto-fill service shows no matching items.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1177]
## Describe the Bug
If you enable Auto-fill service, Use Accessibility, and Use Draw-Over:
The Accessibility service's banner (White and Black) would return results from the vault while the Auto-fill service's banner (White and Blue) would return no matching items in the vault.

## Steps To Reproduce
1. Add 3 items with the same domain but different sub-domains in the URI and set the match rule to Exact or Starts with.
2. Go to the sub-domain login page.
3. Tap on the username or password field.
4. Tap once on the Accessibility service's banner and once on the Auto-fill service's banner. You can move the page around to switch between the banners.

## Expected Result
To have both banners return the same result from the vault. Either there is or there isn't a matching item in the vault.

## Actual Result
Accessibility service's banner returns a matching item in the vault.
Auto-fill service's banner returns that there are no matching items in the vault.

## Screenshots or Videos
N/A.

## Environment

- Device: Samsung Galaxy Note 10+.
- Operating system: Android 10.
- Build Version: 2.7.0 (3258).
- Is this a Beta release? N.

## Additional Context
Here are the URIs I tested with:
https://www.umb.sk/
https://iam.umb.sk/
https://ais2.umb.sk/ais/start.do

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1177
