### ISSUE TITLE
iOS - When Vault Timeout Action is set to Log out and 2FA is configured, Auto-fill prompt does not read NFC YubiKey.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1178]
## Describe the Bug
When you set the Vault Timeout Action to Log out, and you have 2FA using a YubiKey OTP Security Key configured:
When you click on 'Passwords' at the top of the keyboard to auto-fill your credentials, the 2FA authentication step does not read the YubiKey 5C NFC, it does not display the 'Ready to Scan' prompt. Holding the YubiKey to the NFC scanner would display a banner for Yubico's website.

## Steps To Reproduce
1. Set your Vault Timeout Action to Log out.
2. Set the Vault Timeout to 1 Minute.
3. Go to http://vault.bitwarden.com/
4. Tap a credential field and then tap on 'Passwords'.
5. Enter your email address and master password.

## Expected Result
Bitwarden would read the NFC YubiKey and log in.

## Actual Result
Bitwarden does not prompt to scan the NFC YubiKey and you cannot log in.

## Screenshots or Videos
N/A.

## Environment

- Device: iPhone SE 2020.
- Operating system: iOS 14.2.
- Build Version: 2.7.0 (358).
- Is this a Beta release? N.

## Additional Context
Please note that you can log in by using a YubiKey 5Ci. You can tap the YubiKey TOTP field and then tap the YubiKey 5Ci while it's connected to the Lightning port.

**Comment by thprather** [comment]
I've been experiencing the same issue on iOS 14.4. in Build Version 2.8.0 (449).

**Comment by SergeantConfused** [comment]
This is caused by a limitation within the operating system that prevents using NFC in the autofill flow and we cannot change that. This means that it would not be possible to use autofill on iOS if the 'Vault Timeout Action' is set to 'Log out' and the only 2FA method requires NFC.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1178
