### ISSUE TITLE
Base domain dont match Top-level domain

### ISSUE THREAD

**Issue by bb2** [bitwarden/android#1191]
## Describe the Bug

Base domain dont match Top-level domain
Example:
- URI base domain value: http://example/login
- Not match: http://example/login

## Steps To Reproduce

1.Add http://example/login login item
2.Use bitwarden autofill login on the http://example/login

## Expected Result

Match http://example/login login item

## Actual Result

Shows no http://example/login login item

## Environment

- Device: Google Pixel 5
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.7.0 (3257)
- Is this a Beta release? [N]

**Comment by Greenderella** [comment]
Could you give us a more concrete example? I'm unable to reproduce this issue with the provided instructions and autofill is working as expected with the match detection option set as: base domain (https://bitwarden.com/help/article/uri-match-detection/#match-detection-options)

**Comment by bb2** [comment]
Do you use the top-level domain to reproduce? What is the domain you used when reproducing. In my case, there is no matching login item when accessing a URL like http://example/. It is worth noting that if you are on a Wi-Fi network  Under access to the top-level domain, it may automatically jump to the non-top-level domain according to the router configuration.  You can use a network capture tool to confirm that you have indeed visited the top-level domain.

**Comment by MexHigh** [comment]
May be related to #578

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1191
