### ISSUE TITLE
Android 11: Clipboard isn't cleared

### ISSUE THREAD

**Issue by hn-sl** [bitwarden/android#1195]
## Describe the Bug

This is similar to https://github.com/bitwarden/mobile/issues/1165 but the difference is that clipboard isn't cleared even after password is pasted on Galaxy Note 20 after OS update from android 10 to 11.

## Steps To Reproduce
Same as https://github.com/bitwarden/mobile/issues/1165
1. Set the time for clearing the clipboard to 10 seconds.
2. Copy a password and leave the Bitwarden app open in the foreground for 10 seconds.
3. Put Bitwarden in the background and wait for 10 seconds.
4. Go to any text entry field and you are able to paste the password. After password is pasted, it is still in clipboard.

## Expected Result

After 10 seconds, the clipboard is empty and nothing pastes.

## Actual Result
After 10 seconds, the clipboard is not empty though nothing pastes.

## Environment
- Device: Galaxy Note 20
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.7.0 (3258)
- Is this a Beta release? N

**Comment by SergeantConfused** [comment]
Hi there,

Please uninstall Bitwarden, reboot your device by turning it off and then on, and reinstall Bitwarden. Then, make sure you're running Bitwarden 2.7.2 and test this again. Please let me know if that behaviour persists.

Thank you in advance,

**Comment by the-anonymous009** [comment]
> Hi there,
> 
> Please uninstall Bitwarden, reboot your device by turning it off and then on, and reinstall Bitwarden. Then, make sure you're running Bitwarden 2.7.2 and test this again. Please let me know if that behaviour persists.
> 
> Thank you in advance,

I just uninstalled Bitwarden, rebooted my device and reinstalled Bitwarden from Google Play but now the version is  2.6.1 which is even older than before and the behaviour  also persists. It is quite weird that my Bitwarden version was downgraded after reinstall. Is this expected?

**Comment by SergeantConfused** [comment]
No, you shouldn't be downgrading. Please go to your Play Store, open Bitwarden's page, click on What's new, and scroll to the bottom, and attach a screenshot of what you see there.

Thank you in advance,

**Comment by the-anonymous009** [comment]
> No, you shouldn't be downgrading. Please go to your Play Store, open Bitwarden's page, click on What's new, and scroll to the bottom, and attach a screenshot of what you see there.
> 
> Thank you in advance,
Please refer to this. Thanks.
![bitwarden_screenshot](https://user-images.githubusercontent.com/48025074/103209700-0a585980-4947-11eb-9fa8-2d11ad7604f4.jpg)

**Comment by the-anonymous009** [comment]
Now on Google Playstore I see the latest version 2.7.2 though I din't change anything. But the issue still persists with this version. One different thing is that now empty text is added to clipboard but clipboard also have the password.

**Comment by IpCarrara** [comment]
I can attest to the same problem. I tested on a (Samsung Galaxy M51, Android 11, One UI Core 3.1) and it has 40 spots on "clipboard history". When Bitwarden clears the clipboard, it fills 1 spot with a blank clip, but leaves 39 behind. Because of that, the password stay in the "clipboard history" even after Bitwarden effectively did its job. This is a flaw in the Samsung device's security, which Bitwarden could solve by, instead of filling 1 entry with a blank clip, filling 41 entries. This way all the clipboard history space would be filled with blank clips and no password would be visible.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1195
