### ISSUE TITLE
iOS - Asks to scan NFC YubiKey while One of my keys supports NFC is not ticked.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1204]
## Describe the Bug
The iOS client asks to hold the YubiKey to the phone's NFC antenna while 'One of my keys supports NFC.' is not ticked.

## Steps To Reproduce
1. Log into the web vault.
2. Add a non-NFC YubiKey as 2FA. I tested with a YubiKey 5Ci.
3. Make sure that 'One of my keys supports NFC.' is unticked.

## Expected Result
To show me the YubiKey screen where I tap on the OTP text field and then touch the YubiKey to enter the OTP.

## Actual Result
I receive a prompt saying 'Ready to Scan' and asking to hold the YubiKey near the top of the device.

## Screenshots or Videos
N/A.

## Environment

- Device: iPhone SE 2020.
- Operating system: iOS 14.3.
- Build Version: 2.7.2 (401).
- Is this a Beta release? N.

## Additional Context
Please note this does not prevent anyone from logging in using a non-NFC YubiKey on iOS.
You would cancel the 'Ready to Scan' prompt, tap the OTP text field, and then touch the YubiKey.

**Comment by wackerow** [comment]
Hey everyone! I am also encountering this issue using an iPad. 

I had "One of my keys supports NFC" checked, and I was unable to get in using my iPad because it requested NFC. Unchecked this option in my settings (from another device), but did not fix this. Reinstalled the app on my iPad, no luck.

> ![image](https://user-images.githubusercontent.com/54227730/106657083-6c147080-6550-11eb-8adb-a3c22b72646e.png)
> Only option is NFC

> Tapping "Use another two-step login method" gives two options
> ![image](https://user-images.githubusercontent.com/54227730/106657116-7afb2300-6550-11eb-9fd7-296fb966eadf.png)
> Tapping "YubiKey Security Key" brings you back to first image
> Tapping "Recovery Code" brings you to web reference

> Tapping "Continue" gives error
> ![image](https://user-images.githubusercontent.com/54227730/106657357-c4e40900-6550-11eb-889a-79f0f1713e95.png)
> And "Cancel" goes back to username/password

## Environment
- Device: iPad Pro (12.9-inch) (3rd generation)
- iOS version: 14.4 (18D52)
- Build: 2.8.0
- Not beta

Would love to see this addressed, as personally it's preventing me from being able to using entirely on my iPad

Hope this helps a little, and thanks in advance for considering!

**Comment by SergeantConfused** [comment]
@wackerow, please note that if you're able to plug your YubiKey into your tablet, you can tap on the line just above the 'Remember me' toggle and then tap the golden patch on your YubiKey to enter the OTP code and log in. You're not limited to NFC.

**Comment by wackerow** [comment]
@SergeantConfused Hey! Appreciate you replying, and I suppose I should've posted an update. I did eventually realize that so I was able to get in. I suppose a separate thought beyond this issue would be a slight UI/UX improvement to help make this more obvious (like placeholder text perhaps). The full-width line by itself gave the appearance of a divider to me.

**Comment by SergeantConfused** [comment]
With pleasure. And you're absolutely right, and we're working on it.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1204
