### ISSUE TITLE
iOS - Bitwarden does not clear the TOTP 6-digit code from the clipboard.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1217]
## Describe the Bug
The TOTP 6-digit code that is generated in Bitwarden and automatically copied into the clipboard is not cleared from the clipboard after the 'Clear Clipboard' duration passes.

## Steps To Reproduce
1. Open your iOS Bitwarden client.
2. Go to Settings > Options > and set 'Clear Clipboard' to 10 seconds.
3. Log into an account with TOTP 2FA that is generated in Bitwarden.

## Expected Result
That the clipboard would be cleared after 10 seconds.

## Actual Result
The clipboard contains the TOTP 6-digit code longer than 10 seconds.

## Screenshots or Videos
N/A.

## Environment

- Device: iPhone SE 2020.
- Operating system: iOS 14.3.
- Build Version: 2.7.2 (401).
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by lugaetsch** [comment]
same disfunction in Android

Environment

- Device: Samsung Galaxy A5 (SM-A500FU)
- Android 6.0.1
- Build Version: 2.7.2
- Beta release? No

**Comment by F8wuoabTtC** [comment]
> ## Describe the Bug
> 
> The TOTP 6-digit code that is generated in Bitwarden and automatically copied into the clipboard is not cleared from the clipboard after the 'Clear Clipboard' duration passes.
> ## Steps To Reproduce
> 
>     1. Open your iOS Bitwarden client.
> 
>     2. Go to Settings > Options > and set 'Clear Clipboard' to 10 seconds.
> 
>     3. Log into an account with TOTP 2FA that is generated in Bitwarden.
> 
> 
> ## Expected Result
> 
> That the clipboard would be cleared after 10 seconds.
> ## Actual Result
> 
> The clipboard contains the TOTP 6-digit code longer than 10 seconds.
> ## Screenshots or Videos
> 
> N/A.
> ## Environment
> 
>     * Device: iPhone SE 2020.
> 
>     * Operating system: iOS 14.3.
> 
>     * Build Version: 2.7.2 (401).
> 
>     * Is this a Beta release? N.
> 
> 
> ## Additional Context
> 
> N/A.

I will be ideal if you set clear clipboard after 30 seconds

**Comment by F8wuoabTtC** [comment]
It will be ideal if you set clear clipboard after 30 seconds!

**Comment by lugaetsch** [comment]
> It will be ideal if you set clear clipboard after 30 seconds rather than 10 seconds!

set it to 30 seconds - no difference (on iOS).

**Comment by F8wuoabTtC** [comment]
Try changing you keyboard and turn off clipboard!

**Comment by lugaetsch** [comment]
> Try changing you keyboard and turn off clipboard!

This issue is about using the clipboard to copy TOTP after auto-filling password.
I can change the keyboard, but why should i disable clipboard then?

**Comment by F8wuoabTtC** [comment]
Then  try clipboard cleaner until the bug fixed

**Comment by lugaetsch** [comment]
> Then try clipboard cleaner until the bug fixed

That's the plan :) I build an iOS-Shortcut for clearing the clipboard.
Thanks for your help.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1217
