### ISSUE TITLE
Android - Bitwarden is picking up the browser's package name as the URI, instead of the site's URL.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1247]
## Describe the Bug
On Chrome, Edge, and Brave, Bitwarden is saving the browser's package name as the URI, and not the website's URL. Through Firefox, Bitwarden picks up the webpage URL.

## Steps To Reproduce
1. Open the web vault in a Chromium-based browser.
2. Tap on the email field.
3. Open your Bitwarden vault through the autofill banner.
4. Tap on the + button.

## Expected Result
To see https://vault.bitwarden.com/ in the URI.

## Actual Result
You see androidapp://com.android.chrome/ in the URI.

## Screenshots or Videos
N/A.

## Environment
- Device: Google Nexus 10.
- Operating system: Android 5.1.
- Build Version: 2.8.0.
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by SahilPulikal** [comment]
Even I'm facing the same issue on Android 5.1.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1247
