### ISSUE TITLE
Auto-fill pop-up is not showing in Tangerine Android App

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/android#1249]
## Describe the Bug

Auto-fill pop-up is not showing in Tangerine Android App
## Steps To Reproduce

Install Tangerine banking app and try to log in.

## Expected Result

The usual pop-up will show when you click the username

## Actual Result

The usual pop-up won't show up

## Environment

- Device: Android 10
- App Version: 2.8.0

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1249
