### ISSUE TITLE
iOS BitWarden keeps scrolling to bottom of Secure Note

### ISSUE THREAD

**Issue by JSimmons0311** [bitwarden/android#1257]
## Describe the Bug

When I am editing a Secure Note and I tap text (to copy/paste), BitWarden will scroll to the very bottom of the Secure Note. 

## Steps To Reproduce

1. Open an existing Secure Note that is longer than the display can display
2. Click on Edit
3. Tap some text near the top (or middle) like you are going to select text

## Expected Result

I expect the scroll position of the page to remain the same. 

## Actual Result

BitWarden will scroll to the very bottom of the Secure Note. 

## Environment

- Device: iPhone 7+
- Operating system: iOS 14.4
- Build Version: 2.8.0 (449)
- Is this a Beta release? No

**Comment by k-matti** [comment]
Have the same issue. Any info about fix progress?

**Comment by duianto** [comment]
I'm seeing the same thing.
- Bitwarden Version: 2.10.0 (616)
- iOS 14.4.2 (18D70)
- iPhone X

On an iPhone X, fifteen and a half lines fit on screen at the same time while editing a note.
If the note has twenty lines, and the cursor is placed on any of the first four lines.
Then the twentieth line at the bottom of the note scrolls into view,
and the first four lines and the cursor scrolls up behind the top bar.

This makes it difficult to select and edit text at the beginning of a long note.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1257
