### ISSUE TITLE
iOS - Cannot change to certain keyboard languages when editing password fields

### ISSUE THREAD

**Issue by BlueGreenMagick** [bitwarden/android#1258]
## Describe the Bug

It is not possible to change keyboard language when editing custom field value of type ‘hidden’. The language button does not show up for that specific text input.

## Steps To Reproduce

1. Go to 'add item/ existing login item’
2. Click on 'new custom field’
3. Select type: hidden
4. Create a field with some random name
5. Click on the field value text bar
6. The keyboard does not have the language button between the number ‘123’ button and the whitespace button.

## Expected Result

I should see the language button between the number(special character) button and space.

## Actual Result

Does not appear

## Screenshots or Videos

 

Unable to screen capture with keyboard

## Environment

- Device: iPhone SE 2
- Operating system: iOS14.4
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (449)
- Is this a Beta release? N

## Additional Context

The language button appears in every other text fields, including when editing custom field of type ‘text’.

**Comment by Greenderella** [comment]
Hi @BlueGreenMagick, I have the same device, same Bitwarden and iOS version, and I'm unable to reproduce this issue:
![image](https://user-images.githubusercontent.com/5418577/107350768-2153a500-6aca-11eb-953a-f6ebc2058131.png)

What's your default language? I'm testing it with English and Spanish, but maybe the issue arises on other languages I don't know.

**Comment by BlueGreenMagick** [comment]
Sorry! I meant when editing field value, not field name. Edited the post accordingly.

**Comment by Greenderella** [comment]
Same thing, I'm still able to see the globe button, it doesn't matter if I'm editing the value or adding it, or which type of custom field I chose.

Will you try uninstalling the application, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

**Comment by BlueGreenMagick** [comment]
I've tried with other languages, and it looks like only keyboards for languages like Chinese(Pinyin), Korean, and Japanese(Kana) do not show up on hidden custom value text field. I found that other languages such as Spanish or Arabic _do_ show up.

I can reproduce this on my iPad as well, so it's unlikely to be a device specific issue.

**Comment by BlueGreenMagick** [comment]
It's not just the custom values field, but also the password field - Korean keyboard does not show up, but Spanish does.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1258
