### ISSUE TITLE
part of password is inserted into username 

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/android#1259]
## Describe the Bug

The username from auto-fill contains a few additional characters from password

## Steps To Reproduce

1. Install GWCU mobile app com.softek.ofxclmobile.goldenwestcu
2. auto-fill it  (add entry if you don't have any)

## Expected Result

Username and password are auto-filled correctly.

## Actual Result

 Bitwarden insists on concatenating the username (which is shortened by 4 letters) and last 4 characters of the password in the username field (dale%^dD).  %^dD are the last 4 characters of the password.  

## Environment

- Operating system: Android 
- Build Version: 2.8.1
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1259
