### ISSUE TITLE
Firefox 86.x - only searches for base domain regardless of URI match settings. 

### ISSUE THREAD

**Issue by jeffshead** [bitwarden/android#1275]
## Describe the Bug
When using the Android app to auto-fill a login form on a webpage in the Firefox for Android browser, I get, "There are no items in your vault for mysite.com.

## Steps To Reproduce
1. Go to website.
2. Touch the password filed to display the Auto-fill with Bitwarden pop-up.
3. Touch the Bitwarden Auto-fill pop-up which opens Bitwarden.

## Expected Result
You should see a list of matching logins.
## Actual Result

Get a warning that there are no matching items in the vault.

## Environment

- Device: Samsung Galaxy S7
- Operating system: Android 8
- Build Version 
- Is this a Beta release? No

## Additional Context

The problem is that the webpage URL is **https://www.mysite.com** but Bitwarden is searching for matches for **https://mysite.com**. As a work around, I can add **https://mysite.com** as a second URI to the matching logins and then Bitwarden lists the matching logins but I should not have to do this. For some reason, BW is only looking for matches to the base domain, not the subdomain. It does not do this if I use the Chrome browser on the same phone.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1275
