### ISSUE TITLE
Crash at Start on Android app

### ISSUE THREAD

**Issue by drbeco** [bitwarden/android#1279]
My phone is a:

* Asus Zenfone 5 selfie
* Model ASUS_X017D
* Android 9
* Kernel 3.18.115
* CPU 1.4 GHz 
* RAM 4Gb with 1.9GB free
* Internal 64GB with 24GB free
* SD 64GB with 62GB free

There is a timed crash at this exact time, to help you guys find in the logs:
20/Feb/2021, exactly at 11h00 GMT-3.

App crash on start up.
No cache cleaning solve it. It won't start in any way.

I also tried to uninstall, reboot and reinstall at least 4 times, to no avail.

I also got an email from support from Mister Suliman, and replyed there with a link to this issue.

I just rebooted and tried again, 21/Feb/2021, more or less at 8h30 GMT-3.

(I replied also to an old issue, but I think it is better to start a new one, since the old one is for Android 7, link: https://github.com/bitwarden/mobile/issues/616 )

Thanks for helping.

**Comment by drbeco** [comment]
With the help of support, I also tested:

* uninstall
* hard reboot mobile (with power-off and power-on)
* reinstall from google play store
* try opening it
* clear cache and data
* try opening it again
* uninstall
* install from F-Droid
* try opening it
* clear cache and data
* try opening it again
* hard reboot
* try opening it again
* uninstall
* wait for a miracle

No luck until now. Thanks for looking into it.

**Comment by tiagoposse** [comment]
Also [1212](https://github.com/bitwarden/mobile/issues/1212)

**Comment by drbeco** [comment]
Not exactly the same, but related.

My case, it shows only the LOGO screen, but I never get to see the LOGIN screen.

After the LOGO shows for about 2 seconds, the app simply closes.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1279
