### ISSUE TITLE
Deleting Bulk Passwords freezes UI

### ISSUE THREAD

**Issue by ncodee** [bitwarden/android#1291]
## Describe the Bug

I have over 2k passwords, and I wanted to delete in bulk, by using the web UI select all method, but the UI keeps hanging/freezing, and after a while stops responding with a white screen. I'm not sure it's quitely deleting everything in the background, as there is no indication that it's actually doing anything, however only a select few passwords had been removed.

Maybe we could have some sort of indication, that it's processing in the background?

I should point out, this is by deleting using 'Select all' method, and not using Purge Vault button.

## Steps To Reproduce

1) Select All passwords
2) Click Delete selected
3) Freezes after clicking Delete on prompt

## Expected Result

Delete the passwords, and not freeze.

## Actual Result

The UI freezes, making it unsuable. I have to close the tab, then reload again.

## Environment

Self-Hosted Docker, on the web UI

**Comment by cscharf** [comment]
Thanks for this report, we'll take a look at this, not sure we've tested a bulk delete with this quantity/volume before.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1291
