### ISSUE TITLE
Bitwarden and Maxthon browser on android

### ISSUE THREAD

**Issue by Ices-Eyes** [bitwarden/android#1300]
## Describe the Bug
On Maxthon browser on Android, when you go to an inpur box and tap on the bitwarden banner, the app open to select the account to use but the list search for mx.browser app instead of the website you are browsing 

## Expected Result
The list to choose from should be of website' associated accounts, not for the app itself

## Actual Result
The app shows matching entries (none) for mx.browser app

## Environment

- Device: Huawei P20
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1300
