### ISSUE TITLE
Match detection "starts with" and "exact" dont't work on Android

### ISSUE THREAD

**Issue by yurividal** [bitwarden/android#1302]
Chrome 90
Android 11

The only match detection that seems to work on Android is "host".
I have some different services in things like:

domain.com/app1

domain.com/app2

domain.com/app3

I have set the different match detections to be "starts with".

It works fine on desktop,  but on Android it does't match, and I have to manually search every time.

**Comment by MexHigh** [comment]
May be related to #578

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1302
