### ISSUE TITLE
Emoji passwords incorrectly displayed

### ISSUE THREAD

**Issue by edent** [bitwarden/android#1310]
## Describe the Bug

My password is a string of Emoji `✅🐎🔋📎`

It displays as `✅������`

![Emoji Test](https://user-images.githubusercontent.com/837136/110757200-0730f200-8243-11eb-8101-02227daef289.jpg)

When copied, the password is correct - it is only the display that is corrupted.  All other fields display emoji correctly.

## Steps To Reproduce

1. Create a new entry
2. Paste or type emoji into the password field
3. Save the password
4. View the password.

## Expected Result

The password should display the emoji - not a series of Unicode replacement characters.

## Screenshots or Videos

This also occurs on the Desktop app (Linux) and the browser extension.  I can raise bugs on those repos if necessary.

### Browser
![Screenshot from 2021-03-11 08-16-12](https://user-images.githubusercontent.com/837136/110757395-3fd0cb80-8243-11eb-922a-dee4a43c5f7e.png)

### Desktop Linux
![Screenshot from 2021-03-11 08-14-14](https://user-images.githubusercontent.com/837136/110757397-40696200-8243-11eb-8d8c-ddcb3f4b7acc.png)

### Web Vault
This displays the password properly
![Screenshot from 2021-03-11 08-26-23](https://user-images.githubusercontent.com/837136/110757650-8b837500-8243-11eb-8269-1c91dda76407.png)

## Environment

- Device: OnePlus 5T
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Is this a Beta release? N

## Additional Context

I know that having [an emoji password is a stupid idea](https://apple.stackexchange.com/questions/202143/i-included-emoji-in-my-password-and-now-i-cant-log-in-to-my-account-on-yosemite)!

**Comment by eliykat** [comment]
@gryffs, this is the mobile version of the bug we discussed here: https://github.com/bitwarden/jslib/pull/354#issuecomment-853578031.

Please let me know if it's still on your radar. It's not urgent, just keeping track of things.

**Comment by gryffs** [comment]
Thanks @eliykat , things did get a little crazy for me recently, but I hope to jump on this issue soon and will reach out with any questions.

**Comment by idarlund** [comment]
Just experienced this bug today. Have you had a chance to look at it @gryffs?

**Comment by mhmatthewhugley** [comment]
Parity between versions would be great considering this was fixed on desktop and browser extensions. https://github.com/bitwarden/clients/issues/1682 https://github.com/bitwarden/desktop/issues/768

**Comment by edent** [comment]
Happy 3rd birthday to this little bug!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1310
