### ISSUE TITLE
Match detection does not work reliable with iOS Auto-fill

### ISSUE THREAD

**Issue by fysch** [bitwarden/android#1325]
## Describe the Bug

iOS Auto-fill recommends an account, that does not match the previously set match detection rules.
This does only affect the suggestion above the keyboard and inside the popup, which opens, when you press the the key-icon at the top-right of the keyboard.

## Steps To Reproduce

1. Create multiple accounts in Bitwarden.
Default match detection: Base domain
**Account 1:**
URI 1: https://tu-braunschweig.de
Match detection: Base domain
URI 2: https://tu-bs.de
Match detection: Base domain
**Account 2:**
URI: https://aura.sz.etc.tu-bs.de/
Match detection: Host
**Account 3:**
URI: https://www1.unisport.etc.tu-bs.de/
Match detection: Host

2. Use an iOS device and visit https://studip.tu-braunschweig.de
3. Click "Login"
4. Choose TU Braunschweig as Identity Provider
5. You should be redirected to https://sso.tu-bs.de
6. The iOS Auto-fill suggestion will be Account 2
7. If you click the key icon in the top-right corner, iOS will suggest Account 2 and Account 3

## Expected Result

iOS should suggest Account 1 and not Account 2 or 3.

## Actual Result

iOS suggests Account 2 & 3.
If you use the Bitwarden extension (accessible through the share menu), the Bitwarden overlay suggests Account 1, as expected.
The Browser extension (tested with Chrome and Firefox on Linux and Windows) does also suggest Account 1.

## Screenshots or Videos

![bitwarden_chrome](https://user-images.githubusercontent.com/21131438/111601438-a40b0680-87d2-11eb-9931-96399527f542.png)
![bitwarden_ios_1](https://user-images.githubusercontent.com/21131438/111601445-a53c3380-87d2-11eb-9a26-83c97cf54f5f.PNG)
![bitwarden_ios_2](https://user-images.githubusercontent.com/21131438/111601447-a53c3380-87d2-11eb-8ded-afb5b84d8ec4.PNG)

## Environment

- Device: iPhone 8 Plus and iPad
- Operating system: iOS 14.4.1 and iPadOS 14.4.1
- Is this a Beta release? N

**Comment by Trapperjohn61** [comment]
I am also having the same problem when using a port on the end of a url if the same url is listed in bitwarden several times but with different ports even if i use host in uri it does recognize the specific port

**Comment by aiotter** [comment]
I have the same issue with my university account. In my case it is like below.

Account 1: student.iimc.kyoto-u.ac.jp (Base domain)
Account 2: www.alumni.kyoto-u.ac.jp (Host)

When I access to https://student.iimc.kyoto-u.ac.jp and click Login button, it redirects to https://authidp1.iimc.kyoto-u.ac.jp/...
Although only Account 1 should be suggested, iOS does suggest Account 2 at the top of the list, and also Account 1 as the second option.

Bitwarden extension from the share menu suggests only Account 1 as expected. The Safari extension and Brave extension on macOS also suggests only Account 1.

I use iPhone SE (2nd gen) with iOS 15.0. I have been suffering from this issue since I registered these websites to my Bitwarden account (~1.5y before).

**Comment by petertadrous** [comment]
I'm also having this issue, iOS 15.5 on iPhone 12 Pro Max. Using a local IP Address with a port.  


Saved logins:
- Account #1:
  - uri: '192.168.1.123:1234'
  - match type: 'Starts With'
- Account #2:
  - uri: '192.168.1.123:7825'
  - match type: 'Starts With'
- Account #3:
  - uri: '192.168.1.123:5728'
  - match type: 'Starts With'
- Account #4:
  - uri: '192.168.1.123:1236'
  - match type: 'Starts With'

When accessing any of the above addresses on safari on iOS, it will recommend the logins for all of them at once. On my PC on google chrome, the match detection type is respected

**Comment by bverkron** [comment]
In the process of migrating from 1Password to BW and just found out about this issue after setting up auto fill on IOS. Really bummed this is the case. URL matching is one of the primary reasons I wanted to move to BW and it doesn’t work on iOS. 😞

**Comment by M4RC02U1F4A4** [comment]
I noticed that the problem in my case occurs only with the .xyz TLD, maybe it could be something related to some TLDs not being recognized correctly

**Comment by maisen20** [comment]
Any news on that? i have many websites which only has different ports and now i always see all stored passwords for the same ip/main domain. very bad and it‘s not usefull at all, because often the login username is the same (for example my mail address).

**Comment by pduchnovsky** [comment]
Same problem here, honestly very annoying. :/

**Comment by bverkron** [comment]
I haven't tried it yet but 1Password seems to now support matching on port as well. Might be time to switch back.

> You’ll see the item as a suggestion only if the domain (hostname and port) is an exact match.

https://support.1password.com/autofill-behavior/

**Comment by ishanjain28** [comment]
2 years and this continues to be a problem

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1325
