### ISSUE TITLE
Auto-fill Not Working: Via Browser 4.2.3 on Android 10

### ISSUE THREAD

**Issue by CNDVidel** [bitwarden/android#1327]
## Describe the Bug

The auto-fill function does not work in the Via Browser version 4.2.3 on Android 10. I've tested it in the Chrome browser for Android and it works fine there.

## Steps To Reproduce

1. Go to any login page in the Via browser
2. Click on the Username/Password field

## Expected Result

A small popup should appear with either a list of available logins from my Bitwarden vault and/or an option to go to my vault.

## Actual Result

Nothing pops up at all.

## Environment

- Device: CWOWDEFU F10W(F10W) Tablet
- Operating system: Android 10 API29
- Build Version (go to "Settings" → "About" in the app): Version: 2.9.1 (3444)
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1327
