### ISSUE TITLE
Android - Bitwarden does not offer to autofill basic access authentication prompts when logging into a website.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1328]
## Describe the Bug
Bitwarden does not offer to autofill the basic access authentication prompts / windows on Android via Chrome or Firefox.

## Steps To Reproduce
1. Open Chrome or Firefox.
2. Go to http://iimei.co.uk/btech7/
3. Try to autofill.

## Expected Result
For Bitwarden to prompt to autofill.

## Actual Result
Bitwarden does not prompt to autofill.

## Screenshots or Videos
N/A.

## Environment
- Device: Samsung Note10+.
- Operating system: Android 11.
- Build Version: 2.9.1.
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by AverytheFurry** [comment]
Bitwarden almost never successfully prompts to autofill for me either, I have to click the text box, click something else, and then click the text box over and over until it decides to show the autofill box

**Comment by SergeantConfused** [comment]
This appears to work when using the Bitwarden add-on on mobile Firefox.

**Comment by NRG-600** [comment]
> This appears to work when using the Bitwarden add-on on mobile Firefox.

Did you tested this by yourself....?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1328
