### ISSUE TITLE
[iOS black/dark/nord theme] + / - buttons almost invisible / low contrast

### ISSUE THREAD

**Issue by kennymc-c** [bitwarden/android#1329]
## Describe the Bug

The plus and minus buttons in the generator tab are virtually invisible when using the black theme and have very little contrast with the dark and nord themes.

## Steps To Reproduce

1. Open the app
2. Go to Generator tab

## Expected Result

Plus / Minus Buttons should be brighter to be visible (black theme) or have more contrast (dark / nord theme)

## Actual Result

Plus / Minus Buttons are almost invisible (black theme) or have too little contrast (dark / nord theme)

## Screenshots or Videos

black theme:
![IMG_0539](https://user-images.githubusercontent.com/14995555/111909194-9a94cf00-8a5c-11eb-92c1-098ec163e091.PNG)

nord theme
![IMG_0537](https://user-images.githubusercontent.com/14995555/111909209-a6809100-8a5c-11eb-9459-2e9d5e865737.PNG)

dark theme
![IMG_0538](https://user-images.githubusercontent.com/14995555/111909217-b304e980-8a5c-11eb-9cde-64b57fd7e445.PNG)

## Environment

- Operating system: iOS 14.4.1
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (544)
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1329
