### ISSUE TITLE
Persist notification is not persistent on Android

### ISSUE THREAD

**Issue by edouardmenayde** [bitwarden/android#134]
Persist notification can be swiped away on Android 6.

**Comment by kspearrin** [comment]
It should come back though, correct?

**Comment by edouardmenayde** [comment]
Sometimes but not always.
Why is this the notification not really persistent ? Could there be an option for persistent notification and swipable one separately, if the current behavior is the intended one ?

**Comment by kspearrin** [comment]
This is the expected behavior currently. It's not a [setOngoing](https://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing(boolean)) notification in terms of Android Development.

**Comment by louisgrasset** [comment]
So is there a way you add an option with a setOngoing notification ?

**Comment by kspearrin** [comment]
Would have to look into it. We'll need to update the ongoing notification with new "extras" each time the URI changes for the given webpage/app. Need to figure out how that is done.

**Comment by ecarl65** [comment]
I also have this issue rather frequently. I can't seem to do anything to make the notification appear when it's gone. I've tried going in and turning that setting off and on again, but it doesn't appear to work.

**Comment by andrebrait** [comment]
It doesn't even appear to me, Running Android 8.0 on a Zenfone 4.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/134
