### ISSUE TITLE
Sometime force close, cant open. Force clear data to use

### ISSUE THREAD

**Issue by oldman20** [bitwarden/android#1344]
## Describe the Bug
Sometime not usualy Bitwarden on my Samsung Note 9 OneUI2.5 force close, cant open. I must clear data of Bitwarden and login again to coninuosly using.

## Steps To Reproduce
Open direct Bitwarden or over any fiels have to fill user and password. All results just force close Bitwarden

4. Click on '...'

## Environment

- Device: Samsung Galaxy Note 9
- Operating system: android 10 OneUI 2.5
- Build Version (go to "Settings" → "About" in the app): 2.8.0
- Is this a Beta release? N

## Additional Context

This is logcat with keyword "bitwarden" i searched after force close app appear
> `<<< log_count = 28 >>> [03-30 10:59:22.912 3253:3253 E/AndroidRuntime] FATAL EXCEPTION: main Process: com.x8bit.bitwarden, PID: 3253 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) Caused by: java.lang.reflect.InvocationTargetException 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 	... 1 more Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key 	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:246) 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368) 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120) 	at java.security.KeyStore.getKey(KeyStore.java:1062) 	at crc64720bb2db43a66fe9.NavigationPageRenderer.n_onAttachedToWindow(Native Method) 	at crc64720bb2db43a66fe9.NavigationPageRenderer.onAttachedToWindow(NavigationPageRenderer.java:49) 	at android.view.View.dispatchAttachedToWindow(View.java:21304) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2571) 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225) 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126) 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999) 	at android.view.Choreographer.doCallbacks(Choreographer.java:797) 	at android.view.Choreographer.doFrame(Choreographer.java:732) 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:237) 	at android.app.ActivityThread.main(ActivityThread.java:8167) 	... 3 more Caused by: android.security.KeyStoreException: User authentication required 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1536) 	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248) 	... 28 more [03-30 10:59:25.205 19140:19140 E/AndroidRuntime] FATAL EXCEPTION: main Process: com.x8bit.bitwarden, PID: 19140 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) Caused by: java.lang.reflect.InvocationTargetException 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 	... 1 more Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key 	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:246) 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368) 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120) 	at java.security.KeyStore.getKey(KeyStore.java:1062) 	at crc64720bb2db43a66fe9.NavigationPageRenderer.n_onAttachedToWindow(Native Method) 	at crc64720bb2db43a66fe9.NavigationPageRenderer.onAttachedToWindow(NavigationPageRenderer.java:49) 	at android.view.View.dispatchAttachedToWindow(View.java:21304) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246) 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2571) 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225) 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126) 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999) 	at android.view.Choreographer.doCallbacks(Choreographer.java:797) 	at android.view.Choreographer.doFrame(Choreographer.java:732) 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:237) 	at android.app.ActivityThread.main(ActivityThread.java:8167) 	... 3 more Caused by: android.security.KeyStoreException: User authentication required 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1536) 	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248) 	... 28 more [03-30 11:19:14.633 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Freezeable -> Frozen, Reason: Binder(1)-mismatch) [03-30 11:19:14.633 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(22062) [03-30 11:19:14.634 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(0), reason: Bg [03-30 11:20:30.138 975:1261 V/AlarmManagerEXT] AppSync scheduleAlarms: changed --- PendingIntent{9e2f88c: PendingIntentRecord{5a6abd5 com.x8bit.bitwarden broadcastIntent}} [03-30 11:20:30.139 975:1261 D/FreecessController] UFZ : com.x8bit.bitwarden(22062) [03-30 11:20:30.148 975:1261 D/FreecessController] UFZ : com.x8bit.bitwarden(0), reason: Alarm [03-30 11:20:30.156 975:1261 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: Alarm) [03-30 11:20:30.188 975:1261 V/SamsungAlarmManager] Sending to uid : 10251 action=null alarm=Alarm{5df410a type 3 when 16441956 com.x8bit.bitwarden} [03-30 11:20:40.158 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Freezeable -> Frozen, Reason: Alarm) [03-30 11:20:40.160 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(22062) [03-30 11:20:40.162 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(0), reason: Bg [03-30 11:20:44.325 975:1448 D/FreecessController] UFZ : com.x8bit.bitwarden(22062) [03-30 11:20:44.326 975:1448 D/FreecessController] UFZ : com.x8bit.bitwarden(0), reason: Binder(1)-mismatch [03-30 11:20:44.332 975:1448 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: Binder(1)-mismatch) [03-30 11:20:44.499 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: uidIdle) [03-30 11:20:47.593 975:2913 I/sysui_multi_action] [757,906,758,4,806,com.tencent.mobileqq,871,com.tencent.mobileqq.activity.ForwardRecentActivity,908,com.x8bit.bitwarden,1452,0,1456,2134215097] [03-30 11:20:50.743 975:4039 I/sysui_multi_action] [757,907,758,4,806,com.tencent.mobileqq,871,com.tencent.mobileqq.activity.ForwardRecentActivity,908,com.x8bit.bitwarden,1454,1,1456,2134215097] [03-30 11:20:50.744 975:4039 I/sysui_multi_action] [757,919,758,4,806,com.tencent.mobileqq,871,com.tencent.mobileqq.activity.ForwardRecentActivity,908,com.x8bit.bitwarden,1455,1,1456,2134215097] [03-30 11:21:53.967 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: uidIdle) [03-30 11:22:03.971 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Freezeable -> Frozen, Reason: uidIdle) [03-30 11:22:03.972 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(22062) [03-30 11:22:03.973 975:2501 D/FreecessController] FZ : com.x8bit.bitwarden(0), reason: Bg [03-30 11:22:32.861 975:2945 D/FreecessController] UFZ : com.x8bit.bitwarden(22062) [03-30 11:22:32.863 975:2945 D/FreecessController] UFZ : com.x8bit.bitwarden(0), reason: Binder(1)-mismatch [03-30 11:22:32.878 975:2945 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: Binder(1)-mismatch) [03-30 11:22:33.093 975:2501 D/FreecessController] com.x8bit.bitwarden(state: Initial -> Freezeable, Reason: uidIdle) 
`

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1344
