### ISSUE TITLE
Android non-english Language Issue

### ISSUE THREAD

**Issue by isacfjr** [bitwarden/android#1347]
There’s an issue with the Android App version.
(please forgive me if this is not the right place for bug report)

When system language is changed, for example, to Portuguese (Brazil) - after the reboot Bitwarden’s Auto-fill services are not shown as ENABLED anymore in its’ Settings screen (and user is not able to change its state either). Its fill-in feature also doesn’t show up on browsers like Vivaldi that requires use of draw-over.

If the user changes the system back to English, after a Reboot everything works fine: auto-fill and draw-over, also settings screen.

Attached screen:

![Bitwarden language bug](https://user-images.githubusercontent.com/81274728/113199497-911a1c80-923d-11eb-93ad-d8fc2f413858.jpg)

## Environment

- Device: Xiaomi Mi 9
- Operating system: Android 10 (MIUI 12.0.4)
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (3444)
- Is this a Beta release? N

**Comment by Greenderella** [comment]
I have tested this with 2 different Xiaomi devices but none of them uses MIUI, and I'm unable to reproduce this issue, maybe it's OS/MIUI related?

**Comment by isacfjr** [comment]
> I have tested this with 2 different Xiaomi devices but none of them uses MIUI, and I'm unable to reproduce this issue, maybe it's OS/MIUI related?

Hi, @Greenderella 
I cannot affirm if it's a MIUI or non-english specific but I can asure same configuration worked fine in other password manager - lastpass.
It seems to be something worth to take a deeper look since others already reported similiar issues for both other languages on MIUI or EMUI here on Github. I have tried many ways to reconfigure but no luck - after some time same issue.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1347
