### ISSUE TITLE
New items being saved to incorrect folder when using Safari autofill

### ISSUE THREAD

**Issue by hampton8** [bitwarden/android#1353]
When I create a new login entry using the autofill prompt within Safari on iOS and select a folder, the new login item is actually saved to the folder the comes after the one selected. ~~For example: let's say I have three folders - A, B and C - and I create a new login entry in my BitWarden vault using the Safari autofill interface, and I choose to save the new entry to folder B. When I open the BitWarden app, I will find that the new entry has in fact been saved to folder C, not B.~~ **See my comment below for a more accurate description.**

**Comment by SergeantConfused** [comment]
Hi there,

I opened Safari, went to https://vault.bitwarden.com/#/, tapped on the email address field, tapped on the Key above the keyboard, tapped on Bitwarden, then created a new item and assigned it to Folder 'B' and it was saved into folder 'B', not 'C'. I've tested this on an iPhone SE 2020 running iOS 14.4.1. Please uninstall Bitwarden off your iOS device, turn your device off and back on, reinstall Bitwarden from the Apple App Store, and let me know if this behaviour persists.

I thank you in advance for your understanding and cooperation.


All the best,

**Comment by hampton8** [comment]
Hi @SergeantConfused 

I've uninstalled Bitwarden, turned my phone off and on again, and reinstalled it, and I can confirm that the issue is still present - although it seems my generalisation in the original post was wrong, since strangely when I create a folder called 'B' and save a login to it via Safari, it _does_ actually save there. However, for certain other folders it does not. Items saved to 'Productivity' are actually saved to 'Safes, Padlocks, Gates & Doors', 'School & College' are actually saved to the first subfolder ('School & College/School Name'), 'Shopping' becomes 'Social', 'Social' becomes 'Software Licences', 'Software Licences' becomes 'Technology' and 'Technology' becomes 'Travel'.

Other folders, however, work fine, including 'Banking', 'Health & Fitness' and 'Money'.

This issue is also present on my iPad Air 2, as well as my iPhone 11.

**Comment by lychengr3x** [comment]
I have the same issue. It seems that the folder is always to be the next in the sequence. 🤔

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you, @hampton8, for your detailed response. I was able to reproduce this behaviour on iOS 17.0.2 with Bitwarden 2023.9.1, and have flagged this internally to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.


Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1353
