### ISSUE TITLE
Punycode domains don't work properly

### ISSUE THREAD

**Issue by AFakeman** [bitwarden/android#1356]
## Describe the Bug

If you use non-ASCII domain name for your own deployment, you cannot input it directly into the application.

## Steps To Reproduce

1. Set up a Bitwarden Server on hostname like "битварден.host.example"
2. Try putting it into the mobile app
3. Try logging in

## Expected Result

The application works just as if you used a regular ASCII domain

## Actual Result

An error pops up, saying that this domain is not supported

## Environment

- Device: iPhone XR
- Operating system: iOS 14.4.2
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (544)
- Is this a Beta release? N

## Additional Context

Encoding punycode and putting it as xn-… works, but is inconvenient to keep the encoding somewhere or using a tool each time.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1356
