### ISSUE TITLE
Android and iOS - If Unlock with Biometrics is Enabled, Bitwarden would still lock the vault even if the Vault Timeout is set to Never.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1363]
## Describe the Bug
If you set your Vault Timeout to Never and leave Unlock with Biometrics Enabled, Bitwarden would still lock the vault when you reboot the device. If Unlock with Biometrics is Disabled, the vault remains unlocked after rebooting.

## Steps To Reproduce
1. Set your Vault Timeout to Never.
2. Set your Vault Timeout Action to Lock.
3. Enable Unlock with Biometrics.
4. Reboot the device.

## Expected Result
For the vault to be unlocked.

## Actual Result
The vault is locked and biometrics are required to unlock it.

## Screenshots or Videos
N/A.

## Environment
- Device: Samsung Note 10+ and iPhone SE 2020.
- Operating system: Android 11 and iOS 14.4.2.
- Build Version: Android: 2.9.1 (3444) - iOS: 2.9.1 (544).
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by alexandrewurtzfr** [comment]
I have the same problem.
Safe expiration time configured forever, and digital unlocking.
After a while my volt locks up and I have to unlock it again with my finger.
On Android 11, version 2.9.1.

**Comment by doclucas** [comment]
Yes, this issue also happens with other set timouts, not only never.
Time outs such as until app restart or 4 hours are not respected. It always relock.

**Comment by Yash-Garg** [comment]
Is there any workaround for this? Because I am having the same issue on Android 11.

**Comment by escape0707** [comment]
This is not fixed.

But for now, if I select never and don't use biometric unlock, the PM should never lock again right?

Btw, the similar problem seems to happen on iOS version, too.

**Comment by JSK333** [comment]
I have the same issue on Android 12.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1363
