### ISSUE TITLE
Application theme ignored when launching with accessibility popup on Android

### ISSUE THREAD

**Issue by Nedlinin** [bitwarden/android#1364]
## Describe the Bug

The application theme does not appear to be respected when launching using the Accessibility/Autofill popup/popover on Android.

## Steps To Reproduce

1. Go to a website/application that has the autofill field detected.
2. Click on 'Auto-fill with Bitwarden...Go to my vault'

## Expected Result

The splash screen being the dark theme, not burning your retinas when you're in a dark room at 2AM.

## Actual Result

Splash screen is the white themed bright version.

## Screenshots or Videos

https://www.youtube.com/watch?v=wdFJR5spBVg
It is a bit hard to notice due to animation/loading speeds but the first load of the app you'll see it is using the dark theme for the splash screen (about the 1 second mark). Starting at 0:03, I close Bitwarden completely and launch it using the "Auto-fill with Bitwarden" autofill popup option in the browser and the splash screen is white (0:07 mark or so). -- Watching in quarter speed helps.

## Environment

- Device: S21
- Operating system: Android 11 - OneUI 3.1
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (3444)
- Is this a Beta release? I'm in the beta channel through Google Play.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1364
