### ISSUE TITLE
Unable to paste into master password field to log into bitwarden app

### ISSUE THREAD

**Issue by treewolf** [bitwarden/android#1372]
## Describe the Bug

Unable to paste a password into the "Master Password" field in order to unlock the bitwarden app.

## Steps To Reproduce

1. Open the bitwarden app
2. Press and hold in empty "Master Password" field

## Expected Result

A pop up menu should show and allow to paste into field.

## Actual Result

No menu is shown.

## Screenshots or Videos

None currently.

## Environment

- Device: Google Pixel 3
- Operating system: Android 11
- Build Version 2.9.1 (3444)
- Is this a Beta release? N

## Additional Context

The current workaround for this is to either:
* Type the password manually, or
* Type into the field a character, which then allows a paste menu to pop up

I find that after activating the field by entering a character, the field will continue to allow the paste-menu to show. Only on a a Fresh load of the unlock or login view does the issue occur.

**Comment by treewolf** [comment]
I saw a few issues open for similar fields being unpaste-able, but none for logging into the actual bitwarden app.

**Comment by jahway603** [comment]
Experienced this same issue and ended up having to manually type the password into the Android app. Unsure of what the fix would be.

Device: Google Pixel 4a
Operating system: Android 13
Build Version 2032.3.2

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1372
