### ISSUE TITLE
Android and iOS - Bitwarden does not update the 6-digit TOTP code when it's not in focus.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1376]
## Describe the Bug
When you switch away from viewing a vault item with a 6-digit TOTP code in Bitwarden, Bitwarden would not update the TOTP code when you switch back to it from another application on iOS. On Android, this happens when you turn the screen off and back on, when viewing the vault item.

## Steps To Reproduce
1. Add a test TOTP code to Bitwarden on iOS.
2. Add the same test TOTP code to Google Authenticator on iOS.
3. Return to Bitwarden and view the item with the TOTP code.
4. Use the App Switcher to focus on Google Authenticator.
5. Once the TOTP code changes in Google Authenticator, switch back to Bitwarden using the App Switcher.

## Expected Result
To see the updated 6-digit TOTP code in Bitwarden.

## Actual Result
You see the last 6-digit TOTP code in Bitwarden.

## Screenshots or Videos
N/A.

## Environment
- Device: iPhone SE 2020.
- Operating system: iOS 14.4.2.
- Build Version: 2.9.1 (554).
- Is this a Beta release? N.

## Additional Context
On Android, you can open Bitwarden and view the vault item with the TOTP code, turn the screen off and wait 30 seconds, turn it back on, and you'll see the same code.

**Comment by CJStylesOrg** [comment]
Hey! Some additional info is that no matter what.. it'll copy the updated totp code when autofilling, It will not copy the code that stays there when you're not focused on the app or if phone is shut. though this weird glitch should still be looked into.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1376
