### ISSUE TITLE
Difficult to capture barcode for authenticator

### ISSUE THREAD

**Issue by lloricode** [bitwarden/android#1378]
## Describe the Bug
When capturing bar-code for authenticator, the camera result is not proportion

this is the actual photo https://bit.ly/2QK5eUs
and this is the result https://bit.ly/3sB1DFy it becomes rectangle (sorry for blur image)

and  too difficult capturing, sometime crash the app itself

## Steps To Reproduce

1. Select any login
2. Click edit button
3. Click camera logo for capturing barcode for authenticator

## Expected Result

Its capture easily

## Actual Result

difficult to capture image, the image capturing is not proportion result, sometimes crash it
## Environment

- Device: Samsung A51
- Operating system: Android 11
- Build Version 2.9.1 (3444)  
- Is this a Beta release? N

**Comment by apjyotirmay** [comment]
+1 facing the same issue here. Sometimes I need to do multiple attempts to get it done, and sometimes it works flawlessly. 

Device: Galaxy Note 9
OS: One UI 2.5 (Android 10)
Build: Official one from play store

**Comment by empjustine** [comment]
Device: Samsung Galaxy A50
OS: One UI 3.1 (Android 11)
Build: Play Store 2.17.0

Collected stacktrace of the offending Camera event:
```
FATAL EXCEPTION: main
Process: com.x8bit.bitwarden, PID: 27983
java.lang.RuntimeException: Camera is being used after Camera.release() was called
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:2153)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8550)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by thomasbbrunner** [comment]
I am also facing the same issues: the shown camera output was distorted and the app crashed when reading the QR code.

Tried multiple times with no success.

Running Android 12 on a Pixel 4a 5G with Bitwarden version 2022.05.0 (4636)

**Comment by fedemkr** [comment]
Hi, thank you all for the reports and the information. About the crashing there is already an issue #1228 and a fix for that #1942 that is going to be deployed in next release.
If there are more reports about crashing after the release please reopen #1228

**Comment by develop7** [comment]
@fedemkr yeah, the camera proportions are off for me too (Pixel 5 running Android 12)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1378
