### ISSUE TITLE
Search in mobile app does not include custom fields in the results but does in web vault

### ISSUE THREAD

**Issue by bleedashes** [bitwarden/android#1403]
## Describe the Bug

Search within iOS mobile app does not include custom fields in the results but does in web vault

## Steps To Reproduce

1. Login web vault
2. Click on search
3. Search for a custom field (e.g. PIN)
4. Entries were found
5. Open Bitwarden iOS app
6. Go to vault
7. Click on search
8. Search for a custom field (e.g. PIN)
9. No entries were found

The app can't find any results, even though in the web vault it can.
See attached screenshots.

## Expected Result

In my opinion the search in the mobile app should give the same result as in the web vault

## Actual Result

Currently the search result differs between mobile app and web vaul

## Screenshots or Videos

Webvault:
https://user-images.githubusercontent.com/40542903/118394490-592c3480-b645-11eb-8ab9-93c50dc9eada.png

iOS App:
https://user-images.githubusercontent.com/40542903/118394543-9264a480-b645-11eb-860a-55f22a372b63.jpeg

## Environment

- Device:  iPhone X
- Operating system: iOS 14.5.1
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (544)
- Is this a Beta release? N

**Comment by c02y** [comment]
It fails on Android too, I add some kind of info in the note field, as the tag for the same category.

**Comment by perariontaeadastra** [comment]
wow. this issue is 2 years old. 
wildcard search doesn’t work either for notes in ios and android.

**Comment by HarburGER** [comment]
Sorry to have to say this so clearly, but search on mobile devices is a load of shit.

Here's a comparison of search on iOS between BitWarden and SafeInCloud:


![comparison search function - BitWarden vs  SafeInCloud - on iOS _kleiner](https://github.com/bitwarden/mobile/assets/11475297/6be57342-2318-452b-8da5-07da3b17ae73)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1403
