### ISSUE TITLE
iOS - problematic Username “suggestions” in Edit Item

### ISSUE THREAD

**Issue by onshisan** [bitwarden/android#1413]
## Describe the Bug
When adding or editing items in iOS, the Username field is subject to “suggestions” that complicate accurate data entry.

Portions of certain email address domains (email being the most common username in my experience) are “corrected” to short words, which forces me to go back and edit them, spurious caps are inserted, or other miscellaneous autocorrect issues are introduced to the Username field.

## Steps To Reproduce
Create a new item and begin to enter any username that does not consist of “proper” dictionary words expected by iOS, which does not start with a capital letter, an email address with an unusual tld, etc., and this issue will be evident. 

## Expected Result
Keyboard entry accepted verbatim without interference from autocorrect.

## Actual Result
Entered characters are repeatedly adjusted according to autocorrect’s expectations. User must start entering text and then delete it in order to proceed, and this issue may recur later in the username (after “@“ in an email for example). Unnoticed corrections interfere with utility of Bitwarden.

## Environment

- Device: various recent iPhones
- Operating system: iOS 14.4.2
- Build Version 2.10.0 (616)
- Is this a Beta release? N

## Additional Context
Treating username more like password (not engaging autocorrect if possible) would seem to be an improvement here. Usernames should not be expected to be dictionary words or to correspond to grammatical or orthographic rules, so autocorrect handles them poorly.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1413
