### ISSUE TITLE
Android - Deactivating the screen lock and deleting the fingerprints causes Bitwarden to crash if it had 'Unlock with Biometrics' activated.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#1429]
## Describe the Bug
If Bitwarden has 'Unlock with Biometrics' activated and you deactivate the screen lock and delete the registered fingerprints, Bitwarden would start crashing when you launch it.

## Steps To Reproduce
1. Activate 'Unlock with Biometrics' in Bitwarden's Settings page.
2. Go to your device's Settings and deactivate your screen lock and delete the registered fingerprints.
3. Open Bitwarden.

## Expected Result
To be prompted to enter the master password.

## Actual Result
The application shows the splash screen for a second and then closes.

## Screenshots or Videos
N/A.

## Environment
- Device: Samsung Galaxy Note10+.
- Operating system: Android 11.
- Build Version: 2.10.0 (3516).
- Is this a Beta release? N.

## Additional Context
Rebooting the device does not help, but clearing the application's cache and data helps.

**Comment by JonasBernard** [comment]
I faced the exact same issue on my

- Device: Samsung Galaxy A8
- Operating System: Android 9
- Build Version: 2.10.0 (3516)
- Is this a Beta release? No

I also reset the app data and logged in again. Forcing an app stop did not work, and I could not get any log output (which is correct from a sercurity perspective).

**Comment by ccrowles** [comment]
Same issue here unfortunately, and somehow the removal of the biometric unlock on my phone also logged me out of my bitwarden browser session on my pc.

**Comment by dsrev** [comment]
Got the same issue yesterday. Clearing all application data helps.

- Device: realme 7
- Operating system: Android 10
- Build Version: 2.12.0 (3742)
- Is this a Beta release? N

**Comment by rhelminen** [comment]
Exact same issue here. Adding back the lock screen password and fingerprint didn't help, but reinstalling the app did.

- Device: Honor 10
- Operating system: Android 10
- Build Version: 2.12.0 (3742)
- Is this a Beta release? No

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1429
