### ISSUE TITLE
Bitwarden autofill service causes severe lag with Disqus comments

### ISSUE THREAD

**Issue by ghost** [bitwarden/android#1467]
## Describe the Bug

Enabled Bitwarden autofill service causes severe lag scrolling Disqus comments on webpages in Chrome and some Chromium derivatives on Android

## Steps To Reproduce

1. Enable Bitwarden autofill service
2. Go to the website, that uses Disqus for comments (example: https://www.androidpolice.com/2021/07/01/stadia-game-list/ )
3. Scroll to a comment section
4. Scrolling through them starts to stutter and lag. The more you load, the worse it gets. Looks like CPU is loaded a lot, since the device starts to heat up

## Expected Result

Normal, undisrupted browsing

## Actual Result

Severe stutter. Inability to normally navigate through page

## Screenshots or Videos

Video demonstration: https://drive.google.com/file/d/1WouyXKiYl1LrzG0JFFuyRQzEaBMiun2v/view
Screen recorning is only 30 FPS. Effect isn't as prominent. Stutter is most noticeable on a device with 120 FPS screen.

    0:00 - 0:40 - without bitwarden
    0:40 - 1:35 - with bitwarden

## Environment

- Device: Samsung Galaxy S10, Samsung Galaxy S21 Ultra
- Operating system: Android 11
- Build Version: 2.11.0, 2.11.1
- Is this a Beta release? No

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1467
