### ISSUE TITLE
Autofill in Firefox browser not working

### ISSUE THREAD

**Issue by NRG-600** [bitwarden/android#1479]
Expected behaviour : Tap on password field and type on Autofill and bitward should fill password

Steps to reproduce bug : Open firefox and navigate to instagram or Facebook and try to Autofill your passwords and username and you'll see a toast message saying no password field detected

Firefox  Version : 90.1.2
Android Version : 9 Pie
Android OEM : Huawei/Honor 9n

**Comment by julian-alarcon** [comment]
I got the same issue in Firefox 94.1, Android 12, Samsung Galaxy S21.

**Comment by julian-alarcon** [comment]
I found a workaround for Firefox here
https://github.com/mozilla-mobile/fenix/issues/20987#issuecomment-904772802

Workaround for this:
1- tap to password area
2- press to three dot to open Firefox menu
3- press outside of menu to close it

Also, there is bugzilla report https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1479
