### ISSUE TITLE
Passphrase generator in app extension does not use default options from main app

### ISSUE THREAD

**Issue by jamesmendel** [bitwarden/android#1485]
## Describe the Bug
When using Bitwarden to create new a new entry in iOS by launching the autofill "🔑 Passwords" menu, the password generator only allows for alphanumeric passwords to be generated, disallowing the option for passphrases.
This occurs even when the 'Generator' Tab in the app is set to Type: Passphrase

## Steps To Reproduce

1. Go to a site or app where there is a username / password field
2. Click on the username or password field
3. Click on '🔑 Passwords' in the autocomplete section
3. Click '+' in the top right
4. Click 'Generate Password'

## Expected Result
A selection box to choose between Password and Passphase would appear, or the setting would be inherited from the setting set in the app: Generator > Type: Password/Passphrase.

## Actual Result
The type can only be password.

## Environment

- Device: iPhone XS
- Operating system: iOS 14.6
- Build Version 2.11.1 (704)
- Is this a Beta release? N

**Comment by SergeantConfused** [comment]
Hi @jamesmendel,

I just tested this on an iPhone SE 2020 running iOS 14.7.1 and Bitwarden 2.11.1, and it was possible to create a passphrase from the autofill flow. Please retry this and after you tap on the '+', tap 'Generate password' and then on 'Password' under 'Type', and let me know if you're able to change that into 'Passphrase'.

Thank you in advance,

**Comment by jamesmendel** [comment]
PEBKAC
Not sure how that slipped through... You are correct the option does allow me to switch. I think it was in a previous version that I tried and could not get the switcher to appear.

However, I would like to add that at the bottom it says:
"Option defaults are set from the main Bitwarden app's password generator tool."
It does not seem that the passphrase options are being pulled through when using the autofill flow.
Each time I load it, it reverts back to password settings, ignoring the fact that when using the app I have the option 'Passphrase' selected.

**Comment by eliykat** [comment]
I added the passphrase option on this screen a while ago ^_^ It's possible that I missed applying the default options though, we can use this issue to track this defect instead.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1485
