### ISSUE TITLE
iPadOS - Cannot change password type when using Slide Over

### ISSUE THREAD

**Issue by shiftingsand** [bitwarden/android#1500]
## Describe the Bug

I encountered a scenario on an iPad where you cannot change the password type. The two choices are presented, but the "done" button is missing. That means you can't finalize your choice and switch to another password type.

## Steps To Reproduce

1. Hold the iPad in landscape mode.
2. Start another app in full screen mode.
3. Start Bitwarden in Slide Over mode.
4. Go to the password generator
5. Touch "Password" under "Type"
6. You are presented two choices but the "Done" button is missing. You cannot change password type.

## Expected Result

A toolbar with a "Done" button should appear above the two choices like it does when the app is in full screen mode.

## Actual Result

The type can only be password.

## Screenshots or Videos

![081421bitwarden](https://user-images.githubusercontent.com/31398736/129446698-6677abc5-9f01-457d-97ef-fdaa20dbbe3a.jpg)

## Environment

- Device: iPad Pro 11"
- Operating system: iPadOS 14.7.1
- Build Version: 2.11.1 (704)
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1500
