### ISSUE TITLE
ChromeOS: Bitwarden display blacked out when not on native display

### ISSUE THREAD

**Issue by au-82** [bitwarden/android#1501]
## Describe the Bug

The application window opens on an additional display monitor from the default, with the window title areas blue and a black window where the content is usually displayed.
## Steps To Reproduce

1. Open Application not on the default display for the tablet.

## Expected Result

Opening the application, shows the login screen or content.
## Actual Result

Open the application, show black blank window when not on the default device display.
## Screenshots or Videos

![image](https://user-images.githubusercontent.com/47090600/129449062-07119060-a047-4df0-a2b6-d66ad95bfc15.png)
## Environment
- Device: Pixel Slate
- Operating system: Chrome OS 92.0.4515.130
- Build Version (go to "Settings" → "About" in the app): 2.11.3 (3653)
- Is this a Beta release? N

**Comment by windowsdeveloperwannabe** [comment]
Same problem here. On the Chromebook's own display the app works fine, but if you drag it to an external screen it goes black.

Device: Acer Spin 513
Operating system: Chrome OS 102.0.5005.75
Build Version: 2022.05.0 (4636)
Is this a Beta release? N

**Comment by confused-nerd** [comment]
I'm also having the same problem:

Device: Pixel Slate
Operating system: Chrome OS 104.0.5112.105

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1501
