### ISSUE TITLE
Color coding for password is missing from iOS app

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/android#1516]
## Describe the Bug

iOS app used to have color coding for passwords to differentiate between character, number, & symbols.
The feature is used to be there but now it's missing.

## Expected Result

character, number, & symbols have different color

## Actual Result

character, number, & symbols have the same color
 
## Environment

- Operating system: iOS
- Build Version (go to "Settings" → "About" in the app): 2.11.1

**Comment by leo-lax** [comment]
Hi there!
Would there be any updates on this?
Appreciate it!

**Comment by eliykat** [comment]
Hi @leo-lax, I confirm we've reproduced this at our end, however I can't provide any specific timeline for a fix. We have to manage our resources across many bug reports, including higher priority defects that need attention first.

I'll add a help-wanted label in case anyone would like to take a look at it in the meantime.

**Comment by kspearrin** [comment]
It is my understanding that this is a Xamarin Forms bug and we are waiting for a fix from the Xamarin team.

**Comment by leo-lax** [comment]
Howdy! Would anyone happen to know if there are any developments on this? Much appreciated!
