### ISSUE TITLE
Cannot exit full screen on Pine Phone

### ISSUE THREAD

**Issue by NicholasConrad** [bitwarden/android#1532]
## Describe the Bug

Can enter full screen mode on pine phone, but then there is no way to exit full screen mode

## Steps To Reproduce

1. From pine phone select 'full screen' from the menu. 
2. Attempt to exit full screen mode
3. Be unable to

## Expected Result

There should be a way to exit full screen mode

## Actual Result

There is no way to exit fullscreen mode 

## Screenshots or Videos

Unfortuantely it is not possible to access the screenshot tool while in fullscreen mode :(

## Environment

- Device: Pine Phone community edition
- Operating system: Manjaro beta 7
- Build Version Cannot access build information while in full screen mode :(
- Is this a Beta release? Of the OS? Yes. Of Bitwarden? No?

**Comment by jwillikers** [comment]
Yep, just hit this using Plasma Mobile on the PinePhone.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1532
