### ISSUE TITLE
Refresh toggle needed for autofill

### ISSUE THREAD

**Issue by ristein** [bitwarden/android#1536]
### Steps To Reproduce

1. Add entry from PC
2. Go to website on mobile
3. click bitwarden
-> entry does not appear in list, swipeing down does not refresh

### Expected Result

swipeing down refreshes and gets new entry

### Actual Result

I have to close bitwarden autofill window, minimize browser/app, open Bitwarden, refresh manually, go to browser/app again, open bitwarden autofill again, now the item is there

### Operating System

Android

### Operating System Version

9-10-11

### Device

Oneplus 2, Oneplus 7 pro

### Build Version

2.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sso-bitwarden** [comment]
The "swipe down for refresh" needs to be turned on at Settings -> Sync.

**Comment by ristein** [comment]
I still can't refresh on the "items for xxx" page. This would solve the problem

**Comment by 1player** [comment]
> The "swipe down for refresh" needs to be turned on at Settings -> Sync.

The issue is not on the app, but when using autofill i.e. in Safari. There is no way of refreshing/syncing from the autofill popup. Either a refresh button/pull to refresh or automated sync would work. 

It's extremely annoying when trying to log in on a website whose password has just been created on another device.

**Comment by plantroon** [comment]
This still exists, I thought that something was wrong with my server that I need to go to the app every time and trigger a refresh. Really it would be a useful feature, either trigger a sync automatically when starting autofill popup or allow pull to refresh in the autofill popup.

**Comment by mind-overflow** [comment]
Bump on this feature, seems like a huge QoL improvement and very possible to implement. I can try to look into it, but I've only worked with Android, so I don't know if I'd be able to implement it for both platforms.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1536
