### ISSUE TITLE
Enabling Accessibility Service prevents from using "Swipe down from notification panel" option

### ISSUE THREAD

**Issue by novmikvis** [bitwarden/android#1539]
### Steps To Reproduce

1. Enable Bitwarden Accessibility Service under Accessibility tab
2. Enable "Swipe down from notification panel" either by going to Settings → Display → Home Screen or long pressing empty space on home screen and tapping Home screen settings.
Option may be also called "Quick open notification" panel or "swipe down to show notifications" depending on Android version

### Expected Result

I should be able to swipe down in any place on home screen to show notification toolbar

### Actual Result

Swiping down has no effect if Bitwarden Accessibility Service is enabled

### Screenshots or Videos

Video demonstration:
When Accessibility Service is disabled swipe down option works like intended
https://user-images.githubusercontent.com/6789264/133221196-9b3a8497-aef0-45a5-94d9-005c0260f3b9.mp4

### Operating System

Android

### Operating System Version

Android 8.1.0 LineageOS

### Device

Xiaomi redmi 4 prime

### Build Version

2.12.0 (3742)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1539
