### ISSUE TITLE
Browser crashes with hCaptcha when logging in to Discord

### ISSUE THREAD

**Issue by Khsmty** [bitwarden/android#1551]
### Steps To Reproduce

1. Enable 'Autofill service'
2. Open 'Chrome'
3. Access to 'https://discord.com/login'
4. Enter your login information and tap login button
5. Check "I am a human" in hCaptcha
6. Chrome crashes

### Expected Result

chrome does not crash and you can log in successfully.

### Actual Result

Chrome crashes and I can't log in

### Screenshots or Videos

https://user-images.githubusercontent.com/70151015/134791015-0b5d45f1-fd6f-4bad-9e10-a22af343c0c8.mov

### Operating System

Android

### Operating System Version

EMUI 11.0.0 (Android 10)

### Device

Huawei P30 (ELE-L29)

### Build Version

2.13.0 (3828)

### Beta

- [x] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi @tubuanha 

I'm unable to reproduce this issue with a Xiaomi Android 10 device + Bitwarden 2.13.0 (3828). Will you first try uninstalling the application, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Let me know if that helps.

**Comment by tubuanha** [comment]
I uninstalled the app, restarted and reinstalled, but it didn't improve.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1551
