### ISSUE TITLE
Password shows up briefly with Firefox on android

### ISSUE THREAD

**Issue by mawi675lr81** [bitwarden/android#1552]
### Steps To Reproduce

1. Go to website like github.com or instagram.com (ones I've tested)
2. Log into the site and the password shows up briefly

Behavior not observed in chromium based browser. Also uploaded a video of it

### Expected Result

Password must not show up

### Actual Result

Password shows up briefly

### Screenshots or Videos

https://user-images.githubusercontent.com/80794277/135189647-2552a332-d255-4a64-b70d-0551284db6fc.mp4

### Operating System

Android

### Operating System Version

11.0

### Device

OnePlus 5t

### Build Version

lineage_dumpling-userdebug 11 RQ3A.210905.001 3301ade7c6

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sso-bitwarden** [comment]
On Android, there is a setting to "show password briefly as you type". You can look for this setting and turn it off.

**Comment by mawi675lr81** [comment]
That setting is turned off but it still shows password. Again, no problem with chrome based browser that I tried

**Comment by Practicalbutterfly5** [comment]
This problem still exists. Is this a Firefox android issue?

**Comment by Glassertje** [comment]
i have the same issue. After some research i found out that it happens if i use accessibility to fill in the username/password. If i use the autofill on my the keyboard, than there is no issue. Because it is a security issue, I'm surprised that nobody seems to care about it.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1552
