### ISSUE TITLE
wrong OTP is copied

### ISSUE THREAD

**Issue by AnthillSudoku** [bitwarden/android#1554]
### Steps To Reproduce

1. open Bitwarden and unlock the vault
2. open Firefox and the site you want to login
3. select the right Bitwarden entry (and not open the vault even if it is already unlock)
4. login and paste the OTP

The OTP pasted is wrong

6. reload login page
7. choose to go open the vault (even if it already opened)
8. select the right entry
9. refresh the site (since the autofill option now is missing due to other bug)
10. login and paste OTP

Hopefully now the login succeed (but few times not)

In the settings my timeout of the vault is 5 minutes

Thanks

### Expected Result

correct OTP is pasted

### Actual Result

wrong OTP or no OTP at all is copied and pasted since paste result is a previous copy & paste session

### Operating System

Android

### Operating System Version

10

### Build Version

2.13.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sso-bitwarden** [comment]
Is your device's time being sync with the network?

**Comment by lucamp** [comment]
Yes, if I open Bitwarden and display or copy the OTP manually no issue

**Comment by nataloko** [comment]
it sounds same as #1207 and #494

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1554
