### ISSUE TITLE
List is obscured by the keyboard when searching for account for auto populating

### ISSUE THREAD

**Issue by 211217613** [bitwarden/android#1560]
### Steps To Reproduce

1. Go to an app and get to the password prompt
2. Sometimes the URI doesn't match the app so you need to click on the magnifying glass to search for an account
3. Scroll down to the bottom most entry in the search box.  Notice that the on screen keyboard is obscuring the bottom most entry in the search field and you can't click on the entry.

### Expected Result

The on screen keyboard should be the limit of the scroll for entries in your vault. So when you scroll all the way to the bottom you should see the last entry.

### Actual Result

When the list of entries in your vault is longer than the view, the last element in the window is obscured by the on-screen keyboard and can't be clicked.

### Screenshots or Videos

![IMG_1188](https://user-images.githubusercontent.com/7006850/135884011-b31a6907-17f4-472e-b45c-a1b99163eb88.jpg)
Notice the scroll bar indicator in the bottom right.

### Operating System

iOS

### Operating System Version

15.0.1

### Device

iPhone XR

### Build Version

2.13.0 (929)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1560
