### ISSUE TITLE
App crashed when using 3rd party launcher on IOS

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/android#1636]
### Steps To Reproduce

1. Install launcher app from https://www.cromulentlabs.com 
2. Add bitwarden and set the launcher to the home screen
3. Launch Bitwarden from the launcher shortcut

### Expected Result

Bitwarden is able to run

### Actual Result

Bitwarden crashed when launched from a fresh (system reboot) state.
Upon running the Bitwarden app manually, the launcher could successfully launch Bitwarden app

### Operating System

iOS

### Operating System Version

15

### Device

Iphone SE

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1636
