### ISSUE TITLE
Bitwarden pop-up box obstructing the input field on Android 12

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/android#1641]
### Steps To Reproduce

No particular steps, configure auto-fill as per normal.

### Expected Result

Pop-up box is drawn below the input field

### Actual Result

pop-up box obstructing the input field.

### Screenshots or Videos

![8Z1jVCh-u3vGJH-bLbTjlGH2IJ5wN3YFzQ](https://user-images.githubusercontent.com/75601583/141252718-d376f230-8b12-46f7-b8fc-5ab8ab6bc2c5.png)

### Operating System

Android

### Operating System Version

12

### Device

Pixel

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by hornetster** [comment]
Yes, have this issue.
Impossible to either manually insert a password (can't see the password to ensure correct), or paste (will not allow you to long press the field to bring up the paste option.)
Maybe an option to dismiss the Bitwarden prompt?

**Comment by voxitme** [comment]
This issue can be extended to Android 11 as well.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1641
