### ISSUE TITLE
Item password generator mistakenly shows policy management

### ISSUE THREAD

**Issue by luc-bw** [bitwarden/android#1643]
### Steps To Reproduce

1. Create new Login type item
2. Select the button to generate a password

### Expected Result

Password Generator loads without warnings.

### Actual Result

For a brief moment, the password generator incorrectly displays the notification that your generator settings are affected by an Organization policy. It then disappears.

### Additional Context

The Password Generator policy is not enabled.

This is tested using both an account that is part of an Enterprise Organization and an account that has no Organization associations.

This does not affect the Android application.

### Operating System

iOS

### Operating System Version

15.1

### Device

iPhone SE (2020)

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1643
