### ISSUE TITLE
Inline Autofill is barely visible in dark mode

### ISSUE THREAD

**Issue by uiii** [bitwarden/android#1670]
### Steps To Reproduce

1. Switch your phone to dark mode
2. Set `Use Inline Autofill` in Bitwarden's autofill settings
2. Go to any login form you have saved credentials for
3. Try to autofill (tap in the input field)

### Expected Result

Texts in the suggestions bar of the keyboard are **properly** visible when the system is in dark mode.

### Actual Result

Some texts in the suggestions bar in keyboard are **barely** visible when the system is in dark mode.

### Screenshots or Videos

![Screenshot_20211201-161629_Chrome](https://user-images.githubusercontent.com/179219/144261606-54746891-ee43-4190-8221-938f0a80c449.jpg)

### Operating System

Android

### Operating System Version

11

### Device

Samsung Galaxy S10e

### Build Version

2.14.2 (4005)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by uiii** [comment]
Just checked it works well in Android 12, Samsung One UI 4

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1670
