### ISSUE TITLE
adriond app bug: server use ssl  by nginx ,when login it show  java.security.cert.certpathvalidatorexception

### ISSUE THREAD

**Issue by baiyun1102** [bitwarden/android#1672]
### Steps To Reproduce

1. Go to 'adroin app.'
2. Click on 'login.'
3. Scroll down to 

### Expected Result

adriond app bug: server use ssl  by nginx ,when login it show  java.security.cert.certpathvalidatorexception:trust anchor for certification path not found

### Actual Result

fyi

### Operating System

Android

### Device

huawei p40

### Build Version

none

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1672
