### ISSUE TITLE
Cannot login to vault on Android app while using Wireguard VPN hosted on AWS

### ISSUE THREAD

**Issue by shahzainb** [bitwarden/android#1678]
### Steps To Reproduce

1. Launch Android app
2. Click on Log in
3. Fill in username and password
4. Click on Log In

### Expected Result

I should be logged in and able to access vault

### Actual Result

"An error has occured"

### Additional Context

I am running a unbound + Pi-hole + pi-vpn setup through Wireguard on AWS, with a static IP. Yesterday, I have suddently encountered the issue where I cannot login into the app at all. I checked pi-hole and nothing was being blocked there relevant to bitwarden. Calls to `api.bitwarden.com` are all passing through fine. 

On the same VPN, I can login through `vault.bitwarden.com` fine. I can login to the app without connecting to the AWS VPN, using my home network, which has mostly the same setup as the AWS server (unbound + pi-hole), but without the wireguard process. I tried to debug the pi-vpn instance, but couldn't find any issues there as the network requests didn't seem to reach at all. 

When I encountered the issue yesterday, I changed the static IP associated with the VPN instance on AWS, and am still facing the same issue, so it doesn't seem that it's a blacklisted IP problem. The issue is also persistent on another phone (Samsung Galaxy S21+) that I have the same VPN on too, but using a completely different Bitwarden account.

This has started happening since yesterday only and has been previously working fine.

### Operating System

Android

### Operating System Version

11

### Device

Sony Xperia 5 II

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by davidbuckleyni** [comment]
I failed to see how this is the developers bug. You have put extra vpn auth on ur connection. I have a feeling this will not be a bug.

**Comment by 0n** [comment]
I have the same issue on the default bitwarden servers and IPVanish's Montreal servers as my VPN, so I doubt it's a misconfiguration on your side

**Comment by GGYYNY** [comment]
Same issue. Cannot login thru VPN.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1678
