### ISSUE TITLE
iOS share sheet button disappears

### ISSUE THREAD

**Issue by kimjetam** [bitwarden/android#1685]
### Steps To Reproduce

1. go to “share” button in mobile Safari
2. either close the contextual menu OR click on bitwarden button, wait for bitwarden to open and then cancel it
3. go again to "share" button in safari
4. bitwarden button is missing

### Expected Result

bitwarden button should always be in contextual menu when clicking share button

### Actual Result

bitwarden button desappeard after provided steps

### Screenshots or Videos

![IMG_0078](https://user-images.githubusercontent.com/25957373/145671714-a984353f-c93d-4c87-8f23-9b9e5c60f13e.JPEG)
![IMG_0079](https://user-images.githubusercontent.com/25957373/145671721-d11651e7-44e5-4cc9-990a-7f962692c4db.JPEG)

### Additional Context

this problem can be resolved by closing up the and restarting safari, but with provided steps, the problem is back

### Operating System

iOS

### Operating System Version

15.2 (19C56)

### Device

iPhone 12

### Build Version

2.15.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1685
