### ISSUE TITLE
Android add app URI to existing entry

### ISSUE THREAD

**Issue by m3thm4th** [bitwarden/android#1696]
### Steps To Reproduce

When trying to autocomplete inside an app without candidates, there's only the option to create a new entry where only the URI field is filled with the app URI.

### Expected Result

There should be an option to select an existing entry and add that URI to that entry instead of creating a new entry from scratch.

### Actual Result

If an entry already exists this means you have to copy the URI and paste it in the correct entry.

### Operating System

Android

### Build Version

Any

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1696
