### ISSUE TITLE
Bitwarden does not work at all with duck duck go browser on Android

### ISSUE THREAD

**Issue by BeeFox-sys** [bitwarden/android#1697]
### Steps To Reproduce

1. install and set up bitwarden and duck duck go on Android
2. go to any site with a login function
3. wait for bitwarden to pop up and offer to open vault

### Expected Result

bitwarden pops up and you can access the vault to fill the login page

### Actual Result

nothing at all

### Additional Context

I have tried this with several combinations of accessibility settings, none worked. i have also tried various sites that work in Chrome, again, none worked

### Operating System

Android

### Operating System Version

Android 11, ColorOS 11.1

### Device

Oppo A53

### Build Version

2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by K-techie** [comment]
I have also faced this issue but i think this may happen due to aggressive tracker blocking on Duckduckgo

**Comment by gamebird92** [comment]
Having this issue too... that's why i had to switch back to firefox

**Comment by Des-Conocido-De** [comment]
Given this puff piece about DDG and bitwarden integration you might think this issue would be a priority.

https://9to5mac.com/2022/12/07/bitwarden-duckduckgo/

**Comment by owyongsk** [comment]
Could this be due to DDG mobile browser using Android Webview instead of its own browser?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1697
