### ISSUE TITLE
bitwarden not showing website logo/favicon in autofill prompt

### ISSUE THREAD

**Issue by sheikh-azharuddin** [bitwarden/android#1702]
### Steps To Reproduce

Try to login to any website for which bitwarden has saved credential.
It does not show the logo/favicon of the website in the autofill prompt even though vault item has logo

### Expected Result

Should show logo/favicon of the website in autofill prompt

### Actual Result

Logo/favicon not showing in autofill prompt

### Screenshots or Videos

![Screenshot_20211229-194626062 (1)](https://user-images.githubusercontent.com/58127841/147671546-5b4611cd-337d-4f49-a931-0ee17377fbf6.jpg)

### Operating System

Android

### Operating System Version

11

### Device

rog3

### Build Version

15.2

### Beta

- [X] Using a pre-release version of the application.

**Comment by sheikh-azharuddin** [comment]
Issue is still there..any update ?

**Comment by nd306hj** [comment]
Hi,  can i take this issue? @fedemkr

**Comment by djsmith85** [comment]
@nd306hj Thank you for your interest in tackling this. Feel free to create a PR and make sure to link it to this issue.

**Comment by meeddhhaa** [comment]
Hey @djsmith85 @sheikh-azharuddin I'm new to open source and I'd love to work on this.
Can you please give me some additional details on how to tackle this?

**Comment by djsmith85** [comment]
@nd306hj ,@meeddhhaa Thank you for offering your help with this. 

To get started, please read through our [Contribution Guidelines](https://contributing.bitwarden.com/). These will help you to get started and how to set up your development environment.

**Comment by XxBrezxX** [comment]
Hey, is this bug still active? I wanna contribute

**Comment by sheikh-azharuddin** [comment]
> Hey, is this bug still active? I wanna contribute

Yes still active

**Comment by RadoslavK1** [comment]
Hello, seeing as the last update was in the beginning of July, I assume it's still up for grabs? If so, I'd like to work on this.

**Comment by AkazaRenn** [comment]
Still seeing this issue with auto fill integrated into Gboard.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1702
