### ISSUE TITLE
"Disable Save Prompt" is ignored on Android 12

### ISSUE THREAD

**Issue by tangowithfoxtrot** [bitwarden/android#1703]
### Steps To Reproduce

1. Go to Bitwarden > Settings > Options > enable "Disable Save Prompt".
2. Attempt to log in to an app for the first time with a new account.

### Expected Result

No prompt will appear.

### Actual Result

The save prompt appears.

### Operating System

Android

### Operating System Version

Android 12

### Device

Pixel 3a

### Build Version

2.15.0 (4125)

### Beta

- [X] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Possibly solved by https://github.com/bitwarden/mobile/pull/1722

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1703
