### ISSUE TITLE
App crash if fingerprint unlock feature isn't working

### ISSUE THREAD

**Issue by stemy2** [bitwarden/android#1704]
### Steps To Reproduce

1. Configure the app so it has to be unlocked with fingerprint
2. For an unknow reason, the fingerprint features doesn't work anymore

### Expected Result

Ability to open the app, even when fingerprint unlock isn't working.

### Actual Result

The app crashes if i try to open it.

### Operating System

Android

### Build Version

Don't know since i can't even open the app

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1704
