### ISSUE TITLE
No refresh before autofilling

### ISSUE THREAD

**Issue by Fealthas** [bitwarden/android#1710]
### Steps To Reproduce

1. Make an new (non bw) account on a PC and save it in BW
2. download that accounts app on your phone
3. attempt to sign into your new account on the phone app using the autofill feature

### Expected Result

The proper account is found and auto-filled.

### Actual Result

Nothing is found, because the bitwarden app needs to be manually synced before anything shows up.

There is no way to sync on the autofill find credentials app page.

### Additional Context

This is incredibly irritating as it breaks the flow of using the app, which is otherwise quite easy to use.

I have to exit out of the app im trying to sign into, go to BW, manually sync, then go back into the app.

### Operating System

Android, iOS

### Device

iphone se gen 2

### Build Version

2.15.0 1225

### Beta

- [ ] Using a pre-release version of the application.

**Comment by kamild1996** [comment]
Still an issue year later. Tested on Android 12, app version 2022.11.0.

**Comment by kamild1996** [comment]
@SergeantConfused I can confirm this is still happening to me. Android 13, Bitwarden 2023.7.0 (self-hosted Bitwarden instance, if that matters). Here's how I reproduced it just now on my end:

- On PC through a browser extension, add credentials to a new website. The credentials are saved in the vault and I am able to use them immediately through the PC browser (Microsoft Edge).
- On my phone, I open the same website (also on Microsoft Edge), tap the password field to make my keyboard (Swiftkey) show up, then I choose "Unlock vault" from the inline autofill. 
- After unlocking the vault, I'm shown a message that no credentials are found. Even if I wait several minutes, the new credentials never show up on the phone. To make them show up, I have to open the Bitwarden app and pull down the list to make it sync.

**Comment by PermaFreez** [comment]
I would also really like this to finally work. It seems someone has already made a PR, but after 5 months it's still not included.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1710
