### ISSUE TITLE
Master password re-prompt option only prompts when editing, not when viewing

### ISSUE THREAD

**Issue by alexaka1** [bitwarden/android#1713]
### Steps To Reproduce

1. Open any item (eg. secure note) 
2. Enable master password re-prompt
3. Close the item
4. Open the item

### Expected Result

The item cannot be accessed (viewed) unless the user enters the MP again. 

### Actual Result

In the browser extension and web vault the above steps result in you having to re-enter your MP to even view the item. On mobile you can view the item without MP re-prompt, but when you edit it, it prompts you.

### Operating System

Android

### Build Version

Version: 2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1713
