### ISSUE TITLE
[Android] BitWarden crashes while opening the big Vault

### ISSUE THREAD

**Issue by yhnavein** [bitwarden/android#1715]
### Steps To Reproduce

1. Have at least 1000 items in the Vault. In my case it was close to 1500
2. Open BitWarden app on Android to see the Vault
3. In around 60% of cases app crashes

### Expected Result

App starts and I can see my Vault

### Actual Result

In circa 60% of cases BitWarden app crashes

### Additional Context

Because reliablility on my phone is crucial I migrated to other Password Manager last month after numerous crashes, so right now I cannot provide more details of the error (logs, etc). 
In the migration process I removed some of old passwords, so that there are now only 980 in my Vault.
I tried recently to open BitWarden with this limited amount of elements and apart from waiting for around 2-4 seconds to load the whole list, the app works stable.

Problem might have been fixed since last month. But it may be worth to see if it's still the case for anyone.

### Operating System

Android

### Operating System Version

Android 11

### Device

Oppo Reno 3

### Build Version

2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sso-bitwarden** [comment]
@yhnavein  Thank you for your report. I just tested with 2400 items and the app was loading fine.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1715
