### ISSUE TITLE
Vault Timeout on App Restart not respected

### ISSUE THREAD

**Issue by heiserhorn** [bitwarden/android#1718]
### Steps To Reproduce

Set Vault Timeout to  "On App Restart"
Under android settings --> Apps --> Bitwarden --> Battery Select unrestricted

### Expected Result

Should be able to autofill without having to enter password/pin unless I restart the app manually or I restart the phone

### Actual Result

After some time (varying) the vault is locked and I have to enter password/pin

### Additional Context

I am using only inline autofill.

### Operating System

Android

### Operating System Version

12

### Device

Pixel 6

### Build Version

SD1A.210817.036

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vinnyperella** [comment]
I'm having the same issue and it used to work up until I logged out today to try and fix another issue. I set up my PIN and select "Yes" when it asks "Do you want to require unlocking with your master password when the application is restarted?" Up until today that worked fine I would only get prompted for my master password when my phone restarted or the Bitwarden app updated but now every time I move away from Bitwarden when I go back it's always asking for my master password.

I've tried clearing data/reinstalling/rebooting phone and nothing seems to work.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1718
