### ISSUE TITLE
Sync fails when Google One VPN is enabled

### ISSUE THREAD

**Issue by jorickert** [bitwarden/android#1719]
### Steps To Reproduce
1. Enable the Google One VPN
2. Click on the "Sync vault now" button or wait for an automatic sync

### Expected Result

The vault gets synced

### Actual Result

The "Syncing..." spinner spins for a long time, before the message Syncing failed appears

### Additional Context

This only occurs when the Google One VPN is used.
When allowing Bitwarden to bypass the VPN the sync works flawlessly

### Operating System

Android

### Operating System Version

Android 12

### Device

Google Pixel 4a

### Build Version

2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ShellWen** [comment]
it works on my device

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1719
