### ISSUE TITLE
autofill not working on iOS 15.3 (both iPhone and iPad)

### ISSUE THREAD

**Issue by fearlessfara** [bitwarden/android#1754]
### Steps To Reproduce

1. try to access a network that requires username and password (for example, also crashes on normal websites)
2. Click on the memorised passwords system bar that appears
3. The selection for the username and password disappears from the system bar and no prompt for faceID or touchID is displayed

### Expected Result

I expect to be able to choose with which username/password i want to fill the form

### Actual Result

the autofill feature crashes and I cannot fill the form

### Operating System

iOS

### Operating System Version

15.3

### Device

iPhone 12, iPad Air 4th

### Build Version

2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1754
