### ISSUE TITLE
Android app no longer locks on vault timeout in version 2.16.1

### ISSUE THREAD

**Issue by dh024** [bitwarden/android#1772]
### Steps To Reproduce

1. In Settings, set Vault Timeout to any time increment (e.g., 1 minute)
2. In Settings, set Vault Timeout Action to Lock
3. On your device, navigate away from Bitwarden so that it is no longer in the foreground
4. Wait until the time interval selected above has passed
5. Re-open Bitwarden and there is no prompt to unlock the vault

### Expected Result

If the select Vault Timeout period has elapsed, the vault should automatically lock and the user should be presented with a challenge to unlock the vault, which is how it has worked in past versions (i.e., up to and including app version 2.15).

### Actual Result

In release 2.16.1, the vault does not lock and the user is not presented with a challenge to unlock the vault, even though the vault timeout period has elapsed.

### Additional Context

Issue reported on the Community Forums at: 
https://community.bitwarden.com/t/android-app-vault-lock-not-working/38010

### Operating System

Android

### Operating System Version

Android 12, kernel version 4.19.113-23195093

### Device

Samsung Galaxy S20 5G

### Build Version

2.16.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Thanks for the report @dh024, we'll take a look.
