### ISSUE TITLE
Touch ID instead of Face ID in prompts

### ISSUE THREAD

**Issue by the-woocash** [bitwarden/android#1790]
### Steps To Reproduce

1. On a Face ID equipped iPhone open Bitwarden or auto fill panel with biometric unlock enabled
2. Notice Touch ID instead of Face ID in prompts

### Expected Result

The prompt should ask for a Face ID not Touch ID authentication

### Actual Result

Touch ID is in the prompts. 

### Screenshots or Videos

![7AAA142B-016F-4875-9571-D3F7D9B3997C](https://user-images.githubusercontent.com/46818724/154820099-2afe72f5-677d-441a-89e1-97a01e126d2b.jpeg)
![6096D053-FCFA-4C87-B3CB-E7064537B4A0](https://user-images.githubusercontent.com/46818724/154820100-aaf801b2-414b-4047-a2d2-4927f97a9049.jpeg)

### Additional Context

Settings properly mention Face ID in the biometric setup menu item. 

### Operating System

iOS

### Operating System Version

15.4 beta 3

### Device

iPhone 13 Pro

### Build Version

Unable - app crashes when trying to scroll down 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by philipgo** [comment]
Do you use Bitwarden on another device with TouchID? For me this error occurs after unlocking Bitwarden on my ipad with TouchID.

**Comment by the-woocash** [comment]
Yes, i also use Bitwarden on an iPad with Touch ID. 
But still the wrong name for biometric unlocking is displayed on my iPhone always - independent of whether I have just used iPad or not.

**Comment by philipgo** [comment]
I have the same problem, but it started exactly in the moment when I installed Bitwarden on my iPad and activated TouchID.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1790
