### ISSUE TITLE
Autofill prompt blocks OK button for BankID, Android

### ISSUE THREAD

**Issue by plumber-craic** [bitwarden/android#1816]
### Steps To Reproduce

Using Android 11, and BankID, (electronic identification system in Norway with over 4m users) 
1. Unlock the phone
2. Initiate a BankID authentication session either on the phone or from a different device
3. The BankID prompt appears on the phone, providing a unique phrase
4. The next BankID screen requests a pin number
5. User enters their BankID PIN
6. The Bitwarden autofill prompt blocks access to the OK button, making it untappable. 

Workaround 1
1. enable rotation in Android. In landscape the OK button can be tapped after scrolling down

Workaround 2
1. keep the phone locked
2. Initiate a BankID authentication session
3. The Bitwarden autofill prompt does not appear, so the BankID OK button can be tapped in portrait mode

### Expected Result

The autofill "popover" should not block the OK button from BankID

### Actual Result

The autofill "popover" blocks the OK button from BankID

### Screenshots or Videos

Initial BankID prompt:
![2022-02-28 13_02_11-Screenshot_20220228-125553_SIM toolkit jpg ‎- Photos](https://user-images.githubusercontent.com/48294683/155980462-5ab09781-82de-4f62-8fc0-73e5c0a10239.png)

During step 2 the PIN should be entered. The Bitwarden overlay is blocking the OK button in portait mode. The overlay persists even after the user types values into this input field:
![2022-02-28 13_02_24-Screenshot_20220228-125609_SIM toolkit jpg ‎- Photos](https://user-images.githubusercontent.com/48294683/155980503-cfaeae64-2bbc-40e6-8d54-ebc02f69c2d1.png)

Using workaround 1, device is in landscape mode so the OK button is available:
![2022-02-28 13_02_02-Screenshot_20220228-125623_SIM toolkit jpg ‎- Photos](https://user-images.githubusercontent.com/48294683/155980561-df1384da-a404-4e7c-ba41-407f7cb69e38.png)

### Additional Context

NB: There is another identification system called BankID in Sweden, but this is an entirely separate system from the Norwegian one which I am reporting here. 

### Operating System

Android

### Operating System Version

11

### Device

Samsung s21

### Build Version

2.16.2 (4334)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ThrashAbaddon** [comment]
This autofill button should be floatable, so the user can move it somewhere else where it doesn't cover an important part of the screen.

**Comment by sheikh-azharuddin** [comment]
Or this could be shown on the bottom part like enpass

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1816
