### ISSUE TITLE
Copy & paste of password does not work (iphone->macbook)

### ISSUE THREAD

**Issue by kolszewska** [bitwarden/android#1824]
### Steps To Reproduce

1. Have iPhone + MacBook copy & paste function setup
2. Go to Bitwarden mobile app 
3. Click Login button
4. Click 3 dots for one of the logins 
5. Click on Copy password button

### Expected Result

I have acees to my copied password on MacBook.

### Actual Result

I do not have access to my copied password.

### Additional Context

I am sure that my copy&paste feature works because pasting the password to notes app and then copying it again gives me access to it on my MacBook.

Additionally this feature was working. Seems like it broke in the last 2-3 weeks or so?

### Operating System

iOS

### Operating System Version

15.3.1

### Device

iPhone XS

### Build Version

Version: 2.16.2 (1434)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by yetdog** [comment]
Zero comments? This is maddening for a password manager to have non functional C/P.

**Comment by mikovsky** [comment]
Yeah, I have the same issue. iPhone 11 Pro Max with iOS 15.5

**Comment by fedemkr** [comment]
Hi thank you all for the report and feedback. Yes, that was changed at the time taking into consideration security but it's been discussed and we're going to add a Setting that you can turn on to copy to other devices through Handoff feature (it will be disabled by default)

**Comment by ionixjunior** [comment]
Hello, @fedemkr! 

I'd like to try to solve this issue. Is it possible?

Thank you so much!

**Comment by fedemkr** [comment]
Hi @ionixjunior thanks so much but for now the team is researching some further considerations about this

**Comment by emamex98** [comment]
In the meantime, I've found a workaround to allow pasting passwords with continuity. Using the Shortcuts app, create a shortcut that takes your current clipboard and copies it again to the clipboard, add it to your Home Screen, and after copying the desired password on the Bitwarden app, tap on the shortcut.

**Comment by elhayra** [comment]
any news on this? it's really annoying having to use workarounds to make such a basic thing to work.

**Comment by kstevens715** [comment]
This feature was disabled in the name of security, but to work-around it I usually paste the password into another app and then copy it again which is less secure than if this just worked.

**Comment by t0xe** [comment]
As other users have suggested, this just creates an open security hole since I've been copy / pasting between apps and then between devices for this to work.
Since in my work laptop I cannot have bitwarden installed I cannot rely on extensions or the bitwarden app.

**Comment by victornpb** [comment]
IMO having the Desktop App on your computer is LESS secure. I'm only using Bitwarden on iOS, and I copy/paste SINGLE passwords over handoff.

I've seen someones Macbook being compromised recently. 
It would be really trivial for a malware to copy the entire Bitwarden App with settings + vault. And just wait listening for your master password the first time you have  to log in into any __insert_random_website__. Boom! Now your ENTIRE life is gone.

I much rather have less security for SINGLE passwords, than having my master password being constantly exposed to malwares.

Just make this a setting please.

**Comment by jpmorby** [comment]
@fedemkr any update on this?  I'm currently trying to move away from an old OTP application which is no longer supported on iOS and move to using Bitwarden (I figure I'm paying for BW, I might as well use all the features) but the fact that I can't copy/paste OTP codes from my phone to my browser/etc is becoming a real pain ... so much so that I'm considering changing password managers to something which does support this.

I note that a year ago you said a unilateral change was made and it looked like there was going to be a user configurable option to enable/disable localOnly on pasteboard actions ... this would, I think, solve my (and other people's) problems .. 

My old OTP app allowed Universal Clipboard processing, and it made my life considerably easier (I have to OTP probably 50-60 times a day on different platforms) ... which is why this is so important to me.

**Comment by nodet** [comment]
Hi @fedemkr, 

On 2022-10-25, you wrote:
> Hi @ionixjunior thanks so much but for now the team is researching some further considerations about this

Did you come to a conclusion?  Would you accept a PR that would turn the flag into a user-configurable setting?

**Comment by fedemkr** [comment]
Hi everyone, thanks for the additional info and initiative. I will have this ready soon in an upcoming release.

**Comment by rubnogueira** [comment]
@fedemkr do you have an estimation for this feature? Thanks!

**Comment by micahblut** [comment]
@rubnogueira we have this on our backlog as something we'd like to implement, but have a few other items we're interested in tackling first.

**Comment by jpmorby** [comment]
This has been broken for over a year and is a real pita ... it's a simple change to re-enable (yes more work to make it a user configurable option) ... please make the change, I really don't want to have to switch to yet another password manager but its getting to the point where I may have to.

There are times when despite trusting the machine I'm on, I don't have Bitwarden installed but I still need to copy and paste a password from Bitwarden onto that client ... and at the moment I'm having to take it out of BW, into Notes, copy it from Notes and then paste it on the Desktop I'm using ... which is cumbersome.

**Comment by francesco-cuccio** [comment]
This has driven me NUTS thinking handoff wasn't working... PLEASE bring this back.

**Comment by francesco-cuccio** [comment]
> Hello everyone, I've found that this feature doesn't work for some networks only. I don't know why, but I'm sure it has not been deprecated cause it's working with some wifi networks in my Mac (Sonoma 14.3.1).

Well I wish I had your network, because on 3/3 networks of mine it doesn't work... :( Interesting find...

**Comment by kstevens715** [comment]
One year ago I mentioned the work-around I was using. I've been using a work-around that's a bit easier lately:

I go into Bitwarden, edit the entry, click the "eye" to view the password and then triple-tap the password to pull up the context menu and then copy it to my clipboard using the normal iOS clipboard functionality.

Copying it in that way allows it to be pasted on my Mac. This is still six clicks instead of one, so I'd still very much like for this feature to be re-enabled.

**Comment by tetardbleu** [comment]
@kstevens715 Thank you for the tip ! I'm still hoping there will be an oficial way to allow universal clipboard in settings though.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1824

**Comment by victornpb** [comment]
this finally is an option in the ios app. My 2 years of suffering copying pasting passwords daily its finally just a bit easier. thank god
