### ISSUE TITLE
Not asking for password re-prompt when enabled

### ISSUE THREAD

**Issue by dylansealy** [bitwarden/android#1866]
### Steps To Reproduce

1. Go to a website or app which is **not** in the uri list of the protected item.
2. Unlock your vault with the inline keyboard auto-fill option.
3. Search for the protected item.
4. Auto-fill the protected item.

### Expected Result

I expect that a password re-prompt appears. This is the behaviour when auto-filling on a website which is in the uri list and also the behaviour with the Chrome extension.

### Actual Result

The password is auto-filled, while password re-prompt is on.

### Operating System

Android

### Operating System Version

12L (12.1.0)

### Device

Google Pixel 6

### Build Version

2.17.0 (4526)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by florinbarbisch** [comment]
I experienced the same today on my Pixel 6 (Android 13, Build Version: 1011.11.0 (5580)). For me, this is a very critical bug.

**Comment by florinbarbisch** [comment]
@Ruparani777 I think this fix landed in the wrong repository/issue. This repository concerns the mobile versions not windows 10.

**Comment by Ruparani777** [comment]
okay

**Comment by 4di5h** [comment]
Hello Bitwarden community,

I'm diving into this particular issue for the first time and have successfully run the emulator for the relevant device to reproduce the problem. I'm curious about whether I should utilize my personal Bitwarden account, create a dedicated testing account, or if the developers have provided an account specifically for testing purposes. Any guidance on this matter would be appreciated.

**Comment by Gerardv514** [comment]
> Hello Bitwarden community,
> 
> I'm diving into this particular issue for the first time and have successfully run the emulator for the relevant device to reproduce the problem. I'm curious about whether I should utilize my personal Bitwarden account, create a dedicated testing account, or if the developers have provided an account specifically for testing purposes. Any guidance on this matter would be appreciated.

Any update?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1866
