### ISSUE TITLE
Auto-Fill in Browser started from HomeScreen Shortcut not working

### ISSUE THREAD

**Issue by SHU-red** [bitwarden/android#1875]
### Steps To Reproduce

In My Case im Using Android 12 and Vivaldi Browser 5.2.2620.35

1. Go to 'Vivaldi Browser'
2. Go to certain Site
3. Click on "Add to Homescreen"
4. [Homescreen shortcut to this page is created]
5. Click on Homescreen shortcut
6. [Site opens, but not directly in a vivaldi-browser window, but in some sort of Web-View without any browser items like adress-/status bar etc
7. Trying to fill out username/password fields with bitwarden autodetection
8. Bitwarden buttons not appearing
9. Trying to trigger auto-fill from control buttons in upper toolbar on android --> No Password fields detected

I have set up a server-application as "starting-dashboard" to go to different services
For these services i am ALWAYS asked for username/password
It is really annoying to switch between apps and copy/paste the password from within bitwarden app itsself

Thanks

### Expected Result

Auto-Detect sould provide buttons to immediately fill the fields

### Actual Result

No buttons / Possibility to fill out the forms

### Operating System

Android

### Operating System Version

Android 12

### Device

Pixel 6

### Build Version

2.17.0 (4526)

### Beta

- [X] Using a pre-release version of the application.

**Comment by yashwalter12** [comment]
Hello @SHU-red  We are not able to reprodce on Pixel 5 running Android 12. If we click on the homescreen shortcut, it is currently opened in a Vivaldi window. If this issue is still happening could you please provide more information on
1. What site you are specifically having issue with on autofill or is it all the sites?

**Comment by SHU-red** [comment]
My homeserver has a certain IP through which i access it.

Lets say it would be 123.123.123.10

So my shortcut on the homescreen points to
http://123.123.123.10:8081
because at port 8081 i am running a Dashboard application from a docker container.

After that i click on a link which i prepared at my dashboard to quickly access other services.
In a explicit case i tested right now, i tried the link
http://123.123.123.10:9000/#!/home
which leads me to Portainer (which is a WebUI based management system for Docker containers)

At this point im seeing the username/password form but bitwarden does not appear as i put the cursor into one of these fields.

Due to the fact, that im accessing these pages to a shortcut from the homescreen i do not have a address-bar or something

I immediately tried the same thing, but accessed the same dashboard from the normal vivaldi android browser and not through the shortcut --> Here i click at the username field and immediately the "old" pop-up/hover message appears which asks me "Auto fill by BitWarden"

So maybe the "old auto-fill button" does not work in a homescreen-shortcut window without address-bar?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1875
