### ISSUE TITLE
Bitwarden mobile autofills in twitter search bar

### ISSUE THREAD

**Issue by Idlefase** [bitwarden/android#1897]
### Steps To Reproduce

1. Go to the Twitter app
2. Click on search tab 
3. click search field 
4. Start typing

### Expected Result

I expected the bit warden app to recognize this as a text field. Not a form.

### Actual Result

It offered to autofill saved passwords and or store them for me.

### Additional Context

OS android 12

 Grammarly keyboard

Apps installed trough google play

### Operating System

Android

### Operating System Version

12

### Device

Samsung Galaxy A51

### Build Version

2.18.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by iamrogerr** [comment]
I'm facing a similar issue but with Twitter's search bar, it's being recognized as a login field.


![Screenshot_20220429-234331](https://user-images.githubusercontent.com/34585299/166087545-fefa5578-752f-48c1-aa62-f210e785461d.png)

**Comment by ifernandezdiaz** [comment]
Hi @Idlefase, we couldn't replicate this issue on our latest version. Could you please confirm if the issue you reported is stills being replicable on your side? Thanks in advance!

**Comment by Idlefase** [comment]
Hi there, @ifernandezdiaz. I've double-checked on the bug and found that I made a mistake in the bug report. Tweets are unaffected by this but as @iamrogerr stated it will affect the search bar. 

Sorry in advance for the inconvenience.

**Comment by inakimendez** [comment]
Any news?

**Comment by slasherfun** [comment]
Same issue on a OnePlus 5 running Android 10 (OxygenOS 10.0.2, which is the ROM provided by OnePlus), so unrelated to OneUI.

**Comment by guillemglez** [comment]
This has been reproducible on all the versions of Twitter and Bitwarden I've used on my Pixel 6 device for the past year.

**Comment by opcck** [comment]
2024  This issue still remains unresolved.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1897

**Comment by ramxdier** [comment]
2025 and it's still happening... What a shame.

**Comment by fessmm** [comment]
Can confirm, still happening with latest version as of today
