### ISSUE TITLE
Android biometrics use only face. Fingerprint appear after long time and doesn't works

### ISSUE THREAD

**Issue by Bazzu85** [bitwarden/android#1902]
### Steps To Reproduce

1. Open the app
2. Avoid face login (dark room or not watching the phone)
3. The app keep waiting for a long time
4. After a while fingerprint is required but using it doesn't access the vault

### Expected Result

When searching for biometrics if the face is not recognized after 2 or 3 seconds the app can fallback to fingerprint and using it have to work

### Actual Result

- Too long wait for fingerprint fallback
- Fingerprint not working

### Screenshots or Videos

can't take videos of biometric process

### Operating System

Android

### Operating System Version

12

### Device

Oppo Find X-2 Lite

### Build Version

CPH2005VF_11_F.01

### Beta

- [X] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1902
