### ISSUE TITLE
[Android] Match Detection settings misbehaving with Inline Autofill

### ISSUE THREAD

**Issue by rg9400** [bitwarden/android#1946]
### Steps To Reproduce

1. Create two password items. First is for `domain.com/test` or any subpath. This needs to be set to use Match Detection as "Starts With". Then create one for `domain.com` (has to match prior domain). Set this url to use Match Detection "Exact"
2. Enable Inline Autofill and Accessibility services for the quick-action tile
3. Go to `domain.com/test`
4. Try to use the inline autofill. Notice how it pulls the password item for `domain.com` and not the one for `domain.com/test`
5. Try to use the quick setting tile. Notice how it pulls the password item for `domain.com/test` and not `domain.com`

### Expected Result

The Inline Autofill should behave like the Quick Actions tile in the above example. In other words, it should respect that the `domain.com` password is not relevant since `domain.com/test` is not an exact match for `domain.com`, and likewise, it should see that `domain.com/test` is meeting the match detection for `domain.com`

### Actual Result

I am not sure exactly what is happening because in both password items, the match detection option is failing. Yet it is still recognizing that `domain.com` is the base domain for `domain.com/test` and giving that password. It seems to work in most other cases and is only failing in this type of specific example, at least that I have noticed. Might be some sort of edge case?

### Operating System

Android

### Operating System Version

Android 12

### Device

Samsung S22 Ultra

### Build Version

2022.05.0 (4636)

### Beta

- [X] Using a pre-release version of the application.

**Comment by rg9400** [comment]
@creyhani I noticed this issue was marked closed, but I am still having this bug. Is it released to a beta/stable build yet?

**Comment by clayadams5226** [comment]
Hey @rg9400, apologies for this getting closed without a comment that was an oversight on our part. Have you had a chance to test this on the most recent Android build? We are unable to reproduce it on our side.

**Comment by rg9400** [comment]
Yes, I am still having this issue on the latest build. I am going to show my exact setup. I have this URL Match Detection configured for my "Plex" item. Everything blocked out is my domain. You can see that I have the root domain as an exact match, and a variety of subfolders as Stars With match

![image](https://user-images.githubusercontent.com/39887349/190049653-264fc02f-67ce-4cde-a694-312bea2feaa7.png)

This is my "Filebrowser" item. It is set to a different subfolder, with URL Detection set to Starts With as well

![image](https://user-images.githubusercontent.com/39887349/190049810-f6421c06-d688-449c-b41a-c5943649e499.png)

The theory is that if I go to domain.com, domain.com/tautulli, domain.com/#Stuff, then Plex item should pop up. This works as expected.

However, if I go to domain.com/filebrowser, then I expect to see the Filebrowser item pop up. This is not happening with Inline Autofill. Crucially, this works fine on Desktop and even using the Settings Tile or Autofill Overlay. Only Inline Autofill is failing and shows the Plex item. I am unable to take a screenshot of the overlay/Settings Tile, but trust me it shows the Filebrowser item correctly. So only the Inline Autofill is failing with something related to this configuration.

![190051736-85689f18-e995-4d87-9964-c5e328209f52](https://user-images.githubusercontent.com/39887349/190052657-fc6bf54f-247c-4041-9c5e-9291dccf84d1.png)

![image](https://user-images.githubusercontent.com/39887349/190052422-bb8ceae0-7bac-4b98-82eb-d5d87ae0713e.png)

**Comment by clayadams5226** [comment]
Thanks for the added details @rg9400. We'll get a couple more people to take a look at this.

**Comment by SgtBatten** [comment]
I am also experiencing this same issue. 

I run my own nginx webserver using swag and have many domains like @rg9400 

the password for https://mydomain.net has 3 URIs all set to exact

https://domain.net
https://domain.net/#Homepage
https://domain.net/#OrganizrLogin

I run many reverse proxied services all with similar setups e.g Tautulli

https://tautulli.domain.net is the URI that is reverse proxied. I have this set to exact or starts which both work fine
When I access through Organizr it presents each app as an iframe at e.g https://domain.net/#Tautulli
I set this to exact or starts with and both work as expected on my pc browser extention, but on mobile (pixel 4a and pixel 7 pro) I am given options for domain.net and not tautulli. If i swipe down and select autofill from the android settings tiles it only suggests the correct tautulli login.

**Comment by Skitals** [comment]
The android app is not working for me using exact or regex match detection. I have these two in my vault:

regex: ^https://[a-z]+\.domain\.com/authelia
exact: https://deluge.domain.com/

My relevant booksmarks that work fine in desktop chrome, simply says "There are no items in your vault for domain.com" when I click Bitwarden on gboard.

Interestingly if I change URI match from "https://deluge.domain.com/" to "https://deluge.domain.com" it starts working on android... but stops working on desktop chrome.

**Comment by motoridersd** [comment]
I have the same issue when using paths after my main domain. Works fine with the Chrome extension but matching is broken in Android 13 (Pixel 7 Pro)

**Comment by rg9400** [comment]
@clayadams5226 any update on this issue? I noticed a few others confirming this is broken on Android, and the bug request has been open for nearly a year. Thanks!

**Comment by Dentic89** [comment]
Got the same issue, is there any fix yet?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1946
