### ISSUE TITLE
keyboard not opening when entering pin on android 

### ISSUE THREAD

**Issue by bulldoza99** [bitwarden/android#1958]
### Steps To Reproduce

when using bitwarden android app and using it to autofill, the pin page comes up to unlock, but recently the keyboard stopped coming up automatically and requires the user to click on the pin text block and then the numeric keyboard comes up.
This used to work up until a few weeks/ month ago.

### Expected Result

keyboard to open when going to the pin screen 

### Actual Result

extra click to make the keyboard pop up when unlocking

### Operating System

Android

### Operating System Version

android 12

### Device

Galaxy S22

### Build Version

22.05.0 4636

### Beta

- [ ] Using a pre-release version of the application.

**Comment by PomaranskiD** [comment]
Same problem on Huawei P30 Pro. Sometimes keyboard shows and sometimes not.

**Comment by bulldoza999** [comment]
Latest update on Android 13 and still have the issue.. it is 100% of the time it happens. 
now on latest 2022.10.0(5247)

**Comment by djtoast** [comment]
Same here even when opening app unable to pull android keyboard to type master password

**Comment by PomaranskiD** [comment]
Solution that worked for me was to force stop Android System WebView from android setting.

**Comment by djtoast** [comment]
> 

That worked THANK YOU !!!

**Comment by PomaranskiD** [comment]
Glad I could help

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1958
