### ISSUE TITLE
Display Picture of Account Not Visible

### ISSUE THREAD

**Issue by aka-0x4C3DD** [bitwarden/android#1963]
### Steps To Reproduce

After logging into the app, check the top right corner. 3rd icon from the right.

### Expected Result

The gravatar picture should be displayed, for those who have added.

### Actual Result

Only the first letters of First & Last name are visible.

### Screenshots or Videos

![WhatsApp Image 2022-06-22 at 9 33 24 AM](https://user-images.githubusercontent.com/93938476/174941298-5ebc1fe0-d62b-4e7b-904e-29cb15b5748b.jpeg)
![Screenshot 2022-06-22 093547](https://user-images.githubusercontent.com/93938476/174941311-40dec278-ac57-4d57-a3b9-f83309975f0d.png)

### Operating System

Android

### Operating System Version

11 (R)

### Device

POCO X3 (Karna)

### Build Version

2022.05.01 (4730)

### Beta

- [X] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1963
