### ISSUE TITLE
iOS: Account switcher UI gets cut off on iPhone 13

### ISSUE THREAD

**Issue by ChrisBegley** [bitwarden/android#2003]
### Steps To Reproduce

Tap on the account switcher on the auto-fill screen. You'll see that the UI gets cut off on the right hand side. Screenshot attached below:

![v](https://user-images.githubusercontent.com/7050515/180364268-e9dc5d6a-6c88-439d-8246-cabdecc7f7ef.PNG)

### Operating System

iOS

### Operating System Version

15.6

### Device

iPhone 13

### Build Version

2022.6.2 (1951)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ataruselli** [comment]
Hello @ChrisBegley , thank you for taking the time to report this. 
We expect to fix this issue in upcoming versions of the app.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2003
