### ISSUE TITLE
Loading/syncing should happen off the main UI thread on Android app

### ISSUE THREAD

**Issue by Snuupy** [bitwarden/android#2006]
### Steps To Reproduce

1. login to mobile app
2. have a large number of items (say, several thousand)
3. wait for app to sync
4. try to interact with app on any UI elements, such as clicking the search button
5. see android prompt that the app is "not responding" and prompts user to either keep waiting or to force close the app

### Expected Result

should sync/load/decrypt login store without having the OS think the app is frozen and needs to be force closed. probably needs to be done by having the data load in another thread, not on the main UI thread.

### Actual Result

user prompted to wait/force close app

### Screenshots or Videos

![Screenshot_20220722-095322](https://user-images.githubusercontent.com/964538/180487938-917f8ba4-9d21-4844-b848-cf7eab764b6c.png)

### Additional Context

from: https://www.reddit.com/r/IAmA/comments/w3zsff/im_dw_technical_evangelist_at_bitwarden_here_with/ih1eizw/

### Operating System

Android

### Operating System Version

12

### Device

pixel 4a

### Build Version

2022.6.2 (4851)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by farfromrefug** [comment]
I really would like to see that fix. It does make the app hard to use.
Also if I may add it here why is the loading of the database so slow ? It is a really small database (around a 1000 entries) and it takes 10s if not more on my middle end phone

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2006
