### ISSUE TITLE
About information not available when logged out

### ISSUE THREAD

**Issue by waldyrious** [bitwarden/android#2010]
### Steps To Reproduce

1. Install the app
2. Open it for the first time (without logging in)
3. Click on the Settings gear icon ⚙️

### Expected Result

There should be an "About" entry where we could get the version of the application

### Actual Result

There is no "About" entry in the settings

### Additional Context

I bumped into this when trying to access the version of the app in the process of reporting an issue with the "Create Account" flow (#2009).

### Operating System

Android

### Operating System Version

12

### Device

Pixel 4a

### Build Version

Version: 2022.6.2 (4851)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by OmriOn** [comment]
seems to be a bug. it probably will be fixed by #2020 soon.

**Comment by Sundar1709** [comment]
is it still open how do i start contributing to this

**Comment by OmriOn** [comment]
> is it still open how do i start contributing to this 
> 

Contribute to this on pull request #2020

**Comment by toruwatanbe** [comment]
Is this still open?

**Comment by tactipus** [comment]
Sup. Still open?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2010
