### ISSUE TITLE
Hidden PIN on Android app

### ISSUE THREAD

**Issue by n2ttin** [bitwarden/android#2036]
### Steps To Reproduce

Setting up PIN Code in Settings

### Expected Result

The PIN Code should be hidden

### Actual Result

The PIN Code was appeared

### Screenshots or Videos

![Screenshot_2022-08-14-11-18-25-722_com x8bit bitwarden](https://user-images.githubusercontent.com/107202990/184522364-ceaab421-a574-4668-a0bc-4beb6aeb901f.jpg)

### Operating System

Android

### Operating System Version

Android 10

### Device

Xiaomi Redmi 8A

### Build Version

2022.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2036
