### ISSUE TITLE
Android Cannot connect to Bitwarden servers using WiFi via IPv6

### ISSUE THREAD

**Issue by ginjj** [bitwarden/android#2043]
### Steps To Reproduce

Android app
1. Go to + add item (login)
2. Fill in details for new login
3. Click save at top

### Expected Result

New login item saved to my account on Bitwarden servers

### Actual Result

Save times out with:

`An error has occurred. 
Exception message: failed to connect to identity.bitwarden.com...'

### Screenshots or Videos

![IMG-20220821-WA0003](https://user-images.githubusercontent.com/27459697/185798882-ca246276-8bb2-4d38-be58-1474cd94a786.jpg)

### Additional Context

See community form discussion that suggests this is an issue with IPv6 on WiFi [unable-to-login-on-android](https://community.bitwarden.com/t/unable-to-login-on-android/14447/20) 

Work around is to turn off WiFi and use LTE network.

### Operating System

Android

### Operating System Version

Android 11

### Device

OnePlus 7T

### Build Version

Version: 2022.8.0 (4911)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by yaovenus** [comment]
Me too.
Ipv4.
OnePlus .

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2043
