### ISSUE TITLE
Android App: Clear clipboard function does not actually clear clipboard.

### ISSUE THREAD

**Issue by apmech707** [bitwarden/android#2067]
### Steps To Reproduce

On the Android mobile app if you:

1. click on settings
2. scroll to OTHER -> OPTIONS
3. set the CLEAR CLIPBOARD setting to something like 10 sec.
4. navigate to a stored password and copy the password
5. wait the amount of time needed to have the clipboard automatically cleared.
6. notice that you now cannot paste anything in your clipboard
7. navigate to your messages
8. touch and hold a text entry field and tap the clipboard button that appears.
9. There you will see your previously copied password still in your clipboard. 

### Expected Result

I would appreciate the clear clipboard function to completely clear the password from my clipboard and remove the possibility of me accidentally texting someone my password while trying to paste in another copied text.

### Actual Result

I copy a password from the mobile app and after the app has cleared the clipboard I go to text someone and copy and paste something to text them and almost pasted in my sensitive password while scanning through my clipboard history. 

### Additional Context

It seems like only the first item in the clipboard is deleted but all the previous passwords that i had copied for weeks were still there and I was relying on the clear clipboard function to have cleared it. Now, I do not know if this clipboard history could even be potentially accessed by a malicious actor that had gained access to an android device, but this seemed like a security risk. I am open to being informed about whether this is a concern or not. 

Thank you all for contributing to this awesome app. As soon as I have developed my coding skills further this is a project that I would love to contribute to. 

Cheers

### Operating System

Android

### Operating System Version

Android Version 12

### Device

Galaxy A32 5G

### Build Version

2022.8.0(4911)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dbosompem** [comment]
Hi @apmech707 , thank you for raising this issue. The team will try and reproduce this, and upon a successful one we'd make time and resolve this. We will get back to you if we need any additional information. Thanks!

**Comment by THEOCKID** [comment]
oh this has been this way for years.  I see this as a Galaxy bug, tho.  Galaxy has like 20-30 clipboard slots, and thus no program is able of clearing them.  I will say that I developed a workaround: I used (trying to remember here.... ) MacroDroid?, and created a macro that every X minutes it would push data to the clipboard and repeat 30x, thus filling the clipboard with dummy data.  I was never able to get the macro program to *clear* data from the clipboard, but I could *push* data there, reaching the same desired endpoint -- my password info was wiped.

I hope this helps a little :)

**Comment by apmech707** [comment]
Hi thank you for contacting me and offering a solution. This does sound
like an android problem rather than a bug in butwarden. I really appreciate
you looking into it. Thanks so much, hope that i can contribute to this
project as I get better at coding. Have a good one

**Comment by ThrashAbaddon** [comment]
The source of the problem may be on the android side, but the issue still stands, the clearing of clipboard doesn't work. If the functionality can't be supported, for whatever reason, then it needs to clearly explain to the user that the current OS doesn't support that and the functionality is disabled.

Do not lose trust over something that isn't even your fault.

![image](https://user-images.githubusercontent.com/7493180/214386597-30acecd7-0337-4ae0-8962-33c4cfe59c4d.png)

**Comment by dwbit** [comment]
Hey @ThrashAbaddon thanks for the information, the team is reviewing this one.

**Comment by HarryBouch96** [comment]
Any updates on this?

**Comment by KobeW50** [comment]
It may be a good idea to close this issue in favor of https://github.com/bitwarden/mobile/issues/2356. Although this bug report was opened first, 2356 has detailed information on why the bug occurs and is likely to be more up-to-date in general.

**Comment by KobeW50** [comment]
@vvolkgang Please close this as well

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2067
