### ISSUE TITLE
no popup to save new login on android's apps

### ISSUE THREAD

**Issue by AnthillSudoku** [bitwarden/android#2074]
### Steps To Reproduce

1. Open an Android app that is not a browser (eg hostelworld, libretube)
2. Login with your credentials (they must not already be present in bitwarden)

### Expected Result

Bitwarden shows a popup to save the new login

### Actual Result

No popup is shown to save the new credential

### Operating System

Android

### Operating System Version

10

### Device

Oppo cph1931

### Build Version

2022.9.0 (5038)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2074
