### ISSUE TITLE
username is not recognized when saving a new entry from popup

### ISSUE THREAD

**Issue by AnthillSudoku** [bitwarden/android#2080]
### Steps To Reproduce

1. Open Firefox (mine is 104.1.0)
2. Login to a site that does not have a bitwarden entry
3. Choose to save the new credential

### Expected Result

Bitwarden fill username (plus password, name, url) in a new entry that can be saved 

### Actual Result

Username field is empty

### Operating System

Android

### Operating System Version

10

### Build Version

Versione: 2022.9.1 (5047)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2080
