### ISSUE TITLE
iOS 16: Camera notification is on even after exiting camera for scanning TOTP

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/android#2082]
### Steps To Reproduce

1. Go to Bitwarden App 
2. Go ahead and edit item
3. Click on camera icon to scan TOTP 
4. Green dot will appear at the top of screen indicating camera is being used
5. Exit camera mode and go back to simply navigating the vault - Greed dot notification remains 

### Expected Result

1. Go to Bitwarden App 
2. Go ahead and edit item
3. Click on camera icon to scan TOTP 
4. Green dot will appear at the top of screen indicating camera is being used
5. Exit camera mode and green dot notification should not be visible as camera is no longer in use. 

### Actual Result

1. Go to Bitwarden App 
2. Go ahead and edit item
3. Click on camera icon to scan TOTP 
4. Green dot will appear at the top of screen indicating camera is being used
5. Exit camera mode and green dot notification is still visible, even after exiting Bitwarden app and going back to it 
![IMG_6360](https://user-images.githubusercontent.com/36608718/191016544-e24557a7-ef2d-4cc6-af5c-97772ca8813d.jpg)

### Operating System

iOS

### Operating System Version

16.0

### Device

iPhone 12

### Build Version

2022.9.1 (2147)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2082
