### ISSUE TITLE
One-time key from YubiKey NFC not written to input during 2FA from iPhone AutoFill Passwords

### ISSUE THREAD

**Issue by mtcarbon** [bitwarden/android#2085]
### Steps To Reproduce

1. Go to a mobile app with 2FA 
2. Tap on Password field
3. Tap on Password button 
4. Log in to Bitwarden after redirect
5. Scan YubiKey

### Expected Result

Generate one-time key, and Continue option to turn opaque.

### Actual Result

iPhone notification "Firefox NFC Tag: Open in Firefox" appears.

### Screenshots or Videos

The keyboard and Passwords button are not captured by the screenshot tool. 
![97FDFB01-444F-4732-8659-1050E0DE34E1_1_201_a](https://user-images.githubusercontent.com/58127651/191149654-01df626f-8a68-4bd2-9d37-775904afa2b8.jpeg)
![18960183-FD66-4386-948D-CF1CAA487361_1_201_a](https://user-images.githubusercontent.com/58127651/191149676-a102581d-e01a-4c68-8c58-594427817e7e.jpeg)
![4D7DED4E-1EDE-4E12-AFB4-7967800BE8EC_1_102_o](https://user-images.githubusercontent.com/58127651/191149699-9fbfbeb7-c8f3-41b1-9d4b-3cf9b54b796a.jpeg)
![20615408-88F4-4F20-9AB6-352A71FD0A70_1_102_o](https://user-images.githubusercontent.com/58127651/191149713-86f78832-2aa0-49c2-bdb0-efe24d2760de.jpeg)

### Operating System

iOS

### Operating System Version

15.6.1

### Device

iPhone SE

### Build Version

19G82

### Beta

- [ ] Using a pre-release version of the application.

**Comment by THEOCKID** [comment]
ha, that same exact totally annoying popup happens to me too: iOS 16.0.2, iPhone 14 Pro (but also happened on iOS 15 with iPhone 13 mini as well):   I try  using the yubikey NFC and i get the pop up redirecting me to a webpage (on Opera) and it does nothing for me : I get a validation option or an option to copy the  30+ character code, but I can't get into the place I want to get in to.  :(

**Comment by mp-bw** [comment]
@mtcarbon Thanks for the screenshots!  Can you and @THEOCKID try tapping on the text entry (dark line directly above the `Remember Me` switch) to confirm the entry has focus _before_ scanning your key?  (This is supposed to happen automatically when that screen is first displayed but it doesn't look focused in the screenshot, which could be a bug on our part)

**Comment by mtcarbon** [comment]
@mp-bw Thanks for responding. I confirmed the entry had focus and then got the same behavior.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2085
