### ISSUE TITLE
Icon requests are made even when `Show website icons` is disabled

### ISSUE THREAD

**Issue by jjlin** [bitwarden/android#2087]
### Steps To Reproduce

1. Disable the `Show website icons` option in the mobile app
2. Tail your reverse proxy logs
3. Scroll through login entries that would have shown icons if the `Show website icons` option were enabled
4. Observe that the reverse proxy logs show that icon requests are being made, even though no icons are actually displayed in the app

### Expected Result

No icon requests are observed

### Actual Result

Icon requests are observed despite no icons actually being displayed in the app

### Additional Context

This issue seems to be specific to the mobile client. It's most easily observed with a self-hosted server, though I expect the same issue is present when using Bitwarden-hosted servers.

### Operating System

Android

### Build Version

2022.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tangowithfoxtrot** [comment]
Hi, @jjlin. I was able to reproduce this on my end as well. I have marked this as being reproducible on our internal tracking system. Thanks for reporting!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2087
