### ISSUE TITLE
Biometric unlock bug when camera access is blocked

### ISSUE THREAD

**Issue by dretyuiop** [bitwarden/android#2098]
### Steps To Reproduce

1. Setup face unlock on the phone.
2. Turn on biometric unlock in bitwarden.
3. Block camera access in quick tiles.
4. Open bitwarden while its locked.

### Expected Result

Bitwarden should let me use fingerprint to unlock.

### Actual Result

Face unlock window pops up for half a second, and then the biometric unlock is disabled for the whole phone, including other apps and lock screen. Fingerprint sensor does not register my fingerprint and I cannot even access the fingerprint and face options in settings. This problem persists until a reboot.

### Additional Context

Bitwarden works like normal and lets me use fingerprint unlock if i delete my face model or have camera access unblocked. It produces the same bug even if i did not turn on the option to use face unlock for app biometric unlock though. 

### Operating System

Android

### Operating System Version

12

### Device

Poco X3 Pro

### Build Version

2022.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2098
