### ISSUE TITLE
App Crashes after repeatedly tapping Search button

### ISSUE THREAD

**Issue by 0rangePanda1** [bitwarden/android#2120]
### Steps To Reproduce

1. Launch Bitwarden
2. Before Vault loads in, repeatedly tap the Search button
3. When in search menu, wait about 30 seconds for app to crash

### Expected Result

The app would keep working as intended

### Actual Result

The app crashes and when relaunched through the recents menu it displays a grey screen and is unresponsive

### Screenshots or Videos

https://user-images.githubusercontent.com/87389420/194774879-628d590d-a9c4-4d1b-9292-e1efd70e19fc.mp4

### Operating System

Android

### Operating System Version

Android 12 / ColorOS V12.1

### Device

OPPO A54s

### Build Version

CPH223_11_C.28

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2120
