### ISSUE TITLE
Regex matching not working on Android Chrome (works on desktop)

### ISSUE THREAD

**Issue by shanereichart** [bitwarden/android#2124]
### Steps To Reproduce

1. Create a login with regex type matching. For testing, I used: `\?page=admin$`. (Match _any_ URL ending in the literal string "?page=admin".)
2. Visit a domain which should match the regex. ("{anydomain.com}?page=admin")
3. Tap on a field requesting login credentials.

### Expected Result

I expect Bitwarden on Android Chrome to have the same matching results it has on Windows Edge, where I see the expected matching result.

### Actual Result

Bitwarden on Android fails to find any login matches.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16807422/195136332-6ca8e9fe-af6a-4610-9fb7-2e345ae7f7fb.png)

![Screenshot_20221011-113911](https://user-images.githubusercontent.com/16807422/195137378-26ec6608-3e4c-424d-880b-9d94c10b2505.png)

### Additional Context

I saw there was a previous issue with Android Chrome not matching _starts with_ patterns because the schema is not shown in the address bar. This is not related to that issue because in this case, whether the schema is shown or not, the makeshift "ends with" pattern should match.

### Operating System

Android

### Build Version

2022.9.1 (5047)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by nomonkeynodeal** [comment]
Came here to post this same issue. It's been a problem since I started using regex matching maybe a year ago.

**Comment by chewiebug** [comment]
same for me

### Steps To Reproduce

- Create a login with regex type matching (https://(www.)?gospelchor-winterthur.ch/login/)
- visit https://www.gospelchor-winterthur.ch/login/
- Tap on a field requesting login credentials.

### Expected Result
See all matches (same configuration works in Browser extensions on Windows 10 and iPad OS 15)

### Actual Result
Bitwarden on Android fails to find any login matches.

### Screenshots or Videos

### Additional Context
same issue with "starts with" patterns.

### Operating System
Android

### Operating System Version
11

### Device
Fairphone 4

### Build Version
2022.10.0 (5247)

### Beta
- [ ] Using a pre-release version of the application.

**Comment by Skitals** [comment]
Same here. Regex matching not working on Android Chrome. Latest android and apps on Pixel 7 Pro.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2124
