### ISSUE TITLE
Auto fill on Android seems to truncate some password characters (in one instance)

### ISSUE THREAD

**Issue by fearedbliss** [bitwarden/android#2145]
### Steps To Reproduce

1. Go to the following URL: frame.work
2. Attempt to log into your account by using the Bitwarden Auto-fill feature.
3. Select your frame.work credentials when the auto-fill selector opens up.
4. Click "log in"

### Expected Result

Password should be auto-filled correctly (without truncating characters) and the log in should work.

### Actual Result

This will give you an incorrect password message. I tried this in Brave and Chrome for Android.

The error doesn't happen if I manually copy the password out of the Bitwarden Vault. This issue also doesn't happen on Desktop.

### Additional Context

This doesn't seem to happen for other applications or websites that I've tried to log into.

### Operating System

Android

### Operating System Version

Android 13

### Device

Stock Android on Pixel 4a (TP1A.221005.002)

### Build Version

2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2145
