### ISSUE TITLE
Android client got no response randomly.

### ISSUE THREAD

**Issue by 2ndMessiah** [bitwarden/android#2147]
### Steps To Reproduce

This happens really randomly. 

The app appears to be frozen(it feels like it was masked by some layer honestly speaking), with no buttons tappable. But fingerprint auth prompts out at the start normally, and I could finish the auth, after which everything is still irresponsive, including the password entries, and sections on the bottom.

I tried clearing the data and launching it again, but it still acts like the aforementioned. 

I dropped the phone aside for a while and it magically recovered normally...

I met with this situation for many times and I decide to record it this time.

Thx the dev for making Bitwarden better!! Looking forward to a reply.

### Screenshots or Videos

Check out this video that was shot then.
https://img.niubi.tk/bitwarden2.mp4

And this clip after a data clear..
https://img.niubi.tk/bitwarden.mp4

### Operating System

Android

### Operating System Version

MIUI 12.5.16 android11

### Device

Xiaomi Mi 11

### Build Version

2022.10.0 from playstore

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2147
