### ISSUE TITLE
iOS: “generate username” missing when creating an entry from the share menu

### ISSUE THREAD

**Issue by jrcast** [bitwarden/android#2158]
### Steps To Reproduce

(See video)
1. Go to a website in safari or other browser
2. Click on share
3. Select Bitwarden and authenticate
4. Click the “+” icon
5. There’s a _generate password_ option but no _generate username_ option.  

### Expected Result

this option is available when adding an account from within the Bitwarden app’s main screen. I expect the option to be there as well when creating a new account from the share menu. 

(See screenshot) 

### Actual Result

”Generate username” is missing

### Screenshots or Videos

**When adding an object from main screen:**
![71657017-5390-41F8-86BD-8F6D93AA8060](https://user-images.githubusercontent.com/22987396/198848064-e3099bdf-72b8-4de0-a2d4-ec924f363ecc.jpeg)

**When adding an object from the share menu:**

https://user-images.githubusercontent.com/22987396/198851947-47baa096-96af-4443-81d4-ba01ecf92ad1.mp4

### Operating System

iOS

### Operating System Version

15.6.1

### Device

iPhone 13 Pro Max

### Build Version

Version: 2022.10.0 (2347)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2158
