### ISSUE TITLE
Saved credentials aren't visible

### ISSUE THREAD

**Issue by mateusztylec** [bitwarden/android#2168]
### Steps To Reproduce

Can't reproduce the behaviour. It happens randomly

### Expected Result

Wanted to see all my saved credentials

### Actual Result

Saved credentials aren't visible

### Screenshots or Videos

![IMG_4506](https://user-images.githubusercontent.com/79941376/200078598-c8437686-2654-4a5e-922f-aee998e3afed.PNG)

### Additional Context

From time to time if i want to access any saved credentials i can't do this because all my credentials are missing (not visible). It happens on other machine (like macos, browser) as well. After some time (like about 1 day) everything is back to normal.

### Operating System

iOS

### Operating System Version

16.0

### Device

iPhone 10

### Build Version

2022.10.0(2347)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2168
