### ISSUE TITLE
app thinks I'm free user and prompts to buy premium when uploading a file

### ISSUE THREAD

**Issue by iTrooz** [bitwarden/android#2169]
### Steps To Reproduce

1. Buy personal premium membership (website)
2. Open Android app
3. Add an attachment or send a file

### Expected Result

No prompt about buying a premium membership

### Actual Result

When I add an attachment, I get the prompt but I can dismiss it and upload the attachment
When I try to send a file, I can't dismiss the prompt

### Screenshots or Videos

https://user-images.githubusercontent.com/42669835/200087458-58ae66ef-cf3c-481b-b698-6f4008e988fc.mp4

### Additional Context

Clearing data and re-logging to my account fix the problem

### Operating System

Android

### Operating System Version

Android 12

### Device

Pocophone F1 (LineageOS)

### Build Version

2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bnagawiecki** [comment]
Hey @iTrooz, 

Thanks for submitting this issue! I replicated it myself and have escalated it internally for prioritization.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2169
