### ISSUE TITLE
Android - When using Ghostery browser, Bitwarden pulls the browser's package name instead of the website's URL.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2170]
### Steps To Reproduce

1. Install Ghostery browser on your Android phone.
2. Navigate to Vimeo.
3. Attempt to log in.
4. Open Bitwarden from the Inline Autofill prompt.
5. Attempt to create a new vault item.

### Expected Result

To see Vimeo's URL in the new vault item's URI field.

### Actual Result

Ghostery's package name is present in the new vault item's URI field.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

Android

### Operating System Version

12.

### Device

Samsung Note10+.

### Build Version

2022.10.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by PeterKW** [comment]
@SergeantConfused This is the GitHub repo for the Android version of Ghostery if that's of use? https://github.com/ghostery/user-agent-android

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2170
