### ISSUE TITLE
Digits of folder size number stack with long folder names

### ISSUE THREAD

**Issue by paksnuk** [bitwarden/android#2171]
### Steps To Reproduce

1. Have a folder with a name that is being abbreviated in the main vault view due to its length and assign at least 10 items to it.

### Expected Result

The number of items in the folder should be displayed in one line, e.g. "29".

### Actual Result

The 2 digits of the number are stacked on top of each other, e.g.
"
2
9
"

### Screenshots or Videos

![Screenshot_Bitwarden](https://user-images.githubusercontent.com/104631052/200119994-008582dc-ab06-4eaf-89c4-746e4dc851fd.png)

### Operating System

iOS

### Operating System Version

16.1

### Device

iPhone SE 2020

### Build Version

2022.10.0 (2347)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by syveqc** [comment]
Just confirmed this on my device, a Samsung Galaxy A52s 5G (SM-A528B/DS) with Android 12 and bitwarden build version 22.20.0 (5247)!

**Comment by bnagawiecki** [comment]
Hey @paksnuk, 

Thanks for submitting this issue! At first I wasn't able to replicate with 10-19 items in the folder, but it looks like it does start to happen at 20 (with the exception of of 21, 31, etc.). I'll get this raised internally for prioritization.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2171
