### ISSUE TITLE
Bitwarden doesn't send notifications about new login attempts

### ISSUE THREAD

**Issue by popogomo** [bitwarden/android#2197]
### Steps To Reproduce

Its basically 2 issues in 1:

1. When I login to Bitwarden from a new browser or device, I am not getting a login attempt notification email. My understanding is that it should notify via email (or push notifications on mobile) that there was an attempt to login to account.
2. Likewise, I am using Bitwarden on Android and "Approve Login Requests" option is turned on, however, I never receive any login prompt approvals. If it helps, I am on GrapheneOS.

### Expected Result

1. Bitwarden should send a login attempt notification email on each logon from a new browser or device
2. Bitwarden for Android should receive a prompt to authorize a new device as per Approve Login Requests settings.

### Actual Result

1. Bitwarden doesn't send a notification email when logging in from a new browser or device
2. Bitwarden on Android doesn't send a push notification asking to approve the login

### Operating System

Android

### Operating System Version

Android 13 Build TD1A.221105.0012022111000

### Device

Pixel 7 Pro

### Build Version

2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vinnyperella** [comment]
I'm also not receiving any prompt to authenticate my other session from the Android app with the setting(s) enabled.

**Comment by diamant711** [comment]
I have the same problem. I'm on A13 so I have to enable notification from settings but the actual settings are immutable set to off.

**Comment by michaelwtm** [comment]
I also have this problem. When I attempt to activate the "Approve Login Requests" function, it doesn't use the standard permissions granting popup that other apps use. It takes me to the app info page for Bitwarden and implies that I should manually activate notification permission. The problem is that the toggle is locked to the off position, I suppose because the app hasn't asked for the permission, so the system doesn't know that it should be an option.

Pixel 6a, CalyxOS 4.11.0 (Android 13)

**Comment by Tyri0n** [comment]
no prompt appearing on Android here. also, signed out on iPad and it let me sign back in without approving login on Android.

**Comment by benjiwolff** [comment]
I am having the same issue. I do a see a toggle in the iOS settings for Bitwarden notifications so the app should have the necessary permissions.

On a side note, you can still approve the login requests in the "Pending login requests" section in the settings of the mobile app without the notification.

**Comment by develop7** [comment]
Confirming that, I was getting notifications when the feature was introduced, but I'm not anymore. 

On a side note, "pending login requests" in case of presence of any, deserve better visibility — right now there's no way to know there are any except to go Settings → Account security → pending….

**Comment by ACCESSDENIIED** [comment]
> Confirming that, I was getting notifications when the feature was introduced, but I'm not anymore.
> 
> On a side note, "pending login requests" in case of presence of any, deserve better visibility — right now there's no way to know there are any except to go Settings → Account security → pending….

(Android) I absolutely agree with this. It's so out of the way compared to other apps such as my banking app. My banking app has "Payments to approve" at the very top of the startup page. Replacing this with "Logins to approve" or something similar and placing it at the very top of the startup page would be a MUCH better location for it.

Also confirming push notifications aren't working on my device either, they did previously.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2197
