### ISSUE TITLE
Autofill turns itself off randomly

### ISSUE THREAD

**Issue by tthies0** [bitwarden/android#2202]
### Steps To Reproduce

1. Wait a random amount of time

### Expected Result

Autofill is still turned on

### Actual Result

Bitwarden says Autofill is off, Autofill is not working, Android still shows that Bitwarden is the selected Autofill App.

### Additional Context

Sometimes it doesnt happen for months, then multiple times a day or a few times a week and then it just works for months again.

### Operating System

Android

### Operating System Version

Android 11

### Device

realme X2 Pro

### Build Version

2022.10.0(5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2202
