### ISSUE TITLE
Android app replaces value for non login field

### ISSUE THREAD

**Issue by ZuBB** [bitwarden/android#2208]
#### Prerequisites
* Download and install [app](https://play.google.com/store/apps/details?id=com.ukrsibbank.client.android)
* Create a record in bitwarden with fake data for the target app

1. open ukrsibbank app
2. tap on the password field
3. click on bitwarden tile on keyboard
4. authorize in bitwarden and select the target app record
5. See that 1st field is overridden

### Expected Result

Value of the 1st control is not touched/changed

### Actual Result

Value of the 1st control is changed, despite its a dropdown/listitem

### Screenshots or Videos

<details>
  <summary>initial screen</summary>

![Screenshot_2022-11-29-11-54-36-73_411440065f246194bfccff27bdf19e53](https://user-images.githubusercontent.com/597016/204558718-80499605-3c47-4b73-a4f1-83f8f60eaa5b.jpg)  
</details>

<details>
  <summary>content of the 1st control</summary>

![Screenshot_2022-11-29-11-54-42-58_411440065f246194bfccff27bdf19e53](https://user-images.githubusercontent.com/597016/204558725-404ed1c3-def8-4e4e-a69b-ad3391e13eb0.jpg)
</details>

<details>
  <summary>erros state</summary>

![Screenshot_2022-11-29-12-10-18-84_411440065f246194bfccff27bdf19e53](https://user-images.githubusercontent.com/597016/204560650-ee04afe3-08c1-41f8-85fb-86636159587c.jpg)
</details>

### Additional Context

If the screens that I provided are not enough, I have a video I can share privately

----

I suspect its due to the ID of that input control. I decompiled the app and found the following line from view.

```xml
    <com.ukrsibbank.client.android.p010ui.operation.combobox.ListItemChooserView
        android:id="@+id/loginTypeValue" /* <---- my guess is that its due to `login` token as a part of the id */
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/default_padding"
        android:layout_marginRight="@dimen/default_padding"/>
```

### Operating System

Android

### Operating System Version

Android 12

### Device

Oneplus 9R

### Build Version

2022.10.0

**Comment by ZuBB** [comment]
if we can figure out a fix for that, I hope for a workaround at least

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2208
