### ISSUE TITLE
Text alignment problem (fr) 

### ISSUE THREAD

**Issue by Ludo-code** [bitwarden/android#2223]
### Steps To Reproduce

1. Go to 'any element of your vault'
2. Click on 'edit button and then click the generate button in username field and then you can find the problem 

### Expected Result

The text should be more down

### Actual Result

The text is not at the right place

### Screenshots or Videos

![Screenshot_20221205_220911](https://user-images.githubusercontent.com/56892223/205744307-190ba087-eaab-4e81-903c-514dff1cc274.jpg)

### Operating System

Android

### Operating System Version

Android 12 with magic ui 6.0

### Device

Honor 50

### Build Version

2022.11.0 (5580)

### Beta

- [X] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2223
