### ISSUE TITLE
Using "Blue Light Filter" app by Leap Fitness Group makes Bitwarden unfunctional

### ISSUE THREAD

**Issue by GOTHMONEY** [bitwarden/android#2231]
### Steps To Reproduce

1. Install the "Blue Light Filter - Night Mode" app on the Google Play store ([com.eyefilter.nightmode.bluelightfilter](https://play.google.com/store/apps/details?id=com.eyefilter.nightmode.bluelightfilter&hl=en&gl=US))
2. Open the app and just make sure it is turned on.
3. Open Bitwarden
4. You won't be able to interact with the app at all.

### Expected Result

The app should function normally while the Blue Light Filter is on, you should be able to type in your PIN, autofill, edit your fault etc...

### Actual Result

The app is unusable and doesn't recognize any input from the user while the filter is on. Not exclusive to the login screen, autofill in websites doesn't work either, the entire app just stops recognizing input altogether.

### Screenshots or Videos

Recorded via scrcpy and ShareX.
![bitwarden](https://user-images.githubusercontent.com/91788386/206664070-c11e1bc0-65a6-42d0-9660-eaccfec882b1.gif)

### Operating System

Android

### Operating System Version

Android Version 10

### Device

Motorola One Fusion+

### Build Version

2022.11.0 (5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2231
