### ISSUE TITLE
Please revert TOTP entry changes

### ISSUE THREAD

**Issue by dm7p** [bitwarden/android#2235]
### Steps To Reproduce

1. Tap FAB to switch to "Add Item" view
2. Go down to "Authenticator key (TOTP)" field.
3. Attempt to enter the TOTP seed in clipboard.

### Expected Result

There is a text field where I paste in the TOTP seed, as well as a camera icon for those who use the scanning feature. Once pasted I hit 'save' and I'm done.

### Actual Result

The text field is gone and there's a big camera button. I have to open the camera, then click the link for the thing I want, then paste it in, then press an additional button, then press save.

### Additional Context

I tried denying camera permissions but then I can't enter _anything at all_ and entering new TOTP seeds is impossible.

### Operating System

Android

### Operating System Version

Android 12

### Device

Pixel 5

### Build Version

2022.11.0 (5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dm7p** [comment]
for the curious: last version before this was implemented is [2022.8.0](https://github.com/bitwarden/mobile/releases/tag/v2022.8.0)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2235
