### ISSUE TITLE
On vault open do not show last opened item

### ISSUE THREAD

**Issue by gitbq** [bitwarden/android#2237]
Currently on both ios and android, when I unlock the vault, the most recent view is opened.
If I have looked at item "A" before the vault was closed, after reopening, item "A" is once again displayed. If someone wise accessed the vault they could know what was the most recently accessed item. 

Preferred behaviour:
Whenever the vault is opened the default view is shown. Not the most recent item including the most recently accessed item....

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2237
