### ISSUE TITLE
Sync issue - User with revoked access, still has access to data after few hours. 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/android#2252]
### Steps To Reproduce

1. Go to web vault organisation 
2. Revoke access of one of the users 
3. The other user should now try to access the data on their mobile device

### Expected Result

Expected result would be that the user with revoked access would not be able to access the data on the vault within an hour or when vault is synced manually. 

### Actual Result

User with revoked access is still able to access the data on their mobile client. This user has access to the data for many hours despite vault showing that it has been synced few minutes ago. It seems there might be a sync issue on the mobile client, despite it saying it was synced. 

### Additional Context

Cloud Bitwarden 

### Operating System

iOS

### Operating System Version

16.1.1

### Device

iPhone

### Build Version

2022.11.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2252
