### ISSUE TITLE
If the uri contains port information when selecting host matching, the mobile client cannot pop up the correct auto fill option

### ISSUE THREAD

**Issue by qiaoyun680** [bitwarden/android#2261]
### Steps To Reproduce

1. URI match select HOST
2. URI contain port like xxx.com:1443
3. visit xxx.com:1443
4. pop up the selection dont have the right info

### Expected Result

pop up the right account info

### Actual Result

dont have account info

### Screenshots or Videos

![IMG_20221225_160435](https://user-images.githubusercontent.com/10334189/209461045-d8fc11fd-e4aa-43ed-a616-253b71152826.jpg)
![IMG_20221225_162515](https://user-images.githubusercontent.com/10334189/209461547-2391b76b-e03d-4e4d-917c-185bd2b410f9.jpg)
![IMG_20221225_160343](https://user-images.githubusercontent.com/10334189/209461048-208750bc-dc1d-4b29-837d-ebabf430ab5b.jpg)

### Additional Context

If the uri contains port information when selecting host matching, the mobile client cannot pop up the correct auto fill option

### Operating System

Android

### Build Version

2022.11.0(5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by PlanetWilson** [comment]
Same behaviour on iOS

**Comment by Fmstrat** [comment]
Looks like the search starts here: https://github.com/bitwarden/mobile/blob/master/src/Core/Models/View/LoginUriView.cs#L76

And may be due to the logic in this function: https://github.com/bitwarden/mobile/blob/master/src/Core/Utilities/CoreHelpers.cs#L65

**Comment by gldl137** [comment]
解决没

**Comment by skymkmk** [comment]
The auto fill service on Android seems like it won't pass the port field so that the client can't match the URI correctly because Android doesn't pass the port to the client at all. I hope that BitWarden can add a new option that relies solely on the full domain name, which excludes port, to match the URI.

**Comment by likeman66** [comment]
Bitwarden will not pass the full url into the app. For example, when I'm viewing https:/home.alist.org:4433/, and set the host match, what the inline auto fill pass to bitwarden app is only the base domain part which is alist.org, the port and the other level of domain names are completely ignored. And this bug has existed for over two years

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2261
