### ISSUE TITLE
Expired TOTP are shown when returning to app (iOS)

### ISSUE THREAD

**Issue by paksnuk** [bitwarden/android#2275]
### Steps To Reproduce

1. Open the TOTP view on the iOS app
2. Leave the app (remember any TOTP to verify the bug)
3. Reopen the app after the timer has expired at least once

### Expected Result

The TOTPs should be correct, which means they must have changed as the previous timer has expired.

### Actual Result

The TOTPs have not updated since leaving the app. Since the previous time period has expired, the codes are now incorrect.
A workaround is to manually update the view by pulling down or waiting for another period to expire; it seems the codes are automatically regenerated when the timer expires while the app is open.

### Operating System

iOS

### Operating System Version

16.2

### Device

iPhone SE 2020

### Build Version

2022.11.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2275
