### ISSUE TITLE
Firefox add on not syncing

### ISSUE THREAD

**Issue by Taur1O** [bitwarden/android#2321]
### Steps To Reproduce

Make changes to your vault on another running instance of BitWarden such as adding a password or changing one
Attempt log in to the site or simply check the credentials in the vault

### Expected Result

Vault should be the same whether using the app on Android, add on in Firefox for Android or plug in for Firefox on the desktop.

### Actual Result

Recently updated passwords were correct in both the desktop plug in and the Android app on multiple devices, but on those same devices the Firefox add on was still showing the old vault data. 

### Additional Context

This isn't a new problem, I've had errors before, but hadn't thought much about them, until I erased and updated my entire vault recently, and realized that the new data was not reflected in Firefox for Android. A check revealed that the vault hadn't updated since 23 Dec, roughly three weeks ago. Add on is as downloaded, no customization to the settings.

### Operating System

Android

### Operating System Version

Android 11, Android 10, Android Go 11, Android 11

### Device

Lenovo YT-J706F, LG Velvet, Cat S22, Motorola Razr (2020)

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Curtis-D** [comment]
I have this issue, but relating to the master password, and it's intermittent between old and new password. Is this issue tracked somewhere or should I open a new issue?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2321
