### ISSUE TITLE
Bitwarden does not recognize that there is a credential field and does not offer to autofill at Tutanota.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2323]
### Steps To Reproduce

1. Install the Tutanota mail client.
2. Attempt to log in.

### Expected Result

Bitwarden should prompt to perform autofill.

### Actual Result

No autofill prompt is displayed, except if the (Use accessibility) Autofill Service is activated.

### Screenshots or Videos

N/A.

### Additional Context

The Use accessibility Autofill Service does show an autofill prompt.

### Operating System

Android

### Operating System Version

12.

### Device

Samsung Note10+.

### Build Version

2023.1.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thank you for the report @SergeantConfused!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2323
