### ISSUE TITLE
iOS - When creating a new vault item via the Autofill flow through Firefox, Bitwarden does not allow you to set a Username type.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2324]
### Steps To Reproduce

1. Navigate to Vimeo's registration webpage (https://vimeo.com/join) via Firefox.
2. Tap on the (Email) field.
3. Tap on the (Passwords) button above the keyboard.
4. Tap on the (+) button.
5. Tap on the (Username Generator) button.
6. Tap on the (Username type) field.
7. Attempt to select a different Username type.

### Expected Result

To see a (Done) button in the upper right corner of that menu.

### Actual Result

There is no (Done) button in the upper right corner of that menu.

### Screenshots or Videos

Internal.

### Additional Context

This works as expected through Safari.

### Operating System

iOS

### Operating System Version

16.2.

### Device

Iphone SE 2020.

### Build Version

2023.1.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2324
