### ISSUE TITLE
horizontal three dots icon covered 

### ISSUE THREAD

**Issue by brrry2022** [bitwarden/android#2329]
### Steps To Reproduce

1.  In Vault, click Login (Type)
2.  Scroll down to the very bottom.
3.  Lower right is the add Item button (Blue circle). Behind it is the horizontal three dots icon.

### Expected Result

If I want to copy username or password   I have to just click the 3 dots .

### Actual Result

The blue add item icon is covering it.

### Screenshots or Videos

![Screenshot](https://user-images.githubusercontent.com/100246267/214745646-65b161ae-dcde-4cf2-9f7d-7ca921abadfb.jpg)

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 7 Pro

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2329
