### ISSUE TITLE
TOTP Password can't be copied from protected Credentials but seen

### ISSUE THREAD

**Issue by chraebsli** [bitwarden/android#2336]
### Steps To Reproduce

1. Create a new Credential with a TOTP Code
2. Enable the Master Password Protected Option
3. Save the Credential
4. In the App, open the Credential in view mode (without entering a password)

### Expected Result

The TOTP Code either can't be seen and copied without entering the master password
OR the TOTP Code can be seen and copied without the master password

### Actual Result

You can see the TOTP Code and the remaining time but if you want to copy it, you have to enter the master password

### Screenshots or Videos

The TOTP Code can be seen on protected credentials
![totp can be seen](https://user-images.githubusercontent.com/73113302/215997738-bec749dd-6042-4b3f-913f-49b000d995f5.jpg)

To copy the TOTP code, you need to enter the master password
![totp needs password to copy](https://user-images.githubusercontent.com/73113302/215997731-add06e7d-ff2a-4df4-ad98-e4ba48f715ae.jpg)

### Additional Context

It doesn't make sense if the code is protected to copy if you can see it. The only 2 possibilities that make sense are:

1. TOTP Code can't be seen nor copied without master password
2. TOTP Code can be seen and copied without the master password

> This is also an issue in the chrome extention. [Issue Link](https://github.com/bitwarden/clients/issues/4616)

### Operating System

Android

### Operating System Version

Android 12

### Device

Oneplus 10 Pro

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi @chraebsli, this is the expected behavior, at the moment the master password re-prompt only triggers for passwords or hidden custom fields.

If this is important to you, please consider joining our community and voting for it on our feature request page: https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737

I hope you find this helpful. Please do not hesitate to let me know if you have any questions.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2336
