### ISSUE TITLE
Using an NFC-based Yubikey doesn't allow you to choose "Remember Me".

### ISSUE THREAD

**Issue by trparky** [bitwarden/android#2347]
### Steps To Reproduce

1. Login.
2. Note how it goes right to wanting to have you scan your NFC tag without giving you the option to "Remember Me".

### Expected Result

I expected to be giving the option to "Remember Me".

### Actual Result

It doesn't give you an option to choose "Remember Me".

### Additional Context

To fix this, you have to tell iOS to cancel scanning an NFC tag, check "Remember Me", then tell the app to trigger an NFC tag scan.

### Operating System

iOS

### Operating System Version

16.3 (20D47)

### Device

iPhone 13 Pro

### Build Version

2023.1.0 (2886)

### Beta

- [X] Using a pre-release version of the application.

**Comment by djchateau** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by trparky** [comment]
Good to know that you've been able to reproduce this issue. Looking forward to a potential fix.

**Comment by trparky** [comment]
Any idea when this will be fixed?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2347
