### ISSUE TITLE
Cannot choose random "Username"

### ISSUE THREAD

**Issue by inna984** [bitwarden/android#2348]
### Steps To Reproduce

1. Go to "DuckDuckGo" mobile browser on IOS.
2. Click on the password/key looking icon on the password fill in field on the website. Then click on the + to add a new login. After click on the "circle" icon with the arrows to bring up the "Generator" field.
3. Scroll down to "Username type"
4.  and then select what is there and try to switch it. For instance if you switch from "Plus addressed email" and choose "Random Word" There is no okay button or done button visible. There is no way to select it. Therefore you are stuck always on the "Plus Addressed email" selection. 

### Expected Result

I expect to be able to choose the username type like on the desktop and for it to be able to work. I cant even change the username field to random word or plus addressed email. It doesn't work.

### Actual Result

![IMG_0690](https://user-images.githubusercontent.com/37850929/217115610-371f4dc5-7cec-4f63-848a-a3dead6a00b3.jpeg)

see the picture. you cannot select any of the scrollable items at the bottom. 

### Screenshots or Videos

![IMG_0690](https://user-images.githubusercontent.com/37850929/217115610-371f4dc5-7cec-4f63-848a-a3dead6a00b3.jpeg)

### Additional Context

if you look at the picture near the bottom you can scroll through the different types of selections but you cannot select one. There is no "Done" or "Okay" button.

### Operating System

iOS

### Operating System Version

16.3

### Device

Iphone 14 Pro Max

### Build Version

2023.1.0 (2886)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Nater454** [comment]
Same issue started happening on my device. Have generated usernames successfully before, but can't get it to work now.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2348
