### ISSUE TITLE
No auto-keyboard on android app start (while beeing previously logged in)

### ISSUE THREAD

**Issue by mhombach** [bitwarden/android#2349]
### Steps To Reproduce

1. start android app (while beeing already "logged in" but having the vault beeing locked)
2. wait for the app to load and show the "enter password to unlock" screen

### Expected Result

As it was happening in some earlier versions, the user expects the kayboard to automatically popup/appear.
The user-flow in this case is in 99.9% to instantly start typing the password. Having to tap the password-field and wait for the delay to show the onscreen-keyboard is wasting previous time.

### Actual Result

Nothing happens, no onscreen-keyboard is shown

### Operating System

Android

### Device

Xiaomi Redmi Note 10

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by unoukujou** [comment]
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

6 months later. Still a problem. Keyboard should be open and text field should receive focus and ready to type in. It's the expected behavior.

**Comment by unoukujou** [comment]
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

6 months later. Still a problem. Keyboard should be open and text field should receive focus and ready to type in. It's the expected behavior. And was working as expected in old versions.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2349
