### ISSUE TITLE
Android - When creating or editing a vault item while the keyboard is visible, the Save button is no long reachable.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2362]
### Steps To Reproduce

1. Open the Bitwarden Android client.
2. Please on the (+) button to create a new vault item.
3. Tap on the Name field.
4. Tap on the Notes field.

### Expected Result

The Save button should be accessible when focusing on either field.

### Actual Result

The (Save) button is reachable only when focusing on the Name field.

### Screenshots or Videos

N/A.

### Additional Context

I am using Gboard.

### Operating System

Android

### Operating System Version

Android 13.

### Device

Pixel 5.

### Build Version

2023.1.0 (5786).

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi,

Thank you for your report! This issue has flagged to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2362
