### ISSUE TITLE
URl escaped if WebAuthN is not supported

### ISSUE THREAD

**Issue by edent** [bitwarden/android#2364]
### Steps To Reproduce

1. Install BitWarden on a phone with *only* the default AOSP browser (no Chrome or Firefox)
2. Sign in to an account protected by a FIDO security key
3. Attempt to sign in using WebAuthN
4. An error message is displayed - the URl is improperly escaped

### Expected Result

URl should be presented in an unescaped format.

### Actual Result

The `NotAllowedError` message is difficult to read.

### Screenshots or Videos

![Screenshot of the error](https://user-images.githubusercontent.com/837136/218444585-0c52b64d-34ba-4862-9a9b-b370698d1d58.jpg)

### Additional Context

I believe this may have been introduced by #1534? It could also relate to #2334. It is also documented in https://github.com/bitwarden/mobile/issues/1594#issuecomment-1412097146

### Operating System

Android

### Operating System Version

13

### Device

OnePlus 5T

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @edent,

Thank you for reporting this. Just to make sure that you and I are on the same page, by "default AOSP browser" are you referring to Android WebView?


Thank you in advance,

**Comment by edent** [comment]
@SergeantConfused yes, the default Android WebView. 

As per this announcement, it doesn't support WebAuthN https://groups.google.com/a/chromium.org/g/blink-dev/c/qCJhuuZH5p0

See also https://hwsecurity.dev/guide/fido-webview/ and https://mobile.twitter.com/agl__/status/1536058673327288320

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2364
