### ISSUE TITLE
Launch action fails with "www." in the URI

### ISSUE THREAD

**Issue by ttorrisi** [bitwarden/android#2396]
### Steps To Reproduce

1. Ensure that Amazon Shopping mobile app is installed on device
2. Create a Login with required fields (user name, password)
3. Add the URI: https://www.amazon.com, Save
4. Attempt to LAUNCH the login from View item > URI > Launch button or Triple Dot > Launch
5. Note that nothing appears to happen
6. Edit the URI and save as https://amazon.com
7. Repeat step 4, noting that it now launches the website
8. Revert URI entry to https://www.amazon.com
9. Uninstall Amazon Shopping app
10. Repeat step 4, note that it now works

### Expected Result

I would expect that any valid permutation of a URL that launches via a browser should work from within the Bitwarden app. Adding or removing "www." should not effect the behavior, as long as that URL is valid.

### Actual Result

Using https://www.amazon.com instead of https://amazon.com, while the Amazon Shopping app is installed on the mobile device, does not work. Uninstalling the Amazon Shopping app allows both permutations or the URI to function properly using the LAUNCH action.

### Additional Context

I have contacted Bitwarden support about this, and an issue should already be in the system tagged to the email "ttorrisi@gmail.com"

### Operating System

Android

### Operating System Version

Android 13, February 5, 2023 Security Update

### Device

Google Pixel 6a

### Build Version

2023.2.0 (5944)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @ttorrisi ,

My colleagues and I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our previous email thread, so we can continue troubleshooting.

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ttorrisi** [comment]
Per Adam in Bitwarden support, I am uploading a screen capture of this happening on my device along with some additional information.

>>>
Interestingly enough, the behavior also resolves itself when I disable "Open supported links" via:
Apps > Default Apps > Opening Links > Amazon Shopping

Within that list, I see 55 verified links. Also interesting is that while "[www.amazon.com](http://www.amazon.com/)" is listed, "[amazon.com](http://amazon.com/)" is NOT.

https://user-images.githubusercontent.com/59843880/222724586-6f57a47a-00c0-4f5b-8a0b-85519f49c97e.mp4

**Comment by atjbramley** [comment]
Hi @ttorrisi, 

Thank you for your report and additional information! 

I've now flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by ttorrisi** [comment]
After further conversation with Adam, I wanted to add a bit more context. This also happens regardless of whether or not I include the protocol of https://.

The attached video shows all 4 permutations of the URL (amazon.com, www.amazon.com, https://amazon.com, https://www.amazon.com) and how the behavior changes based on whether "Open supported links" is enabled in the App settings.

https://user-images.githubusercontent.com/59843880/222757066-c185fe06-d178-40a2-9de8-d1886b5d5909.mp4

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2396
