### ISSUE TITLE
Android Last Sync timestamp is inaccurate

### ISSUE THREAD

**Issue by avipars** [bitwarden/android#2420]
### Steps To Reproduce

Android 13 on an s23 

In settings the sync timestamp is inaccurate kn the preference screen. 
When I click on sync, I then actually see the accurate last sync time

### Expected Result

To see the accurate sync timestamp 

### Actual Result

I see an outdated sync timestamp 

### Screenshots or Videos

![Screenshot_20230320_101052](https://user-images.githubusercontent.com/5733247/226282020-7251d56b-2e64-413a-85aa-262fe3a1a965.jpg)
![Screenshot_20230320_101048](https://user-images.githubusercontent.com/5733247/226282026-1bfdd760-6762-475b-97e9-ee9a236ab4bc.jpg)

### Operating System

Android

### Operating System Version

Android 13

### Device

Samsung galaxy s23

### Build Version

Version: 2023.2.0 (5944)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @avipars ,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by avipars** [comment]
One thing to add, my phone is using 24-hour time. 
When I switched to 12-hour time it appears to be correct.

**Comment by atjbramley** [comment]
Thanks for this addition - however when I tested this, the time shown on the 'settings' screen was wrong for both hours and minutes!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2420
