### ISSUE TITLE
Cannot save PDF attachment on iPad

### ISSUE THREAD

**Issue by marcw** [bitwarden/android#2447]
### Steps To Reproduce

1. Go to an item
2. Click on a PDF attachment. 
3. Use the share sheet that opens.
4. Click on « Files »

### Expected Result

I should be able to select where I want my file to be saved, and the file should be saved where I decided.

### Actual Result

I can’t choose where to save the file, and the file isn’t downloaded.

### Additional Context

A small blank modal appears and disappears. On iOS, this modal contains the destination selection sheet.

### Operating System

iOS

### Operating System Version

iPadOS 16.3.1

### Device

iPad Pro (11-inch) (4th generation)

### Build Version

2023.2.0 (3044)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @marcw,

Thank you for your report. I was able to reproduce this issue on an iPhone running iOS 16.3.1, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you once again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2447
