### ISSUE TITLE
[Bug] TOTP screen is closed when switching to the OTP app while logging in to Bitwarden in Safari

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/android#2479]
### Steps To Reproduce

1. Log in to Bitwarden on iOS
2. Set the "Vault timeout" to a small number, like 15 minutes, and the "Vault timeout action" to "Log out"
3. Log in to Bitwarden in Safari
4. (Optional) Completely close Safari from the App Switcher
5. Wait for the timeout to expire
6. Open Safari and navigate to a website where you have an entry for (I did this in the Private Browsing mode)
7. Click on "Passwords" to open Bitwarden
8. Fill in the username and password fields
9. When you see the TOTP screen, use the App Switcher to minimize Safari
10. Open your OTP app and copy the TOTP
11. Go back to Safari from the App Switcher
12. Observe the Bitwarden login window is completely closed
13. Click on "Passwords" again
14. You will go back to step 8.

### Expected Result

The TOTP screen is expected to remain open when switching to the OTP app to copy a TOTP

### Actual Result

The user gets somewhat stuck in an infinite loop where they can not log in to Bitwarden unless they jump through a few hoops

### Screenshots or Videos

The password screen (which is followed by the TOTP screen)
![IMG_3756](https://user-images.githubusercontent.com/11276349/232553841-1f3da9fd-00d4-4a1b-b7f6-e51ddb53c521.PNG)

After coming back to Safari to enter the TOTP
![IMG_3757](https://user-images.githubusercontent.com/11276349/232553862-03de1fac-228c-4210-a869-96dc84e4262b.PNG)

### Operating System

iOS

### Operating System Version

16.4.1

### Device

iPhone XS

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by MahdiNazemi** [comment]
@Krychaz, this bug hasn't been resolved although 7 months have passed since the initial bug report. Can you please remind your engineering team of this annoying problem?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2479
