### ISSUE TITLE
Yubikey not recognized through iOS auto fill 

### ISSUE THREAD

**Issue by cryptomtnbiker** [bitwarden/android#2485]
### Steps To Reproduce

1. Configure bitwarden to use yubikey 5c nfc (only one I’ve tested with)
2. Set iOS bitwarden app to log out immediately (or any set time period)
3. Allow time in step 2 to expire
4. Open any app or site that has a password, preferably one stored on bitwarden
5. Click on “passwords” to launch bitwarden
6. Enter email address and password
7. Yubikey prompt will show yubikey neo and not recognize yubikey 5c nfc
8. You will be unable to log into bitwarden

### Expected Result

I expect that the yubikey prompt will recognize my yubikey 5c nfc and allow authentication. 

### Actual Result

Yubikey 5c nfc is not recognized. 

### Screenshots or Videos

![217417BA-A658-4FE6-BF47-5F3676108645](https://user-images.githubusercontent.com/96400516/233473862-260e8f96-b15f-422e-b47c-e90065781e0a.jpeg)

### Operating System

iOS

### Operating System Version

iOS 16.3.1 (20D67)

### Device

iPhone xs

### Build Version

Version: 2023.3.2 (3195)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by cryptomtnbiker** [comment]
In addition. 
if you have bitwarden set to log off, and have unlock with FaceID set to on, password auto fill will always prompt for login. Even if you have already logged in and authenticated through the app.

**Comment by c1-jack** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2485

**Comment by SebDominguez** [comment]
I think the last iOS app update reintroduced this bug
