### ISSUE TITLE
Low resolution for default icons of login elements

### ISSUE THREAD

**Issue by Erd89** [bitwarden/android#2492]
### Steps To Reproduce

1. Add a login item with URIs that do not have a favicon

### Expected Result

The default icon for login elements should correspond to the one presented in the app's home under  'types'.

### Actual Result

The icons are the same but at different resolutions. The one in the login element has such a low resolution that it is completely grainy on a retina display (iphone 14).

### Screenshots or Videos

![IMG_2195](https://user-images.githubusercontent.com/68340121/233927710-f41f9157-ded5-469c-9b59-0a7ff7fc3b07.PNG)
![IMG_2196 (1)](https://user-images.githubusercontent.com/68340121/233928003-3b14d987-a982-4890-ab27-a14f7412bb96.PNG)

### Operating System

iOS

### Operating System Version

16.4.2

### Device

iPhone 14

### Build Version

2023.3.2 (3195)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by c1-jack** [comment]
Hi @Erd89,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2492
