### ISSUE TITLE
"Auto-fill with Bitwarden" obscures the text field on Android tablet

### ISSUE THREAD

**Issue by dj-louw** [bitwarden/android#2522]
### Steps To Reproduce

1. Using any browser, go to any site that has a login form, 
2. Tap on the any of the fields to put the cursor in the field, and make the prompt appear
3. See how the prompt obscures the field that is currently in focus.

### Expected Result

The prompt would appear below or to the side of the field, so that it's still possible to see what I am typing if I elect to not autofill with Bitwarden at this time.

### Actual Result

The prompt obscures the field, making it difficult to see what I am typing in.

### Screenshots or Videos

![Screenshot_20230515_103252_Edge](https://github.com/bitwarden/mobile/assets/1496180/ca589559-a643-482f-bac0-06744573307e)
![Screenshot_20230515_103442_Chrome](https://github.com/bitwarden/mobile/assets/1496180/563b35af-7fe2-4f4d-b036-b7ee2cf34c7d)
![Screenshot_20230515_103639_Firefox](https://github.com/bitwarden/mobile/assets/1496180/a7035fe7-a1e1-478c-94a8-40581f1b8f6a)
![Screenshot_20230515_103233_Edge](https://github.com/bitwarden/mobile/assets/1496180/f319d2a0-52d8-40d7-80db-8090ea62bf85)
![Screenshot_20230515_103258_Edge](https://github.com/bitwarden/mobile/assets/1496180/0651b369-44b9-4429-b13c-48f8c2737db1)
![Screenshot_20230515_103522_Chrome](https://github.com/bitwarden/mobile/assets/1496180/09030486-de3e-4a08-90ab-86706cdfcde9)
![Screenshot_20230515_103632_Chrome](https://github.com/bitwarden/mobile/assets/1496180/e953422a-9bd8-4b2e-b6eb-2b5d7bfa1e50)
![Screenshot_20230515_103700_Firefox](https://github.com/bitwarden/mobile/assets/1496180/9ba8806e-eb62-4f71-8ff6-01b5b283f8fa)
![Screenshot_20230515_103507_Chrome](https://github.com/bitwarden/mobile/assets/1496180/7d1a7fd8-8d32-4659-bc62-90f2fd518c2c)

### Additional Context

This issue was replicated on various websites, (see screenshots), using Chrome, MS Edge and Firefox.
The issue persists regardless if the UI is in portrait or landscape

### Operating System

Android

### Operating System Version

Android 13, Samsung OneUI 5.1

### Device

Samsung Galaxy Tab S8 Ultra

### Build Version

2023.4.0 (6203)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dj-louw** [comment]
That's good to hear @SergeantConfused ,

I think I have given enough screenshots to clearly illustrate the problem. 

If I need to provide specific additional information, or if I can help out by testing a beta or other testing version, I'm more than happy to do so. 

Please let me know in this thread.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2522
