### ISSUE TITLE
Passphrase generation disallows empty word separator

### ISSUE THREAD

**Issue by joseph082** [bitwarden/android#2525]
### Steps To Reproduce

1. Go to Generator
2. Set the generator to generate a passphrase
3. Make the word separator empty
4. Generate a passphrase which will be generated with space as the word separator

### Expected Result

The expected behavior is to generate a passphrase with the empty string as the word separator.

### Actual Result

The actual behavior is to generate a passphrase with space as the word separator.

### Additional Context

Same issue as https://github.com/bitwarden/clients/issues/5437. This was intended behavior and not a bug (there's no other issue template). This issue https://github.com/bitwarden/desktop/issues/1099#issuecomment-941733523 says that allowing the empty string being the word separator is okay.

### Operating System

Android

### Build Version

2023.4.0 (6203)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @joseph082 ,

Thank you for your report and PR.

I was able to reproduce this issue, and I have flagged this to our engineering team.  A member will vet your submission shortly.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2525
