### ISSUE TITLE
Static fields on Identity cards are missing copy buttons

### ISSUE THREAD

**Issue by mackaaij** [bitwarden/android#2527]
### Steps To Reproduce

1. Go to Vaults
2. Click on Identity
3. Open an identity card
4. Notice there are copy buttons for any adjusted fields you may have added, but not for the default fields.

### Expected Result

I was expecting a copy button behind every field.

### Actual Result

Only custom fields have a copy button.

### Screenshots or Videos

I think this can do without a screenshot but let me know if it helps.

### Operating System

iOS

### Operating System Version

16.4

### Device

IPad Pro

### Build Version

2023.4.0 (3303)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2527
