### ISSUE TITLE
Bitwarden do not works with Lemur Browser Beta

### ISSUE THREAD

**Issue by iamgitcat** [bitwarden/android#2528]
### Steps To Reproduce

Autofill not working
1. Keyboard shows Bitwarden without logins
2. Clicking opens Bitwarden and shows `no elements for com.lemurbrowser.exts.beta`

Saving not working
1. Bitwarden asks to save new login
2. Clicking opens saving for `com.lemurbrowser.exts.beta` forgetting the login itself, the name, but remembering password only

### Expected Result

I expect it should be like and other browser, even Lemur Browser itself (not beta), should not show me anything about `com.lemurbrowser.exts.beta`

### Actual Result

Think any element is `com.lemurbrowser.exts.beta`

### Operating System

Android

### Operating System Version

Android 12

### Device

Tekno Pova 3

### Build Version

2023.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team. Take into account that the autofill function is working as expected in the Stable release of Lemur browser.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2528
