### ISSUE TITLE
Cannot create a new Bitwarden account though the mobile Android and iOS clients.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2565]
### Steps To Reproduce

1. Launch Bitwarden.
2. Tap on (Create account).
3. Enter your email address and master password twice, and accept the Terms of Service and Privacy Policy.
4. Tap on (Submit).

### Expected Result

To create a new Bitwarden account.

### Actual Result

An error message is shown. (An error has occurred. An unhandled server error has occurred.)

### Screenshots or Videos

N/A

### Additional Context

Also reproducible on Android 12 with Bitwarden 2023.5.0. Deactivating the (Check for known data breached for this password) function during sign-up does not help.

### Operating System

Android, iOS

### Operating System Version

16.5

### Device

iPhone SE (2020)

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2565
