### ISSUE TITLE
It is not possible to scroll down to view the part of the window or page that's covered by the keyboard.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2581]
### Steps To Reproduce

1. Open the Bitwarden mobile client and tap on the email address field in order to log in.
2. Attempt to scroll down to see the part of the window that's behind the keyboard.

### Expected Result

To be able to scroll down to see the part that's hidden behind the keyboard.

### Actual Result

It's not possible to scroll down.

### Screenshots or Videos

Internal.

### Additional Context

This can be problematic when combined with very large text sizes because it would push the email address field outside the window and make it unreachable, or when the text is large enough to push the email address field to the bottom half and hide it behind the keyboard when attempting to type the email address and log in; It can also completely hide the (Create account) button.

### Operating System

Android, iOS

### Operating System Version

iOS 16.5 and Android 12.

### Device

Samsung Note10+ and iPhone SE (2020)

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2581
