### ISSUE TITLE
iOS Accessibility - VoiceOver states that the Type, Folder, and Ownership fields are Text Fields.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2588]
### Steps To Reproduce

1. Activate VoiceOver on iOS.
2. Open Bitwarden and create a new vault item.
3. Tap once on the Type, Folder, and Ownership selections (not headers).

### Expected Result

For VoiceOver to identify those correctly; They show a selection of options through a scrolling menu.

### Actual Result

VoiceOver identifies them as Text Fields.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

iOS

### Operating System Version

16.5.1

### Device

iPhone SE (2020)

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2588
