### ISSUE TITLE
Android app cannot connect to self hosted server over Tailscale

### ISSUE THREAD

**Issue by sdht0** [bitwarden/android#2599]
### Steps To Reproduce

0. Setup tailscale on homelab and mobile, bitwarden.example.com points to homelab tailscale ip.
1. Setup self hosted bitwarden server at https://bitwarden.example.com:9099.
2. Mobile app sign in and sync works when both homelab and mobile is on the same wifi network.
3. Disconnect mobile from wifi and use LTE.
4. Try to sync the vault.

### Expected Result

Sync should succeed.

### Actual Result

Sync over tailscale when not on the same wifi network fails.

* I am able to access https://bitwarden.example.com:9099 from the mobile browser, so it's not a connection issue.
* Connecting laptop to mobile hotspot over LTE and syncing browser extension also works, so it seems to be an issue only with the mobile app.
* Connecting the phone back to the wifi network (where homelab is) makes sync from the app work again. So it is an issue only when the phone is outside my local network.

### Operating System

Android

### Operating System Version

Android 14 beta

### Device

Pixel 6 pro

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @sdht0,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2599
