### ISSUE TITLE
Yubikey login not working on pixel fold

### ISSUE THREAD

**Issue by pragmaticpandy** [bitwarden/android#2600]
### Steps To Reproduce

1. Add yubikeys using the web interface on chrome macos. I added both a Yubikey ~~NEO~~5 NFC and Yubikey 4C
2. try to login to bitwarden on pixel fold using Yubikey as 2FA. tried:
    * 5 NFC over USB
    * 5 NFC over NFC
    * 4C over USB

### Expected Result

Successful login

### Actual Result

Generic error message and login failure

### Operating System

Android

### Operating System Version

13

### Device

Pixel Fold

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

edit: it's a Yubikey 5 NFC, not a NEO

**Comment by Krychaz** [comment]
Hello there,

Which 2FA method are you using, Yubico OTP (https://bitwarden.com/help/setup-two-step-login-yubikey/) or FIDO2 WebAuthn (https://bitwarden.com/help/setup-two-step-login-fido/)?

Could you test your keys here:
https://demo.yubico.com/otp/verify
https://demo.yubico.com/webauthn-technical/registration

Are there any errors shown on either test?

Could you please download and install the Yubikey Manager Suite from Yubikey's website: https://www.yubico.com/support/download/yubikey-manager/ 

Once you have done this, would you check the Interfaces screen, ensuring that all the Interfaces are enabled.

**Comment by pragmaticpandy** [comment]
> Which 2FA method are you using, Yubico OTP (https://bitwarden.com/help/setup-two-step-login-yubikey/) or FIDO2 WebAuthn (https://bitwarden.com/help/setup-two-step-login-fido/)?
Yubico OTP

>Could you test your keys here: 
both keys work with OTP

>Are there any errors shown on either test?
none on OPT test

>Once you have done this, would you check the Interfaces screen, ensuring that all the Interfaces are enabled.
Yep, they are all enabled.

Also, slight correction, it was a Yubikey 5 NFC, not a NEO. I'll update the original post too.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2600
