### ISSUE TITLE
iOS/IPadOS: For "Unlock with PIN code" mode, Auto-Fill should prompt for PIN but instead prompts for master password

### ISSUE THREAD

**Issue by gsharratt** [bitwarden/android#2601]
### Steps To Reproduce

1. Log into the BW app on the iPhone or iPad device.
2. In the BW app, enable "Unlock with PIN code", selecting Yes for "Do you want to require unlocking with your master password when the application is restarted?"  And disable "Unlock with Face ID".
3. Choose a login item from the BW vault.  
4. Verify that the login item has "Master password re-prompt" disabled.
5. Navigate a browser to the website corresponding to the login item.
6. Verify that this website is not already logged into.
7. Touch the userid field or the password field in the website login form.

Alternatively, run the above repro using an app on the device instead of a website.

### Expected Result

1. If the BW vault is not (yet) locked, the login item's userid and password will be auto-filled (with no prior prompt).
2. If the BW vault is locked, the user will get a BW PIN prompt (prior to auto-fill happening).

### Actual Result

1. If the BW vault is not (yet) locked, the user gets a Master Password prompt (prior to auto-fill happening).
2. If the BW vault is locked, the user gets a Master Password prompt (prior to auto-fill happening).

### Operating System

iOS

### Operating System Version

iOS 16.5.1

### Device

iPhone 13 mini

### Build Version

2023.5.0 (3430)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by gsharratt** [comment]
Hello Support,
This bug is still present after 9 months, for both logins to apps and logins to websites.
Could I please get an update on plans for fixing it?
Thanks,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2601
