### ISSUE TITLE
iOS Accessibility - Swiping right and left through the Edit menu is unintuitive and out of order.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2607]
### Steps To Reproduce

1. Activate VoiceOver on iOS.
2. Open Bitwarden and edit a vault item.
3. Swipe right to go through the headings, fields, and toggles.

### Expected Result

To go through the headings, fields, and toggles in a correct order.

### Actual Result

Swiping right through the (Favourite) and (Master password re-prompt) options:
1. VoiceOver states "Switch button. Off" but does not state what it corresponds to; It does come after stating "Favourite" but explicitly stating that the switch button relates to that function would be helpful.
2. In the (Master password re-prompt) line VoiceOver states "Toggle visibility", then "Switch button. Off", and then "Master password re-prompt" which is the incorrect order and can cause confusion.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

iOS

### Operating System Version

16.5.1

### Device

iPhone SE (2020)

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2607
