### ISSUE TITLE
iOS Accessibility - Swiping right through the Vaults menu goes through the icons for Login, Card, Identity, and Secure note.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2614]
### Steps To Reproduce

1. Activate VoiceOver on iOS.
2. Open Bitwarden.
3. Swipe right through the (Login), (Card), (Identity), and (Secure note) lines.

### Expected Result

To go through the name, such as (Login), and the number of items.

### Actual Result

VoiceOver goes through the icon of each line, adding an unnecessary swipe.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

iOS

### Operating System Version

16.5.1

### Device

iPhone SE (2020)

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2614
