### ISSUE TITLE
iOS - App doesn’t detect FaceId instead asks for Fingerprint unlock

### ISSUE THREAD

**Issue by manikanta-dornala** [bitwarden/android#2617]
### Steps To Reproduce

Download app
Login
Enable FaceId
Enable autofill
Enable extension
Close app
Use an app that requires input
Click on Bitwarden on keyboard

iOS app on FaceId devices is asking for Fingerprint unlock on iOS 17 Beta 3 on iPhone 12 Pro Max 

### Expected Result

Should ask for Face Unlock

### Actual Result

Currently asking for FingerPrint unlock

### Screenshots or Videos

![IMG_5224](https://github.com/bitwarden/mobile/assets/11387913/63920989-7ed1-4d78-8795-24b4e33fb070)

### Operating System

iOS

### Operating System Version

iOS 17 Beta 3

### Device

iPhone 12 Pro Max

### Build Version

Version: 2023.5.0 (3430)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by DimitriDR** [comment]
Same issue on public iOS 17 beta on iPhone XS.

**Comment by MarsCandyBars** [comment]
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2617
