### ISSUE TITLE
Autofill issue in stargon browser.

### ISSUE THREAD

**Issue by lloo07** [bitwarden/android#2624]
### Steps To Reproduce

Autofill issue in stargon browser.
I searched for this issue and it seems that it has not been resolved since 2 years ago. I hope to be able to resolve this issue.

The corresponding Android app package is "net.onecook.browser".

Below are the previously raised issues.

https://github.com/bitwarden/mobile/issues/1358

### Expected Result

The user login site url should appear.

### Actual Result

It shows net.onecook.browser on top.

### Operating System

Android

### Operating System Version

all versions

### Device

all devices

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below.

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2624
