### ISSUE TITLE
iOS - When you have numerous items for the same page, autofill fails

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/android#2645]
### Steps To Reproduce

Prerequisite: Have over 1,000 items saved in your vault for a single page.

1. Navigate to github.io/login.
2. Click on the username field and wait for the key icon to appear.
3. Tap on the key icon.
4. Unlock your vault.
5. Attempt to autofill the login entry.

### Expected Result

1. Navigate to github.io/login.
2. Click on the username field and wait for the key icon to appear.
3. Tap on the key icon.
4. Unlock your vault.
5. After a successful unlock, you get to search for the desired account and autofill it.

### Actual Result

1. Navigate to github.io/login.
2. Click on the username field and wait for the key icon to appear.
3. Tap on the key icon.
4. Attempt to autofill the login entry by unlocking your vault.
5. After a successful unlock, a brief flash of the vault window is observed.
6. Notice that the vault window closes automatically, and you are redirected back to an empty github.io/login page, no autofill action gets performed.

Note: If you rapidly attempt a second time, after unlocking, 11 items get displayed and the rest of them are discoverable once you tap on the Search icon. The autofill action still fails if you click on any of them.

### Operating System

iOS

### Operating System Version

iOS 16.6

### Device

iPhone SE 2020

### Build Version

2023.7.0 (3881)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by johnduprey** [comment]
I've seen this auto-fill issue occur regardless of how many were available for the site. The vault itself has over 5,000 entries. 

Switching accounts back to personal allows auto-fill to work again, so this appears to be related to the size of the vault.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2645
