### ISSUE TITLE
Mojibake on account name badge when using Devanagari script

### ISSUE THREAD

**Issue by sanketgarade** [bitwarden/android#2651]
### Steps To Reproduce

1. Prerequisite - Your account name should be written in [Devanagari](https://en.wikipedia.org/wiki/Devanagari) script.
2. Go to Vaults page/tab in the mobile app
3. Look at / or tap on the circle in the top left corner when you would expect your account name initial to be displayed.

### Expected Result

The name initial should appear as expected in Devanagari script. Here it how it looks on the web client (as expected) - 

![image](https://github.com/bitwarden/mobile/assets/74632379/023457d0-360b-45e2-b1d9-07c6a36cdee7)

### Actual Result

The name initial doesn't appear in Devanagari, instead there is [mojibake](https://en.wikipedia.org/wiki/Mojibake#). Here is how it looks on the mobile app -

![image](https://github.com/bitwarden/mobile/assets/74632379/06922b32-12ec-451d-8030-8392cb1cb9c7)

### Additional Context

The other places (such as the items list, folders, editor etc.) render Devanagari correctly. It is only the account name badge where the mojibake happens.

### Operating System

iOS

### Operating System Version

iOS 16

### Device

iphone 12 mini

### Build Version

2023.7.0 (3881)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @sanketgarade ,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2651
