### ISSUE TITLE
Empty vault 

### ISSUE THREAD

**Issue by qwerty1twotre** [bitwarden/android#2661]
### Steps To Reproduce

1. Open bitwarden app on android

### Expected Result

I expect that i can show my passwords.

### Actual Result

I can't see my passwords.

### Screenshots or Videos

![Screenshot_20230804_091838](https://github.com/bitwarden/mobile/assets/141397893/f2624553-f0ad-469b-ac60-732ff2d37f2a)

### Operating System

Android

### Operating System Version

13

### Device

Samsung galaxy s20

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
I’m sorry that you’re experiencing this.

My first suggestion would be to sign out and back in again - this is most likely just a connection glitch.
Could you also try signing in on a different browser or client if that doesn't resolve the issue?

I look forward to hearing from you.

**Comment by Keinta15** [comment]
I did found this [https://www.reddit.com/r/Bitwarden/comments/15mjbe7/repeatable_empty_vault_when_log_into_web_vault/?share_id=JrP2Fch0qRI4SiwLGnh96](thread) related to this issue,

**Comment by qwerty1twotre** [comment]
I tried many times to logout and login but I had the same problem.
I tried also to reboot my phone but with no success.

**Comment by Krychaz** [comment]
Hi,

Could you please try to fully reinstall the app. Does that help?

**Comment by qwerty1twotre** [comment]
In really the app has this problem sometimes, for example now there's no problem.
I used bitwarden also in other devices but without errors.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2661
