### ISSUE TITLE
Password formatting not consistent across password creation methods

### ISSUE THREAD

**Issue by ClareClever99** [bitwarden/android#2665]
### Steps To Reproduce

When creating a password within the app, you have formatting that lets you see what the password consists of. The current formatting shows symbols as red and numbers as blue (see photo 4). I really like that and that small feature really helps. It works great if you are creating a new password using the generator inside the app. However, I have noticed that if you use the popup tool that allows you to login on a web-browser the formatting is not the same. Using the generator that is embedded in the popup leads to different formatting (see picture 3).

### Expected Result

I would expect that the formatting should be the same across image 3 and 4. The formatting in image 3 should match how it is in image 4. I like how it is in image 4 and would expect that the formatting in image 4 should be how it is in image 3 as well.

### Actual Result

I really like how it formats the password in picture 4, however when creating a new password in the way detailed in images 1-3 (which BTW is just an example and obviously not my real password) the formatting is striped, leaving the password all black.

### Screenshots or Videos

**_Image 1_=Example of how a user can sign in and use Bitwarden from within the browser**:
![1-Signing in](https://github.com/bitwarden/mobile/assets/59885439/0894deb0-f811-4046-ab3c-befd8f2083da)
**_Image 2_=Popup that allows user to create a new password entry**:
![2-Password creation popup](https://github.com/bitwarden/mobile/assets/59885439/15cb5e21-ae09-4c23-a4e2-515437aaf24a)
**_Image 3_=Popup that allows user to generate a new password for their new entry (no formatting)**:
![3-Password generaor popup](https://github.com/bitwarden/mobile/assets/59885439/cf4e13c9-d28c-4951-bed9-855110448a0c)
**_Image 4_=Password generator tool within the app that displays correct formatting**:
![4-Password generator inside app](https://github.com/bitwarden/mobile/assets/59885439/63b874bd-21c4-45a2-801a-217ccb59f658)

### Additional Context

Let me know if you have any other questions on what this issue is about or how to recreate it.

### Operating System

iOS

### Operating System Version

16.6

### Device

iPhone 12 Pro

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2665
