### ISSUE TITLE
All items duplicated in vault

### ISSUE THREAD

**Issue by scotte** [bitwarden/android#271]
On one of my Android devices, most (but oddly not all) entries were doubled. A sync resolved it, so it was specific somehow to this one device and a transient issue. While ultimately it solved itself after manual sync, I thought I would report it.

**Comment by kspearrin** [comment]
Yea I’ve seen it happen before as well but have been unable to figure out how to reliably reproduce it.

**Comment by kspearrin** [comment]
It also happens on iOS.

**Comment by jonasschuele** [comment]
It happens mostly when Search is clicked on iOS

**Comment by rggjan** [comment]
Yes, Just had the same issue on iOS (while having seen it on Android before as well). Let me know if I can somehow help to resolve this...

**Comment by janos-szenfner** [comment]
Sorry I opened the same problem with new issue Id. It happens on Android continuously.

**Comment by kspearrin** [comment]
@janos-szenfner Do you know how to reproduce it?

**Comment by janos-szenfner** [comment]
Hi, it happened to me when I tried to fill out an application's user/password field in Android. It happened with app multiple times. So something app related and not browser.

Kind Regards

**Comment by kspearrin** [comment]
@janos-szenfner Please let me know if you can find the steps to reliably reproduce it every time.

**Comment by Daptonic** [comment]
Seeing duplicates in my Android and iOS vaults. No dups in web vault ... not trick to getting it to happen, it just does or doesn't sadly.

**Comment by dubstir** [comment]
I am running iOS 10.3.3 and whenever I open the app for the first time of that day I have duplicates for every entry, except any notes. A sync does resolve this, but then it will happen the next day on the initial app opening.

**Comment by juanchristian** [comment]
Running iOS 11.3.1 and I'm also seeing this. It's inconsistent: sometimes nothing is duplicated, other times some of my sites are duplicated. This is very frustrating, the only way to temporally fix is to force sync. This is not a final fix as this behavior repeats after some time.

**Comment by juanchristian** [comment]
I did some testing and it seems this happens for the first time I open the app when it goes out of memory. If I force close the app, wait 5 sec and open it again I can see a bunch of duplicates sites, sometimes they vanish and the app goes back to normal, other times they stick there and I have to force close, wait 5 sec and open again hoping this time they they duplicate.

**Comment by kspearrin** [comment]
Should be fixed next version.

**Comment by silv3r23** [comment]
Hello, I want to re-open this issue. On iOS (iPhone and iPad) I see each entry 4 times once I tapped to the Search Icon and entered a keyword. I can reproduce it on any page/site with any credentials. I don't have multiple entries in my vault (Browser Extension and macOS App) its just the search result.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/271
