### ISSUE TITLE
Email - "New Device Logged In From Android" Wrong IP address

### ISSUE THREAD

**Issue by unoukujou** [bitwarden/android#2727]
I logged in with a new device on EU server.

Got email:

```
Your Bitwarden account was just logged into from a new device.

IP Address: 20.X.X.X
```

This is NOT my IP.

I'm not using a proxy or VPN.

I think this is the IP of the server that is hosting bitwarden EU.

Googled it and yes, I'm not the only one.

Not good. Just saying. Bitwarden is supposed to be highly secure and these kind of issues just doesn't make me feel at ease. An alert telling me a new device logged in, and it gives me the wrong IP. What am I supposed to think? Was it me? Or not? I'm screwed? Help!

### Expected Result

My IP

### Actual Result

Not my IP

### Operating System

Android

**Comment by unoukujou** [comment]
To reproduce:

1) Log in.
2) Read the email you receive with subject: "New Device Logged In..." And see that the IP of this new login is not your IP.

**Comment by unoukujou** [comment]
iOS same thing.

**Comment by unoukujou** [comment]
A guy reported this over 4 years ago. Then the founder of Bitwarden solved the problem by adding a setting to just disable the new login alert emails. No I'm not joking. 🤦 

[https://github.com/bitwarden/server/issues/466](https://github.com/bitwarden/server/issues/466) 

And the guy said... Thanks! 🤦‍♂️ 🤦‍♂️

**Comment by SergeantConfused** [comment]
Hi @unoukujou,

Thank you for your report; I am able to reproduce this and I have flagged it to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,

**Comment by GieltjE** [comment]
Using apache as a reverse proxy, keep getting these for "172.19.0.1"

Setting either

```        RemoteIPHeader X-Forwarded-For
        RemoteIPInternalProxy 172.16.0.0/12```

or

```ProxyPreserveHost On```

Yields no improvement

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2727
