### ISSUE TITLE
iOS share icon has a non-transparent background 

### ISSUE THREAD

**Issue by dnicolson** [bitwarden/android#2744]
### Steps To Reproduce

1. Open Safari
2. Navigate to any page
3. Tap on the share button and scroll down

### Expected Result

The Bitwarden icon has a transparent background as the other items.

### Actual Result

The icon is not transparent.

### Screenshots or Videos

![IMG_9466](https://github.com/bitwarden/mobile/assets/2276355/f52e5b05-ced8-4550-9b9d-47ed890d4852)

### Operating System

iOS

### Operating System Version

iOS 17

### Device

iPhone 13 mini

### Build Version

2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2744
