### ISSUE TITLE
Order of the elements

### ISSUE THREAD

**Issue by ghost** [bitwarden/android#2763]
### Steps To Reproduce

1. Go to Bitwarden
2. Click on login

### Expected Result

The order of the items is incorrect, before the update it was sorted into: Google, Google 2, Google 3

### Actual Result

The order now is Google 2, Google 3, Google

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/138575369/12f8a8b7-b245-411f-b2ba-755fd99a9a39

### Operating System

iOS

### Operating System Version

16.6.1

### Device

iPhone X

### Build Version

2023.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by enzor00** [comment]
Hello, to date the problem still has not been solved. Is there any update on the situation?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2763
