### ISSUE TITLE
Typo in Core.Test.csproj

### ISSUE THREAD

**Issue by RougherO** [bitwarden/android#2809]
### Steps To Reproduce

In Core.Test.csproj under  test/Core.Test/ 
`..\common\Common.csproj` should have uppercase `C` instead of `c` since directory name is `Common`
```
<ItemGroup>
    <ProjectReference Include="..\..\src\Core\Core.csproj" />
    <ProjectReference Include="..\common\Common.csproj" />
</ItemGroup>
  ```

### Expected Result

Should properly build tests

### Actual Result

Error in building tests

### Screenshots or Videos

![image](https://github.com/bitwarden/mobile/assets/83248988/3fd5b7e3-56c8-4a04-89f7-5c2a811dc7e5)

### Operating System

Android, iOS

### Build Version

N/A

### Beta

- [ ] Using a pre-release version of the application.

**Comment by octopols** [comment]
Hello, I'd like to work on this issue. Could it be assigned to me, please?

**Comment by djsmith85** [comment]
Hi @octopols and thank you for your interested in contributing 🚀 

We don't assign issues, but we appreciate any kind of contribution. Best to visit our [Contributing Guidelines](https://contributing.bitwarden.com/), they'll have everything you'll need to get started.

Please make sure to link this ticket if you do create a Pull Request.

Kind regards,
Daniel

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2809
