### ISSUE TITLE
Login suggestions are squished vertically when Bitwarden is locked. Unreadable.

### ISSUE THREAD

**Issue by varunyellina** [bitwarden/android#2829]
### Steps To Reproduce

1. Go to any page where Login details are to be filled
2. You will see that the suggestions are squished.
3. Go to Bitwarden and authenticate yourself
4. Come back to the login page and see that the suggestions are not squished anymore

### Expected Result

The Login suggestions should be shown correctly

### Actual Result

The suggestions are squished. When using Samsung Keyboard it says that Bitwarden Vault is locked. This allowed me to tap on it to show authenticate with Bitwarden. Once done, I'm able to see suggestions in both Gboard and Samsung Keyboard.

### Before Authentication (using fingerprint in Bitwarden)

**Gboard on Firefox**
![Gboard on Firefox](https://github.com/bitwarden/mobile/assets/1850730/c3363ab5-0c76-4c08-88a6-f0b06886c57c)
**Samsung Keyboard on Firefox**
![Samsung Keyboard on Firefox](https://github.com/bitwarden/mobile/assets/1850730/7992c13d-99d8-4476-b9d0-5dd0d27e3cad)

### After Authentication (using fingerprint in Bitwarden)
**Gboard on Firefox**
![Gboard on Firefox](https://github.com/bitwarden/mobile/assets/1850730/dc11463b-17f6-4016-8bdb-b78708ee7fbc)
**Samsung Keyboard on Firefox**
![Samsung Keyboard on Firefox](https://github.com/bitwarden/mobile/assets/1850730/ce7c0fb4-10fd-4f31-b378-856d4af7dc87)

### Operating System

Android

### Operating System Version

13

### Device

Samsung Z Flip 3

### Build Version

2023.9.1 (7790)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2829
