### ISSUE TITLE
Mobile App doesn't respect changed system font size

### ISSUE THREAD

**Issue by raulomator** [bitwarden/android#2830]
### Steps To Reproduce

Mobile App Version: 2023.9.2 (8002)
Mobile Phone: Pixel 8 Pro (Android 14)

It's hard to grasp when or why the app does not respect font size.

I would say, if you open the app through normal touch on the symbol 75% of the time the app opens (in my case) with bigger font size than standard (smaller) Pixel 8 Pro font size.

Every time app is closed and I choose to open it via the default website login form buttons to fill the form out, the app opens in (it seems) the small/default Pixel 8 Pro font size.

Please tell me how I can help fixing this (for me) really annoying bug.

### Expected Result

Respecting Android system _active_ user font size.

### Actual Result

sometimes yes, sometime no

### Operating System

Android

### Operating System Version

14

### Device

Google Pixel 8 Pro

### Build Version

UD1A.230803.041

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Tipoff4317** [comment]
Yes.  I have always had this problems on both Android 12 & 13, although it doesn't bother me enough to pay attention to when it does happen / doesn't.

**Comment by atjbramley** [comment]
Hi @raulomator ,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by fxzxmicah** [comment]
Good to hear. I reported this issue several years ago via support email but unfortunately it was not taken seriously.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2830
