### ISSUE TITLE
TOTP list does not respect "Show website icons" option

### ISSUE THREAD

**Issue by pwseo** [bitwarden/android#2831]
### Steps To Reproduce

1. Set the "Show website icons" option to off
2. Go to the "Verification codes" page
3. Observe that TOTP codes all have website icons
-- bonus: --
4. Go back to your regular Login list
5. Observe that none of the entries has website icons

### Expected Result

Entries in the "Verification codes" list should not have website icons

### Actual Result

Entries in the "Verification codes" list have website icons, despiste the option "Show website icons" being set to off.

### Screenshots or Videos

![totp](https://github.com/bitwarden/mobile/assets/95953/435c0ba3-6adc-40e9-b27c-7f9031dab06e)
![logins](https://github.com/bitwarden/mobile/assets/95953/57419fdc-37ae-46db-96c2-0da13d133f0e)

### Operating System

iOS

### Operating System Version

iOS 16.7.1

### Device

iPhone 12 mini

### Build Version

2023.9.2 (5102)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

Would you be able to provide screenshot of what you see in terms of icons?

**Comment by pwseo** [comment]
Sure. The first image is from the "Verification codes" list, which has website icons even though it should not. The second image is from the Login list, that correctly shows no website icons (just the generic placeholder globe).
![totp](https://github.com/bitwarden/mobile/assets/95953/435c0ba3-6adc-40e9-b27c-7f9031dab06e)
![logins](https://github.com/bitwarden/mobile/assets/95953/57419fdc-37ae-46db-96c2-0da13d133f0e)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2831
