### ISSUE TITLE
Autofill using Spin Browser package name instead of URL

### ISSUE THREAD

**Issue by theRealPadster** [bitwarden/android#2848]
### Steps To Reproduce

Open Spin Browser (https://play.google.com/store/apps/details?id=com.nationaledtech.spinbrowser)

1. Go to any website and log in.
2. Bitwarden Autofill notification appears.
3. Select the notification.
4. It shows com.nationaledtech.spinbrowser instead of website URL.

### Expected Result

The site URL should show in the bitwarden app that pops up, and it should show matching items from my vault. 

### Actual Result

It shows "com.nationaledtech.spinbrowser" as the filter/search instead, and doesn't find any matching items. 

### Screenshots or Videos

![Screenshot_20231031-233032](https://github.com/bitwarden/mobile/assets/1565883/75e51777-0354-40ba-9f9d-fac6ad2efa66)

### Additional Context

This has been happening for a year or two at least, since I started using the browser. It had the same issue on the Pixel 2 (Android 11 I think?) and Samsung Galaxy A13 5G (Android 13) phones I have used. This seems to be the same issue as https://github.com/bitwarden/mobile/issues/2624 and https://github.com/bitwarden/mobile/issues/2528. There looks to be an open PR (https://github.com/bitwarden/mobile/pull/2466) to fix the issue with Lemur Beta, and if it's correct, then I can make a matching PR myself for Spin Browser. 

### Operating System

Android

### Operating System Version

14

### Device

Pixel 7a

### Build Version

Version: 2023.9.2 (8002)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report!

I was able to reproduce this issue, and I have flagged this to our engineering team. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by theRealPadster** [comment]
@Greenderella Thanks for taking a look! I am wondering what needs to be done to get this patched in. The PR I linked for Lemur Browser (https://github.com/bitwarden/mobile/pull/2466) looks like it makes some fairly simple changes to a few files to whitelist the browser package name essentially. Is that all that needs to be done? If that's the case, then I can make a similar PR for Spin Browser as well. I'm just hoping to expedite it as much as I can since it's fairly annoying always having to do a search for the site I'm on whenever I go to autofill.

**Comment by theRealPadster** [comment]
@Greenderella Just for visibility, I've created a PR that should add support, based on the recently-merged PR for Chromite https://github.com/bitwarden/mobile/pull/2466. If you could take a look or flag to the engineering team (or whatever the next steps would be), that would be much appreciated :)

**Comment by Greenderella** [comment]
Thank you @theRealPadster, I can see one of our engineers already linked the PR with this issue!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2848
