### ISSUE TITLE
Android URI recognition fail for ID (unusual)

### ISSUE THREAD

**Issue by businessBoris** [bitwarden/android#2858]
### Steps To Reproduce

1. Take AppID from Google Play App share feature of Costco Wholesale UK app.
Result: https://play.google.com/store/apps/details?id=intl.costco.com.mobile.uk
So AppID is intl.costco.com.mobile.uk
2. Create standard login entry within Bitwarden Android App for Costco entry. 
3. In the URI section, enter the standard protocol prefix:
"androidapp://"
4. Append the AppID to this prefix without spaces etc.
androidapp://intl.costco.com.mobile.uk
6. Save the entry to the vault
7. Note that the URI is recognised as a website not an Android app.

### Expected Result

URI should be recognised as an Android App.
Entry in URI section should show 'URI' entry type with the given AppID in the field. 

### Actual Result

However. The field is named/identified with entry type 'Website'. 
This is incorrect.

### Additional Context

I have many apps past and present stored within Bitwarden. Costco Warehouse UK is the only one I have found that Bitwarden has incorrectly identified.

Perhaps the AppID is incorrectly formatted but the protocol indicator explicitly identifies it as an app, via the protocol identifier 'androidapp://"

### Operating System

Android

### Operating System Version

14 
[5 October 2023 security patch]

### Device

Google Pixel 7 Pro

### Build Version

Version: 2023.10.0 (8257)

### Beta

Standard version of Android Bitwarden. Never used beta.

**Comment by SergeantConfused** [comment]
Hi @businessBoris,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2858

**Comment by businessBoris** [comment]
It's back. Everything is labelled "Website(URI)".

**Build Version**

Version: 2025.6.1 (20398)
