### ISSUE TITLE
no push notification sent to iphone for login with device

### ISSUE THREAD

**Issue by payback007** [bitwarden/android#2859]
### Steps To Reproduce

No push notification is sent to iphone for "login with device". All rights are granted to bitwarden app in internal ios notifications.

### Expected Result

After "login with device" a push notification for opening bitwarden app should be sent to iphone.

### Actual Result

Manual opening of bitwarden app and manual "scroll down" in vault -> notification for unlocking is shown.

### Operating System

iOS

### Operating System Version

17.1

### Device

iPhone SE

### Build Version

2023.10.0 (5357)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @payback007,

Thank you for your report. I was able to reproduce this behaviour right after turning the phone on and before launching Bitwarden, and I have flagged it to our Engineering team. Please note that once Bitwarden is launched at least once after the phone is turned on, the notifications are consistently received successfully.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by payback007** [comment]
I tried to reproduce your statement, that if bitwarden is started once, push notifications are received successfully with this results:
- Phone in standby, bitwarden closed -> no push notification (as described above)
- Phone in standby, bitwarden open -> no push notfication in standby state, no push notification after unlocking of phone
- Phone in standby, bitwarden in backgroud -> no push notfication in standby state, no push notification after unlocking of phone
- Phone unlocked, bitwarden open in foreground -> no push notification

I never get a push notification until I do a manual "scroll down" in openend bitwarden app -> after manual "scroll down", all push notifications are received, one by one every time with a new manual "scroll down".

**Comment by payback007** [comment]
Issue still existing with version 2023.12.0 (5688).

**Comment by payback007** [comment]
Issue still existing with version 2023.12.0 (5688).

**Comment by payback007** [comment]
Issue still existing with version 2023.12.0 (5688).

**Comment by wioch** [comment]
Same in 2024.1.1 (8843).  
Even having mobile app opened, there is no notification at all.

**Comment by jaimeferj** [comment]
Same in 2024.5.1 running on Pixel 8a. 

- Phone in standby, bitwarden closed -> no push notification
- Phone in standby, bitwarden open -> no push notfication in standby state, no push notification after unlocking of phone
- Phone in standby, bitwarden in backgroud -> no push notfication in standby state, no push notification after unlocking of phone
- Phone unlocked, bitwarden open in foreground -> no push notification, only showing the request after manually updating by scrolling down.

The most important thing is that the application never sends a notification in my case. I've already checked that it has permissions. In my case the service is selfhosted.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2859
