### ISSUE TITLE
Pin keyboard won't pop up on application launch

### ISSUE THREAD

**Issue by LeafyLappa** [bitwarden/android#2866]
### Steps To Reproduce

1. Enable "Unlock with PIN code" in account security settings
2. Ensure that the application is not running 
3. Launch the application (I can reproduce this bug by opening Bitwarden using the autofill button on Gboard as well as launching normally)

### Expected Result

"Verify PIN" activity starts. Pin keyboard slides up from the bottom, prompting me to enter the pin.

### Actual Result

"Verify PIN" activity starts. No keyboard is present, however. I have to stretch my finger to the top of the screen to tap the PIN EditText to make the keyboard appear.

### Screenshots or Videos

Self explanatory?

### Additional Context

This problem becomes obnoxious if you set session timeout to "immediately"

### Operating System

Android

### Operating System Version

Android 14 UP1A.231105.003

### Device

Pixel 7

### Build Version

2023.10.0 (8257)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @LeafyLappa,

Thank you for this report. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one, and [this thread](https://community.bitwarden.com/t/automatically-open-keyboard-when-the-pin-entry-screen-is-opened-android/40194) seems to be similar to what you are suggesting.

We use GitHub issues to track bugs and other development related issues; This report will now be closed. Please note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to join the community and to vote for that feature request.

Thank you again,

**Comment by LeafyLappa** [comment]
This is definitely a bug though. The keyboard does in fact pop up on activity restart, it just doesn't when the app is relaunched entirely

**Comment by SergeantConfused** [comment]
Hi @LeafyLappa,

Thank you for following up on this. I've tested this once more; When Bitwarden is launched while it is active in the background and is locked due to the (Vault Timeout) function, the keypad is shown automatically. I will open this GitHub report and route this internally.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2866
