### ISSUE TITLE
Don't say no items in vault initially before verifying

### ISSUE THREAD

**Issue by jidanni** [bitwarden/android#2874]
### Steps To Reproduce

With the Android app, on a highly loaded, slow network, login to your vault, with the master password.

### Expected Result

We see we have 543 items in our vault.

### Actual Result

However, before we see that, for a very short split second, we see "no items in your vault." 

### Screenshots or Videos

Hard to make a screenshot because it happens so fast.

### Additional Context

So there's just simply being the mistake of first using always using that splash screen saying no items in vault, while in the background there's some checking going on.

The thought probably being that an empty response is the same as zero, so we don't have to replace the splash screen during that time. 

However, it does panic users a very large amount even if for a very short time.

So you simply need to have an additional splash screen: "connecting...".

And only after you're sure of what the answer is from the server, only then should you show the statement of the results. Otherwise it is an absolute bug to show the wrong information, even if for not very long.

I must reiterate with your fancy laboratory situation you're not going to reproduce this bug. You need a highly loaded network and cell phone.

Or maybe that screen I saw is just part of the initial screen even before connection is attempted and never intended for the user to see it very long: but I saw it anyway.

Please don't expect me to do videos and screenshots of it because I'm not set up for it.

### Operating System

Android

### Device

Asus Zenfone 3

### Build Version

Latest 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2874
