### ISSUE TITLE
Wrong "save password" dialogue when using OurGroceries App

### ISSUE THREAD

**Issue by mucsushifish** [bitwarden/android#2875]
### Steps To Reproduce

When adding list items in the app "OurGroceries", Bitwarden apps opens the "Save this password?" overlay. OurGroceries is a shopping list app, the list items are not passwords or anything which should trigger a Bitwarden password-save dialogue.

### Expected Result

Adding list items should not open the Bitwarden Save Overlay.

### Actual Result

When adding list items to a shopping list, Bitwarden asks if password shoudl be saved as a new entry.

### Additional Context

The support from OurGroceries confirmed that other users have reported the same behavoir to them. They claim it is an issue of Bitwarden, not OurGroceries.
Behavior changed recently (last 2-3 months), not sure which update (Android, Bitwarden, OurGroceries) triggered it.

### Operating System

Android

### Operating System Version

Android 14, pateches Nov 2023

### Device

Pixel 5

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by lkesteloot** [comment]
Hello, I'm one of the developers of the OurGroceries app. Here's the text field that's triggering Bitwarden:

```xml
        <EditText
            android:layout_height="wrap_content"
            android:lines="1"
            android:layout_width="wrap_content"
            android:hint="@string/add_item_ItemNameHint"
            android:id="@+id/add_item_ItemName"
            android:inputType="text|textFilter"
            android:layout_weight="1"
            android:layout_marginTop="2dp"
            android:imeActionLabel="@string/add_item_KeyboardAction"
            android:imeOptions="actionNone|flagNoExtractUi"
            android:importantForAutofill="no"
            />
```

Note the last attribute. Let me know if there are any other attributes that might help disable Bitwarden's activity here.

**Comment by lkesteloot** [comment]
In our latest release we added this attribute to the `EditText` widget:

```
android:autofillHints="notApplicable"
```

and it didn't help.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2875

**Comment by lkesteloot** [comment]
This issue was migrated to the "mobile" repo, but that repo was then archived. Since this is a reproducible bug that's still affecting our users, can you re-open this one?
