### ISSUE TITLE
IOS app UI problem

### ISSUE THREAD

**Issue by fenghuan1994** [bitwarden/android#2899]
### Steps To Reproduce

Enter the app, toggle the bottom selection, click MY VAULT and other tabs to switch back and forth, every time you click my Vault, often the UI will flash once, see screen recording

### Expected Result

no ui flash

### Actual Result

have ui change

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/22291785/978f9033-c650-4516-9d4e-0a7f5bb8a7a6

### Operating System

iOS

### Operating System Version

ios17.1.2

### Device

iphone 14

### Build Version

2023.12.0(5688)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2899
