### ISSUE TITLE
It is not possible to launch Bitwarden through the Auto-Fill flow on iOS when the Bitwarden client is in a logged-out state.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2915]
### Steps To Reproduce

1. Navigate to Settings > Account Security and tap on (Log out).
2. Open Safari and navigate to (https://github.com/login).
3. Attempt to perform Auto-Fill by pressing on the (Passwords) button above the keyboard.

### Expected Result

For Bitwarden to be launched via the Auto-Fill flow and to be able to log in at that stage.

### Actual Result

The phone's interface behaves as if it's attempting to launch another application or open a new window for a second, but then returns to the browser and the webpage without launching Bitwarden.

### Screenshots or Videos

N/A

### Additional Context

N/A

### Operating System

iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [X] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2915
