### ISSUE TITLE
The Bitwarden client on iOS does not log out when the phone is turned off whilst the Vault Timeout Action is set to Log out.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2916]
### Steps To Reproduce

1. Open Bitwarden on iOS and navigate to Settings > Account Security and set the (Vault Timeout Action) to (Log out).
2. Return to the home screen.
3. Turn the phone off (long press).
4. Turn the phone on. 
5. Launch Bitwarden.

### Expected Result

The client should be logged out at this point.

### Actual Result

The client is still logged-in but is locked.

### Screenshots or Videos

N/A

### Additional Context

1. If you follow the first 2 steps and then open the task switcher and close/remove Bitwarden from the background, the client would follow its set (Vault Timeout Action) and log out.
2. On Android, the client logs out when the device is turned off.

### Operating System

iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2916
