### ISSUE TITLE
The Log out button in the Bitwarden iOS client does not function as expected on first login.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2920]
### Steps To Reproduce

1. Install Bitwarden on an iOS device.
2. Log in.
3. Navigate to Settings > Account security and tap on (Log out).
4. Tap on (Yes) in the modal that's asking (Are you sure you want to log out?)

### Expected Result

To log out.

### Actual Result

The modal is closed, but Bitwarden remains logged-in and unlocked.

### Screenshots or Videos

N/A

### Additional Context

1. If you dismiss Bitwarden from the task switcher and then launch it anew and unlock it, the (Log out) button would work.
2. Was unable to reproduce this on Android 12.
3. If you attempt to view a vault item right after step 4, you'd be shown an error message stating (We were unable to process your request. Please try again or contact us. An error has occurred) with an (OK) button.

### Operating System

iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here — Bitwarden's engineering team will be happy to review these.

**Comment by EricB2024** [comment]
Can the solution to this problem be included in the next Bitwarden app update?

**Comment by EricB2024** [comment]
Is it already known whether this problem will be solved in the upcoming update of the Bitwarden app?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2920
