### ISSUE TITLE
Bitwarden mobile clients do not retain self-hosted URIs after being dismissed from the task switcher and/or after turning the phone off.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2924]
### Steps To Reproduce

1. Point the iOS client to a self-hosted server.
2. Log in.
3. Navigate to Settings > Account security and tap on (Log out).
4. Return to the phone's home screen.
5. Open the task switcher and dismiss (pull up) Bitwarden.
6. Open Bitwarden anew.

### Expected Result

The client should retain the self-hosted URIs.

### Actual Result

The client is pointing to Bitwarden.com.

### Screenshots or Videos

N/A

### Additional Context

1. Same thing happens if you turn an Android or iOS device off and back on, after logging out; Tested with Android 12.
2. This also happens if you select Bitwarden.eu as the server.

### Operating System

Android, iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by c0ball** [comment]
I am not sure if this should be fixed with the newest 2024.1 update, but sadly it does not seem to be fixed.

**Comment by EricB2024** [comment]
Hallo,
I tested it whith the latest update (2024.1). The problem still exist. The self-hosted URL has disappeared after restarting the phone or open the task switcher and dismiss (pull up) Bitwarden.

**Comment by EricB2024** [comment]
Hello Raphael,I tested it whith the latest update (2024.1). The problem still exist. The self-hosted URL has disappeared after restarting the phone or open the task switcher and dismiss (pull up) Bitwarden.Kind regeards,EricOp 11 jan 2024 om 09:12 heeft Raphael ***@***.***> het volgende geschreven:﻿
I am not sure if this should be fixed with the newest 2024.1 update, but sadly it does not seem to be fixed.

**Comment by EricB2024** [comment]
Can the solution to this problem be included in the next Bitwarden app update?

**Comment by EricB2024** [comment]
Unfortunately, I have not received an answer to my question as to when this issue will be resolved.
Is this known by now?

**Comment by SergeantConfused** [comment]
Hi @EricB2024,

Thank you for checking up on this. Could you please let me know if you're still able to reproduce this on Bitwarden 2024.4.2 on iOS 17.4.1? I tested this by configuring a self-hosted server, entering my email address, toggling (Remember me), entering my master password and logging in, and then setting the Vault Timeout Action to Log out and dismissing Bitwarden from the Task Switcher; After opening Bitwarden anew, the self-hosted URI was set configured.


Thank you in advance,

**Comment by c0ball** [comment]
@SergeantConfused I can confirm that when configuring a self-hosted environment, logging in and setting the timeout action to logout will preserve the server configuration. The sole issue that I have observed is that upon pressing the log-out button manually, the server configuration does not persist.

**Comment by EricB2024** [comment]
I have tested it:
If I set the action for the session timeout setting to 'Log out' in the app, the self-hosted URL remains. 
If I choose 'Log out' in the app, the self-hosted URL disappears.

**Comment by EricB2024** [comment]
I have tested it:
If I set the action for the session timeout setting to 'Log out' in the app, the self-hosted URL remains. 
If I choose 'Log out' in the app, the self-hosted URL disappears.

**Comment by netboy3** [comment]
Running 2024.5.1 on Android. I can also confirm that setting session timeout to "Log out" makes the app retain the self-hosted URL. It retains it both on timeout and also on swiping the app away. If session timeout is set to "Lock" it will consistently forget the self-hosted settings and revert to "bitwarden.com" once you swipe the app away or restart the phone (basically if the app needs to "cold-start" and can't be recalled from memory).

**Comment by EricB2024** [comment]
Can this bug be fixed in the upcoming update of the app?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2924
