### ISSUE TITLE
The iOS client returns We were unable to process your request. Please try again or contact us. An error has occurred. when attempting to view a vault item on first login after boot.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2925]
### Steps To Reproduce

1. Make sure that the Bitwarden iOS client is not logged into any Bitwarden account.
2. Turn the iOS device off.
3. Turn the iOS device on.
4. Launch Bitwarden.
5. Tap on (Logging in on:) and select Bitwarden.com as the server.
6. Log into a Bitwarden account.
7. Tap on Types > Login and attempt to view a vault item.

### Expected Result

To view the vault item.

### Actual Result

An error stating (We were unable to process your request. Please try again or contact us. An error has occurred.) is shown.

### Screenshots or Videos

N/A

### Additional Context

1. Unreproducible on Android 12.
2. The (Log out) button does not function at this stage; Could be related to [this report](https://github.com/bitwarden/mobile/issues/2920).
3. If you dismiss Bitwarden from the task switcher and then launch it and unlock it, it'll operate as expected and it becomes possible to view the vault item and to log out.

### Operating System

iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here — Bitwarden's engineering team will be happy to review these.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2925
