### ISSUE TITLE
The iOS client cannot display vault item on a self-hosted server at first launch, after rebooting the phone.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2926]
### Steps To Reproduce

1. Uninstall Bitwarden.
2. Turn the phone off.
3. Turn the phone on.
4. Install Bitwarden.
5. Launch Bitwarden and point it to a self-hosted server.
6. Log in.
7. Navigate to the Types > Login menu and view a vault item.
8. Log out via the Settings > Account security menu.
9. Turn the phone off.
10. Turn the phone back on.
11. Launch Bitwarden.
12. [Point it to the same self-hosted server](https://github.com/bitwarden/mobile/issues/2924).
13. Log in.
14. Attempt to view a vault item.

### Expected Result

To be able to view the vault item.

### Actual Result

An error message stating (We were unable to process your request. Please try again or contact us. An error has occurred.) is shown.

### Screenshots or Videos

N/A

### Additional Context

1. This is unreproducible on Android 12.
2. The (Log out) or (Lock) buttons in the Settings > Account security menu do not function at this stage; Could be related to [this report](https://github.com/bitwarden/mobile/issues/2920).
3. The Send menu displays a message at the top stating (Due to an enterprise policy, you are only able to delete an existing Send) even though the account is not a member of an organization.
4. If you dismiss Bitwarden from the task switcher and then launch it and unlock it, it'll operate as expected and it becomes possible to view the vault item and to log out, and the message is removed from the Send menu.

### Operating System

iOS

### Operating System Version

17.2.1

### Device

iPhone SE (2020)

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here — Bitwarden's engineering team will be happy to review these.

**Comment by EricB2024** [comment]
Can the solution to this problem be included in the next Bitwarden app update?

**Comment by EricB2024** [comment]
Is it already known whether this problem will be solved in the upcoming update of the Bitwarden app?

**Comment by EricB2024** [comment]
Unfortunately, I have not received an answer to my question as to when this issue will be resolved.
Is this known by now?
