### ISSUE TITLE
Every time a false positive login attempt popup after unlocking app

### ISSUE THREAD

**Issue by Martijn8** [bitwarden/android#2958]
### Steps To Reproduce

1. Open the Bitwarden app on your iPhone or iPad.
2. Choose your second account on the upperleft corner of your screen.
3. Unlock the account with your master password or Face ID/Touch ID.
4. A popup will now appear indicating that there is a login attempt on the other account and asking you to switch to the other account. Now choose OK.
5. Unlock your other Bitwarden account using your master password or Face ID/Touch ID.
6. There appears to be no login request.

### Expected Result

Step 4 should not appear because there is actually no login request.
This popup that appears is a false positive.

### Actual Result

![IMG_0055](https://github.com/bitwarden/mobile/assets/143968520/24e7129c-8df0-4c50-bd25-6eef77ce992c)

### Operating System

iOS

### Operating System Version

iOS 17.3

### Device

iPhone 15 Pro

### Build Version

2024.1.0 (5828)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2958
