### ISSUE TITLE
Autofill in android does not identify url port

### ISSUE THREAD

**Issue by panoskpv** [bitwarden/android#2970]
### Steps To Reproduce

1. Open a single word local domain (e.g. server:8080) in any browser
2. Click to auto fill pop up
3. App opens and site name in app is -- instead of site url

### Expected Result

App opens and present password for server:8080

### Actual Result

App opens and site name in app is -- instead of site url and no passwords are returned

### Operating System

Android

### Operating System Version

Android 14

### Build Version

2024.1.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi, may I ask if you are encountering basic auth prompts: https://bitwarden.com/help/basic-auth-autofill/ ?

**Comment by panoskpv** [comment]
Hello, as I can understand, this article is for computer version of Bitwarden. In my case, I have the issue with android version. I do not know if android version works that way. Also, Bitwarden Firefox extension works as expected.

**Comment by panoskpv** [comment]
As an update on the above (I do not know if I should edit my initial report), the actual issue is that Bitwarden does not recognize url port. More specifically, when I visit http://server:123, -- is presented in the app as I described above, and password saved only for http://server are returned.

**Comment by jtodddd** [comment]
Hi, 

On the website that you're trying to autofill, is it doing a basic auth prompt and dropping you a prompt from the top or in the middle of the screen? Or are you just trying to fill a regular form on the website? 

Apologies, I'm still trying to understand the issue. Is it possible that you share a screenshot of the prompt you're getting?

**Comment by panoskpv** [comment]
In the below you can see that when I am at portainer (http://fileserver:9000) aand bitwarden returns result only for wallabag (http://fileserver(:80)). My match detection setting is starting with.
![Screenshot_20240207-095937_Fennec](https://github.com/bitwarden/mobile/assets/84382461/09828c8d-2121-466e-b08e-36f3c38cf722)
You can see also the screen when I tap to my vault where "Items for --" appears instead of the url.
![Screenshot_20240207-095918_Bitwarden](https://github.com/bitwarden/mobile/assets/84382461/b835c168-686c-4c48-a598-0e6007aff01f)

**Comment by Seedthis** [comment]
As far as I know, it's not a "bug" but rather a limitation of the Android autofill API.

There are details about it in this issue : https://github.com/bitwarden/mobile/issues/578

**Comment by pwd-github** [comment]
Is there not another, more modern approach that can be made to fix this issue?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2970
