### ISSUE TITLE
 Send website name to Firefox Relay for username generation

### ISSUE THREAD

**Issue by henningBunk** [bitwarden/android#2971]
### Steps To Reproduce

1. Setup Firefox Relais email proxy account and generate api key
2. Open the Bitwarden Android app and create a new entry
3. Enter a name and URI for that entry, like "Wikipedia" and https://wikipedia.com
4. Generate a new username using your Firefox Relay api key
5. Open your Firefox relay account

### Expected Result

The new e-mail proxy is listed in the Firefox Relais website with a name which makes it possible to know for which website this proxy was created. Like:

    wikpedia.com - Generated by Bitwarden

This is the behaviour when creating new usernames with Bitwarden Desktop on Windows or the Firefox Addon.

### Actual Result

The new proxy gets a generic name like

    Generated by Bitwarden.

### Screenshots or Videos

Upper entry is generate by Android app, lower one by Windows desktop client.

![grafik](https://github.com/bitwarden/mobile/assets/14870695/e1769105-6c6d-4cdb-bea3-cf00b1b77911)

### Additional Context

Made a feature request for it here: https://community.bitwarden.com/t/send-website-name-to-firefox-relay-for-username-generation-in-the-android-app/61337

but was told this is more of a bug because the behaviour of the app is not the same like on desktop or in the browser.

### Operating System

Android

### Operating System Version

2024.1.1

### Device

Samsung S20FE 5G

### Build Version

8843

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by TheKangaroo** [comment]
I see the same behavior on iOS Version 2024.2.0 (6100)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2971

**Comment by TheKangaroo** [comment]
@vvolkgang 
This issue was moved to the bitwarden/mobile repository, but it has now been archived. Should we reopen this issue in this repository, or open a new one with the same content?
