### ISSUE TITLE
iOS push notifications are silent

### ISSUE THREAD

**Issue by jradwan** [bitwarden/android#2997]
### Steps To Reproduce

Using “log in with device” I get the push notification banner on my iPhone but it doesn’t make a sound like other push notifications from other apps do.

### Expected Result

iOS notification sound would accompany the push notification banner.

### Actual Result

Banner appears, but no sound is played.

### Screenshots or Videos

![image](https://github.com/bitwarden/mobile/assets/11047158/586f0814-4586-4c9c-8053-4a96a051336d)

### Operating System

iOS

### Operating System Version

17.3.1

### Device

iPhone 15 Pro

### Build Version

2024.2.0 (6100)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Gerardv514** [comment]
You would think bitwarden employees themselves use their own product, how did they not notice this?!!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2997
