### ISSUE TITLE
new records are deselected on save

### ISSUE THREAD

**Issue by ajcallegari** [bitwarden/android#3007]
### Steps To Reproduce

1) create a new item on the mobile app
2) crease a name and username, and generate a password for the new item
3) save the item

### Expected Result

Expected result is the form will convert from an editable form to a non-editable form while keeping the new record in front of the user. This enables the user to quickly copy the new username and password into the app that has requested the creation of these items. This behavior is found in most password managers including the desktop version of Bitwarden.

### Actual Result

On saving the new item, it disappears.  So the user has to take an additional step to search for the new item which is not typically found in password managers.

### Additional Context

The typical use case for creating a new Bitwarden entry is that the user is registering for a new web app and it has asked them to create a username and password.  The user then accomplishes these two tasks in bitwarden, saves the result, and copies the results into the web app. Most password managers (including the desktop version of Bitwarden) respect this use case by leaving the newly created record in front of the user to enable them to copy fields from it.  

### Operating System

iOS

### Operating System Version

iOS 16.6

### Device

iPhone 11

### Build Version

2024.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3007
