### ISSUE TITLE
Spurious Bitwarden prompt in Duolingo (no visible fields)

### ISSUE THREAD

**Issue by 9numbernine9** [bitwarden/android#3030]
### Steps To Reproduce

1. Open Duolingo.
2. Begin a lesson.
3. Complete the lesson.
4. _Optional_ If there's an ad, watch it.
5. Return to the lesson map.
6. A _Save Password to Bitwarden?_ prompt appears for some reason.

### Expected Result

No Bitwarden _save_ prompt and I continue along my merry way.

### Actual Result

A Bitwarden _save this password?_ prompt appears despite no login fields appearing on the page.

### Screenshots or Videos

[Youtube Link](https://www.youtube.com/watch?v=EB5Bf-07Q2Y) - sorry for the Duolingo ad but _maybe_ this is relevant to the issue?

### Additional Context

- Not sure if this only occurs with Japanese lessons.
- Not sure if watching the post-lesson advertisement triggers this behaviour. 

### Operating System

Android

### Operating System Version

14

### Device

Google Pixel 7

### Build Version

2024.2.0 (9000)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by alxrcs** [comment]
This is happening to me as well, more specifically on the new(-ish) kanji section of the Japanese Duolingo course.

![Screenshot_20240227-222417](https://github.com/bitwarden/mobile/assets/8171561/f9391a8d-5c49-463f-ab96-aa20e10ab421)

The password that is offered to be saved is the last response given for an exercise of type "what sound does this make?". However, the prompt only appears after finishing the whole exercise set and returning to the main screen with the list of kanjis.

I'm using a Pixel 6A with Android 14.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by aboodsukkar** [comment]
The same thing happens using Busuu app also on Japanese course.
Specifically on the lessons that requires writing, after finishing the lesson the prompt appears.
Samsung device on A14

**Comment by Pyrestone** [comment]
I have the same issue with Korean in Duolingo sometimes. Also android 14.
Not sure what causes it, just wanted to show some support.

**Comment by DwukwiatRincewind** [comment]
I have the same issue when i learn english on Busuu app (android 14). 
On every field where I have to write an answer, Bitwarden wants to fullfil password.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3030

**Comment by shurane** [comment]
Looks like https://github.com/bitwarden/mobile/issues/3030 (and its repo) has been archived. So would this be the definitive place for this issue?

I still have this issue with Duolingo and the Bitwarden app, would be nice to have an idea of the fix.

**Comment by SaintPatrck** [comment]
Hi @shurane,

Yes, this is the correct place for Android issues, going forward.

Unfortunately we can't control _when_ the system invokes the autofill framework, so we can't prevent the prompt from showing on our side without implicitly blocking all requests from Duolingo.

As stated in [this comment](https://github.com/bitwarden/mobile/issues/3030#issuecomment-2646062802), you can try to "Block autofill" in "Settings > Autofill" to prevent Bitwarden from reacting to system autofill triggers for specific applications/sites. There is one caveat to that approach; it will also prevent autofill from displaying prompts in Duolingo when you **do** expect them. That means you would have to manually autofill Duolingo to log in.
