### ISSUE TITLE
Password Fill Login Cut Off

### ISSUE THREAD

**Issue by danmeeks** [bitwarden/android#3048]
### Steps To Reproduce

On iPhone 15 Pro and you have multiple accounts on the app:

1. Go to login page and select autofill that shows above the iOS keyboard.
2. From that menu, select the account switch option (selecting the initials at the top).

### Expected Result

The account switch menu shows up but should not be cut off on the side.

### Actual Result

The account list is cut off on the right side.

### Screenshots or Videos

![IMG_9085](https://github.com/bitwarden/mobile/assets/21047670/ac05928e-67e8-476b-be57-cfc7663e9d3e)

### Operating System

iOS

### Device

iPhone 15 Pro

### Build Version

Version: 2024.2.0 (6100)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello everyone,

After further testing, we were able to reproduce this behaviour and have flagged it to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you all again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3048
