### ISSUE TITLE
com.x8bit.bitwarden-fdroid.apk Version 2024.2.1 signature issues

### ISSUE THREAD

**Issue by qwerttvv** [bitwarden/android#3062]
### Steps To Reproduce

Did you change the signature compared to the previous version?

[com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/mobile/releases/download/v2024.2.1/com.x8bit.bitwarden-fdroid.apk)

### Expected Result

na

### Actual Result

na

### Operating System

Android

### Build Version

2024.2.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by nightznero** [comment]
Now signature is from "Android Debug"

**Comment by racingcirc** [comment]
This really discourages me from ever trusting anything coming from Bitwarden's own repo

![Screenshot_20240307-191028](https://github.com/bitwarden/mobile/assets/145857730/69ce2fb5-137e-4b4b-82e4-1f9397494915)

**Comment by Sunsper** [comment]
> [e344184](https://github.com/bitwarden/mobile/commit/e3441845cd01ab31b628a319ec3d0a8de63b009b)
> 
> I see☺️ THX @vgrassia

I suppose this issue could be closed once the build with fixed signature rolls out to F-Droid repo.

> This really discourages me from ever trusting anything coming from Bitwarden's own repo

@racingcirc You're being way too dramatic on this.

**Comment by Sunsper** [comment]
Ah, just installed the fixed build with no signature issues present.
@qwerttvv, close the issue please. Thank you.
