### ISSUE TITLE
Loggin out behaviour is inconsistent

### ISSUE THREAD

**Issue by bakai-taalaibek** [bitwarden/android#3068]
### Steps To Reproduce

1. Install the app on Android
2. Open the app
3. Write email (leaving the "Remember me" checkbox unchecked)
4. Write master password
5. Enter the app
6. Open settings
7. Open Account security
8. Set "Session timeout action" to "Log out"
9. Close the app
10. Wait 15 minutes for it to log out
11. Open the app

### Expected Result

I expect the email field to be empty and the "Remember me" checkbox to be unchecked. 

### Actual Result

I see that when I open the app my email is already filled in and the "Remember me" checkbox is checked

### Screenshots or Videos

No

### Additional Context

The log out behavior is different it this scenario:

1. Install the app on Android
2. Open the app
3. Write email (leaving the "Remember me" checkbox unchecked)
4. Write master password
5. Enter the app
6. Open settings
7. Open Account security
8. Click Log out
9. Confirm logging out
10. I see that the email address is empty and "Remember me" checkbox is unchecked

### Operating System

Android

### Operating System Version

Android 13

### Device

Lenovo Legion Y700

### Build Version

2024.2.0 (9000)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @bakai-taalaibek,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3068
