### ISSUE TITLE
The password generator incorrectly evaluates the minimum required number of special characters.

### ISSUE THREAD

**Issue by mpancode** [bitwarden/android#3076]
### Steps To Reproduce

- The password generator in the Android app incorrectly evaluates the minimum required number of special characters.
- When the generator exits, the next time the generator is opened, the minimum number of special characters is preset to the same value as the minimum number of numeric characters.

### Expected Result

The generated passwords should not contain less than the required number of special characters.

### Actual Result

There are cases in the generated passwords with less than the required number of special characters.

### Screenshots or Videos

![image](https://github.com/bitwarden/mobile/assets/72337457/7e6e01d9-e45e-4792-85ca-17971fdba42a)

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy A54

### Build Version

2024.2.0 (9000)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3076
