### ISSUE TITLE
iOS file browse broken

### ISSUE THREAD

**Issue by Pyrepenol** [bitwarden/android#308]
I just upgraded to premium so I could store my keys along with the notes, but it does not seem to work on iOS. Interestingly, photos work fine-- but any file picked via "Browse..." will fail to show up as selected. The UI is also freaking out, but I'm not sure if that's related.

https://imgur.com/gallery/muJGa4b

**Comment by Pyrepenol** [comment]
I just upgraded to premium so I could store my keys along with the notes, but it does not seem to work on iOS. Interestingly, photos work fine-- but any file picked via "Browse..." will fail to show up as selected. The UI is also freaking out, but I'm not sure if that's related.

https://imgur.com/gallery/muJGa4b

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/308
