### ISSUE TITLE
Inconsistent UI (vs web client)

### ISSUE THREAD

**Issue by dfunkt** [bitwarden/android#3087]
### Steps To Reproduce

1. Create a card entry with a number
2. View said number

### Expected Result

Card number should have spaces included.

### Actual Result

Card number doesn't have spaces included.

### Screenshots or Videos

Web client
![image](https://github.com/bitwarden/mobile/assets/17910432/49f78f2f-4641-42a3-8755-7c05cc2c9b01)
![image](https://github.com/bitwarden/mobile/assets/17910432/531c4aaa-5ad4-4cb3-987f-ef9da690bc12)
 vs
Mobile
![Screenshot_2024-03-16-10-45-50-942_com x8bit bitwarden-edit](https://github.com/bitwarden/mobile/assets/17910432/f0824853-53bb-4f42-b443-c14c439147ec)
![Screenshot_2024-03-16-10-46-20-067_com x8bit bitwarden-edit](https://github.com/bitwarden/mobile/assets/17910432/e9d55792-3f7e-4977-a3b3-5d3904cb28e9)

### Additional Context

On the web client the credit card number has spaces included with leads to better readability, the fact that the mobile app doesn't have them not only affect readability but it also add incosistency to the overall UX.

### Operating System

Android

### Operating System Version

13

### Device

Poco F3

### Build Version

2023.3.0 (9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dfunkt** [comment]
Looks like this will be fixed with https://github.com/bitwarden/mobile/pull/3084

**Comment by SergeantConfused** [comment]
Hi @dfunkt,

Thank you for your report. Generally speaking, we'd most likely consider this to be closer to a [feature request](https://community.bitwarden.com/c/feature-requests/5); However, I will keep this GitHub report open for now as there already is a PR for it.

Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3087
