### ISSUE TITLE
Full text does not display when I try to create a new account

### ISSUE THREAD

**Issue by tonytechhelp** [bitwarden/android#3088]
### Steps To Reproduce

1. Go to 'create a new account'
2. Click on 'create a new account'
3. Scroll down to 'Check known data breaches for this password By checking this box you agree to the following:'
4. Click on 'Create account '

### Expected Result

See all the text and know exactly what we are ticking and agreeing to create a new account.

### Actual Result

I receive an error that I did not agree to the privacy policy terms of use.

### Screenshots or Videos

![Bitwarden](https://github.com/bitwarden/mobile/assets/142281614/3d17b88d-7ac2-4ac4-a059-5f6bfeef199d)

### Additional Context

When I try to create a new account from the mobile app, I have to tick the box for I agree to the Terms of Service, Privacy Policy, but you don't see the full text, and you don't know what you are ticking. If I don't tick the last box, it won't let me create my account.

Please fix this problem so we can see all the text and know exactly what we are ticking and agreeing to.

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy A23 5G

### Build Version

2024.3.0 (9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @tonytechhelp,

Thank you for this report. I tested this on Android 12 and set the Accessibility > Screen Zoom function to the max, and that caused the Terms of Service and Privacy Policy toggle to be positioned lower on the screen; However, I was able to tap on the screen and scroll down to see its links. Could you please try to scroll down and let me know if you then see the links?


Thank you in advance,

**Comment by tonytechhelp** [comment]
I tried to do this, but I still can't see the whole description text.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3088
