### ISSUE TITLE
Not matching with the theme

### ISSUE THREAD

**Issue by BabyOilJohnson** [bitwarden/android#3090]
### Steps To Reproduce

1. Open Bitwarden
2. Change to any theme aside light
3. Click any more option button
4. See

### Expected Result

It should sync with the selected theme.

### Actual Result

Happening the opposite thing.

### Screenshots or Videos

| ![Screenshot_20240317-205636](https://github.com/bitwarden/mobile/assets/101601874/962dc38b-5e61-450e-94e0-ed538c3d8076) | ![Screenshot_20240317-205505](https://github.com/bitwarden/mobile/assets/101601874/62425688-14b5-4c43-8d4a-f227f8c4da74) | ![Screenshot_20240317-205519](https://github.com/bitwarden/mobile/assets/101601874/95c01203-5473-4dd3-ad83-b5bb2fe60581) | ![Screenshot_20240317-205548](https://github.com/bitwarden/mobile/assets/101601874/6b84c674-a358-40fd-abb2-3f941d2c35f4)  | ![Screenshot_20240317-210323](https://github.com/bitwarden/mobile/assets/101601874/0752cedd-ae63-4c50-bb74-1722404e66ba)  |
|--------|--------|--------|--------|------|

### Operating System

Android

### Operating System Version

11

### Device

Samsung A30

### Build Version

2024.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @BabyOilJohnson,

Just to make sure that you and I are on the same page, is your report about the fact that the menus shown, such as the one with Sync, Lock, Exit, are white instead of following the selected theme?


Thank you in advance,

**Comment by BabyOilJohnson** [comment]
> Just to make sure that you and I are on the same page, is your report about the fact that the menus shown, such as the one with Sync, Lock, Exit, are white instead of following the selected theme?

Yes, correct.

**Comment by AlSukkar** [comment]
The issue I'm having looks related to this one.
When changing to or from dark mode the app does not change along with the device, but turning on dark mode while the app is open it follows the device.
Disabling battery optimization does not have an effect.
Version 2024.3.0
Samsung Tab A13, Samsung phone A14
![Screenshot_20240323_072320](https://github.com/bitwarden/mobile/assets/68753528/b661fc1d-42c7-440d-8df9-f87569ce0701)


As you can see in the image the app and the system are not on the same mode.

**Comment by sokai** [comment]
A app restart did the theme change, for me.

1. (Bitwarden) Settings > Appearance > Theme Default: `Default (System)`
2. Restart app
    * (Android) Settings > Apps > Bitwarden
    * [Force stop]
    * Storage and cache
        * [Clear cache]
        * [←] (= go back)
    * [Open] (app again)

After that, changing the `Default dark theme` (in Bitwarden settings) switches immediately…
(For me, it‘s a bit *inconsistent*, if u would ask…)

BR

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3090
