### ISSUE TITLE
'Nord' theme is displayed as 'Nor' when selected

### ISSUE THREAD

**Issue by ghost** [bitwarden/android#3094]
### Steps To Reproduce

1. Go to Settings > Appearance 
2. Select 'Theme'
3. Select 'Nord' theme option

### Expected Result

That Nord would be displayed as Nord when set as the current theme, however it's displayed as 'Nor'. It's missing the 'd'.

### Actual Result

Nord theme is displaying as 'Nor' when selected as the current theme.

### Screenshots or Videos

![Screenshot_20240318-201922](https://github.com/bitwarden/mobile/assets/99270922/9da97a62-ac54-4709-b03a-4b29baf8fa05)
![Screenshot_20240318-201929](https://github.com/bitwarden/mobile/assets/99270922/79452c10-4726-4c65-9b06-48a754b9fd42)

### Operating System

Android

### Operating System Version

14

### Device

Pixel 4a (5G)

### Build Version

2024.3.0 (9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
