### ISSUE TITLE
Bitwarden App doesn't recognize Android version of Waterfox as a browser when matching Auto-Fill

### ISSUE THREAD

**Issue by sushix2000** [bitwarden/android#3109]
### Steps To Reproduce

    Install Waterfox browser for Android (https://play.google.com/store/apps/details?id=net.waterfox.android.release
    Attempt to perform Auto-Fill.

### Expected Result

For the webpage URL to be relayed to Bitwarden.

### Actual Result

The package name is relayed to Bitwarden, so instead of sending the URL of the web page being displayed in Waterfox, Bitwarden thinks it needs to find the info for "net.waterfox.android.release."  And so it returns the message "There are no items in your vault for net.waterfox.android.release".

### Additional Context

It looks like there are numerous other browsers having this issue with Bitwarden thinking it's looking for the login info of the browser and not the url within the browser just from looking at the Open reports still unresolved.   Is this Feature Request related? https://github.com/bitwarden/mobile/pull/2886

### Operating System

Android

### Operating System Version

14

### Device

Pixel 8

### Build Version

2024.3.0(9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @sushix2000,

Thank you for your report. I was able to reproduce this, and have flagged it and that [PR](https://github.com/bitwarden/mobile/pull/2886) internally to the Bitwarden Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.


Thank you again,

**Comment by Avrution** [comment]
Any update on the progress of this?  It has been over two months and the issue still exists.

**Comment by CiRiX-** [comment]
Yes. Waiting for this feature..

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3109

**Comment by Avrution** [comment]
Sorry to add a comment, but is there an ETA for when this will go live?  As of the update 10746 things still haven't changed.

**Comment by dathtd119** [comment]
Hi, I still got this error on the latest version on Play Store, since this closed on Jun 21.

**Comment by Avrution** [comment]
Yeah, still isn't working and really starting to impact my job duties.
