### ISSUE TITLE
iOS 12.5.7 iPhone 6 app closing by itself

### ISSUE THREAD

**Issue by nelson80s** [bitwarden/android#3119]
### Steps To Reproduce

1. Go to Bitwarden iOS 12.5.7 app
2. Click on Search button

### Expected Result

Normally a field would appear to search for login by name in the vault

### Actual Result

The application closes by itself, immediately after tapping search (magnifying glass) in the top right corner

### Additional Context

After many years of using the app on my old iPhone 6, currently stuck on iOS 12.5.7, this was the first time a bug happened in Bitwarden. I uninstalled and reinstalled, the bug continues.
I would like to take this opportunity to thank you for maintaining support on this old Apple phone and operating system

### Operating System

iOS

### Operating System Version

12.5.7

### Device

iPhone 6

### Build Version

2024.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi @nelson80s ,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by jonknud** [comment]
I have the same issue with the same iphone 6 and ios 12.5.7.

https://github.com/bitwarden/mobile/issues/3111

There are also other issues with  iphone 6 and ios 12.5.7.:
- I have problems with autofill: https://github.com/bitwarden/mobile/issues/3115
- And the back button in the settings in the app does not work. If I am in a submenu in the settings I cant go back.

The main issue is the broken search for me. I could make a video but it is very simple.
1. Open App
2. Click on Search
3. App closes

**Comment by jonknud** [comment]
Before the last update the app worked perfect. :-)

**Comment by jonknud** [comment]
Hello,
I just tested a iPhone 5s with iOS 12.5.7 and had the same behavior.
This iPhone was on bitwarden version 2024.2.0 and the search and the settings worked well.
Than I updated it to 2024.2.1 and the app broke like descibed before.

I could send this phone to a developer in germany if you hardware for fixing this bug.

**Comment by jonknud** [comment]
I got an update to Version `2024.3.3 (7191)` . It is still broken for me.

**Comment by nelson80s** [comment]
> I got an update to Version `2024.3.3 (7191)` . It is still broken for me.

The same here.

**Comment by jonknud** [comment]
Hello,
yesterday I spend some time to look at the code. the code is very clean :-)

I would gues that this bug is caused by commit https://github.com/bitwarden/mobile/commit/39a34bd8c48ae9d55d7400a867c89a4350b4c607

I googled and there are several similar issues in other software: 

> .NET MAUI App crashes on iOS 12 device with .NET 8

for example https://github.com/dotnet/maui/issues/16097

I am not an ios or .net developer. I couldn't find the exact bug.

**Comment by jonknud** [comment]
I just looked at the documentation to run the code myself but unfortunaly :-(
> Unfortunately, iOS development requires provisioning profiles and other capabilities only available to internal team members. We do not have any documentation for community developers at this time.

https://contributing.bitwarden.com/getting-started/mobile/

Is the some documentation anywhere?

**Comment by jonknud** [comment]
I installed the update to version 2024.4.0 (7272) and it is still broken :-(

**Comment by jonknud** [comment]
I updated to 2024.4.2 (7528) and it is still broken. Please fix it! 

(Or make the old app version before [39a34bd ](https://github.com/bitwarden/mobile/commit/39a34bd8c48ae9d55d7400a867c89a4350b4c607) for ios 12 availible.)

**Comment by Whaouu** [comment]
I updated to 2024.5.1 and it is still broken. Please fix it!

**Comment by Whaouu** [comment]
UP --- I updated to 2024.5.1 and it is still broken. Please fix it!

**Comment by Whaouu** [comment]
I updated to 2024.6.0 and it is still broken. Please fix it!

**Comment by nelson80s** [comment]
> I updated to 2024.6.0 and it is still broken. Please fix it!

The same continues here. I think they no longer have the iPhone 6 to be able to fix the app. After several updates, the search problem remains.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3119
