### ISSUE TITLE
Selecting a list of text in a note in a password entry hangs Bitwarden on iPhone

### ISSUE THREAD

**Issue by dfjkl** [bitwarden/android#3141]
### Steps To Reproduce

1. Go to a password entry with a note that has at least 18 lines, one of which is a space (content is password like, mixed cases and characters).
2. Click on edit
3. Scroll down to Note
4. Attempt to select whole note and Bitwarden consistently hangs.  Have to swipe away app to try again with the same result.

### Expected Result

Select all text in Note in password entry wothout app hanging.

### Actual Result

App is hanging when selecting note
of at least 18 lines where the 4th line is an empty line.

### Operating System

iOS

### Operating System Version

17.4.1

### Device

iPhone 13 Pro

### Build Version

Version: 2024.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dfjkl** [comment]
It is also hanging using a secure note attempting to select all the text too.

**Comment by Adedamola-Aina** [comment]
Hello @dfjkl 

I attempted to reproduce this issue but was unable to do so, i tried with the iPhone 15 Pro and 15 Pro Max. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, 

Please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

**Comment by dfjkl** [comment]
I will have to follow-up somehow as even after a reboot I can reliably hang Bitwarden just selecting a large blob of text.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3141
