### ISSUE TITLE
The hover behaviour of a Samsung S Pen changes once the Auto-Fill Services are activated on Android.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#3145]
### Steps To Reproduce

1. Launch Samsung Internet and navigate to [Wikipedia](https://en.wikipedia.org/wiki/Main_Page) and hover using the S Pen over a link to see how a line appears under it.
2. Install Bitwarden.
3. Activate only ([Auto-Fill Services](https://bitwarden.com/help/auto-fill-android/#autofill-service)) in the (Auto-fill) menu.
4. Launch Samsung Internet and navigate to [Wikipedia](https://en.wikipedia.org/wiki/Main_Page) and hover the S Pen over a link.

### Expected Result

To see a line under the link when you hover over it using the Samsung S Pen.

### Actual Result

No line appears under the link after the Auto-Fill Services are activated; Hovering seems to not interact with webpages at all.

### Screenshots or Videos

N/A

### Additional Context

This seems to affect Samsung Internet and possibly other browsers, but not Firefox.

### Operating System

Android

### Operating System Version

12

### Device

Samsung Note10+

### Build Version

2024.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3145
