### ISSUE TITLE
Generating selfhosted addy.io username not possible in android app (works in browser extention)

### ISSUE THREAD

**Issue by alphasierracharly** [bitwarden/android#3152]
### Steps To Reproduce

1. Open Bitwarden Android App
2. Click on Generator
3. Choose to generate username
4. Choose addy.io as Service
5. Server URL field missing

The Server URL field is available in the browser extension, but missing in the android app, not allowing to generate new users

### Expected Result

Server URL field showing

### Actual Result

Server URL field missing

### Screenshots or Videos

![BW_Android](https://github.com/bitwarden/mobile/assets/89250306/40d37efd-888a-4a0a-9b68-986b6008542f)
BW Android app with missing server URL entry field

![BW_Browser_Ext](https://github.com/bitwarden/mobile/assets/89250306/7eb906e9-2959-4076-abc8-874972650d11)
BW Browser extention with existing Server URL field.

### Operating System

Android

### Operating System Version

Android 14

### Device

Samsung Galaxy S22

### Build Version

2024.3.3

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3152
