### ISSUE TITLE
2FA / OTP code does not update when app is in background

### ISSUE THREAD

**Issue by sh4dowb** [bitwarden/android#3157]
### Steps To Reproduce

1. Open Bitwarden, choose a login
2. Go back to another app, such as web browser
3. Wait about 30 seconds, so that OTP expires
4. Go back to Bitwarden in the background

### Expected Result

New OTP code should be displayed

### Actual Result

Previous OTP code (when app was last put to background) is displayed

### Additional Context

After switching back to Bitwarden, if you wait until OTP expires (again), the refreshed OTP code is correct.
A possible fix could be, force refreshing the OTP when app is "waken up(?)", since it's a lightweight operation

### Operating System

iOS

### Operating System Version

17.4.1

### Device

iPhone 14

### Build Version

2024.3.3 (7191)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by NovaSilentium** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by sh4dowb** [comment]
In the source, I see that `OnDisappearing()` event calls `_vm.StopCiphersTotpTick()`
And `LoadAsync()` in `CipherDetailsPageViewModel.cs` calls `TimerTask(..,StartCiphersTotpTick,..).RunPeriodic();`
Not very experienced in Xamarin, but I think somewhere around `LoadAsync()` should be looked at, hope this helps!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3157
