### ISSUE TITLE
Autofill not working with immediate locking

### ISSUE THREAD

**Issue by IiroP** [bitwarden/android#318]
When I have set app to lock immediately, Autofill doesn't work (at least not always).

Steps to reproduce:
- Set locking to *Immediately*
- Try to autofill some app or website (I tested with Chrome)
- After you've clicked matching account, you get back to app but login hasn't been filled

It works normally if locking time is i.e. *1 minute*

Device: OnePlus 5T
Android version: 8.1 (OxygenOS 5.1.1)

**Comment by Berjou** [comment]
I see the same problem testing the android app with firefox. (Android 10, Nokia 7+, firefox beta)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/318
