### ISSUE TITLE
F-Droid Repo Icon should be Bitwarden's not F-Droid's

### ISSUE THREAD

**Issue by thgoebel** [bitwarden/android#3181]
### Steps To Reproduce

1. Install F-Droid
2. Add the Bitwarden repo: https://mobileapp.bitwarden.com/fdroid/
3. Go to the "Repositories" screen in F-Droid

### Expected Result

The Bitwarden repo should use the Bitwarden icon.

### Actual Result

The Bitwarden repo uses the F-Droid icon (which is also outdated btw).

### Screenshots or Videos

<img src=https://github.com/bitwarden/mobile/assets/33295590/dcf5d253-45ae-4f8e-997b-1cd89324b8fc width=50%>

### Additional Context

See the docs for how to configure the icon: https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

### Operating System

Android

### Build Version

n/a

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3181
