### ISSUE TITLE
Simple Login forward aliases should not be random

### ISSUE THREAD

**Issue by Teskann** [bitwarden/android#3189]
### Steps To Reproduce

1. Create a new entry in Bitwarden
2. Go into username generator
3. Select forwarded email alias
4. Chose SimpleLogin provider (add your API key)
5. Generate the alias

### Expected Result

I expect the alias to contain the domain name of the website for which I created the alias (this is how behaves the web browser extension).

For instance, let's assume I follow the steps above from the web extension and create an entry from Amazon website. Here is the kind of result I can get:
![image](https://github.com/bitwarden/mobile/assets/47865674/1284ba1e-ea77-4c10-95c7-297341136649)
You can see "amazon" in the email adress.

I would expect the same behavior on mobile app.

### Actual Result

If I do this from the Android app, I get a complete random alias, like `spider_shocking.abcde@simplelogin.com`. This makes it harder to track which adress is linked with which website.

### Additional Context

It seems in [src/Core/Services/EmailForwarders/SimpleLoginForwarder.cs](https://github.com/bitwarden/mobile/blob/06488539b0e1d9b1700b18c91ea083aab348f1e2/src/Core/Services/EmailForwarders/SimpleLoginForwarder.cs#L11), you use the Simple Login API to generate a random alias.

You could instead use this POST method and pass the domain name to the `alias_prefix` parameter: https://github.com/simple-login/app/blob/master/docs/api.md#post-apiv3aliascustomnew

Thanks in advance,
Cheers,

### Operating System

Android

### Build Version

2024.4.0 (10172)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by cbbit** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3189

**Comment by Blubberland** [comment]
I'm having this issue again.
Version: 2024.7.1 (11086)
Would also like to understand, why the version I got from the play store is still flagged Pre-Release here on Github and the latest is [2024.6.0](https://github.com/bitwarden/android/releases/tag/v2024.6.0)
