### ISSUE TITLE
Android app crash when not using https/SSL over tailscale

### ISSUE THREAD

**Issue by Head** [bitwarden/android#3195]
### Steps To Reproduce

I have an own vault behind tailscale without https. (Tailscale is end-to-end encrypted)
Once I try to login the android app crashes. Enabling https in tailscale solved this issue. (https://tailscale.dev/blog/vaultwarden-tailnet)
Everything is working without https on other machines though.

### Expected Result

Work or show error message

### Actual Result

App crashes with no error

### Operating System

Android

### Operating System Version

Android 13

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

Can you confirm which version of self-hosted Bitwarden are you running? Is it Vaultwarden?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3195
