### ISSUE TITLE
Constant crashes using Android application.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bitwarden/android#3207]
### Steps To Reproduce

1.	#### **Install the OS**

	#### **Fairphone FP4**

	*	https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP4/A13/FP4-TP2D-factory.zip or
	*	https://calyxos.org/install/devices/FP4/linux/#run-device-flasher

	#### **Google Pixel 3**
	
	*	https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP5/A13/FP5-TT4C-factory.zip or
	*	https://calyxos.org/install/devices/blueline/linux/#run-device-flasher

1.	#### **Install the Bitwarden AOSP package**

	*	https://www.apkmirror.com/apk/bitwarden-inc/bitwarden-password-manager/bitwarden-password-manager-2024-4-1-release/bitwarden-password-manager-2024-4-1-android-apk-download/ from https://play.google.com/store/apps/details?id=com.x8bit.bitwarden&hl=en&gl=US
	*	https://github.com/bitwarden/mobile/releases/download/v2024.4.0/com.x8bit.bitwarden-fdroid.apk from https://mobileapp.bitwarden.com/fdroid/repo/com.x8bit.bitwarden-fdroid.apk

	https://github.com/bitwarden/mobile/releases/download/v2024.4.0/Bitwarden.iOS.zip is unaffected, alongside the alternative clients:

	*	https://github.com/bitwarden/clients/releases/tag/web-v2024.4.1
	*	https://github.com/bitwarden/clients/releases/tag/desktop-v2024.4.1

	

1.	Login with the account identified by the fingerprint phrase `overuse-definite-poach-almanac-dorsal`.

### Expected Result

I expect to be able to utilize Bitwarden with the same speed I would any other account.

### Actual Result

I am informed every 5 seconds that Bitwarden has crashed.

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/42837531/41110354-d867-4b76-ad85-57826b5f0ea2

<details>

> ![image](https://github.com/bitwarden/mobile/assets/42837531/46349ed8-5dcb-47dd-a738-b24e72b996be) 

</details>

### Additional Context

I have +2056 vault entries, which appears to be the sole differentiator between my account (which is affected) and others' accounts, which aren't affected, even on the same device and installation. I've limited my https://vault.bitwarden.com/#/settings/security/security-keys to 5000 (the minimum available) yet this didn't modify the behaviour whatsoever. https://github.com/AChep/keyguard-app/releases/download/r20240417/androidApp-none-release.apk does not display this behaviour, although it struggles to synchronize my vault.

I've included a https://developer.android.com/studio/debug/bug-report#bugreport at [`bugreport-FP5-TKQ1.230127.002-2024-04-29-15-11-35.zip`](https://github.com/bitwarden/mobile/files/15150631/bugreport-FP5-TKQ1.230127.002-2024-04-29-15-11-35.zip), because https://source.android.com/docs/core/tests/debug/read-bug-reports#event-log indicates that it might be useful.

### Operating System

Android

### Operating System Version

`androidapp://com.android.settings` reports:

> ```txt
> FP5.TT4C.A.154.20240320
> ```

### Device

Fairphone FP5

### Build Version

https://github.com/bitwarden/mobile/releases/download/v2024.4.0/com.x8bit.bitwarden-fdroid.apk

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Freebase394** [comment]
@RokeJulianLockhart  Hi guys. It's true.
Hi everyone, unfortunately it's true, I've been a Bitwarden user for over 3 years or more(I came from LastPass) and I confess that since I purchased this smartphone about 2 months ago, Fossibot 101P (only P Version, not "PRO") Version 2023 new with the Android 13 operating system, on this Android it freezes a lot and most of the time when I log in, I have to enter the credentials 3 / 4 or even 5 times, other times be sure to close all the apps on the background, but background apps its not the problem, im ALWAYS with free memoRY RAM, all this to be able to log in to my account with around 600 / 700 credential entries... let's say there aren't that many... I have other devices that are even weaker, another Samsung J7 DUOS 2017 even with Android 9, 4 GB of RAM and it works much better than this Fossibot that I have at the moment. 
please tell me how I can help, from debugging the APP, sending reports, among other things, to maintaining and contributing to this small and at the same time BIG problem, I don't know if this problem always existed, or just started to exist from some specific version until now, until now.  But I believe that everything has a solution.  Please count on me

**Comment by beedell-roke** [comment]
> https://github.com/bitwarden/mobile/issues/3207#issuecomment-2094983964

@Freebase394, ~~until they respond, another [`adb bugreport`](https://developer.android.com/studio/debug/bug-report#bugreportdevice) and a display recording from you would be useful for mere comparison, at least.~~ Many thanks for the corroboration and point of reference regarding OS versions. This may well have commenced approximately when my FP4 upgraded its OS (although my credential entries were exponentially increasing at that time too).

**Comment by beedell-roke** [comment]
> https://github.com/bitwarden/mobile/issues/3207#issuecomment-2094983964

@Freebase394, you appear to have correctly estimated the cause (albeit, expectedly, not to sufficient standard to know what *ultimately* causes this) – the specifications of the device.

To demonstrate, I have installed [`kojipkgs.fedoraproject.org`'s `waydroid-1.4.2-3.fc40.noarch`](https://kojipkgs.fedoraproject.org//packages/waydroid/1.4.2/3.fc40/noarch/waydroid-1.4.2-3.fc40.noarch.rpm) [^1] and [`v2024.4.2/com.x8bit.bitwarden.apk`](https://github.com/bitwarden/mobile/releases/download/v2024.4.2/com.x8bit.bitwarden.apk) on my powerful desktop system, and the issue does not occur! However, that same configuration (albeit using [`build.alpinelinux.org`'s `waydroid-1.4.2-r5`](https://build.alpinelinux.org/buildlogs/build-edge-aarch64/community/waydroid/waydroid-1.4.2-r5.log)) on my FP4 running postmarketOS exhibits the behaviour, as does my CalyxOS Google Pixel 3, and stock FP5.

[^1]: [`koji.fedoraproject.org/koji/rpminfo?rpmID=38042996`][1]

      [1]: https://koji.fedoraproject.org/koji/rpminfo?rpmID=38042996

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3207

**Comment by beedell-roke** [comment]
> https://github.com/bitwarden/android/issues/3207#issuecomment-2181382118

@vvolkgang, would have been better to use the GitHub-native migration feature, since I can't edit that issue description and my comments to improve them retroactively.

Thanks, though.

**Comment by beedell-roke** [comment]
This remains, per https://github.com/bitwarden/android/issues/5412#issue-3169569962.
