### ISSUE TITLE
[beta][android] unlocking with pin or masterpass not possible after first login

### ISSUE THREAD

**Issue by DunklerPhoenix** [bitwarden/android#3214]
### Steps To Reproduce

1. Selfhost a Bitwarden server
2. Login into beta android app
3. (Optional) Enable pin unlock
4. Wait until the app locks itself or lock it manually
5. Try to unlock. It always fail. It doesn't matter if pin or password 

### Expected Result

Unlocking should work

### Actual Result

I need to logout and login again to acces my vault. 

### Screenshots or Videos

![Screenshot_20240503-160615_Bitwarden](https://github.com/bitwarden/mobile/assets/1261305/e9d994df-7d2b-4393-bf6a-1f1703930bd2)

### Additional Context

I think that the app tries to connect to the official Bitwarden server and not to the selfhosted for unlocking.

### Operating System

Android

### Operating System Version

14

### Device

Pixel 4 XL

### Build Version

2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by chungf** [comment]
Can confirm the same is happening for an account hosted on bitwarden.com. Android app version 2024.4.1.

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by DunklerPhoenix** [comment]
Is there a possibility to enable a debug log? LogCat dont show any errors or useful informations.

It also doesnt come from this single Installation. After a complete deletion of bitwarden and reinstallatiob the problem persists.

I dont have any biological method to unlock (no camera unlocl, no fingerprint, etc). Maybe it happens because of that. 

@chungf do you have a fingerprint sensor or something like that?

**Comment by chungf** [comment]
I don’t have biometric unlock enabled either. The issue I observe is essentially identical to @DunklerPhoenix: Login by master password works normally; unlock by master password always fails; unlock by PIN always fails. Except I’m using bitwarden.com as host.

**Comment by pamperer562580892423** [comment]
I encountered the same problem as @DunklerPhoenix describes (unlock with PIN was not usable anymore). Ist happened immediately after the Beta was installed and was the reason for me to deinstall the Beta. (passkey function wouldn't be available for me anyway, as my Fairphone 5 is still on Android 13)

If it is of concern: my account is on .eu

**Comment by strangefello** [comment]
Can confirm that this issue occurs on the following device:
* Google Pixel 7
* Android version 14
* Android security update: May 5, 2024
* Google Play system update: January 1, 2024
* Build AP1A.240505.005
* Bitwarden app version 2024.4.1 (10283) (beta stream from Google Play)
* Vault host: bitwarden.com

With the following behavior:
* Attempts to unlock app with the master password receive pop ups stating "We were unable to process your request.  Please try again or contact us."
* Attempts to unlock app with known good PINs receive pop ups with stating "Invalid PIN. Try again."
* Attempts to unlock app with bio-metrics (fingerprint) unlock the app as expected.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3214
