### ISSUE TITLE
Connect to Watch option shows on iPad

### ISSUE THREAD

**Issue by infinitepower18** [bitwarden/android#3220]
### Steps To Reproduce

1. Install Bitwarden on iPad
2. Go to settings followed by other
3. You will find the connect to watch option

### Expected Result

Connect to watch option shouldn't be visible on iPad as Apple Watches cannot pair with iPads.

### Actual Result

Connect to watch option shows on iPad which cannot pair with an Apple Watch.

### Screenshots or Videos

![IMG_0047](https://github.com/bitwarden/mobile/assets/44692189/bdb651dc-a0e0-4d2c-8100-cfebed150fb5)

### Operating System

iOS

### Operating System Version

iPadOS 17.4.1

### Device

iPad Air 5th generation

### Build Version

2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @infinitepower18,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - the Engineering team will be happy to review them.

Thank you again,

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3220
