### ISSUE TITLE
Android beta - passkey autofill not working when session timeout set to 'immediately'

### ISSUE THREAD

**Issue by MrSourceUnknown** [bitwarden/android#3228]
### Steps To Reproduce

Not working:
- Go to Settings → account security → session timeout and set it to 'Immediately'
- try to use a passkey anywhere to logon
- after unlocking the vault and selecting the correct passkey it throws an error saying 'something went wong'

Working:
- Go to Settings → account security → session timeout and choose any option _except_ 'immediately' 
- try to use a passkey anywhere to logon
- after unlocking the vault and selecting the correct passkey it is accepted

### Expected Result

I would expect the passkey autofill logic to work even when session timeout is set to 'immediately' as that is how it works for password autofill as well.

### Actual Result

Instead when using autofill the session timeout seems to trigger partway through the selection process.

### Additional Context

Browser used: Chrome version 124.0.6367.113, with 3rd party passkey flag enabled.
Site tested: google account logon using passkey option

### Operating System

Android

### Operating System Version

14

### Device

Pixel 6 Pro

### Build Version

2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by micahblut** [comment]
@MrSourceUnknown thank you for taking the time to test the beta and report this issue. We've replicated the issue and will work on a fix.

**Comment by MrSourceUnknown** [comment]
Thanks!

It's not a massive bother, but good that it was reproducible and will be looked into.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3228
