### ISSUE TITLE
[self-host] iOS app only loads 150x150 icons

### ISSUE THREAD

**Issue by ChrisSlashNull** [bitwarden/android#3229]
### Steps To Reproduce

1. Add an entry to your bitwarden vault with a website which has no 150x150 favicon (32x32 or anything else - for example crowdsec.net, ring.com, nzxt.com, mcdonaldsapps.com, dsquared2.com ...)
2. Bitwarden website and bitwarden desktop apps will display the icon
3. Bitwarden iOS mobile app will display nothing or the grey globe

I have to say, that my bitwarden instance is self-hosted, on the cloud the icon will be displayed.
My instance is on version 2024.4.2, I have no blocked firewall logs, neither any bitwarden logs that throw any error.

### Expected Result

The mobile app displays the website icon, no matter which size the favicon has.

### Actual Result

If the size is 32x32 a grey globe will be displayed instead of the actual website icon.
Any other size the icon will be empty.

### Operating System

iOS

### Build Version

2024.4.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by ChrisSlashNull** [comment]
Thie bug is present since a few releases, I don't know which exactly.

-I tried to reinstall the app
-DNS is working fine
-On the firewall nothing gets blocked
-no error log found (bwdata/logs)

![image](https://github.com/bitwarden/mobile/assets/q128401608/79e2ce06-5a23-47d9-84b7-0acf88a69b5e)

If the size is not 150x150 the app won't show it.

I tested it with https://vault.bitwarden.eu/icons/domain.com/icon.png

A few icons that don't work:

https://vault.bitwarden.eu/icons/nzxt.com/icon.png (grey globe)

https://vault.bitwarden.eu/icons/parqet.com/icon.png (grey globe)

https://vault.bitwarden.eu/icons/ring.com/icon.png (no icon, just blank)

https://vault.bitwarden.eu/icons/crowdsec.net/icon.png (no icon)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3229
