### ISSUE TITLE
Password Generator - can't see number of special characters

### ISSUE THREAD

**Issue by pamperer562580892423** [bitwarden/android#3241]
### Steps To Reproduce

1. Go to the password generator.
2. Click on nothing.
3. Scroll down to "minimum special characters" (here in German "Mindestanzahl Sonderzeichen")
4. Click on nothing.

### Expected Result

I can see the number of chosen special characters.

### Actual Result

The number is hidden behind the minus and plus buttons. (and the German word "Sonderzeichen" (= special character) is truncated as well)

### Screenshots or Videos

![signal-2024-05-13-234647_002](https://github.com/bitwarden/mobile/assets/138042245/7fa39f43-8949-41f6-b364-c98a0ab7d0a6)

### Additional Context

I think there is no context. The only thing I thought about the fontsize - but I think I have a regular fontsize on my Android (13) phone.

### Operating System

Android

### Operating System Version

13

### Device

Fairphone 5

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3241
