### ISSUE TITLE
iOS does not return same search as browser

### ISSUE THREAD

**Issue by bcookatpcsd** [bitwarden/android#3251]
### Steps To Reproduce

I saved a login from a Synology device, (name, username, password, website, and note)

In the note I wrote the word Synology

iOS extension cannot find 'Synology' but browser plugin can. 

Sync'd by hand, still cannot find.

Searching on 1.175 (saved in name and website fields) does bring up the record and 'Synology' is listed in the notes. 

### Expected Result

able to search all fields with saved data and obtain results related to that search with reasonable accuracy. 

### Actual Result

iOS app cannot return the same results as browser extension. 

### Additional Context

iOS: 17.4.1
iOS Bitwarden: 2024.5.1
Vault: Argon2id 
Vault KDF iterations: 3
Vault KDF memory: 64
Vault KDF parallelism: 4
(vault settings were change related to the lastpass event..)

iPhone is newer, no unlocking, or 'oom' problems.

I have screenshots, but hopefully the text is enough.. 

### Operating System

iOS

### Operating System Version

17.41

### Device

iPhone A2849

### Build Version

2024.5.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by lf-** [comment]
This may be https://github.com/bitwarden/mobile/issues/3242?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3251
