### ISSUE TITLE
Android: Unable to set BW as passkey provider

### ISSUE THREAD

**Issue by mimi89999** [bitwarden/android#3253]
### Steps To Reproduce

1. Go to Bitwarden Settings
2. Click on Passkey Management
3. Click on Continue in the Set BW as your passkey provider dialog

### Expected Result

Should be able to set BW as passkey provider somewhere and use passkeys stored in BW

### Actual Result

There is no such option and it's impossible to set BW as passkey provider

### Screenshots or Videos

![Screenshot_20240518-124503](https://github.com/bitwarden/mobile/assets/8530546/27e374b2-7ded-49ca-afb3-80994a37f78a)

[Bitwarden Passkeys configuration.webm](https://github.com/bitwarden/mobile/assets/8530546/cf10ca87-5673-4bde-a044-4504c9a28d40)

### Operating System

Android

### Operating System Version

14

### Device

Sony Xperia 5 V (XQ-DE54)

### Build Version

2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @mimi89999,

Thank you for this report. Just to make sure that you and I are on the same page, did you perform all the steps [outlined in the documentation](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys)?


Thank you,

**Comment by aamadorj** [comment]
BW was working as passkey provider on my Pixel 6 with latest stock Android, but then Chromium 125 was released and the "Enable 3rd party passkey providers"  flag disappeared. Since then, every time a passkey is going to created,  Google Password Manager jumps in, with no option to use BW

**Comment by mimi89999** [comment]
I followed the doc except that I don't have a _Passkey management_ option under autofill nor anywhere else in passwords and accounts

![Screenshot_20240518-144531.png](https://github.com/bitwarden/mobile/assets/8530546/0b268c34-fc9f-4ea5-a80f-6c97e978c3e7)

**Comment by NickCao** [comment]
> BW was working as passkey provider on my Pixel 6 with latest stock Android, but then Chromium 125 was released and the "Enable 3rd party passkey providers" and "Enable for Google Password Manager and 3rd party passkeys" flags disappeared. Since then, every time a passkey is going to created, Google Password Manager jumps in, with no option to use BW

Try setting these flags:

![image](https://github.com/bitwarden/mobile/assets/15247171/581a1f8d-8342-4222-950b-8ae6a1253803)

**Comment by msiqx9** [comment]
> Try setting these flags:

Setting these flags does not solve the problem for me.

**Comment by aamadorj** [comment]
I first enabled the "Temporarily unexpire M124 flags", relaunched latest Brave Browser (base on Chromium 125) and finally I enabled "Android Credential Management for passkeys" with the option "Enable for Google Password Manager and 3rd party passkeys". It was a complete success and I now BW is jumping in when I need to create a passkey or use one. Thanks, @NickCao.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. For anyone that still is not being prompted to use Bitwarden to store a passkey (not 2FA) from a website via the browser on Android, could you please navigate to ```Settings > Google > Autofill > Autofill with Google``` and let me know if this function is activated? If it is, could you please turn it off and then perform [these steps](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys) again, and let me know if that helps?

Thank you in advance,

**Comment by mimi89999** [comment]
Hello,

Autofill with Google was disabled on my device

![Screenshot_20240520-150145.png](https://github.com/bitwarden/mobile/assets/8530546/646d4c39-4a74-4cc5-88da-66c18796a0c9)

**Comment by aamadorj** [comment]
Autofill with Google is disabled on my Pixel 6.

**Comment by msiqx9** [comment]
> ...could you please navigate to `Settings > Google > Autofill > Autofill with Google` and let me know if this function is activated? If it is, could you please turn it off and then perform [these steps](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys) again, and let me know if that helps?

Autofill with Google is disabled and in Autofill service it is Bitwarden that is selected.  Nevertheless, whenever a Passkey is needed in the Chrome browser, Google steps in and says there are no Passkeys.

**Comment by whiskerz007** [comment]
I have followed the instructions to enable passkeys in Chrome v125. While my BW vault is locked, attempting to sign in with a passkey will prompt me to unlock BW and then list available passkeys. Every subsequent sign in attempt using passkeys will bring up Google passkey manager without BW options. Opening BW and manually locking the vault will then allow me to use BW again.

**Comment by msiqx9** [comment]
> To confirm, did the steps in [this comment](https://github.com/bitwarden/mobile/issues/3253#issuecomment-2119338116) assist in getting Bitwarden to be presented as an option when attempting to save or use a passkey on Android 14?

No, Bitwarden was not presented as an option.  On attempting to use a passkey, I get a small window with a Google key logo saying "No passkeys available".

> Please remember that you'd need to first activate the (Temporarily unexpire M124 flags) flag, restart Chrome, and then activate the (Android Credential Management for passkeys) flag, and then follow the rest of the steps [outlined in the documentation](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys).

I have carefully followed these steps perhaps 10 times in the past 24 hours without being offered passkeys stored in Bitwarden.  I am successfully using Bitwarden stored passkeys in Windows 11 and on my iPad.  I am also able to use passkeys on my Android device using the QR code method with my iPad/Bitwarden camera.

**Comment by rehannali** [comment]
Hi, I have followed the steps available on site, and it offered me to use passkey from bitwarden, but I'm stuck on locking an unlocking mechanism. I clicked on unlocked, verified biometrics, and it says, unlock.
If I set it up to value other than immediately,  Google passkey showed and gives me a message no passkey available.

**Comment by msiqx9** [comment]
I've just updated the Android Bitwarden app to 2024.5.1 beta and this problem continues.

**Comment by mimi89999** [comment]
Hello,

I installed the Bitwarden apk on the emulator and I noticed that the Passwords & accounts screen is very different form the screen on my device even though both have Android 14. First screen is form the emulator and the second one is from my Sony Xperia 5 V (XQ-DE54).

![Screenshot_1717949553](https://github.com/bitwarden/mobile/assets/8530546/51d58b32-5e3e-495b-bcb4-3abe1fd06ea3)
![Screenshot_2024-06-09_181830](https://github.com/bitwarden/mobile/assets/8530546/b1e7582a-2697-4bca-914c-52d467423f6d)

**Comment by mimi89999** [comment]
Did others with the same issue check whether that feature is enabled? If it's a more common problem, maybe we should find a way to reach device manufacturers an report it to them?

**Comment by fuxii** [comment]
On my phone it's also not enabled. (Nothing Phone 2, Android 14).

**Comment by Korel** [comment]
> Did others with the same issue check whether that feature is enabled? If it's a more common problem, maybe we should find a way to reach device manufacturers an report it to them?

Android 14 on Motorola Edge 40 (just updated it with recovery tool to be able to use passkeys), my settings also looks like yours (passwords is google and autofill bitwarden, no passkey option) and "adb shell pm has-feature android.software.credentials" returns false...

**Comment by coolssor** [comment]
To throw a spanner in the works...

I checked through ADB for that value:

```
coolssor@fedora:~$ adb shell pm has-feature android.software.credentials
true
```

---

Model: Google Pixel 8 Pro
Android version: 15
Build: AP31.240426.023.B4

Chrome version: 125.0.6422.165

Bitwarden app version: 2024.5.1
Session timeout: 15 minutes (seen this be an issue for some)

1. Enabled "Temporarily unexpire M124 flags." restarted Chrome (force stop from settings), set "Android Credential Management for passkeys" flag to "Enabled for 3rd party passkeys" (this is not called "Enabled for 3rd party passkey providers" as it says in the documentation).
    - I have no other flags enabled.
3. Set my Preferred service in "Passwords, passkeys and accounts" to Microsoft Authenticator, then back to Bitwarden.
4. Rebooted device
5. Removed all passkeys and passwords from 4 Google accounts and local device saved credentials in Google Password Manager.
6. Tested using https://passkeys.io, as per the screenshot in the documentation. This throws up a Google Password Manager request to save a passkey.
7. Selecting "Use a different device" only shows "USB security key" and "Use a different phone or tablet"

**Comment by mimi89999** [comment]
@coolssor what do you see in the Passwords & accounts screen?

**Comment by coolssor** [comment]
> @coolssor what do you see in the Passwords & accounts screen?

![Screenshot_20240616-203808.png](https://github.com/bitwarden/mobile/assets/63597985/3088f9da-21ed-4bb6-82d5-42dcd7b49bbf)

Hey, I see this (censored the section for my accounts for privacy).

**Comment by danielhass** [comment]
@mimi89999 as suspected:

```
$ adb shell pm has-feature android.software.credentials
false
```

So far I haven't been able to get the BW Passkey select screen once on my device. Maybe this is the reason.

**Comment by msiqx9** [comment]
I just updated the Android Bitwarden app to 2024.6.0 but this doesn't fix the Passkey problem.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3253

**Comment by msiqx9** [comment]
This issue has been closed by Bitwarden as completed so I assume it will never be fixed.  As a workround for now, I will save Passkeys to Google Password Manager.
