### ISSUE TITLE
[iOS] The " char in password are automatically replaced by «

### ISSUE THREAD

**Issue by tokcid** [bitwarden/android#3256]
### Steps To Reproduce

1. I create an item, with a password containing the char " (double quote)
2. I save it
3. When I want to modify the item, the item is opened, but the car " is automatically replaced by «
(I'm French with a French keyboard on iOS)

### Expected Result

My password have not to be modify automatically

### Actual Result

The " char in password are automatically replaced by «

### Screenshots or Videos

![image](https://github.com/bitwarden/mobile/assets/8049039/96d70cec-e569-4264-be10-48513833ba20)

### Operating System

iOS

### Operating System Version

 iOS 17.5.1

### Device

iPhone 15

### Build Version

2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tompipe** [comment]
I'm also seeing a bug that seems related. 

When viewing a password, it's losing the first character. I've screenshotted an example, the password should display <password123 but it shows password123. 

![Screenshot_20240524-053357~2](https://github.com/bitwarden/mobile/assets/629719/3273db56-e670-4424-8c82-718f42bbb342)

It does display correctly in the edit screen

![Screenshot_20240524-053412~2](https://github.com/bitwarden/mobile/assets/629719/24228425-df08-4ee6-b1cd-573178de78df)

You can watch it disappear as soon as it's saved. 🫤

I've tried a small selection of other special characters, and I can't recreate with the handful I tried, it seems to be only the <

But something's definitely not right with it, if @tokcid also experiencing a similar issue

Android
Version: 2024.5.1 (10574)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3256
