### ISSUE TITLE
Android password generator does not support minimum number/special character values >5

### ISSUE THREAD

**Issue by b02860de585071a2** [bitwarden/android#3259]
### Steps To Reproduce

1. Go to 'generator' tab of Android app
2. Try to change 'minimum numbers'/'minimum special' to >5

### Expected Result

I should be able to increase these values to (at least) 9, as is the case with other versions of Bitwarden (desktop, browser extension, cli).

### Actual Result

Generator is limited to a maximum value of 5.

### Operating System

Android

### Operating System Version

Android 13-14

### Device

Pixel 8 Pro

### Build Version

2024.4.0 (build 10172)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by b02860de585071a2** [comment]
I have opened https://github.com/bitwarden/mobile/pull/3260 to address this.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3259
