### ISSUE TITLE
LineageOS 21: Bitwarden cannot be used for passkey authentication on mobile

### ISSUE THREAD

**Issue by somova** [bitwarden/android#3310]
### Steps To Reproduce

1. Ensure Bitwarden mobile is set as provider for "Passwords, Passkeys and Data Services"
2. Open mobile Browser
3. Open webpage "https://webauthn.io/"
4. Try to register a passkey or authenticate with a passkey

### Expected Result

Android should offer to select the favorite passkey provider to use with the webpage

### Actual Result

Google only offers to store a new or use an already stored passkey in the Google Account or to select another device. The list of other devices only contains NFC, USB or other smartphone.

### Operating System

Android

### Operating System Version

LineageOS 21 (Build: 20240610; Android 14)

### Device

Oneplus 9 Pro (LE2123)

### Build Version

2024.5.1 (10574)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3310
