### ISSUE TITLE
Plus addressed email setting cannot be saved

### ISSUE THREAD

**Issue by fxzxmicah** [bitwarden/android#3312]
### Steps To Reproduce

1. Go to generator
2. Select generate username
3. Change email address
4. Switch to another page and return to the generator
5. Email address setting is reset

### Expected Result

Save user setting.

### Actual Result

User setting is reset.

### Additional Context

The browser extension can save this user setting, but the behavior of the mobile client is not consistent with it.

### Operating System

Android

### Operating System Version

14

### Device

IQOO Neo 7 Racing

### Build Version

2024.5.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3312
