### ISSUE TITLE
[android] accessibility autofill popup twice: "Go to my vault", then "Vault is locked" - in different location/position

### ISSUE THREAD

**Issue by SVNKoch** [bitwarden/android#3318]
### Steps To Reproduce

1. I have the following activated:
   - auto-fill service
   - accesibility helper
   - popup overlay
3. have a locked vault
4. click on a username / password field
5. see the autofill popup overlay

### Expected Result

get a single popup overlay at a fixed position

### Actual Result

pop up overlay changes a split second after: text changes, icon changes and **most importantly and most annoyingly, the position changes too**

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/39488412/8c53bc4f-145e-4791-8539-22be89a086b5

### Operating System

Android

### Operating System Version

8.1

### Device

ONEPLUS A5010

### Build Version

2024.4.0 (10172)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3318
