### ISSUE TITLE
When autofilling on Android, Bitwarden forgets that it's autofilling if you switch to another app or the home screen

### ISSUE THREAD

**Issue by jabashque** [bitwarden/android#3321]
### Steps To Reproduce

1. Configure Bitwarden to require master password to unlock and to lock immediately if you leave the app.
2. Go to any app with a login screen, page, or dialog box
3. Try to autofill with Bitwarden via Android's autofill framework. Because Bitwarden is locked, this will open a Bitwarden activity that will ask for the user to input the master password.
4. Either switch to another app, or return to the homescreen.
5. Return back to the previous app where you were autofilling with Bitwarden. It should be displaying the unlock screen still.
6. Enter your master password and press the "Unlock" button.

### Expected Result

This should still result in Bitwarden continuing the autofill flow, where it tries to pull up exact and best matches for the given URI, along with an option to search for other entries that didn't get matched to use for autofill purposes.

### Actual Result

Bitwarden seems to forget that it's trying to autofill; instead, it behaves as if you opened the Bitwarden app directly and takes you to the main screen, where you can access your vault, the password generator, options, and so on. You have to press the back button to exit out of the Bitwarden activity to get back to the original app where you were trying to invoke autofill, and then try autofill again, this time _without_ leaving the app or the Bitwarden activity half-way through the autofill process.

### Operating System

Android

### Operating System Version

LineageOS 21 (Android 14)

### Device

OnePlus 8

### Build Version

2024.5.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3321
