### ISSUE TITLE
Is FDroid Repo down?  Url gives 404

### ISSUE THREAD

**Issue by ppittle** [bitwarden/android#3333]
### Steps To Reproduce

1.  Navigate to https://mobileapp.bitwarden.com/fdroid/repo
2. Receive 404

![image](https://github.com/bitwarden/android/assets/1190907/b1e76e33-6c2a-4821-92be-8949c5d5b963)

### Expected Result

200

### Actual Result

404

### Build Version

n/a

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SkewedZeppelin** [comment]
It looks like it was done on purpose https://github.com/bitwarden/android/commit/80ff991da66d48f80d84c2618e34550a9f7bd67e

If you really want to add it still use `https://raw.githubusercontent.com/bitwarden/android/gh-pages/fdroid/repo`

But they're probably just migrating to another server or something.

**Comment by ppittle** [comment]
That looks like a breaking change :p

**Comment by vvolkgang** [comment]
Thank you for the report! This was an unintentional side effect of the new bitwarden/mobile repo migration, we're working to get this page back up.

**Comment by vvolkgang** [comment]
Should be working now!

https://mobileapp.bitwarden.com/fdroid/

**Comment by cwchristerw** [comment]
It works 🥳

**Comment by ppittle** [comment]
> Should be working now!
> 
> https://mobileapp.bitwarden.com/fdroid/

Confirmed!

For your consideration, when the link was down yesterday, I checked the [Bitwarden Status page](https://status.bitwarden.com/) for more information, but everything was green, and no mention of fdroid.  Would have been nice to see a monitor for the fdroid repo url.

**Comment by terminatorbs** [comment]
I know this is a closed issue, but today i tried downloading the app from https://bitwarden.com/download/#downloads-mobile 
and got an error when scanning the QR code.
the link by ppittle above (https://mobileapp.bitwarden.com/fdroid/) worked for me.

I don't know if it's my fdroid that had issues with the first code or if it actually is different, but if i'm not the only one encountering this, i'd suggest updating the QR on the first page i mentioned too, as for me that was the page i naturally ended up when looking where to get the app.
