### ISSUE TITLE
Bitwarden prompt obscures when trying to paste a password.

### ISSUE THREAD

**Issue by hornetster** [bitwarden/android#3337]
### Steps To Reproduce

1. Trying to login to a site.
2. Have been to Bitwarden/MyVault and copied a password.
3. Goto the app and enter the username (usually email - have not tried copying/pasting the username - may have a similar issue??)
4. Try and paste in the password, but after long-pressing, can't paste in password, as the Bitwarden prompt is over the top of it... (Tried to get a screenshot, but when swiping for the password, the Bitwarden prompt disappears..)
5. 

### Expected Result

Should be able to see the "Paste" reference, and be able to select it to paste.

### Actual Result

Bitwarden prompt covers the 'paste' option.

### Additional Context

Similar (but different...) to #1641.

### Build Version

2024.6.0 (10746)

### Environment Details

Pixel 8/Android 14/Fully up-to-date. (5 June 2024)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @hornetster,

Thank you for this report. With regard to the [Autofill Service's](https://bitwarden.com/help/auto-fill-android/#autofill-service) and [Accessibility Service's](https://bitwarden.com/help/auto-fill-android/#accessibility) prompts/banners; Whilst we exchange information with the operating system, the operating system is responsible for how and where those banners are displayed. With that in mind, you can consider deactivating those autofill services and using only Inline autofill.

If you have any questions or concerns, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
