### ISSUE TITLE
App crashes when opening security settings 

### ISSUE THREAD

**Issue by asislife20** [bitwarden/android#3339]
### Steps To Reproduce

1. Go to settings
2. Click on Account Security 

### Expected Result

Expected to open account security settings.

### Actual Result

App crashes completely. It can't be opened again unless I clear data, and login again.

### Build Version

2024.6.1-beta (11139)

### Environment Details

Device: Nubia Red Magic 5G (nx659j)
Android Version: 13
Rom: Lineage OS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by asislife20** [comment]
> Hi there,
> 
> I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below.
> 
> Thanks!

I tested the latest beta version yesterday. As of the latest beta the issue seems to have resolved itself, so I'm closing this issue!
