### ISSUE TITLE
Android beta app Screenshot issues

### ISSUE THREAD

**Issue by likevi9528** [bitwarden/android#3353]
### Steps To Reproduce

I found 2 issues regarding screenshots.

1. When I first logged into the app (using bitwarden.com), "other" -> "allow screenshot capture" was off, but I could take screenshots. After turning "allow screenshot capture" on and off, the functionality returned to normal.

2. "allow screenshot capture" was off, then I switched languages ​​and was able to take screenshots again.

### Expected Result

As mentioned above.

### Actual Result

As mentioned above.

### Additional Context

I also report it on [bitwarden/mobile](https://github.com/bitwarden/mobile/issues/3326) and [bitwarden forums](https://community.bitwarden.com/t/android-beta-app-screenshot-issues/68733) five days ago.

### Build Version

2024.6.1

### Environment Details

- Device: Redmi K30
- OS: Android 12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Greenderella** [comment]
We will close this issue and refer to the original report to prevent duplicate entries.
