### ISSUE TITLE
F-Droid Version: Account security login requests causes nonexistent notification flow

### ISSUE THREAD

**Issue by onkoe** [bitwarden/android#3387]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open up Bitwarden Kotlin with the F-Droid build
2. Head to app Settings > Account security.
3. Toggle on "Use this device to approve login requests from other devices"
4. Select "Yes" on the message box.
5. A new message box will appear, stating that you can "Receive push notifications for new login requests", with "No thanks" and "Settings" buttons.
6. Select Settings, then hit "Notifications"
7. The switch will be grayed out due to there being no Firebase support in the F-Droid build.

### Expected Result

On F-Droid builds, do not enable any settings that require notifications.

### Actual Result

Asks the user to enable a statically turned off notifications switch.

### Screenshots or Videos

![Screenshot_20240630-174000_Settings](https://github.com/bitwarden/android/assets/66580279/75b3d8b7-c8ad-4071-9975-fd7e0c7b8fa1)

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.6.0 (10746)

### Environment Details

- Device: OnePlus 7 Pro
- Environment
  - Distribution: LineageOS for microG 21
  - OS: Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by zzjjaayy** [comment]
@sammbw {sorry for tagging if this is not how you do it}, I wanted to know if this and other issues on github up for grabs by independent contributors?

**Comment by micahblut** [comment]
@onkoe the version you listed is not a native app build. Please be aware that legacy .NET app bugs should be reported in [[bitwarden/mobile](https://github.com/bitwarden/mobile)]

**Comment by micahblut** [comment]
@onkoe the version you listed is not a native app build. Please be aware that legacy .NET app bugs should be reported in [[bitwarden/mobile](https://github.com/bitwarden/mobile)]
