### ISSUE TITLE
Login fails when using email address with uppercase letters

### ISSUE THREAD

**Issue by CerebralDatabank** [bitwarden/android#3410]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Log out if logged in.
2. Try to log in with an email address with uppercase letters
   Example: `John.Smith@example.com` + `(correct password)`
   → Fails with "incorrect username or password"
3. Try to log in with an email address with all lowercase letters
   Example: `john.smith@example.com` + `(correct password)`
   → Succeeds

### Expected Result

Logging in should work regardless of the case of the characters in the email address.

That would also match the behavior of the existing Xamarin Android app, web app, and browser extensions.

### Actual Result

Logging in with an email address with uppercase characters fails, while an all-lowercase email address succeeds.

### Screenshots or Videos

Screen when login fails:

<img src="https://github.com/bitwarden/android/assets/24465111/cd1fc11c-02fa-4d70-a831-5c318de4463c" alt="bitwarden-beta-email-issue" width="400">

### Additional Context

This problem was found on a fresh install of Bitwarden Beta on a Pixel (Android) device.

### Build Version

2024.6.1

### Environment Details

- Device: Pixel 8 Pro
- OS: Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JuliusBairaktaris** [comment]
According to RFC 5321, the local part of an email address should be treated as case-sensitive. Therefore, the behavior you describe is correct and wanted.

**Comment by Hinton** [comment]
Hi @CerebralDatabank,

Thanks for reporting this. This seems indeed to not be the desired behaviour as it's inconsistent with the other applications.
