### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jony5673** [bitwarden/android#3421]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

2. Click on '...'
3. Scroll down to '...'
4. Click on '...'

### Expected Result

d

### Actual Result

sd

### Screenshots or Videos

sd

### Additional Context

sd

### Build Version

sd

### Environment Details

sd

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ayuda012** [comment]
Como Hackear WhatsApp lo que hace tu pareja en WhatsApp? Con el Modo Oculto & Indetectable - HACKEAR WHATSAPP | Espiar WhatsApp DE MI PAREJA | NUEVO TRUCO


👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp 
ahora : https://www.ayudahacker.info/ 👈🏻👈🏻

Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora :   https://www.comoespiarwsp.xyz/    👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/  👈🏻👈🏻

Publicado hace 14 minutos:

TELEGRAM Chat Directo:
[https://telegram.me/ParentalProtect ](https://telegram.me/ParentalProtect)


Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/ 👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora :   https://www.comoespiarwsp.xyz/    👈🏻👈🏻


Publicado hace 10 minutos:



Como hackear WhatsApp España - EEUU - Chile - Perú - Ecuador - Mexico - Colombia - Guatemala - El Salvador - Republica Dominicana - Bolivia. TODOS LOS PAISES DISPONIBLE



Somos lideres en el sector de CyberSeguridad y EthicalHack con mas de 10 años de experiencia en diferentes tipos servicios

¿Tiene sospechas de infidelidad?
Entérese de lo que esta pasando!

Como Hackear WhatsApp en tiempo real
Recuperación de mensajes Eliminados

GARANTIZAMOS TOTAL SEGURIDAD Y DISCRECION

NUESTROS SERVICIOS ESTAN DISPONIBLES EN TODOS LOS PAISES


Copyright © 2024

![ParentalProtect](https://github.com/bitwarden/android/assets/175081891/f7593ce6-b736-4b4b-888f-4ed455c9ea94)

**Comment by Adulsu** [comment]
https://www.facebook.com/profile.php?id=100082071884838&mibextid=LQQJ4d

**Comment by Arlethal** [comment]
No sirve

**Comment by Arlethal** [comment]
No sirve para nada segui los paso y no salió nada
