### ISSUE TITLE
Trashed items not visible

### ISSUE THREAD

**Issue by AleIlMagno** [bitwarden/android#3588]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

0. Have no items in your vault
1. Add any new item to the vault
2. Delete that item

### Expected Result

There should be a way to see the deleted item(s).

### Actual Result

There is no way to see, and therefore restore or permanently delete, a deleted item when the vault is empty because it only shows the button to add a new item.

### Build Version

2025.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @AleIlMagno,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by qwexter** [comment]
Fix here 
https://github.com/bitwarden/android/pull/3624
