### ISSUE TITLE
No quick tile for autofill

### ISSUE THREAD

**Issue by fredgolightly** [bitwarden/android#3595]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

After installation there is no quick tile available in android tile bar to press to autofill 

### Expected Result

Autofill quick tile be available to pin

### Actual Result

No tile available

### Build Version

2023.7.1

### Environment Details

Pixel 8 Android 15 beta
Tab S9, Tab S8 Ultra Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by fredgolightly** [comment]
Reinstalled and tried everything but still can't get this working on a Tab S9 or S8 ultra, should it be working or not yet?

**Comment by Muehli25** [comment]
Based on my experience, you need a service that extends the TileService class to enable tiles in the Quick Settings menu.  However, I couldn't find any such service in the code.

**Comment by MrSourceUnknown** [comment]
Hope this gets picked up for review, the Android Quick Tiles were a very useful feature in the legacy app version. Even just to open the vault.

**Comment by Taomyn** [comment]
Just got beta 2024.8.0 and saw my tiles had vanished. Hope they come back soon, as either auto-fill detection has improved or I'm going to have a miserable time using Bitwarden on my phone.

**Comment by djsmith85** [comment]
[Comment](https://community.bitwarden.com/t/vault-quick-tile-missing-in-beta/69889/6) from the community forums:
> Yep! We’re working on quick tiles for Vault and Generator now.

**Comment by artgru** [comment]
My apologies I must have missed i.

**Comment by micahblut** [comment]
Please note that while we are working on adding quick tiles to quickly access Vault and Generator, there are not plans at this time to re-add the quick tile for Autofill.

**Comment by Taomyn** [comment]
> Please note that while we are working on adding quick tiles to quickly access Vault and Generator, there are not plans at this time to re-add the quick tile for Autofill. 

So you're going to fix the poor auto-fill detection then?

**Comment by bengry** [comment]
> note that while we are working on adding quick tiles to quickly access Vault and Generator, there are not plans at this time to re-add the quick tile for Autofill. 

Any reason for that? Or just prioritization etc.?

The auto-fill tile is extremely useful for cases where Bitwarden doesn't recognize fields. The auto fill quick tile still filters the correct sites or app (URIs). Which happens quite a bit with Android being what it is..

**Comment by micahblut** [comment]
The autofill quick-tile was a way of manually invoking autofill using the accessibility service. Since we are not implementing the accessibility service, there's no way to manually invoke autofill. 

For anyone experiencing poor autofill detection, please please help us make this situation better by providing specific bug reports that include details such as your device model, OS version, software version, site or app where failure occurs, etc. There's been a very positive conversation happening over on our [community forum](https://community.bitwarden.com/t/bitwarden-android-beta-does-not-provide-autofill/68632/31) where these specific reports have led to meaningful improvements.

**Comment by fredgolightly** [comment]
I think as long as there's a quick tile for the vault that's ok for when autofill fails to detect the fields.

It would be great if when opening the app it defaulted to biometrics instead of having to select biometric login to invoke the fingerprint reader, just another step for quicker usage

**Comment by micahblut** [comment]
@fredgolightly good news! #3728

**Comment by archon810** [comment]
@micahblut This is very disappointing news as I don't know if bitwarden can solve all cases, and when it does happen, it's very annoying.

For me, the most used case is the horrible "do you still remember your 2FA password" that Whatsapp shows like every week. I can't believe there's no way to make it stop. Anyway, Bitwarden doesn't offer autofill there, but the tile worked perfectly.

https://android.stackexchange.com/questions/182961/whatsapp-2-step-verification-code-being-asked-frequently

https://www.reddit.com/r/whatsapp/comments/1c1ykyg/whatsapp_2fa_pin_code_recall_is_absurd

https://www.reddit.com/r/whatsapp/comments/y9lh8l/whatsapp_keeps_asking_me_for_verification_everyday

**Comment by travisterrell** [comment]
I want to emphasize how **extremely disappointing** this is. 

I rely on the tile several times a week. Opening the vault and manually searching for and copying a password every time I'm not presented with the native full option is extremely inconvenient! For now I'm rolling back to an old version, but obviously for security reasons this is not a tenable long term solution.

 completely shifted my password management to Bitwarden a few years ago and have converted many other users, so I'm REALLY not interested in switching to an alternative over one little decision. An auto-fill tile is simply a hard requirement for me until all Android apps begin playing nicely with the native framework...and this seems extremely unlikely to ever be the case.

**Comment by fredgolightly** [comment]
When BW beta doesn't work I have to close it, go 'home', open the BW app, log in, search for the site/app, find it won't load anything just a black screen, force close the app, reopen and find & copy the password then go back to the app to paste it in. For non-techy/older family members this becomes a major roadblock to accessing their accounts while being merely frustrating to the rest of us. A poll for it's inclusion, perhaps?

**Comment by TheLimifiedLime** [comment]
I would like to share the same sentiment everyone else has stated. For my workflow this is a requirement as otherwise I essentially have no auto fill in my browser or a lot of native apps for that matter. This feature is one of the main reasons I have stuck with Bitwarden, and without it Bitwarden doesn't really have any advantage over the competition for me.

**Comment by fredgolightly** [comment]
This is annoying for when you need to grab your bank card credentials and no autofil works so you're back to manually opening it

**Comment by jirom** [comment]
I can't believe this was just closed. The quick tile for auto fill has been very helpful when the auto fill detection doesn't work. This version of the app might look "nicer" but the user experience has been a large downgrade.

**Comment by gestate-8** [comment]
No matter how sophisticated Bitwarden's autofill detection gets, it can't react to special cases as quickly as a manual trigger by the user. 
This is a project that still lacks developers, with features promised last year still on hold. Do you really think they can address every edge case that's reported? Just add a Quick Tile.

**Comment by micahblut** [comment]
Hi all, just popping in to provide an update. We hear and appreciate the engagement, and we are investigating how we can re-implement the quick-tile for cases where other autofill methods do not meet user needs. Thank you all for the feedback!

**Comment by gouravkr** [comment]
Just popping in here to add that the beta app was simply not working for me without the tile. Detection of autofill is far from perfect and I have to manually invoke autofill most of the time, especially because Bitwarden doesn't detect credit card fields at all. As of now, I have rolled back to the previous version to get back the tile.

**Comment by archon810** [comment]
Just tonight, I was logging in to Fedex. Nope:

![Screenshot_20240829-210726.png](https://github.com/user-attachments/assets/25402457-b53b-4073-8258-35c45061264e)

Same thing with the Schwab app (on the username entry screen) and so many others. We're just not ready to lose the fill tile.

**Comment by eiqnepm** [comment]
> Hi all, just popping in to provide an update. We hear and appreciate the engagement, and we are investigating how we can re-implement the quick-tile for cases where other autofill methods do not meet user needs. Thank you all for the feedback! 

I really hope this means accessibility autofill is going to continue to be supported.

I rely on accessibility autofill what feels like 40% of the time as native autofill on Android is just terrible. 

Accessibility autofill also allows me to autofill apps in my work profile from Bitwarden in my personal profile.

**Comment by motoridersd** [comment]
I downgraded to the latest release APK from this github, 2024.6.0 and got the AutoFill tile back. Had to uninstall the newer beta and install the older version in its place.

**Comment by Xyaren** [comment]
I agree to what has been mentioned. 

I would like to mention an additional use case which can not be convered by the existing autofill: 

Remote shells/remote desktop apps. 
While using JuiceSSH for example I sometimes need to enter/paste passwords. 

Using the autofill tile this was possible by copying the password to the clipboard and subsequently pasting it.
The same applies for RDP/VNC/TeamViewer apps etc.

If the autofill is not possible maybe at least offer a popup with the related vault entries to copy to the cupboard when clicking the tile.

**Comment by micahblut** [comment]
Quick tile for autofill has been added in the latest beta build.

**Comment by archon810** [comment]
My first test was the Disney+ app, which Bitwarden fails to fill on, and the autofill tile still didn't work, nothing gets filled.

In fact, half the time it failed to even bring up the Bitwarden window - I press the tile and nothing happened.

![Screenshot_20241001-063815.png](https://github.com/user-attachments/assets/8e4ddc57-25f7-4f17-b25c-794d403d1142)

**Comment by archon810** [comment]
Second test on a random app where regular Bitwarden works on - Empower.

Turns out pressing the autofill tile has a huge delay - maybe 5-10s for me. If this delay existed before, it would first show the app window and then spin or show that it's doing something. Now it just has a show delay, which is much worse UX-wise.

Furthermore, this accessibility autofill didn't fill anything in this Empower app either. So 2 for 2 failures.

**Comment by archon810** [comment]
Doing more testing, sometimes nothing happens at all after pressing the button until I tap into a username or password field (Robinhood). Sometimes it works only on the 2nd try (Discover).

All in all, this feels like a regression and quite buggy behavior.

**Comment by micahblut** [comment]
@archon810 thank you for the early feedback. Can you tell me about the device you're testing on? Model and OS version. Thank you!

**Comment by archon810** [comment]
@micahblut Pixel 9 Pro XL, Android 14 stable.

**Comment by archon810** [comment]
Shall we reopen in the meantime?

**Comment by micahblut** [comment]
The quicktile isn't missing, so I'm not sure we want to reopen this issue. I think if there are specific instances where autofill is failing, we want to hear about them. Feel free to continue posting here or open a new issue.

**Comment by archon810** [comment]
I mean... the current reincarnation implementation is really buggy, so I think it's fair to keep the discussion going here, but a new issue can be opened if you'd like.

**Comment by micahblut** [comment]
@archon810 do you mind telling us which empower app you're using? We're trying to replicate and there are a couple of them.

**Comment by archon810** [comment]
Sure. It's https://play.google.com/store/apps/details?id=com.personalcapital.pcapandroid

**Comment by archon810** [comment]
Tried the autofill tile on an Apple TV login in Chrome. The first time nothing happened. The second time it filled in. Not sure why it keeps taking two times.

**Comment by micahblut** [comment]
@RickPJ is the vault locking between steps 2 and 3, or do your timeout settings allow it remain unlocked?

**Comment by RickPJ** [comment]
No, vault does not lock, timeout is 5.mins.

I've played with it in a bit more depth, and it seems that on some sites it misbehaves, on others it doesn't. I can't identify anything about the sites that could account for this.

Also, on many sites where it goes wrong, using the back button, then the quick-tile again will bring up the correct screen. It's a work round, but annoying.

**Comment by eiqnepm** [comment]
I am finding that the new accessibility tile infinity loads or just doesn't appear at all, when it does load it a lot of the time it thinks that app I'm coming from is `android`, this happens in multiple apps including Firefox and Chrome
