### ISSUE TITLE
versions since 2024.6.1-beta not in f-droid repo

### ISSUE THREAD

**Issue by konradmoesch** [bitwarden/android#3641]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open your F-Droid client
(2. Add Bitwarden Repo, if not already done)
3. Search for 'Bitwarden'

### Expected Result

The versions should be available and shown in F-Droid

### Actual Result

The latest version available via F-Droid is 2024.6.0, no newer versions can be found, not even as another app entry / under another package

### Additional Context

F-Droid build artifacts are available here in github, but Seen to not be linked to in your F-Droid repo. Please fix this!

I have enabled "Show unstable versions" in the F-Droid client.

If the updates would be pushed as new versions of the "Bitwarden" app entry (and not, for example, "Bitwarden (Beta)"), without raising "CurrentVersion", the would be marked as Prereleases (see https://f-droid.org/en/docs/Build_Metadata_Reference/#currentversion for more info)

### Build Version

all beginning with 2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @konradmoesch,

Thank you for this report. We currently have no plans to distribute the [Native clients in the Beta](https://bitwarden.com/blog/native-mobile-apps/) stage via F-Droid. Please consider using the Google Play Store or, if you wish, you can download the .apk files off the [GitHub repository](https://github.com/Bitwarden/Android/releases).

If you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) and please include a link to this GitHub report if you do.

Thank you again,

**Comment by konradmoesch** [comment]
@SergeantConfused , thanks for your answer.
Is this a hard decision, or just a matter of priorities? If it is the latter, I would provide the needed code snipppets for changing the github actions workflow / a metadata file for the f-droid repo. If you say there is a chance that you would accept it, of course.

I think I am not the only user that would love to see a less google-centric (or manual) distribution of your betas. The repo and infrastructure already exists, after all
