### ISSUE TITLE
Search filter (Android) should exclude usernames/email addresses

### ISSUE THREAD

**Issue by Thijss** [bitwarden/android#367]
Hi,

In the android app, whenever I search for for the credentials of my email account (e.g., xxx@gmail.com),
all items that use that account as a username also show up in the results. This makes it very tedious to find the credentials of my email account.

For example:
let's say my email is test@gmail.com.
Now I'd like to get the credential to login to my gmail.

However if search for 'test@gmail.com' or 'gmail', results for Twitter, Facebook etc. also show up, since I used that account to sign up for those websites.

** I consider this a bug, since it does not happen when I use the search function of the browser extension (chrome) or the vault (vault.bitwarden.com) ** 

Cheers,

Thijs

**Comment by RoxKilly** [comment]
I agree with the OP that search results could be optimized.  This pain point is one of the reasons I left LastPass for BitWarden.  Basically when a search is run, matches found in the login name itself should take precedence over matches found in the contents.  So if I search for "gmail" and there is a login with gmail in the name, that should show up ahead of all the items that have gmail somewhere in the contents.

This is the behavior in the web extension and the Windows desktop application, but the Android app fails here.

**Comment by snoozysoft** [comment]
This issue particularly pains me as someone who has a Yandex email address; it means not only is the login for my email all the way at the bottom of the list, but it also ends up being covered by the keyboard too.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/367
