### ISSUE TITLE
Keyboard submit button do not work on master password or PIN field

### ISSUE THREAD

**Issue by user-naa** [bitwarden/android#3680]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Lock vault with password or PIN
2. Click unlock input field and enter password/PIN
3. Press submit button on your keyboard

### Expected Result

Nothing happens

### Actual Result

Password should be verified and vault unlocked of password correct

### Build Version

2024.7.3 (18938)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by qwexter** [comment]
Yes, it's work as is and I try to fix it in this screen with some minor improvements. 
We got an answer from dev team, this behavior must be synced with UX\UI team (It's my guess, I don't know what's MAUI mean)

**Comment by qwexter** [comment]
Or I leave here)

Description: The current app does not work properly with Keyboard Actions, which can make it difficult to use certain features, such as:

PIN code input screen: If you press the "Done" button on your keyboard, the keyboard will close, and you'll need to press the CTA (Call-to-Action) button again.
Master password setup: Similarly, when using Keyboard Actions on this screen, the app does not recognize the "Done" button press.
Proposal: I suggest adding support for Keyboard Actions in the following scenarios:

Single CTA button: When there's only one possible action on a screen (e.g., a single button to confirm), allow users to trigger it using a keyboard action.
Multiple input fields: If there are multiple input fields on a screen, use Keyboard Actions to focus on the next field after completing each one, and finally perform the CTA action.

Why is this important? By implementing these improvements, we can enhance the overall user experience of our app, making it more intuitive and efficient for users to interact with it.

**Comment by qwexter** [comment]
@SaintPatrck maybe this issue and my ideas help you with MAUI and other things.

**Comment by micahblut** [comment]
Fixed with #3691
Thank you @qwexter
