### ISSUE TITLE
OTPAuth links don't work

### ISSUE THREAD

**Issue by user-naa** [bitwarden/android#3704]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to any website with 2FA and otpauth link (like lemmy.world)
2. Tap to create 2FA button (which contains otpauth://totp/ link)

### Expected Result

Should open Bitwarden on create TOTP page

### Actual Result

Nothing happens

### Additional Context

Example link
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example

### Build Version

2024.7.3 (18938)

### Environment Details

Android 14
Firefox (Mull)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @user-naa 

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

**Comment by user-naa** [comment]
Maybe this is my browser issue

**Comment by Bazixv13** [comment]
you should check what links bitwarden opens by default it's different on every brand of device but somewhere in the settings
