### ISSUE TITLE
Passkeys don't work

### ISSUE THREAD

**Issue by user-naa** [bitwarden/android#3705]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to any website that supports passkeys
2. Tap create passkey

### Expected Result

Should open Bitwarden

### Actual Result

Nothing happens

### Build Version

2024.7.3 (18938)

### Environment Details

Android 14

Tested on:
Firefox (Mull)
Chromium (Bromite)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by nasiralamreeki** [comment]
Passkeys saving also isn't supported on iOS 18 I know it's a beta but fwiw other password managers including apples new one have the ability to save passkeys right now but when k try on iOS saving doesn't work.

**Comment by user-naa** [comment]
Fixed in latest release
