### ISSUE TITLE
Android Biometrics Popup

### ISSUE THREAD

**Issue by Anthonyy232** [bitwarden/android#3724]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Enable "Unlock with Biometrics"
2. Close app
3. Open app

### Expected Result

Expected: When opening the app with biometrics enabled, the fingerprint and/or facial recognition popup should open

### Actual Result

Result: No popup is shown, user first has to click on "Use biometrics to unlock"

### Build Version

2024.8.0 (18985)

### Environment Details

- Samsung Galaxy S22+
- OneUI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NL-TCH** [comment]
Same in android 15 beta

**Comment by alexbarreras80** [comment]
Same using a S24 Ultra on Android 14 One UI 6.1

**Comment by harikesh409** [comment]
Same using S24+ on Android 14 One UI 6.1

**Comment by ckujau** [comment]
Fixed with [2024.8.1-beta (19099)](https://github.com/bitwarden/android/releases/tag/v2024.8.1) on Android 14 🚀
