### ISSUE TITLE
[minor ui bug] Search fields not showing text correctly 

### ISSUE THREAD

**Issue by Bazixv13** [bitwarden/android#3725]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Tap on the search icon once logged in my valut tab (bug is also present in send tab)
2. Type a lot of characters or just paste some long text 

### Expected Result

text is sliding to the left like in other apps for example YouTube app

https://github.com/user-attachments/assets/186865f6-7ef5-4565-9840-96a42971e05d

### Actual Result

text is being shown incorrectly if there is enough text u are not able to see what you are typing

### Screenshots or Videos

![Screenshot_2024-08-14-04-43-15-463_com x8bit bitwarden](https://github.com/user-attachments/assets/33b8ae17-c2d2-4d4d-b633-f69bbf7203ab)

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

Android 13

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
