### ISSUE TITLE
Passkey is saved in Bitwarden, but this is not communicated back to the website in question

### ISSUE THREAD

**Issue by Zoran-B** [bitwarden/android#3743]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to any website (i.e. https://www.passkeys.io) and attempt to create a passkey
2. Android passkey box opens asking to create passkey in Bitwarden (default passkey app in "Passwords and accounts")
3. Select Continue
4. Bitwarden opens
5. Select login item to add passkey to, or create new item, doesn't matter
6. Biometric auth
7. Bitwarden saves passkey in vault, and displays small overlay "Item saved" with BW logo
8. Back in browser, website didn't get the memo that the passkey had been created...

### Expected Result

Website should prompt for passkey name, or just save it, or in any way acknowledge that a passkey had been created

### Actual Result

Website has no clue passkey has been created making the passkey useless...

### Screenshots or Videos
![bitwarden beta save passkey en](https://github.com/user-attachments/assets/a2757118-4ec4-40c0-9684-b60f08ad5f98)

### Build Version

2024.8.0 (18985)

### Environment Details

Device; Xiaomi 12 Pro
OS: Android 14, HyperOS 1.0.9.0.ULBEUXM

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a not having set up the Chrome flags(https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Zoran-B** [comment]
Checked again, and can confirm that flag in browser Edge) is set.
Passkey ia stored in vault, but website has no knowledge of it

**Comment by Zoran-B** [comment]
Tried changing to Google Password Manager, and it both stores the password and notifies the web of it, displaying the passkey right away.

Switched Bitwarden to be default system app, create a passkey, passkey is created in Bitwarden, but the web doesn't reflect this (no new passkey is displayed). Page refresh doesn't help.

I've been using passkey.io to test, but I've tried with my Microsoft account, and the MS website actually displays a warning saying the passkey could not be created. Passkey.io doesn't display this warning. 

This is dangerous, because even though Bitwarden has stored the passkey and the user **thinks** there's a passkey, login with it is not possible, because the website has not stored the passkey for some reason.

**Comment by Zoran-B** [comment]
I don't know if anybody is reading this, but the issue persists on my Xiaomi 12 Pro Android 14 even with BW ver. 2024.8.1 (19099)
Passkey gets saved to BW but the website doesn't get the info that the key has been created, so it can't be used to login.

**Comment by Zoran-B** [comment]
This issue, even though closed right after reporting is still happening and at least 2 separate threads are active:
https://github.com/bitwarden/android/issues/4669
https://github.com/bitwarden/android/issues/4331
