### ISSUE TITLE
"My Vault" Quick Settings tile is no longer available

### ISSUE THREAD

**Issue by Divinelink** [bitwarden/android#3757]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Swipe down to see Quick Settings tile
2. See that the tile is missing 😳

### Expected Result

I would expect to see the "My Vault" Quick Settings tile and when I click on it, the app should open.

### Actual Result

After updating to native app, it appears that the "My Vault" Quick Settings tile is not longer available. 

### Additional Context

If this is intended and not a bug, I would greatly open a PR and contribute to bring back this feature. 

### Build Version

Version: 2024.8.0 (18985)

### Environment Details

Samsung Galaxy S23+ - Android 14
Xiaomi Pad 6 - Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by noodlejetski** [comment]
@Adedamola-Aina looks like this issue refers to a different quick tile from the one mentioned in the issue you've linked. "My Vault" vs "Autofill".

**Comment by Divinelink** [comment]
It appears to be fixed on version 2024.08.01
