### ISSUE TITLE
Tiles missing? 

### ISSUE THREAD

**Issue by johnkennyuk** [bitwarden/android#3766]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1, pull down from top of screen to see android tilea
2. Find the press the desired tile
3. If tiles were found END
4. Pull down from top twice
5. Choose edit tiles from top left
6. Find Bitwarden tiles and select
7. RETURN to 1

### Expected Result

Expected to see tiles to add or see existing added bitwarden.com tiles for, autofill, generate and vault 

### Actual Result

No tiles available since updating to beta 

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

Oneplus 8t
Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @johnkennyuk,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by Scritterz** [comment]
I too am inconvenienced by this bug - having to go to the web to perform a search is a problem....

**Comment by mbeps** [comment]
Hi, I was also about to create an issue but turns out other people are having it too. I am on a Google Pixel 8 Pro running Android 14 and the tiles are missing ever since the update with the new MaterialYou design. I am currently on version 2024.8.0.

**Comment by EpikPixels** [comment]
Similar situation was wondering why the quick access icon were so out of order and notice it was bitwarden autofill and vault that disappeared. 

Samsung Galaxy S24 Ultra 
SM-S928UI

![Screenshot_20240821_095547_One UI Home](https://github.com/user-attachments/assets/bd412c57-00c7-4b72-996e-adc3fd6cc8fd)
![Screenshot_20240821_095551_One UI Home](https://github.com/user-attachments/assets/872ab0fb-1cd3-4f87-9543-fb3c1c7df232)
![Screenshot_20240821_095556_One UI Home](https://github.com/user-attachments/assets/a52774d2-40f9-42fd-8ee4-9b47f0e62cad)
![Screenshot_20240821_095601_One UI Home](https://github.com/user-attachments/assets/af282c7c-ff23-4081-b4ec-3e84e3a86ddd)

**Comment by johnkennyuk** [comment]
Got the update with the tiles in but looks like we're still missing the autofill tile which would attempt to autofill the current app or url, we had 3 tiles before but unless I'm missing something only seeing 2 tiles presently?

Thanks for the update still though, be icing on the cake to also regain that 3rd tile.

**Comment by mbeps** [comment]
Yes we had 3. The only one missing is the most important one in my opinion. It's the Autofill one that would try to Autofill if the keyboard or drop-down aren't showing which was common especially for Microsoft apps and sites.

**Comment by johnkennyuk** [comment]
> Yes we had 3. The only one missing is the most important one in my opinion. It's the Autofill one that would try to Autofill if the keyboard or drop-down aren't showing which was common especially for Microsoft apps and sites. 

Same mind, 'autofill' was my priority tile if I had to choose priorities. It was my backup / fail over autofill button..

**Comment by johnkennyuk** [comment]
Any update regarding the autofill tile addition? I'm struggling to work without it currently, when my android web pages or apps either fail to provide the autofill prompts or the secure keyboard is activated it's long winded or even at times prevents using apps on android because the apps biometric settings are to tight ie the biometric is prompted every time focus is lost then reactivated.

**Comment by micahblut** [comment]
Autofill tile has been added in the latest available beta build.
