### ISSUE TITLE
Autofill not working in Brave Browser

### ISSUE THREAD

**Issue by Focron** [bitwarden/android#3767]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Activate autofill in Bitwarden (Beta)
2. Open Brave
3. Open any website
4. Click on the login field

### Expected Result

Available autofill options are shown.

### Actual Result

Nothing happens.

### Screenshots or Videos

![1000012185](https://github.com/user-attachments/assets/b54c30a2-b5d6-4331-91d3-8be9b15bdb52)
![1000012186](https://github.com/user-attachments/assets/39b46495-1827-401f-98a0-2681b1161643)

### Additional Context

First image shows Autofill not working in brave.

Second image shows Autofill working in vanadium (GrapheneOS version of Chromeium).

--------

Both normal and inline Autofill was tested and both didn't work in brave.

Bitwarden was installed using F-Droid (Bitwarden Repo)
Brave was installed using the Google Playstore.

### Build Version

Bitwarden version: 2024.8.0 (18985)

### Environment Details

- Device: Google Pixel 6a
- OS: GrapheneOS (build: 2024080600)
- Android version: 14
- Brave version: 1.68.137
- Chromium version: 127.0.6533.100

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Derby9491** [comment]
Exactly the same happens to me in Opera. Maybe a problem with chrome-based browsers?

**Comment by Focron** [comment]
I don't think if that's the case since it seems to work in [Vanadium](https://github.com/GrapheneOS/Vanadium) which is also Chromium based. Maybe Brave and Opera just don't implement the Android Autofill API? The Bitwarden beta app doesn't seem to have the old Accessability based fallback  which could be used if an app didn't implement the Autofill API. 
I'm honestly not sure if that's the issue though, just speculating a bit.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by imtipi** [comment]
> > 嘿，你好
> > 我无法重现此问题，已上报以进行进一步调查。如果您有更多信息可以帮助我们，请在下面添加。
> > 谢谢！
> 
> Hello, I’m very curious about the browsers you use for testing, and the version of Bitwarden on Android that you test with. The same regular expression works very accurately on the PC when using Edge with the extension [link to Edge extension](https://microsoftedge.microsoft.com/addons/detail/bitwarden-%E5%AF%86%E7%A0%81%E7%AE%A1%E7%90%86%E5%99%A8/jbkfoedolllekgbhcbcoahefnbanhhlh). However, on the Android side, Bitwarden Android has never correctly recognized the URL when used in the Kiwi Browser [link to Kiwi Browser](https://play.google.com/store/search?q=bitwarden&c=apps).
> 
> So I’m very curious about what version you used to test and couldn’t replicate the issue.

i am using brave 1.69.164 and bitwarden beta 2024.8.1,can't trigger the autofill

**Comment by splattergamesextended** [comment]
this seems to be a Brave issue, first and foremost. The current fix for this:
- Go to: brave://flags
- search for "Enable the setting to provide a virtual view structure for Autofill" and enable it with the option "enabled without any compatibility check".
- Restart the browser (best would be to force quit).
- A new menu should appear in settings below " Downloads" called "Autofill Services"
- in that menu, select "other providers"
- restart browser again

Now your autofill should be working. At least that worked for me.

**Comment by SaintPatrck** [comment]
As stated above, this is a configuration issue within Brave browser. When enabled, passkeys are working as expected.

**Comment by Lenzelot** [comment]
@splattergamesextended thanks so much, your solution worked for me. Wasted 20 minutes or more on this crap... Seems really weird that Brave chose this behavior. It's fine to set this by default off but the option to enable it should be more easily accessible. Thanks Bitwarden guys, love the product!

**Comment by NicholasFlamy** [comment]
This seems to have broken again.

**Comment by NicholasFlamy** [comment]
> This seems to have broken again.

It seems Google has blocked autofill on http sites.

**Comment by jbh** [comment]
@splattergamesextended - I've searched through all the flags, and I cannot find anything similar to the one you mention. Even when I try to search with just "autofill," nothing similar comes up. At least, not that I can tell. Could you please verify? Or give the actual flag ID? For example, `#show-autofill-type-predictions`.

**Comment by n3t-admin** [comment]
> [@splattergamesextended](https://github.com/splattergamesextended) - I've searched through all the flags, and I cannot find anything similar to the one you mention. Even when I try to search with just "autofill," nothing similar comes up. At least, not that I can tell. Could you please verify? Or give the actual flag ID? For example, `#show-autofill-type-predictions`.

I'm sorry, I don't have an Android phone anymore to test :( It may very well be that there was an update to that flag. I hope someone else can confirm that.

**Comment by vdbrink** [comment]
The Brave flag `#show-autofill-type-predictions` doesn't exists anymore.

What worked for me was to change a setting in Bitwarden, I didn't need to change anything in Brave.
(I translated the menu items from another language so it can be a little bit different)
Go to `Settings` > `Autofill` > Enable the toggle `Use Brave autofill integration`

**Comment by jbh** [comment]
@vdbrink strange. That flag still shows for me. No matter, I was just giving an example, so it's irrelevant. 

Your suggestion to change the setting in BitWarden worked. Technically, it's a shortcut to a setting in Brave, actually. The setting in Brave is: 

Open Brave -> Settings -> Autofill services -> Change `Autofill with Brave` to `Autofill using another service`.

Thanks very much for the help. It works now, which will save me a ton of time jumping between the applications.

**Comment by febs** [comment]
I've done all that and it's still broken. Bitwarden is selected among the options but then the login form is not filled.

**Comment by NicholasFlamy** [comment]
> I've done all that and it's still broken. Bitwarden is selected among the options but then the login form is not filled.

I have it happen all the time and I just reopen Brave and it works. It's a pain.
