### ISSUE TITLE
release for v2024.8.0 is missing?

### ISSUE THREAD

**Issue by masterflitzer** [bitwarden/android#3776]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

github repo / release page (https://github.com/bitwarden/android/releases) shows [v2024.6.0](https://github.com/bitwarden/android/releases/tag/v2024.6.0) as latest, but i got [v2024.8.0](https://github.com/bitwarden/android/releases/tag/v2024.8.0) via google play beta, the tag exists, but where is the release entry and the build artifacts for v2024.8.0?

### Expected Result

v2024.8.0 should have a release entry on github at this location: https://github.com/bitwarden/android/releases/tag/v2024.8.0

### Actual Result

v2024.8.0 tag is there, but no release (so no assets like apk and sha)

### Build Version

2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,
 We've since added an entry for this release here:  https://github.com/bitwarden/android/releases/tag/v2024.8.0
 
 Thanks!

**Comment by masterflitzer** [comment]
thank you very much, i appreciate the work, the app is beautiful
