### ISSUE TITLE
showing error while login "totp wrong"

### ISSUE THREAD

**Issue by olumolu** [bitwarden/android#3804]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to 'login give password'
2. Click on 'login and it will prompt you for totp after proving totp press login but it showing wrong totp
3. But same totp works in web bitwarden and old app.

### Expected Result

This should log in without any error.

### Actual Result

No issues should have shown it should logged into my account.

### Build Version

2024.8.0

### Environment Details

Motorola
Android 11

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by micahblut** [comment]
Duplices #3796
