### ISSUE TITLE
Android: Unlock with biometrics requires additional press

### ISSUE THREAD

**Issue by koehntopp** [bitwarden/android#3818]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

(As written in my previous bug report, I'm getting logged out a lot...)
When the locked out screen appears I need to authenticate

### Expected Result

As I have set "Use biometrics" I'm expecting the fingerprint / FaceID dialog to pop up immediately

### Actual Result

I'm presented with a screen that requires me to click "Use biometrics"

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/ff14bdd7-4eec-454e-8b11-da173f47d16e)

### Build Version

2024.8.0 (18985)

### Environment Details

Pixel 9 Pro XL

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Duplicate [#3724](https://github.com/bitwarden/android/issues/3724)
