### ISSUE TITLE
Black screen after vault unlock

### ISSUE THREAD

**Issue by Ehab-d** [bitwarden/android#3828]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open Bitwarden
2. Unlock the Vault

### Expected Result

My Vault screen appears instantly.

### Actual Result

A black screen appears before the My Vault screen opens.

### Screenshots or Videos

https://github.com/user-attachments/assets/3bb0ee79-93de-4599-b52e-90c0e6e2e660

### Build Version

v2024.8.0 (18985)

### Environment Details

OPPO Reno - Android 10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Ehab-d,

Thank you for reporting this. I tested this on Android 14 with Bitwarden 2024.8.0; I launched Bitwarden, tapped on (Use biometrics to unlock), touched the fingerprint sensor, and then the view transitioned to the (Vaults) menu, and I didn't see a black screen at any point in this process. I would recommend checking if a fresh new installation assists; Please uninstall Bitwarden off your Android device, turn your device off (long press) and back on, install Bitwarden anew from the Google Play Store, and test that once more. Please remember to activate all the supported Auto-Fill services as outlined here (https://bitwarden.com/help/auto-fill-android/). Additionally, bear in mind that the procedure to launch and unlock Bitwarden on a Pixel 5 was smoother and quicker overall, than what I saw in the video; So, this could be related to the device itself where it's taking slightly longer to decrypt the vault and render it locally; Please also check if you're able to update the operating system as that may assist.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Lastly, please consider editing the attached video and hiding any sensitive information, such as your Bitwarden account's email address and/or the vault items, just to be on the safe side.

Thank you again,
