### ISSUE TITLE
.zip releases break obtanium auto updates

### ISSUE THREAD

**Issue by jstride** [bitwarden/android#3836]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to Git Hub Releaae 
2. Click on Latest Version
3. Releaae packages are zipped
4. Go back to previous beta release
5. Releases are not zipped

### Expected Result

Release packages are apk

### Actual Result

Release packages are zipped containing apk

### Build Version

2024.08.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Hi @jstride. 2024.8.0 release artifacts have been corrected. Thank you for your report.
