### ISSUE TITLE
ios app won’t add attachments other than photos 

### ISSUE THREAD

**Issue by suyrulola** [bitwarden/android#385]
I’m trying to add a pdf attachment to a secure bitwarden note. The pdf file resides in the apple files app. 

1. create a secure note.
2. select “attachments@
3. select file
4. search
5. pick the pdf file (or any other)
6. now the filename should show but doesn’t. Nothing is attached.

Adding fotos from camera/ foto roll works however.

App is v1.19.0 (37), iphone with ios 12.

**Comment by kspearrin** [comment]
Do you have a premium membership?

**Comment by suyrulola** [comment]
Yes, premium is active.

**Comment by cfis** [comment]
I also have a premium membership and have the same issue.
iOS 12, iPhone X.  I am trying to upload a PDF file saved to the built in ios File App.

**Comment by ShirokaiLon** [comment]
Having a similar problem on the Android app. On Android 6.0.1.

Can add images through the Camera or Gallery apps just fine. But if I try to add a file (even an image) through the My Files/Documents view that first opens up, I'm taken back to the front page of the app and no file is attached.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/385
