### ISSUE TITLE
Face unlock missing

### ISSUE THREAD

**Issue by fredgolightly** [bitwarden/android#3868]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

In settings, biometrics is available+enabled and I have face recognition enabled & working on my device, yet no unlock with face biometrics option exists

### Expected Result

Be able to use face unlock, this was available in the old app

### Actual Result

No option

### Build Version

18985

### Environment Details

Samsung Tab S8 Ultra, Tab S9 Android 14
Pixel 8 Android 15

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello,

Will you first try uninstalling the application, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Let me know if that helps.

**Comment by fredgolightly** [comment]
All have been restarted and two I've reinstalled but all are the same, under Security, Unlock options, I have only two toggle options unlock with biometrics and unlock with pin. Where should the face option be? Thanks for the swift reply!

**Comment by qwexter** [comment]
@fredgolightly hi!
There are two types of face unlock exist in android - "weak" and "strong". "Weak" is the way when phone use only front camera to take a picture to decide is it you or not. "Strong" is when you have some depth or similar sensors, that can make a shot like 3d and use this 3d shot to decide is it you or not.
If I remember correctly Bitwarden app use only "strong" one. And I think it's usual for all banking apps and other high security things. Can you share you're phone model or check this setup by yourself?

**Comment by fredgolightly** [comment]
> @fredgolightly hi! There are two types of face unlock exist in android

Good point! The Pixel 8 has class 3/strong https://xcancel.com/MishaalRahman/status/1709594298981695734 I can't find info for the tablets so I'll assume not 3. My Pixel 8 unlocks my banking apps with my face automatically.

**Comment by Krychaz** [comment]
@fredgolightly Can you confirm that you are experiencing this issue both on your tablet and Pixel 8?

**Comment by fredgolightly** [comment]
> @fredgolightly Can you confirm that you are experiencing this issue both on your tablet and Pixel 8?

Yes, but I expect on the Tablets it's dueto biometrics not being class 3. My Pixel 8 has strong/class 3 face biometrics but there's no option for it in the BW app

**Comment by SergeantConfused** [comment]
Hello @fredgolightly,

Thank you for this report.
1. Were you able to use facial recognition as an unlock method in the legacy Bitwarden Android client (.NET)?
2. Were you able to use facial recognition as an unlock method on Android 14? I ask as you seem to be using a Beta operating system.

Thank you in advance,

**Comment by SergeantConfused** [comment]
Hello @fredgolightly,

Could you please try to unlock Bitwarden whilst the phone is held up to your face? You may need to touch the screen afterwards in order to be able to use facial recognition to unlock Bitwarden; The thumbprint animation on the fingerprint sensor would change to an unlocked lock and the message on-screen would be "Unlocked by face. Press to continue", if that's successful.

Thank you in advance,

**Comment by fredgolightly** [comment]
Updated to 19099 and it appears to work now, whether that fixed it or not I don't know. Thanks!
