### ISSUE TITLE
Cannot use/create passkeys with Mull

### ISSUE THREAD

**Issue by lucasmz-dev** [bitwarden/android#3949]
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Get Mull from F-Droid
2. Try creating a passkey with it on e.g. GitHub

### Expected Result

Successful creation and registration of the passkey

### Actual Result

Error about "not being a privileged browser" shows up.

### Additional Context

There are two versions of Mull, I haven't tested both; one is from F-Droid and built, verified/signed by F-Droid, and one comes from DivestOS' app repo.

This works fine in regular Firefox.

### Build Version

2024.8.1

### Environment Details

- Device: Moto G52 "rhode"
- System version: CalyxOS 5.11.1, Android 14

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by singhh9596** [comment]
+1. It doesn't work even with the add-on

**Comment by lucasmz-dev** [comment]
using the add-on would also be inconvenient af this is meant to work with android, really

**Comment by singhh9596** [comment]
> using the add-on would also be inconvenient af this is meant to work with android, really

Well, i tried with add on as well. It didn't work. Add-on is good for desktop but not for phones. Those pop-ups really spoils the browsing experience.  Anyways. I guess it only works with chrome. None of the passkeys works on browsers other than chrome

**Comment by lucasmz-dev** [comment]
@singhh9596 Can I ask what your setup is? Are you using stock Android?
To me, Bitwarden passkeys work for Firefox and forks, but not any Chromium based browsers at all even after changing the Android Credential Management flag. Mull has the extra issue of not being "privileged" which doesn't let me create passkeys.

microG passkeys do not work for me (neither would I want to use them, they're not backed up IG) due to https://gitlab.com/CalyxOS/calyxos/-/issues/2115

Also more on this issue from the CalyxOS side: https://gitlab.com/CalyxOS/calyxos/-/issues/2621

**Comment by SkewedZeppelin** [comment]
> There are two versions of Mull

they're identical

**Comment by singhh9596** [comment]
> @singhh9596 Can I ask what your setup is? Are you using stock Android? To me, Bitwarden passkeys work for Firefox and forks, but not any Chromium based browsers at all even after changing the Android Credential Management flag. Mull has the extra issue of not being "privileged" which doesn't let me create passkeys.
> 
> microG passkeys do not work for me (neither would I want to use them, they're not backed up IG) due to https://gitlab.com/CalyxOS/calyxos/-/issues/2115
> 
> Also more on this issue from the CalyxOS side: https://gitlab.com/CalyxOS/calyxos/-/issues/2621

I've 2 devices. One is running on oneUI and the other one is on stock android.  And I'm using mull (github version)

**Comment by lucasmz-dev** [comment]
> they're identical

They aren't signed the same though right? I would expect this to potentially be an issue if Bitwarden has to approve browsers

**Comment by SkewedZeppelin** [comment]
@lucasmz-dev 
fair, that is the only difference, otherwise they are the same codebase & variant

**Comment by SaintPatrck** [comment]
Thank you for reporting your issue. This is expected behavior. In order for Bitwarden to accept FIDO 2 requests from Mull (or any other browser) on behalf of other relying parties, it must be included in our list of known privileged applications.[^1] This is in accordance with the Android Credential Manager integration guidelines regarding privileged applications.[^2]

[^1]: [fido2_privileged_allow_list.json](https://github.com/bitwarden/android/blob/main/app/src/main/assets/fido2_privileged_allow_list.json)

[^2]: [Credential Provider - Obtain an allowlist of privileged apps](https://developer.android.com/identity/sign-in/credential-provider#obtain-allowlist)

**Comment by SkewedZeppelin** [comment]
You might also consider adding Fennec F-Droid too of which I co-maintain, it is also already in the autofill list.
```
    {
      "type": "android",
      "info": {
        "package_name": "org.mozilla.fennec_fdroid",
        "signatures": [
          {
            "build": "release",
            "cert_fingerprint_sha256": "06:66:53:58:EF:D8:BA:05:BE:23:6A:47:A1:2C:B0:95:8D:7D:75:DD:93:9D:77:C2:B3:1F:53:98:53:7E:BD:C5"
          }
        ]
      }
    },
```

key is from the F-Droid.org built/signed version:
- https://f-droid.org/repo/org.mozilla.fennec_fdroid_1290200.apk

**Comment by lucasmz-dev** [comment]
Before just creating passkeys didn't work, now, it seems using them is also not working. I guess that was just a bug in the specification in the previous version of the Bitwarden beta native app.

Please do add these to the allowlist. Mull is a great browser, trusted by many. It is *the* chosen one for anyone using anything like Arkenfox on the desktop.

**Comment by lucasmz-dev** [comment]
@SaintPatrck Maybe it'd make sense to re-open this since there would still be the need for this to implemented in the code?

**Comment by singhh9596** [comment]
![Screenshot_20241116_132813_Mull](https://github.com/user-attachments/assets/de476956-859c-4108-9aaa-9f22b47ed1e5)

Not completely but passkey is somewhat working now at least on some sites

**Comment by singhh9596** [comment]
Working fine on android 14 now
