### ISSUE TITLE
Push Notifications don't work 

### ISSUE THREAD

**Issue by dnewsholme** [bitwarden/android#3966]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open Android app click logins to view all logins
2. Edit a login name on a separate client such as web client.
3. Item should automatically update on android client using push notifications but doesn't update unless manually synced.

### Expected Result

Items should automatically update within a few seconds from a push notification to the android client.

### Actual Result

Items don't update unless synced manually.

### Build Version

2024.8.1(19099)

### Environment Details

Client Device: Google Pixel 9  Pro XL

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by NicholasFlamy** [comment]
Is this with the Google Play Beta or the GitHub apk?

I'd question if it (similarly to the old app) only works with the Google Play app.

**Comment by dnewsholme** [comment]
It's with the Google play store beta app. Strangely the device login push
notifications do work. Just the push updates against password entries do
not.

**Comment by NicholasFlamy** [comment]
You're using the Official Bitwarden service, not self-hosted, correct?

(If so, then I don't know what's up.)

(Another thing to check is whether you're using any VPNs or other things that affect networking.)

**Comment by dnewsholme** [comment]
Yeah this is with the official server on vault.bitwarden.com without any
VPN.

**Comment by leftcausedit** [comment]
same issue, this is my fcm diagnose
```
09-30 00:58:53.514 net=1: Received com.x8bit.bitwarden 0:1727629133884291%25627aa4f9fd7ecd
09-30 00:58:53.583 net=1: Acked com.x8bit.bitwarden:0 0:1727629133884291%25627aa4f9fd7ecd
09-30 00:58:53.601 net=1: Successful broadcast to com.x8bit.bitwarden (id=0:1727629133884291%25627aa4f9fd7ecd time=58ms priority=NORMAL)
09-30 00:58:53.602 net=1: Message handled com.x8bit.bitwarden:0 0:1727629133884291%25627aa4f9fd7ecd
```
by the way, push update works will on my ipad

**Comment by SaintPatrck** [comment]
Hi all. Thank you for reporting your issue. The behavior you're describing is expected. The Beta builds do not currently support push notifications from other clients. You can still trigger vault sync via the overflow menu or by enabling swipe-to-refresh syncing in Settings.
