### ISSUE TITLE
iPhone XS Max UI overlap

### ISSUE THREAD

**Issue by lethenju** [bitwarden/android#397]
"cancel" button overlaps system time on the top of the screen on iPhone XS Max on "search vault" screen.

**Comment by lethenju** [comment]
Screenshot : https://imgur.com/a/lJEK3ol

**Comment by lethenju** [comment]
Screenshot : https://imgur.com/a/lJEK3ol

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/397
