### ISSUE TITLE
HSBC Mobile Banking app will not run with "Use accessibility" turned on

### ISSUE THREAD

**Issue by BJReplay** [bitwarden/android#4004]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to Settings
2. Click on Auto-fill
3. Click on Use accessibility 
4. Open HSBC AU banking app

### Expected Result

Banking app runs as it does when Bitwarden legacy has accessibility enabled. 

### Actual Result

Error message noting that app is blocked due to Bitwarden Beta Accessibility. Disable accessibility or remove the app to use HSBC Banking. 

### Screenshots or Videos

Not possible - blocked by banking app. 

### Additional Context

App details: https://play.google.com/store/apps/details?id=au.com.hsbc.hsbcaustralia

Bitwarden Beta version (running late build to debug passkey issues): 2024.9.0 (19213)

### Build Version

2024.9.0 (19213)

### Environment Details

Samsung SM-S908E S22U
One UI 6

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
The Quick Tile is absent in version 2024.8.0 because it depended on Accessibility Services, which Google has been urging developers to move away from. The engineering team is currently evaluating the situation to determine if it can be reintroduced.

**Comment by BJReplay** [comment]
@BBGhub please note version reported in this issue: 2024.9.0 (19213).

The bug report is not that the tile is missing, but that another app will not run when accessibility is enabled.
