### ISSUE TITLE
Password update problem

### ISSUE THREAD

**Issue by leobel96** [bitwarden/android#402]
When I update a password for an app (I tried it using Amazon app on Android) a new element is created instead of update the Amazon one. It would be great if the app would recognise the same URL and update the already existing element instead of create a new one.

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta?

**Comment by leobel96** [comment]
I am a beta tester but the newest version on PlayStore is 1.22.1. Do you mean this one?

**Comment by kspearrin** [comment]
v2.0 was just released. It might take a little while to propagate.

**Comment by leobel96** [comment]
I've tried the version 2.0 with Amazon app. If I manually write mail and password Bitwarden suggests me to save them. If I decide to save them, a new item is added in the logins list and no option to update an existing login appear nor It automatically recognizes that a login with the same URL already exists.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/402
