### ISSUE TITLE
[BUG] Bitwarden Beta can't save Android App‘s password correctly

### ISSUE THREAD

**Issue by chuwza** [bitwarden/android#4082]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to an Android App
2. Enter the App's account password
3. Save the password by Bitwarden Beta
4. Log out of the app and log back in
5. The password you just saved is not displayed

### Expected Result

Saved passwords can be associated with the app

### Actual Result

As you can see in video, passwords saved by Bitwarden Beta can't be used by auto-fill, and I've found the reason why:

Bitwarden Beta is missing a string “androidapp://” when saving passwords, as shown in the picture, the right side of the picture associates the app with the password, which is OK (right app is KeyGuard, an alternative client for the Bitwarden) (https://github.com/AChep/keyguard-app), but the left side of the picture has the Bitwarden Beta does not associate the app with the password when saving the password. I can't see the “androidapp://” string even when I click the settings icon for that URI.

So passwords saved through Bitwarden Beta are not actually available, only in browsers, but not for Android Apps.

### Screenshots or Videos

VIDEO IS HERE

https://github.com/user-attachments/assets/11ab30fb-0495-477a-8204-bde995a13252

PIcture
![IMG_20241012_204326](https://github.com/user-attachments/assets/8209a4a8-12f3-4452-9781-f715a9e75b49)

### Additional Context

I use the official Bitwarden Beta, official server

### Build Version

© Bitwarden Inc. 2015-2024 Version: 2024.9.0 (19209)

### Environment Details

Any device
Any OS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by chuwza** [comment]
> @chuwza Hi there sounds like its fixed tyr the new release 2024.11.3 (19432)

Sorry, I test the 2024.11.3 (19432), The bug has not been fixed🥲
![Screenshot_20241112-185444_Bitwarden_Beta~2](https://github.com/user-attachments/assets/93b274bc-b727-473f-a249-cbbb982de0fb)

**Comment by Gammachange** [comment]
I confirm its new work on the new release
2024.11.3 (19432)
Sounds like its just for you!

**Comment by chuwza** [comment]
> @chuwza I confirm its new work on the new release 2024.11.3 (19432) Sounds like its just for you! See here - https://github.com/user-attachments/assets/d8bf67d3-0845-4b19-b27e-3caaed5e7e34
> 
> and here -
> 
>  ScreenRecording_20241112_111947.mp4

Yes, I repeated your steps and in this case the bug was indeed fixed.

https://github.com/user-attachments/assets/a5f1cf24-5790-447c-b58a-dc26efde1c57


However, in the case of ‘After entering the password for the app, Bitwarden pops up an autosave prompt and selects save’, the bug is still not fixed.

https://github.com/user-attachments/assets/da680afa-a29b-4ef8-8f24-3c670498362e



In other words, the bug is half fixed😂😥

**Comment by maxmini1** [comment]
I think merge this pull request well fixed! https://github.com/bitwarden/android/pull/4420

**Comment by chuwza** [comment]
> I think merge this pull request well fixed! #4420

Glad to hear this, let's wait for the next update😆

**Comment by Git-Boy-Slim** [comment]
Unfortunately I still have the exact same behaviour of not saving the `androidapp://` part in front of the URI of newly entered login details when prompted by the Bitwarden pop-up. 

I experienced this with multiple apps but just tested it with `de.rossmann.app.android` and `se.parkster.client.android` and both did not save with with the androidapp scheme. 

I'm using version `2024.12.0`

**Comment by chuwza** [comment]
> Unfortunately I still have the exact same behaviour of not saving the `androidapp://` part in front of the URI of newly entered login details when prompted by the Bitwarden pop-up.
> 
> I experienced this with multiple apps but just tested it with `de.rossmann.app.android` and `se.parkster.client.android` and both did not save with with the androidapp scheme.
> 
> I'm using version `2024.12.0`

You are right. In version 2024.12.0, after my testing, I can confirm that the BUG has not been fixed.

However, this may just be because the 2024.12.0 version did not merge this fix. (#4420)

In short, the BUG has not been fixed. Could you please reopen this issue? @aj-rosado

**Comment by chuwza** [comment]
In my test, this bug has been fixed in in 2025.1.0 😄
![Screenshot_20250111-070035_Bitwarden_Beta](https://github.com/user-attachments/assets/262dd204-8da6-4cda-8a54-2cd6ec7fd61c)
![Screenshot_20250111-070058_Bitwarden_Beta](https://github.com/user-attachments/assets/ef76a057-9ea3-4a24-846d-8824c36d4330)
