### ISSUE TITLE
Need to update F-Droid repo

### ISSUE THREAD

**Issue by AntiWorkIncel** [bitwarden/android#4086]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. add the repo

### Expected Result

It should work

### Actual Result

The key is expired.

### Build Version

idk

### Environment Details

Just update it, it's not working.

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by AntiWorkIncel** [comment]
> Still nothing. The stable release channel is still overwritten by the beta branch, even though the beta repo is available on its own by now.

Idk. I've just checked it hour ago and now it's working with the stable version.
Maybe you need to remove and re-enable the repo.
