### ISSUE TITLE
Autofill not working with external keyboard

### ISSUE THREAD

**Issue by tiptruck** [bitwarden/android#4094]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Connect external bluetooth keyboard.
Goto any site that requires a login

### Expected Result

An overlay is presented to allow the autofill.  Or some other method such as a notification

### Actual Result

There is no way to commence autofill as the soft keyboard is not available and no overlay is presented.

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.9.0 (19209)

### Environment Details

Samsung Tab S7
Android 13

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by singhh9596** [comment]
On heliboard it's working.

**Comment by SergeantConfused** [comment]
Hello @tiptruck,

Thank you for reporting this. I tested this on Android 12 and Android 14 with Gboard installed, and in both cases I was shown a bubble next to the text field that I tapped on which allowed me to display the on-screen keyboard; When using Samsung keyboard, tapping on Username/Password field caused the on-screen keyboard to appear even when a Bluetooth keyboard was paired with and connected to the device. Once the on-screen keyboard was shown, the Inline autofill menu was accessible. I'd recommend testing this with a different on-screen keyboard, or rebooting the device as that may assist.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
