### ISSUE TITLE
Android Beta doesn't save password history for hidden-custom fields.

### ISSUE THREAD

**Issue by starktower007** [bitwarden/android#4131]
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Create a login and add username, password, a hidden-custom field and a value in it.
2. Edit the hidden field value and save it.
3. Check the password history to see that the old value from the hidden field was not saved in the history.

### Expected Result

Old value from the hidden field is saved in the password history in all other clients.

### Actual Result

Old value from the hidden field was not saved in the password history. This could potentially lead to data loss as hidden fields are used for sensitive data like a password.

### Screenshots or Videos

https://github.com/user-attachments/assets/4ad1d3bf-d8c8-4b3b-9a0d-c363e4317057

https://github.com/user-attachments/assets/d099b58f-6116-4855-9312-faa42fb59f1a

https://github.com/user-attachments/assets/1cae9efc-99da-4c8f-b456-0d87581535c2

https://github.com/user-attachments/assets/02007819-42d3-42df-8ce2-aa9b03be7bbb

### Build Version

2024.9.0-beta (19209)

### Environment Details

Device - Oneplus 9R
OS Version - Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by starktower007** [comment]
This functional regression has been seen since the move away from Xamarin.

**Comment by rajatkshaju** [comment]
Fixed herehttps://github.com/bitwarden/android/pull/4047

**Comment by starktower007** [comment]
Fixed in release - 2024.10.1 (19388)

https://github.com/bitwarden/android/pull/4047
