### ISSUE TITLE
If the uri contains port information when selecting host matching, the mobile client cannot pop up the correct auto fill option

### ISSUE THREAD

**Issue by qiaoyun680** [bitwarden/android#4138]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. URI match select HOST
2. URI contain port like xxx.com:1443
3. visit xxx.com:1443
4. pop up the selection dont have the right info

### Expected Result

pop up the right account info

### Actual Result

dont have account info
Only corresponding to xxx.com can be matched.

### Build Version

2024.9.0 (19209)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by qiaoyun680** [comment]
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and I have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

1. open websit like 192.168.5.7:5700 ( or domain:port )
![1](https://github.com/user-attachments/assets/d22e9391-7c15-495f-8cf9-c22ccb8f8c3a)

2. There will be pop-up options, but the URL for this option is 192.168.5.6, not matching 192.158.5.6:5700. Additionally, the URI for the newly saved project is also 192.168.5.6, not 192.158.5.6:5700. I believe the port number is not being considered, and the browser extension version is not at fault.
![2](https://github.com/user-attachments/assets/0d074020-f3e6-4fa6-b747-e7de6cc64672)
![3](https://github.com/user-attachments/assets/77ae9205-1b4a-44f9-9f35-e98692ad7bb3)
![4](https://github.com/user-attachments/assets/7044e12c-338d-4896-8dd7-5c8033b09006)
