### ISSUE TITLE
iOS app requires login when already set up

### ISSUE THREAD

**Issue by colinator19** [bitwarden/android#419]
Every now and then (often enough to be a pain...) it appears that I have to login again on Bitwarden.
When I open the app, it does unlock with FaceID but it also states I can register or login while that was already done before.

Expected behaviour would be for the app to open the password library after validating via FaceID.

Once I press login; it did remember my email address but I have to put in the password again. It will work for a while but then suddely it wants me to login again even while FaceID still works (as it shows to do FaceID validation) but does not login again.

App Version: 1.20.0 (43)
iPhone X
iOS: 12.1
Self Hosted Bitwarden
Version: 2.5.0

Screens attached:
![faceid_unlock](https://user-images.githubusercontent.com/15741333/49256738-48b18080-f430-11e8-82fb-ea2503459b23.PNG)

![after_faceid_unlock](https://user-images.githubusercontent.com/15741333/49256740-4bac7100-f430-11e8-8314-9833c8449f95.PNG)

**Comment by kspearrin** [comment]
Weird. I have never seen this happen with TouchID. How often does this occur?

**Comment by colinerd** [comment]
About 2/3 times a week but it is really random and depends on how often I use the app. I have not been able to put my finger on what scenarios this is being triggerd.

I believe the auto-fill function in iOS 12 is not being affected by this issue, it is always working. Looks like it is really upon opening the app intermittendly.

**Comment by colinerd** [comment]
It appears I have the same issue on my iPad Pro 2 which uses Touch ID. Just wanted to add it here.
I did however found something interesting - Without filling in my account details again, if I force close the app and reopen, it works and opens my safe correctly after Touch ID.

I also think I might know when this will occur, if you have used the app and then move to another app, after a while of inactivity, it will show this issue once you reopen it. I believe iOS does something to apps in the background that have not been used for a while to free up memory, I think this is the point where this issue might occur.

Just throwing in here what I know and see, hopefully to find the cause of this or atleast help for you to find the cause.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/419
