### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by rrha** [bitwarden/android#4192]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

2. Click on '...'
3. Scroll down to '...'
4. Click on '...'

### Expected Result

Application opens

### Actual Result

Application crashes before launching

### Screenshots or Videos

https://github.com/user-attachments/assets/2adfda6b-5442-4adf-9745-5cdf6c347e77

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.10.1 (19388)

### Environment Details

Redmi Note 10 
android 13 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Thanks for reporting this today - this issue has been previously reported, and you can track the issue’s progress at the link below.

GitHub: https://github.com/bitwarden/android/issues/4191

A current workaround is to open Settings → Apps → Bitwarden → Storage and cache for me, then tap on both Clear storage and Clear cache, then log back into the app once more. Alternatively, you can also uninstall, then re-install the app to resolve this.
