### ISSUE TITLE
Release 2024.10.1 mentions iOS release instead of Android

### ISSUE THREAD

**Issue by lucasmz-dev** [bitwarden/android#4193]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to GitHub releases

### Expected Result

2024.10.1 should say "native Android release"

### Actual Result

2024.10.1 days "iOS release"

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BJReplay** [comment]
Tagging @vvolkgang who made the release hoping for a quick edit.
