### ISSUE TITLE
DuckDuckGo email generation error

### ISSUE THREAD

**Issue by ExtendedGuru4883** [bitwarden/android#4207]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Update to v2024.10.2
2. Try generating a DuckDuckGo email alias (valid API key, working in other versions of Bitwarden)

### Expected Result

A DuckDuckGo email alias is generated

### Actual Result

Get error message "error sending request for url (https://quack.duckduckgo.com/api/email/addresses)

### Build Version

2024.10.2

### Environment Details

- Device: Xiaomi Redmi Note 12 Pro 5G (22101316G)
- Android version: 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/android/issues/4205

**Comment by ExtendedGuru4883** [comment]
> Duplicate of #4205

Sorry didn't see it
