### ISSUE TITLE
2024.11.0 Crash

### ISSUE THREAD

**Issue by pcartwright81** [bitwarden/android#4223]
### Steps To Reproduce

Open the app. Put finger on scanner. Crash.
Everything was working on the previous version. 

### Expected Result

Open the app. Put finger on scanner.  App unlocks. 

### Actual Result

Open the app. Put finger on scanner. Crash.
Everything was working on the previous version. 

### Additional Context

Clearing cache does not fix the issue, but clearing storage does 

### Build Version

2024.11.0

### What server are you connecting to?

US

### Environment Details

Pixel 9 pro XL Android 15

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Vstory** [comment]
Same error, here is the crash log.

`Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: M2102K1AC
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 10215
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.x8bit.bitwarden
[Version Name]: 2024.11.0
[Version Code]: 19415
[Target SDK]: 34
[Min SDK]: 29
[Error Type]: JVM
[Crash Time]: 2024-11-04T10:14:03.624
[Stack Trace]:
java.lang.NullPointerException: Attempt to read from field 'java.lang.String P7.c.b' on a null object reference in method 'java.lang.Object J7.o.invokeSuspend(java.lang.Object)'
	at J7.o.invokeSuspend(Unknown Source:11)
	at Gb.a.resumeWith(Unknown Source:7)
	at bc.K.run(Unknown Source:106)
	at ic.b.run(Unknown Source:126)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [s0{Cancelling}@bad453f, Dispatchers.Unconfined]`

**Comment by differsthecat** [comment]
Hi @pcartwright81 , @Vstory, we are actively looking into this and are having a hard time diagnosing what could be the issue. Can you provide more info to help us investigate?

1. What login/unlock methods are you using? Biometrics? 
2. Do you have 2fa enabled?
3. Do you have multiple accounts?
4. What environment are you connecting to? (US cloud, EU cloud, or self-hosted) 

If you don't want to share this publicly, you can contact our support team directly [here](https://bitwarden.com/contact/) or by emailing support@bitwarden.com.

**Comment by pcartwright81** [comment]
1 Biometrics
2 Yes 2FA
3 Only 1 Account
4 US Prod

**Comment by Vstory** [comment]
> Same error, here is the crash log.
> 
> ```
> Generated by AppErrorsTracking 1.3(6)
> Project URL: https://github.com/KitsunePie/AppErrorsTracking
> [Device Brand]: Xiaomi
> [Device Model]: M2102K1AC
> [Display]: TKQ1.220829.002 test-keys
> [Android Version]: 13
> [Android API Level]: 33
> [System Locale]: zh_CN
> [Process ID]: 10215
> [User ID]: 0
> [CPU ABI]: arm64-v8a
> [Package Name]: com.x8bit.bitwarden
> [Version Name]: 2024.11.0
> [Version Code]: 19415
> [Target SDK]: 34
> [Min SDK]: 29
> [Error Type]: JVM
> [Crash Time]: 2024-11-04T10:14:03.624
> [Stack Trace]:
> java.lang.NullPointerException: Attempt to read from field 'java.lang.String P7.c.b' on a null object reference in method 'java.lang.Object J7.o.invokeSuspend(java.lang.Object)'
> 	at J7.o.invokeSuspend(Unknown Source:11)
> 	at Gb.a.resumeWith(Unknown Source:7)
> 	at bc.K.run(Unknown Source:106)
> 	at ic.b.run(Unknown Source:126)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [s0{Cancelling}@bad453f, Dispatchers.Unconfined]
> ```

When using autofill, the app crashes after jumping to unlock the vault and verifying the fingerprint.

**Comment by Vstory** [comment]
> 1. What login/unlock methods are you using? Biometrics?

Yes

> 2. Do you have 2fa enabled?

No

> 3. Do you have multiple accounts?

900+

> 4. What environment are you connecting to? (US cloud, EU cloud, or self-hosted)

Us Cloud

**Comment by differsthecat** [comment]
Thank you all for the info; it has been very helpful!

We believe we have fixed this with #4231, which has been released in version `2024.11.1`.

**Comment by pcartwright81** [comment]
Thanks, I was wondering if this was only a me issue.

**Comment by pcartwright81** [comment]
This version is a complete rewrite from C# to a native Kotlin app.  A bug fix for infinite loading was pushed yesterday and I thought I was commenting on that one.  I can't remember getting no items before yesterday.
