### ISSUE TITLE
2024.11.1 is missing from releases and never made it to beta

### ISSUE THREAD

**Issue by uniquePWD** [bitwarden/android#4234]
### Steps To Reproduce

Check what version each release is using 

### Expected Result

2024.11.1 should be in the release list and Beta should be on 2024.11.1 too.

### Actual Result

Beta is on 2024.9.0

### Build Version

2024.9.0

### What server are you connecting to?

EU

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Thank you for reporting this! It has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by SaintPatrck** [comment]
Hi @uniquePWD,

Releases 2024.11.0 and 2024.11.1 have been created. Thank you for bringing this to our attention.

**Comment by gokulkgm** [comment]
Hi @SaintPatrck ,

Will the "Bitwarden Beta" app continue to receive updates for future releases, or is it planned to be discontinued?

https://play.google.com/store/apps/details?id=com.x8bit.bitwarden.beta
