### ISSUE TITLE
Android client does not retain settings after logout

### ISSUE THREAD

**Issue by raidenii** [bitwarden/android#4241]
### Steps To Reproduce

1. Go to settings and change some user setting, e.g., others->clear clipboard to 30s
2. Click logout from 3-dot menu after vault is locked
3. Log back into Bitwarden
4. Check settings

### Expected Result

The client settings should retain.

### Actual Result

Client settings are reverted to default.

### Build Version

2024.11.1

### What server are you connecting to?

Self-host

### Self-host Server Version

Vaultwarden latest

### Environment Details

Pixel 7 Android 15

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Hi @raidenii,

Thank you for reporting your issue. The behavior you're describing is expected. When a user logs out all of their device specific settings, like vault timeout, are cleared. If you lock your vault instead of logging out, your settings will be retained when the vault is unlocked.
