### ISSUE TITLE
Creating a new vault item - "password" generator shows no option for "passphrases"

### ISSUE THREAD

**Issue by pamperer562580892423** [bitwarden/android#4261]
### Steps To Reproduce

Open the Bitwarden mobile app.
Press the "+" for adding a new vault item.
Tap on the generator symbol for "passwords".
The generator for "passwords" opens correctly, but there is no option for choosing "passphrases" instead.

### Expected Result

There should be an option to alternatively get a passphrase generated.

### Actual Result

There is no option to change from "password generator" to "passphrase generator".

### Screenshots or Videos

No option to change to "passphrases" available here:

![Screenshot_20241108-130033](https://github.com/user-attachments/assets/e91ddd50-4562-4699-845c-ebfe573f7549)

### Build Version

2024.10.2 (19397)

### What server are you connecting to?

EU

### Environment Details

Fairphone 5, Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maxmini1** [comment]
@pamperer562580892423: see the new release
https://github.com/bitwarden/android/releases/tag/v2024.11.3

**Comment by pamperer562580892423** [comment]
@maxmini1 Thanks, but your screenshot shows the general "Generator tab" - and that looks the same for me now already. Please read my "steps to reproduce" again. If you try to add a new vault item and open the generator from there - right from the "password" field - then there is no option to change to passphrases for me. If that was changed with the 2024.11.3, that would be nice - but I don't see a corresponding pull request in the changelogs since the 2024.10.2. Maybe you can check that?

(BTW I didn't update to 2024.11.3 already because I wanted to wait for the official PlayStore updates now because of the accessibility / quick tile feature which - as I just learned these days - doesn't work with a manual update via the apk.)

**Comment by maxmini1** [comment]
> @maxmini1 Thanks, but your screenshot shows the general “Generator tab” - and that looks the same for me now already (so in the general “Generator” tab I also have the option to choose between password, passphrase and username). Please read my "steps to reproduce" again, since it wasn't about the general "Generator tab". If you try to add a new vault item and open the generator from there - right from the “password” field - then there is no option to change to passwords for me. 
> 
@pamperer562580892423 : i see its my fault, the issue its still there in the new releases 
https://github.com/bitwarden/android/releases/tag/v2024.11.3
![Screenshot_20241108_160703_Bitwarden Beta](https://github.com/user-attachments/assets/597a95c3-fad2-4b9d-8bcc-86d283247b5d)
> 
> BTW I didn't update to 2024.11.3 already because I wanted to wait for the official PlayStore updates now because of the accessibility / quick tile feature which - as I just learned these days - 
 doesn't work with a manual update via the 
> apk.)
Quick thing here is that the new accessibility/quick tiles feature works perfectly at least for me!
