### ISSUE TITLE
Password Manager: install fails (NO_MATCHING_ABIS)

### ISSUE THREAD

**Issue by nofishonfriday** [bitwarden/android#4298]
### Steps To Reproduce

I try to install from Aurora store, as I use a Google free phone.

### Expected Result

Installation works.

### Actual Result

Installation refuses with below error message.

### Screenshots or Videos

![screenshot](https://github.com/user-attachments/assets/f6ae92b1-10fa-4db9-ac43-ec34bb406c4e)

### Build Version

-

### What server are you connecting to?

US

### Environment Details

Galaxy S4 mini, LineageOS19 (Android 12) microG (Google free), Magisk (root)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We recommend signing out of Aurora and signing back in to refresh your session, as the session key might be stale or invalid. A team member tested this and confirmed they are seeing version 2024.11.5, while you are currently seeing version 2024.10.0. This discrepancy could indicate a session-related issue.

Let us know how it goes!

**Comment by Gammachange** [comment]
> Hey, thanks for the fast reply, appreciated. I tried what you suggested (sign out/in, even several times), but for some reason I can still only see version 2024.10.0. But could you tell me the version code (the number seen in brackets in the screenshot) for 2024.11.5, then I could try to manually download this version from Aurora.
> 
> edit: Hm...on GitHub the latest release seems also [2024.10.0](https://github.com/bitwarden/mobile/releases), so where is 2024.11.5 coming from?

Th new release on github its 2024.11.5 (19461)

**Comment by Greenderella** [comment]
Should be [2024.11.5 (19461) ](https://github.com/bitwarden/android/releases/tag/v2024.11.5)

![image](https://github.com/user-attachments/assets/fa368cdf-8a35-4f47-afd4-ed9693a3038e)

**Comment by Gammachange** [comment]
> > Hey, thanks for the fast reply, appreciated. I tried what you suggested (sign out/in, even several times), but for some reason I can still only see version 2024.10.0. But could you tell me the version code (the number seen in brackets in the screenshot) for 2024.11.5, then I could try to manually download this version from Aurora.
> > edit: Hm...on GitHub the latest release seems also [2024.10.0](https://github.com/bitwarden/mobile/releases), so where is 2024.11.5 coming from?
> 
@nofishonfriday 
> Th new release on github its 2024.11.5 (19461)

**Comment by nofishonfriday** [comment]
update: Meanwhile I found the 2024.11.5 APK on an APK hosting site, and installing this version worked!
Thanks again for the help.
Closing the issue.
