### ISSUE TITLE
Android: Does Not Indicate You Need Premium To Add Attachments

### ISSUE THREAD

**Issue by Noah-Huppert** [bitwarden/android#430]
The Android app does not notify you that a premium membership is required to upload attachments.  
Instead it will let you pick a file but there will not be an upload button.  
This left me confused.  

I only learned about the premium membership requirement when I tried uploading a file via the browser extension and a pop-up displayed.

**Comment by kspearrin** [comment]
Unfortunately the app stores won't allow us to show notifications about paid features since we do not currently accept in-app payments.

**Comment by Noah-Huppert** [comment]
Interesting.  
It would be nice if there was some way of making the process a bit less confusing.  
Perhaps by removing the upload screen if you don't have pro?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/430
