### ISSUE TITLE
Latest version (2024.11.5) not available on F-Droid

### ISSUE THREAD

**Issue by vinnyperella** [bitwarden/android#4342]
### Steps To Reproduce

Go on F-Droid and search for Bitwarden and look at the available versions.

### Expected Result

2024.11.5 is available on F-Droid.

### Actual Result

Latest version on F-Droid is 2024.11.3, 2024.11.5 has been out for more than a week.

### Build Version

2024.11.3

### What server are you connecting to?

US

### Self-host Server Version

2024.11.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Felitendo** [comment]
F-Droid will always be behind in term of updates. If you want the latest update "on release" then you can use Obtanium to always be up to date with the latest version when it releases here on GitHub

**Comment by jtodddd** [comment]
Hi there,
Thank you for your report! It has been escalated for further investigation. If you have more information that can help us, please add it below.
Thanks!

**Comment by singhh9596** [comment]
Good thing. Passkey is broken on the build available on github

**Comment by cesaryuan** [comment]
@jtodddd As I can see, the workflow `fdroid.yml` in https://github.com/bitwarden/f-droid has broken, which causes this bug.

Looks like there is an error when installing fdroid-server in action.

![image](https://github.com/user-attachments/assets/8af3fcae-67a4-466a-bab8-05e94def1489)

![image](https://github.com/user-attachments/assets/f73d3735-d994-45b9-9bd1-37e56d22f374)

**Comment by singhh9596** [comment]
24.11.7 isn't available on fdroid as well.

**Comment by SaintPatrck** [comment]
All versions of Bitwarden are now available in our official F-Droid repo.
