### ISSUE TITLE
Firefox Nightly is "not privileged" for Passkeys

### ISSUE THREAD

**Issue by ido1901** [bitwarden/android#4352]
### Steps To Reproduce

1. Try to login to any website with passkey
2. Unlock the vault with fingerprint

### Expected Result

Choose my account and login

### Actual Result

Bitwarden gives an error: "Passkey operation failed because browser is not privileged".

### Additional Context

Passkeys work just fine with stable Firefox.

### Build Version

2024.11.5

### What server are you connecting to?

US

### Environment Details

Galaxy S22, Android 14 OneUI 6.1.1, Firefox nightly 134.0a1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi @segln

Hi there,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for desktop environments (https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated Android client (https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

This issue will now be closed.
Thanks!
