### ISSUE TITLE
App logs me out if vault is unreachable

### ISSUE THREAD

**Issue by yurividal** [bitwarden/android#4366]
### Steps To Reproduce

I self-host Bitwarden. Never had a problem with the old version of the android app. With the beta, I have realized that if my vault is unreachable, for example if my server went down for a few minutes, the Android app logs me out.
Next time I open the app, I have to log back in with my master password. Strangely, it doesn't request any 2FA for this re-login.
I also have to go to the settings and re-enable biometric login every time this happens. 

### Expected Result

Same behavior as old app. App keeps logged in even if vault is temporarily unavailable. 

### Actual Result

I have to login all over again. 

### Build Version

Latest

### What server are you connecting to?

Self-host

### Self-host Server Version

Latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by yurividal** [comment]
Steps to reproduce:

- Open the beta android app 
- sync the vault. sync works fine.
- go to reverse proxy and disable the bitwarden proxy (to simulate server being down)
- open beta android app. wait for it to try to sync, or force a sync
- exit out of the app
- re-enable bitwarden on the reverse proxy
- open the android app again. it will be logged out. User needs to enter master password again to log back in. All settings are also lost, so user needs to re-enable biometrics, and any other settings they had before.

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by ad-on-is** [comment]
I have exactly the same issue.

I was wondering why the app keeps me asking for a master password randomly. 

Wow! Given that my self-hosted server runs on a Ryzen mini PC, which is known to experience random restarts without any reason, this very much explains the problem.

**Comment by yurividal** [comment]
[Some users on Reddit](https://www.reddit.com/r/Bitwarden/s/jTnnWrks4d) are reporting this issue happens even on non-self-hosted.

**Comment by fedonr** [comment]
Same, I had 3 accounts on Biometric, it would unlock once with Biometric (when server is offline) but in few seconds it would throw error message (stays logged in). Close the from Recents and open it again, it'll be logged out. Same with all 3 accounts

**Comment by krasen1234** [comment]
Same issue only on Android, I changed proxy, host etc , keep having the issue

**Comment by Buenno** [comment]
I'm also experiencing this issue. I'm running wireguard in order to access my self-hosted infra, but my work network blocks wireguard traffic. This causes my server to become unreachable, and my bit locked account to disconnect.

**Comment by yurividal** [comment]
Is this bug just going to keep being ignored by the Bitwarden team? So far, not even an acknowledgement from the developers...

**Comment by krasen1234** [comment]
Works perfectly fine on other devices, I have 10 users and all problem with Android app

**Comment by curtis-livefront** [comment]
If you are still experiencing this issue, please share the following details.

1. App Version: Which version of the app are you currently using?
2. Log Out Behavior: Are you experiencing a soft logout (where some settings persist) or a hard logout (where all settings, including biometric login, are reset)?
3. Confirm your environment: Are you experiencing this on Bitwarden.com or another environment?

**Comment by krasen1234** [comment]
> If you are still experiencing this issue, please share the following details.
> 
> 1. App Version: Which version of the app are you currently using?
> 2. Log Out Behavior: Are you experiencing a soft logout (where some settings persist) or a hard logout (where all settings, including biometric login, are reset)?
> 3. Confirm your environment: Are you experiencing this on Bitwarden.com or another environment?

1. All versions since the stupid UI and design change was done. Was fine before
2. All is reset. Need to change the settings again
3. Self hosted, tried several different proxys and even bare

**Comment by yurividal** [comment]
Same here. Every version since thr UI refresh.
If I'm offline, or my self-histed vault is unreachable, even for a few minutes, the bitwarden app completely resets.
Logs me out, and resets all the settings.
I then have to login again. Strangely enough, it doesn't request 2FA when logging back in, so at least the session tokens are being saved.

**Comment by fedonr** [comment]
Seems to be fixed in v2024.11.7, I tried the update and it doesn't log me  out anymore, like it did earlier even when self-hosted instance is offline.

**Comment by curtis-livefront** [comment]
@yurividal What is the latest version of the app that you are on?

**Comment by yurividal** [comment]
Version: 2024.11.7 (19528)
It seems to have fixed this issue.

**Comment by poly2it** [comment]
I'm getting this issue multiple times daily, and it is really frustrating. We self-host Vaultwarden at my company. Can this issue be reopened?

**Comment by pamperer562580892423** [comment]
@poly2it:

> We self-host Vaultwarden at my company. Can this issue be reopened?

They explicitly request to raise any issues with them:

<img width="854" height="150" alt="Image" src="https://github.com/user-attachments/assets/e6d94030-0bd7-4f50-9f18-8bb427eba7bf" />

(--> https://github.com/dani-garcia/vaultwarden)
