### ISSUE TITLE
Passkey login failing on android

### ISSUE THREAD

**Issue by DariB123** [bitwarden/android#4376]
### Steps To Reproduce

1. Click on 'sign in with passkey'
![1](https://github.com/user-attachments/assets/f9e07355-2ee7-4711-b74e-91b89bfdc9b3)
2. Unlock bitwarden vault
![2](https://github.com/user-attachments/assets/abf6b4b3-1e75-40b8-bf9d-7e0bd510f319)
3. Click on 'Continue'
![3](https://github.com/user-attachments/assets/234713b0-7fca-4d10-87ce-c0288446d226)

### Expected Result

Login with passkey should succeed. 

### Actual Result

Passkey login fails with prompt  "Error reading passkey" and "There was a problem reading your passkey for. Try again later."

### Additional Context

I've also tried with this other services I have passkey login for and have experienced the same behavior.

### Build Version

2024.10.0 (11270)

### What server are you connecting to?

Self-host

### Environment Details

- Browser: ms-edge (also tried on google-chrome)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Can you please share your Android version and which version of Bitwarden you are self-hosting?

**Comment by DariB123** [comment]
I'm on Android 15, build number AP3A.241105.008. 

I'm self hosting the latest version vaultwarden at the moment, I'd be curious to see if anybody can replicate this issue on regular bitwarden. I'm not really convinced it'll make a difference because logging in using a passkey via the browser extension works fine.

**Comment by Krychaz** [comment]
Vaultwarden has support for the new native mobile apps apps in version 1.31.0 and above and you may need to upgrade your server. Another way to confirm that you need to upgrade your server is that you should be able to log into other clients (i.e. the browser extension or the web app) with the old Vaultwarden version. 

It is important to note that vaultwarden is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

**Comment by singh9596** [comment]
Yes, passkey doesn't work to login as well. For now switch back to 2024.11.3.
