### ISSUE TITLE
2024.11.7 gets locked on every close

### ISSUE THREAD

**Issue by ristein** [bitwarden/android#4464]
### Steps To Reproduce

1. Unlock
2. Close (swipe out of recents)
3. Open
4. Unlock again

### Expected Result

should not need main password until set timeout

### Actual Result

need to unlock with main password

### Build Version

2024.11.7 (F-Droid)

### What server are you connecting to?

Self-host

### Self-host Server Version

Vaultwarden Web Version 2024.6.2

### Environment Details

Oneplus 7 pro, Lineageos 21, Android 14, no google

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

It is important to note that vaultwarden is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 

https://bitwarden.com/help/install-and-deploy-offline/ 

This issue will be closed. Thank you for understanding.

**Comment by ristein** [comment]
Do you think the different locking behavior after an update of the vault on my phone has to do with the server?

**Comment by ristein** [comment]
I tried few older releases and they all have the same behavior.
I also tried with official server which shows the same problem.

**Comment by juliokele** [comment]
I had the same problem. After uninstalling and reinstalling the application, it seems to work as expected.
