### ISSUE TITLE
I am having a problem logging in

### ISSUE THREAD

**Issue by jkthorne** [bitwarden/android#447]
I think this might be because I am using an email with a "+" alias.
So I can log in on other platforms and I get emails from bitwarden but when I try to login on the mobile app it throws an error and says username and password are incorrect.

**Comment by kspearrin** [comment]
A + alias shouldn't have anything to do with that. Are you able to log into the web vault on this android device?

**Comment by wontruefree** [comment]
I am able to login via the web but not on iOS

**Comment by dukechem** [comment]
Same for android 7 ...chrome login ok can see vault, but android app always says 'username or password incorrect' or rarely has timeout saying cannot reach server, even on all ok wifi. Feb 2019 updated app from google play but still cannot login.

**Comment by dukechem** [comment]
I will try running on virtual android 7 to see if i can find exact steps to reproduce login err if u want...

**Comment by wontruefree** [comment]
I did a few tests on this.  Although it should not be a problem I think it is.

**Comment by kspearrin** [comment]
Is this still a problem?

**Comment by wontruefree** [comment]
I was forced to use a different email.  This was still a problem the last time I checked.

**Comment by missvickyhuang** [comment]
I'm having this problem too, can only log in with the Firefox extension, and with the iOS app (using fingerprint). Web vault, desktop app will not let me log in.

**Comment by wontruefree** [comment]
I still think this issue is unfixed.  I fixed it by changing over all my accounts.  It was a pain but I think bitwarrden plans to support this.

**Comment by wontruefree** [comment]
I am looking to self host.  Was this ever fixed?

**Comment by moranje** [comment]
I'm running into this with the Adroid app but not with the self-hosted Bitwarden RS. Also am using an email with "+" sign

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/447
