### ISSUE TITLE
Inline Tab Autofill Requires Unlocking Multiple Times Despite Session Timeout Settings

### ISSUE THREAD

**Issue by o2rhkzqx** [bitwarden/android#4475]
### Steps To Reproduce

1. Open a website with a multi-step login process (e.g., email on the first page and password on the next page).
2. Use the inline tab autofill to fill in the email field.
3. Unlock the Bitwarden vault when prompted.
4. Proceed to the next page where a password needs to be entered.
5. Attempt to use the inline tab autofill again.

### Expected Result

The vault should remain unlocked for the duration specified in the session timeout settings and not prompt for unlocking again on subsequent pages.

### Actual Result

Bitwarden prompts to unlock the vault again, even though the session timeout is set to a longer duration.

### Screenshots or Videos

While using the inline tab autofill feature, I encounter an issue where Bitwarden requires me to unlock multiple times, even though the session timeout is set to an option other than "Immediately." This issue only occurs when Bitwarden is locked. If Bitwarden is already unlocked, the behavior does not appear.

### Additional Context

This issue only occurs when Bitwarden is locked. If Bitwarden is already unlocked, the behavior does not appear. It disrupts the user experience, especially for websites with multi-step login processes. It seems the session timeout setting is not being respected when using the inline tab autofill feature.

### Build Version

Version: 2024.11.7 (19528)

### What server are you connecting to?

US

### Environment Details

- Device: Xiomi K50i 5G
- OS version: Android 14 (Xiomi Hyperos 1.0.6.0.ULOINXM)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @o2rhkzqx,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by differsthecat** [comment]
A fix for this has been merged to `main`, thank you!
