### ISSUE TITLE
Session timeout not working

### ISSUE THREAD

**Issue by m0yP** [bitwarden/android#4476]
### Steps To Reproduce

Biometrics enabled.
Session timeout set to "On app restart".
Session timeout action set to "Lock".

### Expected Result

Vault should stay unlocked until app restarts. It was working fine on previous builds.

### Actual Result

Vault locks and app asks for biometrics, even if no password was selected or app was opened from drawer.

### Additional Context

This issue started happening when updated app to v2024.11.7(19528).

### Build Version

2024.11.7 (19528) F-Droid from Bitwarden repo

### What server are you connecting to?

US

### Environment Details

Samsung Galaxy S24 Ultra
Android 14, OneUI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @m0yP,

Thank you for reporting this. I tested this on Android 14 by setting the Vault Timeout/Action to (On app restart/Lock) whilst (Unlock with biometrics) is activated, and I left the phone; the Bitwarden Android client was unlocked when I launched it after ~12 hours. I'd recommend checking if another application or a setting in the operating system is killing the Bitwarden client whilst it's [in the background](https://dontkillmyapp.com/).

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
