### ISSUE TITLE
Clicking move in "move to organisation" without selecting a collection makes the move button dissappear

### ISSUE THREAD

**Issue by KohGeek** [bitwarden/android#4500]
### Steps To Reproduce

1. When an item is open, click the 3 dots on top right and move to organisation.
2. Don't select any collection, click "Move"
3. An error will prompt, close it.
4. Try to select a collection and move again.

### Expected Result

The move button is still there and the collection can be moved.

### Actual Result

The move button dissappears, but is actually still there. Clicking in the same top right location moves the item.

### Screenshots or Videos

![Screenshot_20241222-224337](https://github.com/user-attachments/assets/b2f2d6a7-1948-4c4e-99d4-36d63569a3b2)

### Build Version

2024.10.0 (11270)

### What server are you connecting to?

US

### Environment Details

- Device: Sony Xperia 5 V

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maxmini1** [comment]
@KohGeek Hi there i think you should report that here https://github.com/bitwarden/mobile
Or try the new "native app" beta relesse https://github.com/bitwarden/android/releases/tag/v2024.12.0

**Comment by SergeantConfused** [comment]
Hello @KohGeek,

Could you please let me know if you are able to use the (Move) button that's shown in the screenshot?

Thank you in advance,

**Comment by KohGeek** [comment]
Yes, I am able to use the move button in the screenshot

**Comment by SergeantConfused** [comment]
Hi @KohGeek,

Thank you. In this case, I'm going to proceed and close this GitHub report, at this stage. If you have any questions or concerns, feel free to create a [Support ticket](https://bitwarden.com/help/) and please also include a link to this GitHub report in the body of your ticket, if you do so.

Thank you again,
