### ISSUE TITLE
Android app crash [Root][MicroG]

### ISSUE THREAD

**Issue by Nickdv9** [bitwarden/android#463]
So I've been facing this a lot lately. I use a rooted android device running android 9.0 and I'm currently using MicroG instead of gapps. App was working fine for a while but lately its been crashing a lot. After re-installing the app, it works fine for a day or two and starts crashing again. I'll be attaching logs below. Please, do have a look at it.
[bitwarden.txt](https://github.com/bitwarden/mobile/files/2874892/bitwarden.txt)

**Comment by kspearrin** [comment]
> 02-18 14:43:55.404 I/MonoDroid(17042): UNHANDLED EXCEPTION:
> 02-18 14:43:55.409 I/MonoDroid(17042): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The configuration is invalid. Creating the instance for type ISecureStorageService failed. Failed to obtain information about key ---> SimpleInjector.ActivationException: Failed to obtain information about key ---> Java.Security.GeneralSecurityException: Failed to obtain information about key ---> Java.Lang.Exception: Key not yet valid

Looks like, for whatever reason, your device is losing the ability to access the Bitwarden encryption key from the Android keystore.

**Comment by Nickdv9** [comment]
@kspearrin what I don't understand is how it can access the keys initially and then after a while it fails to do so. Do you suggest me trying anything in particular? This happens like after every 1 or 2 days after re-installing the app.

**Comment by kspearrin** [comment]
I am not sure either. Does your device have a PIN or fingerprint setup to unlock it?

**Comment by Nickdv9** [comment]
@kspearrin yes, I do have two fingerprints setup with a password

**Comment by lys79** [comment]
Same problem for me. Doesn't stop crashing on android 9.0. Drains a lot the battery in the same time 😕

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta?

**Comment by atoponce** [comment]
Came looking for an issue of the Android app crashing. The app always crashes when attempting to add a login entry, either in a specific folder, or "No Folder". I've tried various combinations of data (no username, no password, no URI, etc.) to no effect. I cannot add any login entries. Doesn't matter if I use the fingerprint to unlock, or the master password. I can create a new issue, if needed.

Stock Android 9 on a Pixel 3 XL, with the June 5, 2019 security patch update, no root. Bitwarden 2.0.6 (1938).

**Comment by Aidenir** [comment]
Came here looking for answers, just got a new galaxy s10e, out of the box, when I sign in the app crashes. Have tried enabling all permissions and accessibility service, still no dice.

**Comment by ilovejs** [comment]
rewrite this app

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/463
