### ISSUE TITLE
Self-Signed SSL doesn't work - There is a problem connecting to the server.

### ISSUE THREAD

**Issue by xMate420x** [bitwarden/android#465]
I have validated the certificate, did everything that was suggested in the issues, etc. I'm using a self-signed certificate made by OpenSSL using the command `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out certs.pem -nodes -days 9999 -subj '/CN=domainname.com' -reqexts SAN -extensions SAN -config <(cat /etc/ssl/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:www.domainname.com')) -sha256`

On PC i can install the CA certificate and the desktop app works, but on Samsung phones you cannot install CA certificates without root. There should be an option to disable SSL checking or to use the certificate without having it inside the trust store.

**Comment by kuhlmannmarkus** [comment]
@xMateMCPE I totally agree. In addition, there should be a way to use client certificates as well.

**Comment by AndrewMoscoe** [comment]
Solved: importing the self signed root CA for W-iFi instead of for "VPN and apps" makes it work.

**Comment by xMateMCPE** [comment]
It didn't work for me on Oreo, since it no longer trusts user certificates for apps. Maybe on newer Android versions it works, but I don't have phones with newer versions. For me installing the certificate with root fixed it.

**Comment by chihotdog13** [comment]
I am also having an issue with the app on Pixel 2 and iphone se. I can login via web browser on computer after import certs on computer, and Firefox reports trusted ssl, but not Chrome. I imported the full chain (server, intermediate, and ca) self signed certs as one .crt file, as well as the intermediate and ca separately, both vpn/apps and wifi, and it doesn't work.

**Comment by chihotdog13** [comment]
> 
> 
> I am also having an issue with the app on Pixel 2 and iphone se. I can login via web browser on computer after import certs on computer, and Firefox reports trusted ssl, but not Chrome. I imported the full chain (server, intermediate, and ca) self signed certs as one .crt file, as well as the intermediate and ca separately, both vpn/apps and wifi, and it doesn't work.

OK, please disgregard this post. I resolved the issue. It was related to certificates for sure. I recreated my setup, and made sure my self signed certs were working properly on the computer. Both Chrome and Firefox show green after recreating and fixing problems found from developer console in Chrome. Then I imported certs in android (non-root), and the app works! Thank you again for a great app!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/465
