### ISSUE TITLE
The return does not work in gesture-based navigation.

### ISSUE THREAD

**Issue by 3zmana** [bitwarden/android#482]
Hello, 

On my phone there are no navigation buttons like on other Android phones. I use a navigation by gesture, without buttons. Unfortunately, gesture-based navigation does not seem to be supported by the Bitwarden mobile application. When I enter a submenu, I can't go back. I have to restart the application to return to the home page.

Brand : MEIZU
Model : 16th
Flyme OS: 7.1.1.1G
Android: 8.1
App Bitwarden : 1.22.0

**Comment by kspearrin** [comment]
Thanks for the info. We'll work on adding nav buttons in the next version.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/482
