### ISSUE TITLE
Duck Duck Go & Firefox Focus Issues

### ISSUE THREAD

**Issue by pb1051** [bitwarden/android#505]
I have issues with Duck Duck Go (adding Firefox Focus) not auto-filling well.

1. Browse to store in DDG or FF
2. Click notification
3. BW lists random sites saved in the past
4. Add new site to BW
5. Click notification and now BW shows the correct associated site

Is my process wrong or is this a bug?

**Comment by kspearrin** [comment]
> Browse to store in DDG

Is this a specific website, or just any website will produce the problem?

**Comment by pb1051** [comment]
In my experiences, all sites with DDG are affected. I think it might be related to DDG's security minded practices. I'm not sure the cause. I do know that the first time you try to store a sites login info that it will list all the previous sites stored in DDG. The next time on the same site it will show only that sites login.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/505
