### ISSUE TITLE
Can't select text in the note fields on Android

### ISSUE THREAD

**Issue by RomRider** [bitwarden/android#520]
Using birdwarden 2.0 beta, it seems that sometimes I can't select text in secure notes in the note part. Kind of annoying if you have keys or some info you want retrieve from there.

Using: OP6T/Android 9

**Comment by kspearrin** [comment]
I don't believe you could select text from notes on the view page in v1 either. You would need to edit the item so that you can select and copy information from the editable notes text field.

**Comment by RomRider** [comment]
It's when I edit, I forgot to mention that, sorry

**Comment by kspearrin** [comment]
I am not able to reproduce. I can select/copy/paste just fine when editing the notes field.

**Comment by RomRider** [comment]
I can almost all the time also but when the text has very long lines with a + inside it doesn't work.

Try this in the note field, save and edit again:
`hshshdhfhdjdjdjskdkfjfhdkskdjfbdkskdbfjdjskskfjfkdlsldhfkdoskdjfhfjelskfjfjfis+fjfjdjdjfjfjdjdjfhf`

I'm not able to select the text anymore after that.

**Comment by kspearrin** [comment]
This seems to be a xamarin bug. I will report it upstream. In the meantime, I have made the Notes text selectable on the "View" page.

**Comment by THEOCKID** [comment]
I'm sorry, new to Bitwarden, but this bug still exists (at least for me).  
Running BW 2.2.1 (2063) on Samsung Galaxy S9 running Android 9 (not rooted, up to date on system updates and security updates)
I'm using GBoard and it will not let me (for example) tap and hold on text (i.e. a word) and select the text in the Notes field.  This is really a pain.  I can't do it from either the View or the Edit modes.  If desperate, I can utilize GBoard's manual select option where you position the cursor, hit the Select toggle on Gboard, and then tap tap tap on the right or left arrows until the word or phrase is selected, then I can paste it into a custom field or PW or Username.

Any progress on this fix, @kspearrin ?  Thank you in advance for your assistance.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/520
