### ISSUE TITLE
Auto-fill service not working on Android 9 - fill request timed out

### ISSUE THREAD

**Issue by lgp171188** [bitwarden/android#545]
I have installed the 2.0.6 version of the Bitwarden app through the F-Droid repository on my Redmi Note 4 phone running Android 9. I have enabled the `Auto-fill service` since it works on devices running on Android 8.0 or higher and not enabled the `Accessibility service'. When I click on a text input in an app, press and hold and select `Auto-fill` nothing happens.

When I checked the logcat output when this happened, I see a couple of warning messages related to this issue
```
W RemoteFillService: PendingFillRequest timed out
W RemoteFillService: PendingFillRequest timed out after 5000 ms
```
I also have Keepass2Android app installed and when it is set as the app for the `Auto-fill service`, doing the same does show a prompt to auto-fill using it. So this looks like an issue with the Bitwarden app.

With the `Accessibility service` enabled, things work better and I get a notification prompting for the auto-fill most of the times, but I do not want to use it since the `Auto-fill` service is supposed to work and Google is deprecating the usage of `Accessibility service`. Also enabling it disables the boot time security which prompts for the PIN to boot the phone.

**Comment by kspearrin** [comment]
Does this happen in any app or only certain ones?

**Comment by lgp171188** [comment]
@kspearrin, I checked only in one app before reporting this issue. I will check in other apps and post an update.

**Comment by lgp171188** [comment]
@kspearrin, the auto-fill seems to work in some apps and doesn't work in a few others. Is there any additional information that I can provide in order to help diagnose this?

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/545
