### ISSUE TITLE
iOS Bitwarden app offloads very frequently

### ISSUE THREAD

**Issue by oybed** [bitwarden/android#546]
Using the Bitwarden app on iOS, the app gets offloaded (ie uninstalled) very frequently. I don’t want to disable the offload feature, but other unused apps are not offloaded while Bitwarden is. Very frustrating when I go to use it and find that it needs to be re-downloaded (even though I used it just a few days earlier). Not sure if there is something that can be done on the app side to configure the offloading timeframe, or if this is an iOS issue rather than the app. Either way, wanted to start here to see what you all think. 

Thx

**Comment by oybed** [comment]
BTW: have seen other people complain about the same issue on Reddit - ie:
https://www.reddit.com/r/Bitwarden/comments/bmzjx7/bitwarden_offloading_ios/
https://www.reddit.com/r/ios/comments/bxben2/prevent_app_from_offloading/

**Comment by kspearrin** [comment]
Unfortunately, I don't know of anyway, as the app developer, to tell iOS to not offload the app.

**Comment by Crocmagnon** [comment]
When you say you used it, do you mean you used autofill in a browser/app or you really tapped on the icon to open the app?

**Comment by oybed** [comment]
Launched the app by tapping its icon.

**Comment by oybed** [comment]
FYI: I found the bitwarden app offloaded again yesterday - which is less than ~10 days after last use. This just seems too frequent. Understand that the app devs can't necessarily control this, but are there any other suggestions for next steps for this issue?

**Comment by A1p1n3** [comment]
Than I'm unsure what to tell you, there's no way to disable it for one app only.

**Comment by silvetti** [comment]
> 
> 
> Per original posting, I do not want to disable the feature all together, so changing the setting under _iTunes & AppStore> Offload unused apps_ is not an option.

This is not a Bitwarden issue.
You need to raise feedback to Apple on https://feedbackassistant.apple.com

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/546
