### ISSUE TITLE
Sync issue and clipboard cleaning doesn't work

### ISSUE THREAD

**Issue by pcost1** [bitwarden/android#547]
Hello, I have two problems with the latest android version:

1 - sync issue: the automatic sync only works sometimes. Usually I have to make a manual sync. For instance today when I launched the app the last sync was from 2 days ago, although yesterday I have used the app.

2 - The clipboard clean doesn't work. I have set up to clear the clipboard after 10 seconds but it doesn't work. It never works, sometimes I still have my password on clipboard a few hours after the copy.

I am using the latest android version and I have a Xiaomi Mi 5, running android 6.

**Comment by kspearrin** [comment]
1. Does your device have Google Play Services? This is required for live sync push notifications.

2. I am not able to reproduce this on my test device. We use an Android's alarm manager with a pending intent to a broadcast receiver. Any idea if this somehow behaves differently on older versions of android?

**Comment by pcost1** [comment]
1. Yes, my device has Google Play Services. Before the update to the v2 of Bitwarden the live sync worked perfectly. 

2. Perhaps you're right regarding this feature on older versions of android, because I've just tried on an even older version (android 4) and it doesn't work too. So, on android 4 and android 6 it doesn't work (at least on the devices I've tried).

Thanks.

**Comment by kspearrin** [comment]
How are you expecting the clipboard clearing to work? Are you looking at your clipboard history or something like that? We only clear the current clipboard value by setting it to an empty string, preventing you from pasting it. Any clipboard history would still remain.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/547
