### ISSUE TITLE
App crashes on password save when VPN is not established

### ISSUE THREAD

**Issue by davidplrobinson** [bitwarden/android#564]
If you use a VPN to connect to your bitwarden server from iOS app, when updating a password, the app crashes if the VPN connection is not established when you press 'save'. 

Should either cache the updates until a connection is established and a successful sync is performed, or at a minimum produce a connection error to allow user to connect to VPN and retry.

**Comment by kspearrin** [comment]
> when updating a password

Is this just editing an item and saving from the main app?

**Comment by davidplrobinson** [comment]
Yes, so if a secret already exists in the app, and you update the password while the VPN is not connected, the app crashes.

See attached dropbox link for video showing the issue - 

https://www.dropbox.com/s/fy015yg5ej0z6rq/RPReplay_Final1563795936.MP4?dl=0

**Comment by kspearrin** [comment]
I would think a connection error alert would be produced here since we attempt to account for that. What is the timestamp for that crash in your video? I see 21:45. What time zone is that?

**Comment by davidplrobinson** [comment]
Timezone is Melbourne Australia (GMT+10).

**Comment by kspearrin** [comment]
Can you share what kind of device and iOS version you are using?

**Comment by davidplrobinson** [comment]
Hi, sure... I'm using iPhoneX running on iOS 12.4 - this was upgraded today from 12.3.2 and I can confirm the issue can still be replicated on this new version.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/564
