### ISSUE TITLE
Ability to change language on Android

### ISSUE THREAD

**Issue by hieu-van** [bitwarden/android#571]
Or at least respect the locale setting, not to get the system language setting yourself. Bitwarden seems not to be respecting App Locale Xposed module.
The translation of my language is stupid. I prefer English :D

**Comment by kspearrin** [comment]
What is your device's language/locale set to that is is not respecting?

**Comment by hieutvan** [comment]
en-US

**Comment by kspearrin** [comment]
And you're saying that the app is not displaying content in English?

**Comment by hieutvan** [comment]
On Thứ Năm, 1 tháng 8, 2019 21:48:54 +07 Kyle Spearrin wrote:
> And you're saying that the app is not displaying content in English?
Yup (I have my device language set to non-English, but I use a Xposed module 
called App Locale 2 to change language on a per-app basis, for apps that don't 
have a language option. All other apps which I set to use English are 
working... Except Bitwarden :(

-- 
Hieu Van

Email: hieu.van@posteo.net
Phone: +84 962 017 145

**Comment by kspearrin** [comment]
> but I use a Xposed module called App Locale 2 to change language on a per-app basis

Can you provide more info on how I can use this to reproduce the problem?

**Comment by hieutvan** [comment]
Why not ;)

1. Install _App Locale 2_ Xposed module (I hope you know what Xposed is).
2. Set your device language to something other than English.
3. In _App Locale 2_, set the language for Bitwarden to en_US.
4. Try opening Bitwarden to see what language it is...

**Comment by tschoesi** [comment]
Are there any news on an option to set the language in-app? My device is set to a non-english language, but I would much prefer Bitwarden in english (some terms just dont make sense when translated from english, i.e. the standard URI matching options)

Thanks ! :)

**Comment by Ambr051us** [comment]
Bump.
Please provide a language selector in the app options! Android doesn't have a way to set language per-app without rooting, it's one of the biggest flaws in the OS in my eyes, because I have to nag developers to add the manual toggle to every app that misses it...

**Comment by ryan-ph** [comment]
Any progress on this? I'd be happy to help add this feature if you can point me to a contribution wiki.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/571
