### ISSUE TITLE
Incorrect Environment URL on iOS App Login Page

### ISSUE THREAD

**Issue by emaraszek** [bitwarden/android#580]
**Summary**
The environment URL on the login page for the iOS app references “bitwarden.com” instead of the URL of the user’s self-hosted environment. 

_(Note: This may occur on the Android app as well, but I do not have access to an Android device on which to confirm.)_

**Repro Steps**

1. Open the Bitwarden iOS app, don’t login
1. Observe the text under the Master Password input field

**Actual Result**
The text reads, “Logged in as EMAIL_ADDRESS on bitwarden.com”. 

**Expected Result**
The text reads, “Logged in as EMAIL_ADDRESS on SERVER_URL”, where SERVER_URL reflects the URL of the self-hosted environment.

**Screenshot of Issue**
![D002F4F9-28FC-4201-BAFE-B935521362C2](https://user-images.githubusercontent.com/7446498/63396261-7199ed00-c394-11e9-846a-9728a864915b.jpeg)

**Comment by kspearrin** [comment]
Can you please confirm the version of the app you are using? I thought I fixed this.

**Comment by emaraszek** [comment]
Just updated to 2.2.1 on my iPad before I logged this, same version and issue on my iPhone

**Comment by kspearrin** [comment]
I just tested this on iOS and Android and was not able to reproduce. What are your environment settings set to?

**Comment by emaraszek** [comment]
I have only set the Server URL to the base URL of my self-hosted environment. All other Custom Environment settings are blank.

**iOS App Settings**
![2019-08-21 11_35_06-19-08-21 11-33-33 1621](https://user-images.githubusercontent.com/7446498/63446307-fa9e3c00-c407-11e9-9587-7381fedc786a.png)

Additionally, I have the same settings applied on my desktop and the correct URL appears on the login page.

**Firefox Extension Settings**
![2019-08-21 11_37_41-Clipboard](https://user-images.githubusercontent.com/7446498/63446440-39cc8d00-c408-11e9-9377-20c68b53e2a4.png)

**Firefox Extension Login Page**
![2019-08-21 11_01_46-Log In](https://user-images.githubusercontent.com/7446498/63446618-87e19080-c408-11e9-8814-33c9911c7d9e.png)

**Comment by kspearrin** [comment]
Can you try clearing it and re-saving it maybe?

**Comment by emaraszek** [comment]
I wiped out the environment settings, saved them, then re-opened them, put my custom URL back in, and saved again. The same issue is still occurring.

However, I have noticed something strange which may be of help - if I manually lock my vault via the settings menu, the correct URL shows on the unlock page. The "bitwarden.com" URL only shows up after quitting and then re-opening the app.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/580
