### ISSUE TITLE
Can't login on iOS 12.4 iPhone 7 Self-Hosted

### ISSUE THREAD

**Issue by phischmi** [bitwarden/android#585]
Hi all,
i'm using a self-hosted version of bitwarden with 2FA activated.
I successfully set it up on several browsers and on my iPhone XR.
Now i tried setting it up my second phone - an iPhone 7 with iOS 12.4.
When trying to log in, i'll type in my credentials and then my 2FA code. Afterwards the app says "Validating" and after a few seconds stops with the message "An Error occurred".
Logging in on my iPhone XR or any browser works as expected.
Any ideas what's the problem with my iPhone 7?

Bitwarden: Version 2.11.0
App: 2.2.1

**Comment by phischmi** [comment]
Hi, i'm using a certificate signed by Let'sEncrypt.
What's so strange about it is, that a works on my iPhone XR (iPS 13 Beta) and chrome-plugins at home (OSX Catalina Beta) and at work (Win 10).

**Comment by robpedersendev** [comment]
Any progress or solution for this? I am getting this same issue 

![image](https://user-images.githubusercontent.com/40696979/101722066-ac7ed300-3a66-11eb-9082-1890b4460fdc.png)

**Comment by danielphan2003** [comment]
I have the same experience on Android, but it was because Bitwarden doesn't know how to open the default browser if it is not Chrome for some reason.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/585
