### ISSUE TITLE
[Documentation] Fingerprint lock and encryption

### ISSUE THREAD

**Issue by gpa** [bitwarden/android#590]
I logged in with my passphrase to the mobile app and then set the fingerprint lock. I just assumed that the unencrypted data is kept in memory and then only shown after a fingerprint verification. But then I restarted my phone and was still able to access the data with just the fingerprint. From  reading the source code I could see that a FingerprintUnlockKey is being used, but it is unclear to me how it works and would really appreciate some documentation on it and how it compares to just using the password security-wise.

**Comment by kspearrin** [comment]
The encryption key is persisted to the protected storage area on the device (keychain or key store).

**Comment by uchagani** [comment]
In my opinion, on reboot all instances (app and auto fill extension) should be locked.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/590
