### ISSUE TITLE
Yubikey 4c/5c does not work on iPad Pro (2018)

### ISSUE THREAD

**Issue by repentsinner** [bitwarden/android#592]
If I connect a Yubikey 4c to an iPad Pro (2018) via the native USB-C port and touch the button in any text entry field, the expected OTP string is entered. However, at the `Yubikey Security Key` page of the login flow, the help text and image describes usage for an NFC Yubikey and there is no user discoverable corresponding text entry field to recover the string.

**EDIT:**

The horizontal rule on the login page is a text entry field masquerading as a horizontal rule. Tapping in the right place above it will focus the text entry and allow a Yubikey 4c to work. Would it be possible to auto-focus the field on moving to this screen in the flow, use a more obvious text field outline, or similar?

Thanks for considering!

![Image from iOS](https://user-images.githubusercontent.com/4462072/65361994-9f07cf80-dbba-11e9-87fb-16b81f7102c7.png)

**Comment by kspearrin** [comment]
We just need to make the text field more apparent for users.

**Comment by Alexx-G** [comment]
Yeah, I had same issue with 5Ci, thought it's not supported yet.
What's odd is that when I plugin YubiKey 5Ci to iPad it says that there's no app for the accessory and redirects to AppStore where bitwarden isn't listed (there are other password managers).
Everything works, but it would be great to make it a little more intuitive. Thanks!

**Comment by DonkeyAfterDark** [comment]
Holy duck. That’s sneaky. Just spent 10 minutes trying to figure out to log in with the 5Ci and I make websites for a living!!

**Comment by reevesnick** [comment]
I believe YubiKey 5Ci use a different SDK instance. So even if YubiKey SDK is there, it is not universal on all products. The same thing happening with Brave iOS app when they allow YubiKey support, but only for the 5Ci and not the YubiKey 5 NEO

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/592
