### ISSUE TITLE
iOS 13.0 Application Crash

### ISSUE THREAD

**Issue by TwoTenPvP** [bitwarden/android#611]
I previously used an iPhone XS Max on iOS 12.1.1 Beta 1. I bought an iPhone 11 Pro Max and restored using iCloud. Since then, Bitwarden crashes just a few seconds after it's started. I can still interact with the app in that time, like accessing settings. Must be a fetch crash.

Unable to get any stacktraces as I don't own a macintosh.

[Video here](https://youtu.be/4BJ-GbvGsIM)

Note that this is on version 2.2.3 with the iOS 13 fixes.

**Comment by TwoTenPvP** [comment]
Issue also present on iOS 13.1.1, guessing that isn't too helpful but might aswell let you know.

**Comment by TwoTenPvP** [comment]
Issue fixed when manually logging out of account, then logging back in. Should probably still be looked into even if the reproduction involves restoration.

**Comment by eakoning** [comment]
@TwoTenPvP this makes two of us. ;-) I was unable to press logout button in the app because Face ID was too fast. I uninstalled and reinstalled the app. Then I could login and it was all and well again...

**Comment by TwoTenPvP** [comment]
> @TwoTenPvP this makes two of us. ;-) I was unable to press logout button in the app because Face ID was too fast. I uninstalled and reinstalled the app. Then I could login and it was all and well again...

Yea, I just pointed the phone away from my face.

**Comment by trparky** [comment]
I'm not the developer but you can access app crash data through the Settings app on your iPhone. Simply open up Settings, Privacy, Analytics, Analytics Data. The only bad part is that you're going to have to sift through all of that stuff in that list to find the app crash data file. Once you find it you can then use the Share sheet to copy the data to the iOS clipboard.

Also, if you sync your device to iTunes on a Windows system you can find the diagnostic logs that are copied from the iOS Device. You can find this data in %appdata%\Apple Computer\Logs\CrashReporter\MobileDevice and then open the folder that's named the same name as your iPhone is named.

**Comment by maxgrass** [comment]
There are some device binding keys (bound to face/touch id) as in virtually all apps.. gmail/instagram etc. after restoring from a backup those apps recognize mismatches and log the user out automatically.

**Comment by alexjhart** [comment]
I've also run into this on a restore/migration.

**Comment by janharms** [comment]
I have the same issue on 2.4.3 (69). It is the result of a double entry. 
I had an entry for Berliner Sparkasse (Banking Site) which for some reason does not work in the app. (It does not prefill.) I created the same entry again; so I had the same entry twice. This resulted in the app crashing after login with face-Id. 

Regards

**Comment by cscharf** [comment]
@janharms , that doesn't necessarily make sense given items in your vault are not indexed or managed by name/URL, etc. by rather by a globally unique identifier; I would assume it was the act of logging out and back in that "resolved" the issue for you. Can you confirm by re-adding that duplicate and trying again?

If anyone can reproduce and provide app crash logs from their device that would be immensely helpful.

**Comment by janharms** [comment]
You are right. I cannot reproduce the issue that way anymore. App starts happily even with a duplicate entry. 
Must have been a coincidence.

**Comment by rggjan** [comment]
Just had the same issue. Video attached (in the zip file) as well as two crashlogs. Logging (by pointing it away from the face, then pressing log out) and in again (with the password + yubikey) still crashes.

[RPReplay_Final1596202762.MP4.zip](https://github.com/bitwarden/mobile/files/5007289/RPReplay_Final1596202762.MP4.zip)
[crashlogs.zip](https://github.com/bitwarden/mobile/files/5007294/crashlogs.zip)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/611
