### ISSUE TITLE
Crash at start on Android 7.1

### ISSUE THREAD

**Issue by a-morelos** [bitwarden/android#616]
When you unlock the vault, after 1 or 2 seconds, suddenly crash, you need to restart the app and reunlock the vault to work well.

**Comment by kspearrin** [comment]
Can you reliably reproduce the problem?

**Comment by a-morelos** [comment]
It happens every time when app is launched. It's necessary stop the app and clean cache to fix the problem.

**Comment by kspearrin** [comment]
Can you provide a timestamp of a crash and what type of device you are using so that I can try to locate the issue in our crash logs?

**Comment by a-morelos** [comment]
It was on October 3rd, around 11:30 a.m CDT with a Moto G4 Play (XT1601) with Android 7.1.1

**Comment by drbeco** [comment]
Android 9. Asus Zenphone.  20/Feb/2021, exactly at 11h00 GMT-3. 

App crash on start up.

No cache cleaning solve it. It won't start in any way.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/616
