### ISSUE TITLE
Does not properly identify password fields when default language is French

### ISSUE THREAD

**Issue by spaffrath** [bitwarden/android#626]
Using Android 9 on Galaxy S8, default language French, Bitwarden set to fill password fields, and an app like OurGroceries. Go to add an item into a shopping list and BitWarden will offer auto-fill popup. BitWarden does not do this when default language is English or Spanish.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/626
