### ISSUE TITLE
Android 9 - Have to press search twice for it find my passwords

### ISSUE THREAD

**Issue by FingerlessGlov3s** [bitwarden/android#635]
Hey,

So I press autofill on the notification when using password autofill in Brave Browser.
No passwords show up due to it not recognising the site, no issue I'll search for it, so I type in say Facebook but nothing returns. So I press search again and then it appears.

This also happens when I try auto fill some apps and there's no association between app and site.

Any logs I can provide just ask.

**Comment by escape0707** [comment]
I run into this since a long time ago on iOS, too.
During typing the keyword, the search result shows up normally. But if I enter a character and follow up pressing the search button quickly enough, it shows “There are no items to list.”

**Comment by FingerlessGlov3s** [comment]
So it's still happening to you?

I'm on Android app version 2.2.2

Does the iOS version line up the same?

**Comment by escape0707** [comment]
Just tested on Version: 2.2.5 (59)

**Comment by FingerlessGlov3s** [comment]
How did you get 2.2.5? Beta?

https://github.com/bitwarden/mobile/releases

**Comment by escape0707** [comment]
I just plainly downloaded from the iOS App Store.
Maybe the versioning method differs?
![photo_2019-10-23_10-33-24](https://user-images.githubusercontent.com/11014745/67351693-af77e500-f580-11e9-9e54-7a0f47ebbf12.jpg)

**Comment by FingerlessGlov3s** [comment]
> I just plainly downloaded from the iOS App Store.
> Maybe the versioning method differs?
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/11014745/67351693-af77e500-f580-11e9-9e54-7a0f47ebbf12.jpg">

Yeah it must differ.

Hopefully a developer can fix this in a later update, been like this since I've been using Bitwarden, about 6 months by this point.

**Comment by mportune-bw** [comment]
@FingerlessGlov3s Is this still happening for you with the latest beta?  The accessibility service was completely rewritten.

**Comment by FingerlessGlov3s** [comment]
@mportune-bw evening, so detection is better.
When I go to mail.domain.com it searches for domain.com but my URL is set as host so it doesn't appear as it needs to search the actual hostname mail.domain.com in the url

Also still got the bug where you do go to search, it you type fast enough and then press the search key nothing returns but if you let it auto search it's fine.

**Comment by kspearrin** [comment]
@FingerlessGlov3s Android only supports base domain matching since we don't have access to the full URL.

**Comment by FingerlessGlov3s** [comment]
Now that would make sense to be honest, privacy n that.

Could we have a override option in the bitwarden settings so the autofill can find sites using subdomain HOST from the base domain?

**Comment by kspearrin** [comment]
No, we don't have access to the full URL in Android.

**Comment by FingerlessGlov3s** [comment]
So you have a website password saved using HOST as subdomain.domain.com

So when you browse to subdomain.domain.com, does it present "domain.com" to the autofill?

Would it be possible to have a settings in Bitwarden so it can lookup *domain.com so it shows subdomain ones as well set as HOST?

I hope that makes sense and I haven't misunderstood

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/635
