### ISSUE TITLE
Android - Password generator length selector is difficult to set to the wanted number

### ISSUE THREAD

**Issue by b1zzu** [bitwarden/android#636]
Maybe it's me that I have to big fingers, but I found really difficult to aim the right number in the *Password Generator* -> *Length* selector.

If the selector has fewer possibilities (32 and not 128) or if the selectors could provide also an input fileds it would be easier to use it.

**Comment by LaazV** [comment]
Seconding this request... It's really frustrating to reach the length I want, especially when I am required a maximum of 6 to 12 digits, this range is almost impossible to reach within the first 5 tries. A plus and minus button at the right of the slider, or any other way to change the sensibility of the slider or to force change a single unit would be awesome! 

I'm on Android btw, I'm not sure how the iOS app works.

**Comment by FormularSumo** [comment]
This has also bugged me for a long time. The Android and iOS app here are the same, they both only have a slider to change password length. It'd be really helpful if there was a plus/minus button like on the browser extension and web app to allow a bit more precision where needed, as it's much trickier to be precise on a phone touchscreen with fingers than when using a mouse/trackpad I find.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/636
