### ISSUE TITLE
Password generating options won’t save if change in creating new item

### ISSUE THREAD

**Issue by escape0707** [bitwarden/android#637]
Steps to reproduce:

1. Start an app, say Safari. Find a sheet, invoke Bitwarden in it.
2. Click plus sign, press generate password.
3. Tweak some changes like “minimum numbers in password”.
4. Cancel and cancel.
5. Changes are not saved like they would in Bitwarden app.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/637
