### ISSUE TITLE
Website Icon missing - mydealz.de

### ISSUE THREAD

**Issue by brokoler** [bitwarden/android#642]
Hi together,

my Bitwarden iOS app is missing one website icon, which is shown correctly via Web Access and my Firefox Addon.

The issue appears when saving a login for following website:
https://www.mydealz.de/

I tried syncing multiple times and re-added the account after deleting the entry.
Nothing works, the icon is still not shown.

I'm using the latest version of Bitwarden.

**Comment by wasimmalik88** [comment]
![Screenshot_1573651612](https://user-images.githubusercontent.com/3177074/68767899-57924280-0643-11ea-9669-f4f614444ba7.png)
Tried to produce in my android device.
It looks like it is particular to iOS only.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/642
