### ISSUE TITLE
Access the empty vault after remove account

### ISSUE THREAD

**Issue by AyoPrez** [bitwarden/android#653]
I created today an account with the Android App (downloaded from F-Droid) and activated the biometric login (with fingerprint). A while later, in the web, I removed my account. When accessing the app, I could do it with the fingerprint and I was into "my account". Because there was no item in the vault before removing my account, the app looks the same as before, empty. When I try to add a new item, I get an error (obviously). 

Would it be possible to recognise when an account is not existing anymore and, when the user use the fingerprint to login, show the login/registration screen instead of the user account screen?

**Comment by kspearrin** [comment]
It should eventually log you out of the non-existing account after ~1 hour of deleting the account.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/653
