### ISSUE TITLE
Search broken on iOS when searching while bitwarden is still loading

### ISSUE THREAD

**Issue by rggjan** [bitwarden/android#656]
This is reproducible:
1. Open bitwarden, login via Face ID
2. while bitwarden is still loading, go to search from the menu showing the favourites 
3. search and hit the blue enter button on the iOS Keyboard 
4. the correct entry is displayed 
5. bitwarden is finished initializing and the search result is cleared
6. searching the same term again brings up the entry again 

When waiting long enough between 2 and 3 everything works fine.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/656
