### ISSUE TITLE
Locking during editing results in all entered data being lost

### ISSUE THREAD

**Issue by netvl** [bitwarden/android#669]
Suppose I want to create an item in my vault. I create a new item and start filling it out. Then, before saving I switch to a different application, e.g. to copy some data there. If the vault gets locked before I switch back to Bitwarden (which will happen immediately with them "Immediately" lock option, for example), then all of the data which I entered before locking is lost, because the edit dialog is closed, and the app presents whatever page there was before I started editing.

This behavior is highly annoying, especially with the "Immediately" option turned on, and from my experience, other password managers do not suffer from this issue.

I observe this behavior on iOS 13.2.3, Bitwarden app 2.2.5.

**Comment by MarkJeronimus** [comment]
The 'locking' part is irrelevant here. When I enter data and focus another application, the entered data is still lost because the edit dialog is closed when it loses focus. Luckily I can retrieve the generated password in the history of the generator tab.

**Comment by netvl** [comment]
@MarkJeronimus I believe this repo is about an iOS app :) it has different behavior - if you switch back to Bitwarden from another app without locking, all entered data will still be there.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/669
