### ISSUE TITLE
Hide Badge With Persistent Notification 

### ISSUE THREAD

**Issue by seniorm0ment** [bitwarden/android#681]
Would appreicate a way to keep persistent notification on but just disable the badge. I use the persistent notification for quickly getting into bitwarden and manual entires for stuff it doesn't detect. But the status badge along the top takes up space for other notification badges and is really annoying. Would highly appreicate a way to hide the badge. 
I have went into bitwardens android app settings and disabled the badge but it didn't work.

Android pie, lgv40

**Comment by NicholasConrad** [comment]
In the noticed settings you should be able to set the notification to silent and minimized, which will prevent a badge from appearing in the status bar.

**Comment by Z3ROGRAV1TYx** [comment]
@NicholasConrad No option to minimize it on android, with other apps if I hold down on their notification it offers to minimize. Bitwarden only offers to keep showing or stop showing.
In notification settings on android, icon badge is set to hidden for Bitwarden.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/681
