### ISSUE TITLE
Some settings are persist after logout

### ISSUE THREAD

**Issue by yegle** [bitwarden/android#684]
It looks like certain options are persist after 1) logout, and 2) change server URL.

This is the Android app, not sure about iOS app.

Steps to reproduce:
1. Use https://bw.example.com as server URL, log in as foo@example.com
2. Enable "Autofill service", enable "Unlock using Biometrics"
3. Logout, change server URL to https://bw-testing.example.com

Expected to see:
1. The email address field should be empty, since I changed the server and the expectation is that I should have a different user on a different server.
2. More importantly I would expect "Autofill service" and "login using biometrics" should be off.

Actual:
1. The login form is prefilled with foo@example.com
2. "Autofill service" and "login using biometrics" is on.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/684
