### ISSUE TITLE
[iOS] App lock not working after (re-)login

### ISSUE THREAD

**Issue by ghost** [bitwarden/android#694]
iOS version: 13.3
BW version: 2.2.5 (59)
Lock setting: immediately
Touch ID is used for unlock

1. Logout & Login again
2. Put app in background & get it back to foreground
> should be locked now but it's not
(Lock setting is still on immediately)

Problem can be fixed by killing the app once.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/694
