### ISSUE TITLE
Keyboard covers search results (Android)

### ISSUE THREAD

**Issue by snoozysoft** [bitwarden/android#704]
When searching for logins either in the app or via the autofill interface, the last 5 or so results always end up being covered by the keyboard. Normally when I use similar search functions in Android apps, the interface "squishes up" to accommodate the keyboard being on screen and to ensure that nothing is covered up by it. It's a particular problem for those of us whose certain often used logins always end up at the bottom of a long list.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/704
