### ISSUE TITLE
Android app doesn't recognize websites in Lynket

### ISSUE THREAD

**Issue by citydelver** [bitwarden/android#707]
I use Lynket, which is a special type of browser: it doesn't have an editable URL bar, because it works by opening a custom tab (allowing you to choose in its settings which custom tab provider the users wants to use). I choose Firefox for rendering these custom tabs. So I click a github link (say https://github.com/bitwarden/, e.g.) anywhere, which makes Lynket open https://github.com/bitwarden/ in a custom tab provided by Firefox. It asks for my login, but Bitwarden either doesn't see it as login/password fields (thus not triggering the in-field-droplet nor generating the notification) or sees it but doesn't recognize the website which is open.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/707
