### ISSUE TITLE
Localization issue: Missing plural form

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/android#714]
There is missing plural form in your string. Text like "text(s)" looks bad. In many languages translators need to have one, few (2-4) and also many form.

See grammar rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

https://github.com/bitwarden/mobile/blob/179514ddf15eb2c5fa5ed247825bd7581333128f/src/App/Resources/AppResources.resx#L1319

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/714
