### ISSUE TITLE
Bitwarden Autofill blocking Estonian Mobile-ID "OK" button

### ISSUE THREAD

**Issue by Laurisade** [bitwarden/android#728]
**Phone:** Samsung Galaxy S10 with February patch.
**Bitwarden 2.3.0 (2173)**

Estonian Mobile ID (tied to SIM card) uses Android SIM toolkit.
It's not really an app itself, just an icon (named after carrier: Elisa).

The problem is that this SIM Toolkit thing is widely used in Estonia: it allows to sign documents, logging into internet bank... you name it!
With latest Bitwarden beta, there has been change regarding Accessibility service.
It's now replaced with Popup overlay. This in turn blocks OK button, so you practically can not submit the PIN code (Enter on keyboard does not work).

![Screenshot_20200212-201859_SIM toolkit](https://user-images.githubusercontent.com/6094860/74364896-b350a100-4dd5-11ea-82b5-fd9fa55a3f38.png)

![20200212_202658](https://user-images.githubusercontent.com/6094860/74365457-d16ad100-4dd6-11ea-8cc6-92a657dcb6f8.png)

Could you universally exclude this app? So that login/password is not offered. It's really important I think!
It could be different story with other Android phones, as they might have different SIM Toolkit UI.

**Comment by kspearrin** [comment]
Can you just un-focus the input field and it the overlay will go away?

**Comment by Laurisade** [comment]
> Can you just un-focus the input field and it the overlay will go away?

Unfortunately no. Pressing anywhere in the UI doesn't do anything. Plus even the ... menu on top-right only BW for as long as you keep it open.
You can not press "OK" while that menu is open. And as soon as you close it, BW appears.

**Comment by Laurisade** [comment]
![image](https://user-images.githubusercontent.com/6094860/74367106-f876d200-4dd9-11ea-84c0-ac2f529605e5.png)

Just for reference: here's same window, on Oneplus 5T (latest updates).

**Comment by VeikkoLehmuskorpi** [comment]
Hey, I had the same issue and just wanted to confirm that PR #730 really did solve the issue. Adding "androidapp://com.android.stk" URI to the blacklist did the trick.

**Comment by plumber-craic** [comment]
Same thing happening with Norwegian bankID prompts: https://github.com/bitwarden/mobile/issues/1816

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/728
