### ISSUE TITLE
Bitwarden's icon on F-droid is blurry (not sharp)

### ISSUE THREAD

**Issue by aha999** [bitwarden/android#731]
On F-droid, the icon of Bitwarden is of low quality or blurry, while icons of other apps are sharp:
![slika](https://user-images.githubusercontent.com/50620416/74576690-416e8800-4f8c-11ea-8565-8682afce8415.png)

**Comment by dkanada** [comment]
This is because the asset used for the app icon doesn't have alternate sizes available depending on the screen size. I had the same issue in another app and fixed it by generating all five sizes.
