### ISSUE TITLE
Authorization notification has disappeared

### ISSUE THREAD

**Issue by KOT040188** [bitwarden/android#775]
After some updating, the function of displaying a notification in the blind for authorization disappeared.  I am using opera.  When you click on the input field, the popup window does not appear at all or appears for a split second and disappears again.  This happens not only in opera, but also in other applications.  I gave all permissions.  Using bitwarden is now impossible.

**Comment by dkoppenh** [comment]
Please bring back the notification as an option, for when the accessibility pop-up doesn't work. Which is most of the time due to #784

**Comment by KOT040188** [comment]
How to return a notification ???

**Comment by AutumnalAntlers** [comment]
I'd also like to have the notification see a return, and see no reason to restrict a popular user preference here; was there a technical reason for the change?

**Comment by remewer** [comment]
I tried to revert back to 2.2.8 but the notification won't show. Also tried 2.2.7 but still not showing.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/775
