### ISSUE TITLE
Mobile clients missing the option to (not) remember login email

### ISSUE THREAD

**Issue by dpantel** [bitwarden/android#776]
## Describe the Bug

Mobile clients should have the option to remember (or not) the login email address, just like in the web vault.  The current behaviour is to remember and pre-fill the email address.

Edit: Posted here as a bug, since this may impact security.
Edit2: same issue with browser extensions.

## Environment

- Device: iphone7
- Operating system: ios13x

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/776
