### ISSUE TITLE
IOS bitwarden app cant record login pwd of other apps

### ISSUE THREAD

**Issue by vanyanyan** [bitwarden/android#823]
I am new user , I dont know how to record the app to record login password of ohter apps in IOS, pls help thx!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1170226791151129) by [Unito](https://www.unito.io/learn-more)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/823
