### ISSUE TITLE
Keyboard hides subsequent lines when editing (Android) 

### ISSUE THREAD

**Issue by yaakovfeldman** [bitwarden/android#852]
## Describe the Bug

If the notes field is several lines, and I am editing, I cannot scroll down to subsequent lines.

The only way to edit a subsequent line is to dismiss the keyboard and tap the desired line to reopen the keyboard with the cursor at that line.

Every time the keyboard pops up, the UI scrolls to position the line being edited just above the top of the keyboard but this is 'fixed' until the keyboard is dismissed. 

## Steps To Reproduce

1. Edit a record whose notes field is several lines long

2. Scroll all the way to the bottom (**important** - this bug will not appear otherwise) 

3. Tap a line in the field eg the first. The keyboard will appear with the selected line just visible above it

4. Attempt to scroll down to the last line without dismissing the keyboard 

## Expected Result

The notes field scrolls down allowing editing of a subsequent line

## Actual Result

The field does not scroll

## Environment

- Device: Samsung S10
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2257)
- Is this a Beta release? N

**Comment by yaakovfeldman** [comment]
This could be related to #704

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/852
