### ISSUE TITLE
Too many redirects on iOS

### ISSUE THREAD

**Issue by nessor** [bitwarden/android#855]
## Describe the Bug

I had moved my Bitwarden instance to a new server and had misconfigured the reverse proxy there. So I had a redirect loop. After I fixed it, the error message in the iOS app kept appearing. The only thing that helped was to uninstall and reinstall the app on the iPhone

## Steps To Reproduce

1. Provoke a "too many redirects" error message in the iOS app'
2. Try to log in to the iOS app on the server. The error message appears
3. Solve the "problem"
4. Try to log in to the iOS app on the server. The error still message appears

## Expected Result

After the problem is resolved, the error message should no longer appear.

## Actual Result

The error message still appears

## Screenshots or Videos

./.

## Environment

- Device: iPhone XR
- Operating system: iOS 13.4
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (64)
- Is this a Beta release? N

**Comment by chungnd1** [comment]
I have the same issue with latest version of bitwarden on iOS, except I don't misconfigure the proxy.

**Comment by nessor** [comment]
Did you solved the issue by uninstalling and installing the app again?

**Comment by chungnd1** [comment]
I did, but it keeps come back after few days.

**Comment by genbuckturgidson** [comment]
I have this issue and it's persistent. Uninstall/reinstall fails to resolve it even temporarily.

Additionally, my server works perfectly well on other platforms, but not with iOS.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/855
