### ISSUE TITLE
Inconsistent locking behavior

### ISSUE THREAD

**Issue by flexwie** [bitwarden/android#858]
The app on my phone has a totally inconsistent locking behavior. The locking time is mostly ignored when trying to fill out passwords via the overlay (I always have to fill in my master password) but is honored when I'm opening the app itself.
Also it's never asking me for the PIN I set up.

Weird thing is that this observation is broken from time to time. Eg sometimes it does ask me for my PIN or stays unlocked but those times are rather rare.

I'm running v2.3.1 on Android 10. Phone is a OnePlus 6.

**Comment by vinnyperella** [comment]
Same issue on my phone on the latest mobile version (2022.11.0). It seems like the app restarts when you move focus away from it (minimize it) even if my vault timeout is 5 minutes it asks for my PIN every single time I go back to the app. I've tried all the usual troubleshooting steps and nothing seems to work, it was working fine up until I logged out today to try and fix another issue.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/858
