### ISSUE TITLE
No "cut-copy-paste" popup in any fields while adding a new item from apps

### ISSUE THREAD

**Issue by maxwowpow** [bitwarden/android#863]
## Describe the Bug

No "cut-copy-paste" popup in any fields while adding a new item from apps (my case genuss+ app)

## Steps To Reproduce

1. Go to Any App where you can trigger bitwarden to add a new Item to the vault.
2. Click on "mot de passe / passwords" to trigger the bitwarden and click "+" to add a new password for a website/app.
3. the URI is pre-filled. Try to COPY this URI, try to select the whole text to share it or just copy.

## Expected Result

Popup with "copy". So I copy my URI for my reasons.
## Actual Result

Nothing pops up, no copy menu/helper.

## Screenshots or Videos

this popup is expected:
![34FE4432-F4FE-412E-94F6-AE10FFDC1F18](https://user-images.githubusercontent.com/169885/80658844-913af680-8a87-11ea-92f2-a7c0aaca2105.jpeg)

try selecting:
![C2A94BEE-5B7B-446D-B0D6-51F029CDA67D](https://user-images.githubusercontent.com/169885/80658851-939d5080-8a87-11ea-935f-fb1a77630a6a.jpeg)

## Environment

- Device: iPhone11 Pro Max
- Operating system: iOS 13.3.1
- Build Version (go to "Settings" → "About" in the app): Version: 2.3.1 (64)
- Is this a Beta release? N

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/863
