### ISSUE TITLE
LG Mini view not working anymore when Bitwarden is given accessibility rights

### ISSUE THREAD

**Issue by julian-w** [bitwarden/android#924]
## Describe the Bug

If Bitwarden is given accessibility rights, the "LG Mini view" is not working anymore.

## Steps To Reproduce

Activate LG Mini view. It is now working fine. 
Install Bitwarden and activate accessibility. 
LG Mini view is not working anymore.
A withdrawal of the accessibility rights makes "LG Mini view" functions again.

## Expected Result

"LG Mini view" should still work.

## Actual Result

"LG Mini view" does not work anymore.

## Screenshots or Videos

![Screenshot_20200525-181441](https://user-images.githubusercontent.com/9528445/82829526-c33b4f00-9eb3-11ea-848f-f1e07c024a75.png)

![Screenshot_20200525-181455](https://user-images.githubusercontent.com/9528445/82829523-c1718b80-9eb3-11ea-94e8-3b4176ace5f7.png)

## Environment

- Device: LG G8s
- Operating system: Android 9
- Build Version: 2.3.1 (2257)
- Is this a Beta release? No

**Comment by kspearrin** [comment]
Did you give it overlay rights?

**Comment by julian-w** [comment]
Bitwarden has the "Draw over other apps" rights. However, this does not change the behaviour, no matter whether I revoke the permission or not.

![Screenshot_20200526-154442](https://user-images.githubusercontent.com/9528445/82908374-28e91300-9f68-11ea-8f49-6a4ece3ab58a.png)

Here are my quick test results, if "LG mini view" works or not (phone restarted each time)

|    | "Accessibility Rights" ON | "Accessibility Rights" OFF |
| ------------- | ------------- | ------------- |
| **"Draw over other apps" ON**  | Doesn't work  | _Works_  |
| **"Draw over other apps" OFF**  | Doesn't work  | _Works_  |

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/924
