### ISSUE TITLE
Android URI in 'Host' mode - https interpreted as http 

### ISSUE THREAD

**Issue by gitcatpeter** [bitwarden/android#968]
## Describe the Bug

A bit similar to #803
App v2.4.2
When URI matching by 'host' is used, the auto-fill service does not find any matches for 'https://' sites.

Auto-fill dialog shows as expected, but with no credentials. When 'Go to my vault' is pressed it opens the vault not returning any matches _"there are no items in your vault <base domain>"_ (it shows only base domain, not the whole URL)
A bit of light is shed when the app offers to save the missing credential. I can see the URL is correct, **except for protocol: https is filled out as **http**.**

That would explain no match, because the app is looking for http://address, instead of https://address

## Steps To Reproduce

1. Go to Chrome, enter some address beginning with https://, eg: https://myapp.mydomain
2. Click on login field on the website
3. Auto-fill dialog appears with no matches
4. Press 'go to my vault'
5. Vault opens with no matches
6. Press 'Add an item' and scroll to URL
7. The URI is filled with http://myapp.mydomain
## Expected Result
URI is recognized correctly

## Actual Result
URI is not recognized as https is changed into http

## Environment

- Device: Samsung S8+
- Operating system: Android 9 (ppr1.180610.011)
- Build Version (go to "Settings" → "About" in the app):  v2.4.2
- Is this a Beta release? [Y/N] N

## Additional Context
Happens regardless of 'Auto-Fill' service enabled or disabled.
Thank you for your support!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/968
