### ISSUE TITLE
Overwriting changed password when adding URL

### ISSUE THREAD

**Issue by nijel** [bitwarden/android#972]
## Describe the Bug

The Android application rewrites whole entry when adding an URL. When its vault it not up to date, it can lead to data loss.

## Steps To Reproduce

1. Change entry password in a web vault
2. Open password lookup on Android app, while it is still not yet synced with above change
3. See there is no exact match, do search and select edited entry
4. Tap on "Yes, and Save"

## Expected Result

The entry should contain updated password and newly added URL.

## Actual Result

The entry contains previous password and the new URL. The new password is not even in history, so there is no way to recover the changed password unless you have another not yet synced vault.

## Environment

- Device: Android
- Operating system: 8.1.0
- Build Version 2.4.2 (2501)
- Is this a Beta release? [Y/N]

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/972
