### ISSUE TITLE
Docs/Examples for "Set environment server URL from EMM (ex. AppConfig)"

### ISSUE THREAD

**Issue by pdbs** [bitwarden/android#997]
## Describe the Bug

Is there some example for "Set environment server URL from EMM (ex. AppConfig)". This should work since version 2.3.0 

## Expected Result

Deploy Bitwarden mobile app with preconfigured self hosted server URL

## Environment

- Operating system: iOS
- EMM/MDM: Sophos

**Comment by pdbs** [comment]
Maybe this helps: As in https://www.appconfig.org/ios/: "App developer creates XML definition file (See Appendix) documenting the configurations that the app supports".

I found an example under https://github.com/nextcloud/ios/blob/master/MDM/AppConfig/specfile.xml 

Maybe this could be adapted and integrated in the Bitwarden app. We would love it.

**Comment by idominiki** [comment]
Any news on this?

**Comment by MaxXor** [comment]
I'm also looking for a way to pre-configure the iOS app.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/997
